### ISSUE TITLE
Disable session resumption in TLS 1.3

### ISSUE THREAD

**Issue by kapiliitr** [sfackler/rust-openssl#1007]
Hi

I am trying out  a simple client-server application using TLS 1.3. I am using client certificate authentication. I wish to disable session resumption as I want to look at the packets that are sent across in the TLS handshake in wireshark. I tried setting SslSessionCachedMode::OFF but that doesn't seem to work as I see a SessionId passed in the ClientHello and the same SessionId in the ServerHello messages. Here is a code snippet of the server-

```
builder.clear_options(SslOptions::NO_TLSV1_3);
builder.set_min_proto_version(Some(SslVersion::TLS1_3)).unwrap();

let mut verifyMode = SslVerifyMode::empty();
verifyMode.insert(SslVerifyMode::PEER);
verifyMode.insert(SslVerifyMode::FAIL_IF_NO_PEER_CERT);
builder.set_verify(verifyMode);

builder.set_session_cache_mode(SslSessionCacheMode::OFF)
```

I am seeing the below wireshark trace but I don't see a server certificate being sent or a client certificate being requested. I assume its because it might have been done in an initial request but is not happening in subsequent requests. Can you please help me with turning off session resumption ?
![tls](https://user-images.githubusercontent.com/1621360/46679416-d218a500-cb9b-11e8-8db7-7663769b7442.png)

**Comment by kapiliitr** [comment]
My bad, in TLS 1.3 "All handshake messages after the ServerHello are now encrypted.". I will look at how can the handshake messages be decrypted in wireshark. 

I also saw that I could do the following. Can you confirm which is the right way to turn off session resumption ?
`builder.set_options(SslOptions::NO_SESSION_RESUMPTION_ON_RENEGOTIATION);`

**Comment by sfackler** [comment]
`NO_SESSION_RESUMPTION_ON_RENEGOTIATION` specifically applies to renegotiation, not the initial handshake. `set_session_cache_mode(NONE)` should be the right way to disable it entirely.

**Comment by kapiliitr** [comment]
Sorry but neither of `set_session_cache_mode(SslSessionCacheMode::NONE)` or `set_session_cache_mode(NONE)` seem to work as `NONE` is not found in scope. Did you mean `set_session_cache_mode(SslSessionCacheMode::OFF)` ?

**Comment by sfackler** [comment]
Er, yeah, that's right.

**Comment by kapiliitr** [comment]
Also, how can I enable [SSL_CTX_set_keylog_callback](https://www.openssl.org/docs/manmaster/man3/SSL_CTX_set_keylog_callback.html) as I think I would need the secrets to decrypt the messages ?

**Comment by sfackler** [comment]
Here's an example: https://github.com/sfackler/hyper-openssl/blob/master/src/lib.rs#L425-L434

**Comment by kapiliitr** [comment]
Great thanks. I think this has not yet appeared in the [docs](https://docs.rs/openssl/0.10.12/openssl/ssl/struct.SslConnectorBuilder.html).

**Comment by sfackler** [comment]
It unfortunately doesn't show up in the docs there because docs.rs doesn't have OpenSSL 1.1.1 installed. You can look at the docs locally to see all of the functionality available with your version using cargo: `cargo doc --open --no-deps -p openssl`

**Comment by kapiliitr** [comment]
Awesome! Thanks!
