### ISSUE TITLE
LibreSSL 2.8.2

### ISSUE THREAD

**Issue by reyk** [sfackler/rust-openssl#1009]
Hi,

LibreSSL 2.8.2 has been made available, the release announcement will follow shortly. OpenBSD 6.4 is released at the same time and includes LibreSSL 2.8.2. It would be nice if rust-openssl could be updated accordingly.

https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-2.8.2.tar.gz
https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-2.8.2.tar.gz.asc

I'm also wondering if there is any better way of dealing with LibreSSL releases. On OpenBSD, most developers and many users use snapshot releases or -current that include -current versions of LibreSSL as the library is being developed within the project.

It is very difficult to use rust-openssl on OpenBSD-current because it almost always rejects the "upcoming" LibreSSL version that is in the tree. My current workaround is to fork rust-openssl and to carry the following difference:

https://github.com/reyk/rust-openssl/commit/5f2b69e28f1c497ccec9932ffe96dec04d1c4cae

And to patch it in Cargo.toml:
```
[patch.crates-io]
openssl-sys = { git = "https://github.com/reyk/rust-openssl", branch = "current" }
openssl = { git = "https://github.com/reyk/rust-openssl", branch = "current" }
```

But this is obviously bad.

It would be nice to have a better way in your upstream version. Could you eventually skip the strict version number check on OpenBSD?

We have a strictly linear development model in OpenBSD: our releases will always have one fixed LibreSSL version (since packages won't update it) and the -current or -beta versions might have any newer major or minor version. Temporary API breakage is expected on -current, -beta might have a new version number but it usually doesn't introduce large changes any more, and the release API and ABI is stable and fixed to one release.

Reyk

**Comment by sfackler** [comment]
Thanks for the heads up, I will update! 2.8.2 is the first ABI stable release in the 2.8 series, so we'll be able to whitelist all future 2.8 versions now.

> Could you eventually skip the strict version number check on OpenBSD?

No, we cannot. LibreSSL publicly exposes the layout of structures, and changes their contents over time. Being wrong about layout can and has in practice broken things before, hence the strict version constraints.

OpenSSL learned their lesson about ABI stability and made all of these structures opaque in 1.1.0, but the same has not fully happened in LibreSSL yet.

**Comment by vext01** [comment]
> Could you eventually skip the strict version number check on OpenBSD?

> No, we cannot.

Could I beg you to reconsider? You can say "we officially support these versions, if you use a newer version you are on your own). Spit out a large warning message at build time if you must. Or require some "if I blow my foot off I accept full responsibility" environment variable to be set?

At the moment, we have people using Rust on OpenBSD-current in commercial and academic scenarios who have either:

 * Installed OpenSSL against their will, solely for making Rust code build.
 * Forked your repo, disabled the version check, and overridden the rust-openssl path at the Cargo level.

The former undermines the user and the hard work of the LibreSSL team (who are trying to do better than OpenSSL). The latter makes for a maintainability nightmare. And in general, having to jump these extra hoops makes using Rust unpleasant.

I'd be so grateful if you could do something to make it easier for OpenBSD-current users to build projects that pull in rust-openssl.

Thanks!
