### ISSUE TITLE
Implement TLS session resumption

### ISSUE THREAD

**Issue by kapiliitr** [sfackler/rust-openssl#1013]
Hi

I have been trying to implement session resumption using rust-openssl. Following is the client code for my test app-
```
    let mut builder = SslConnector::builder(SslMethod::tls()).unwrap();

    builder.set_session_cache_mode(SslSessionCacheMode::CLIENT | SslSessionCacheMode::NO_INTERNAL);

    let savedSession = Arc::new(Mutex::new(None));
    let savedSession2 = savedSession.clone();
    builder.set_new_session_callback(move |sslref, session| {
        let mut ss = savedSession2.lock().unwrap();
        *ss = Some(session);
    });

    builder.clear_options(SslOptions::ENABLE_MIDDLEBOX_COMPAT);

    let connector = builder.build();

    let mut iters = 2;

    for _ in 0..iters {
        let mut config = connector.configure().unwrap();

        if let Some(ref ss) = *(savedSession.lock().unwrap()) {
            let mut masterkey = vec![];
            ss.master_key(&mut masterkey);
            println!("Master key : {:#?}", masterkey);
            unsafe {
                config.set_session(ss).unwrap();
            }
        }

        let stream = TcpStream::connect("<ip:port>").unwrap();
        let mut stream = connector.connect("<servername>", stream).unwrap();
        println!("Ssl session reuse : {}", ssl.session_reused());
        loop {
            let mut res = vec![];
            let read = (&mut stream).take(32).read_to_end(&mut res).unwrap();

            // 2-way shutdown
            if stream.get_shutdown() == ShutdownState::RECEIVED {
                stream.shutdown().unwrap();
                break;
            }
        }
    }
```

Instead of `SslRef.set_session()`, I also tried the following code-
```
    let savedSession3 = savedSession.clone();
    builder.set_psk_client_callback(move |_, _, identity, psk| {
        if let Some(ref ss) = *(savedSession3.lock().unwrap()) {
            let ssid = ss.id();
            identity[..ssid.len()].copy_from_slice(&ssid);
            identity[ssid.len()] = 0;

            let mut masterkey = vec![];
            ss.master_key(&mut masterkey);
            psk[..masterkey.len()].copy_from_slice(&masterkey);
            println!("masterkey : {:#?}", masterkey);
            Ok(masterkey.len())
        } else {
            Ok(0)
        }
    });
```

I noticed that the master key returned is always empty and I don't see either the Session Id or the pre_shared_key extension set in the ClientHello message. I tried both TLS 1.2 and 1.3 and both have the same issue and `SslRef.session_reused()` returns false.

Could you please help me set up TLS session resumption.

Thanks

**Comment by sfackler** [comment]
stream.shutdown() must be called for OpenSSL to be willing to reuse the session IIRC.

Is the server generally willing to resume sessions? You can try using `openssl s_client -reconnect` to see.

**Comment by sfackler** [comment]
You need to call shutdown on the client side for the OpenSSL client to be willing to reuse the session: https://www.openssl.org/docs/man1.0.2/ssl/SSL_shutdown.html.

TLS 1.3 significantly changed session reuse to unify it with PSK.

set_session is the right thing to use for session resumption. https://github.com/sfackler/hyper-openssl has a working session resumption setup that you could look at.

**Comment by kapiliitr** [comment]
Isn't that what I'm doing in the code above ? Should I call shutdown again ?
```
// If server sends a CloseNotify, then client also does a shutdown
if stream.get_shutdown() == ShutdownState::RECEIVED {
                stream.shutdown().unwrap();
                break;
            }
```
yes, I looked at hyper-openssl, but I don't think I saw a test for session resumption, so I was unable to figure out what I'm doing wrong.

**Comment by sfackler** [comment]
That's what the code's doing assuming the shutdown state is at RECEIVED.

You could try using something like Wireshark to check if the ClientHello contains the session. If it does and the server isn't selecting it then it doesn't seem like a client issue.

**Comment by kapiliitr** [comment]
I have ENABLE_MIDDLEBOX_COMPAT disabled in the rust client as otherwise the session Id was always populated with a dummy value and I could not get a true TLS 1.3 handshake. Could that be responsible for clearing out the session id meant for session resumption ?

**Comment by sfackler** [comment]
This test passes for me using both 1.1.0 with TLS 1.2 and 1.1.1 with TLS 1.3.

```
#[test]
fn new_session_callback() {
    let listener = TcpListener::bind("127.0.0.1:0").unwrap();
    let port = listener.local_addr().unwrap().port();

    let guard = thread::spawn(move || {
        let mut ctx = SslContext::builder(SslMethod::tls()).unwrap();
        ctx.set_certificate_file(&Path::new("test/cert.pem"), SslFiletype::PEM)
            .unwrap();
        ctx.set_private_key_file(&Path::new("test/key.pem"), SslFiletype::PEM)
            .unwrap();
        ctx.set_session_id_context(b"foo").unwrap();
        let ctx = ctx.build();

        let stream = listener.accept().unwrap().0;
        let ssl = Ssl::new(&ctx).unwrap();
        let mut stream = ssl.accept(stream).unwrap();
        stream.write_all(&[0]).unwrap();
        stream.shutdown().unwrap();

        let stream = listener.accept().unwrap().0;
        let ssl = Ssl::new(&ctx).unwrap();
        let mut stream = ssl.accept(stream).unwrap();
        stream.write_all(&[0]).unwrap();
    });

    let mut ctx = SslContext::builder(SslMethod::tls()).unwrap();
    ctx.set_session_cache_mode(SslSessionCacheMode::CLIENT | SslSessionCacheMode::NO_INTERNAL);
    let session = Arc::new(Mutex::new(None));
    ctx.set_new_session_callback({
        let session = session.clone();
        move |_, sess| *session.lock().unwrap() = Some(sess)
    });
    let ctx = ctx.build();

    let ssl = Ssl::new(&ctx).unwrap();
    let stream = TcpStream::connect(("127.0.0.1", port)).unwrap();
    let mut stream = ssl.connect(stream).unwrap();
    stream.read_exact(&mut [0]).unwrap();
    stream.shutdown().unwrap();

    let mut ssl = Ssl::new(&ctx).unwrap();
    unsafe {
        ssl.set_session(session.lock().unwrap().as_ref().unwrap())
            .unwrap();
    }
    let stream = TcpStream::connect(("127.0.0.1", port)).unwrap();
    let mut stream = ssl.connect(stream).unwrap();
    assert!(stream.ssl().session_reused());
    stream.read_exact(&mut [0]).unwrap();

    guard.join().unwrap();
}
```

**Comment by kapil-ms** [comment]
Yes, that worked. Thanks.

It seems that the SslConnector can not be used if the configuration is being changed and `ConnectConfiguration.connect()` should be used instead.

Shouldn't SslConnector be able to pick up the new configuration ? I would suspect that to happen both logically and from the documentation. Is there a limitation to making that happen ?

It is a bit weird to first call SslConnector.connect() and later use ConnectConfiguration.connect(). I would just use ConnectConfiguration.connect() every time in that case. If you don't think existing behavior should change, I think it might help to put that in the documentation.

Thanks

**Comment by kapiliitr** [comment]
Yes, that worked. Thanks.

It seems that the SslConnector can not be used if the configuration is being changed and `ConnectConfiguration.connect()` should be used instead.

Shouldn't SslConnector be able to pick up the new configuration ? I would suspect that to happen both logically and from the documentation. Is there a limitation to making that happen ?

It is a bit weird to first call SslConnector.connect() and later use ConnectConfiguration.connect(). I would just use ConnectConfiguration.connect() every time in that case. If you don't think existing behavior should change, I think it might help to put that in the documentation.

Thanks

**Comment by sfackler** [comment]
`.configure` is used to make per-connection configuration, not global configuration.
