### ISSUE TITLE
Cross compiling openssl-sys to Windows with mingw fails if vendored

### ISSUE THREAD

**Issue by codido** [sfackler/rust-openssl#1014]
The build fails when trying to find the built static/dynamic libraries. The reason seems to be that with mingw (as opposed to msvc) .a files are created. Since both targets are treated equally here:
https://github.com/sfackler/rust-openssl/blob/b88778bc76b039e26aaa3d54f03716433986fae1/openssl-sys/build/main.rs#L85

...the build ends up looking for liblibssl.a and fails.

**Comment by laumann** [comment]
This should be fixed with #1265.
