### ISSUE TITLE
Support for SHAKE256/128

### ISSUE THREAD

**Issue by sameer** [sfackler/rust-openssl#1017]
Are there plans to support SHAKE256/128?

It is in openssl as an [EVP function](https://www.openssl.org/docs/man1.1.1/man3/EVP_shake256.html) but I don't see that in the extern for `openssl-sys/evp.rs`.

**Comment by sameer** [comment]
Ok, sounds good. Would I have to add the functions in openssl-sys/evp.rs extern c section, then put them in an evp module in the main crate? I haven't done much with bindings in Rust, so any guidance is appreciated.

-------- Original Message --------

**Comment by sfackler** [comment]
The openssl-sys file structure should directly mirror the C headers, yeah, and then you'd just add new constructors to [Cipher](https://docs.rs/openssl/0.10.15/openssl/symm/struct.Cipher.html) in the main crate.

**Comment by sameer** [comment]
What if it doesn't? The evp.rs file is actually missing the shake functions that should be there: https://www.openssl.org/docs/man1.1.1/man3/EVP_shake256.html
They aren't in evp.h for openssl 1.1.0 though.

-------- Original Message --------

**Comment by sfackler** [comment]
Oh sorry, by "should directly mirror the C headers" I meant that you should add stuff to openssl-sys in the same "place" you find it in the OpenSSL headers, not that openssl-sys is complete.

If APIs moved around in the different OpenSSL releases, go off of the newest one. I usually just look at the master branch of https://github.com/openssl/openssl.

**Comment by sameer** [comment]
Alright, I'll try and do a PR tomorrow. Thanks for the help!

-------- Original Message --------

**Comment by sfackler** [comment]
To deal with the extendable output function bits, I think we'd just make a new `pub fn finish_xof(&mut self, buf: &mut [u8]) -> Result<(), ErrorStack>` method on Hasher.

**Comment by sameer** [comment]
> To deal with the extendable output function bits, I think we'd just make a new `pub fn finish_xof(&mut self, buf: &mut [u8]) -> Result<(), ErrorStack>` method on Hasher.

LGTM, I'll implement it.
