### ISSUE TITLE
Mac : failed to run custom build command for `openssl-sys v0.9.39`

### ISSUE THREAD

**Issue by harishbm34** [sfackler/rust-openssl#1028]
error: failed to run custom build command for `openssl-sys v0.9.39`
process didn't exit successfully: `/go/src/github.com/gallactic/sputnikvm-ffi/c/ffi/target/release/build/openssl-sys-c0f270f395a7db7f/build-script-main` (exit code: 101)
--- stdout
cargo:rerun-if-env-changed=X86_64_ALPINE_LINUX_MUSL_OPENSSL_LIB_DIR
cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
cargo:rerun-if-env-changed=X86_64_ALPINE_LINUX_MUSL_OPENSSL_INCLUDE_DIR
cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
cargo:rerun-if-env-changed=X86_64_ALPINE_LINUX_MUSL_OPENSSL_DIR
cargo:rerun-if-env-changed=OPENSSL_DIR
run pkg_config fail: "`\"pkg-config\" \"--libs\" \"--cflags\" \"openssl\"` did not exit successfully: exit code: 1\n--- stderr\nPackage openssl was not found in the pkg-config search path.\nPerhaps you should add the directory containing `openssl.pc\'\nto the PKG_CONFIG_PATH environment variable\nPackage \'openssl\', required by \'virtual:world\', not found\n"

--- stderr
thread 'main' panicked at '

Could not find directory of OpenSSL installation, and this `-sys` crate cannot
proceed without this knowledge. If OpenSSL is installed and this crate had
trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
compilation process.

Make sure you also have the development packages of openssl installed.
For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.

If you're in a situation where you think the directory *should* be found
automatically, please open a bug at https://github.com/sfackler/rust-openssl
and include information about your system as well as this message.

    $HOST = x86_64-alpine-linux-musl
    $TARGET = x86_64-alpine-linux-musl
    openssl-sys = 0.9.39

', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.39/build/main.rs:269:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
make[1]: *** [Makefile:11: build] Error 101

Note : I have openssl in place but still getting the above errors.

**Comment by sfackler** [comment]
Is this mac or alpine linux?

You need to install the openssl-dev package.

**Comment by harishbm34** [comment]
It’s Mac, trying make docker image.

Kindly help me to fix this.

**Comment by sfackler** [comment]
You're compiling this inside of a Docker image. You need to install openssl-dev inside of that docker image.

**Comment by harishbm34** [comment]
@sfackler : Thank you so much for the help :) Resolved that issue.

**Comment by victorpaleologue** [comment]
Why can't it find the version of openssl already installed on the system?
Is there a way to make it work without installing `brew` and tweaking my system?
