### ISSUE TITLE
OpenSSL sys 0.9.37 fails to build

### ISSUE THREAD

**Issue by crocwolf** [sfackler/rust-openssl#1035]
problem to build cargo-web which uses rust openssl sys : 

> Error building OpenSSL:
>     Command: "make"
>     Exit status: exit code: 2
> 
> 
>     /home/m/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-src-110.0.7+1.1.0i/src/lib.rs:273:13

Any idea to complete building ?

**Comment by crocwolf** [comment]
I just replaced dependencies by : 

> rust-openssl = "*"
> openssl-sys = "0.9.37"

I have this output : 

> failed to run custom build command for `openssl-sys v0.9.37`
> process didn't exit successfully: `/home/m/Bureau/WASM FRAMEWORK/quantics/cargo-web/target/release/build/openssl-sys-5095541702d14988/build-script-main` (exit code: 101)
> --- stdout
> cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR
> cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
> cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR
> cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
> cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR
> cargo:rerun-if-env-changed=OPENSSL_DIR
> run pkg_config fail: "`\"pkg-config\" \"--libs\" \"--cflags\" \"openssl\"` did not exit successfully: exit code: 1\n--- stderr\nPackage openssl was not found in the pkg-config search path.\nPerhaps you should add the directory containing `openssl.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'openssl\' found\n"
> 
> --- stderr
> thread 'main' panicked at '
> 
> Could not find directory of OpenSSL installation, and this `-sys` crate cannot
> proceed without this knowledge. If OpenSSL is installed and this crate had
> trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
> compilation process.
> 
> Make sure you also have the development packages of openssl installed.
> For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.
> 
> If you're in a situation where you think the directory *should* be found
> automatically, please open a bug at https://github.com/sfackler/rust-openssl
> and include information about your system as well as this message.
> 
>     $HOST = x86_64-unknown-linux-gnu
>     $TARGET = x86_64-unknown-linux-gnu
>     openssl-sys = 0.9.37
> 
> ', /home/m/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.37/build/main.rs:265:9
> note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
> 
> warning: build failed, waiting for other jobs to finish...
> error: failed to compile `cargo-web v0.6.23 (/home/m/Bureau/WASM FRAMEWORK/quantics/cargo-web)`, intermediate artifacts can be found at `/home/m/Bureau/WASM FRAMEWORK/quantics/cargo-web/target`
> 
> Caused by:
>   build failed

**Comment by sfackler** [comment]
https://docs.rs/openssl/0.10.16/openssl/#automatic

**Comment by crocwolf** [comment]
Thank you :-)

**Comment by OxfordStreet** [comment]
# Debian and Ubuntu
$ sudo apt-get install pkg-config libssl-dev
works for me!
Thanks!!

**Comment by hycinth22** [comment]
> # Debian and Ubuntu
> $ sudo apt-get install pkg-config libssl-dev works for me! Thanks!!

`apt-get install pkg-config` works for me

only the installed `libssl-dev` is not enough.
