### ISSUE TITLE
Constructor of Asn1Time with a string?

### ISSUE THREAD

**Issue by seamlik** [sfackler/rust-openssl#1051]
This would allow constructing an `Asn1Time` with something like "YYYYMMDDHHMMSSZ", just like what the documentation hints, corresponding to `ASN1_TIME_set_string()`.

This feature is required (or useful) if one wants to construct a certificate that never expires. According to [RFC 5280](https://tools.ietf.org/html/rfc5280#section-4.1.2.5), `notAfter` may be set to `99991231235959Z` to indicate an infinite validity.

Or perhaps, I should just set its validity to last, say, a million days?

**Comment by sfackler** [comment]
`ASN1_TIME_set_string` can fail, so it can't be used to implement `From` specifically. A normal constructor would work though.

**Comment by seamlik** [comment]
@sfackler That is a great point.
