### ISSUE TITLE
TLS client authentication

### ISSUE THREAD

**Issue by aburn** [sfackler/rust-openssl#1058]
Hi,

I'm trying to use the *native_tls* crate which seems to use this crate for my platform, to do client authentication. I'm not able to find in the docs on how to configure the *server* to request for client certificate. Is this feature available? or is there an issue open for this already.  I could not find references to `SSL_CTX_set_client_cert_cb` openssl ffi functions. If it already exists, can someone please point me to the relevant section in the code/docs. If its available either in code or documentation I can try to fix the missing in a PR (if one doesn't exist already).

Thanks!

**Comment by sfackler** [comment]
In the openssl API, you'd need to set `SslVerifyMode::PEER` and `SslVerifyMode::FAIL_IF_NO_PEER_CERT`: https://docs.rs/openssl/0.10.16/openssl/ssl/struct.SslVerifyMode.html#associatedconstant.FAIL_IF_NO_PEER_CERT.

**Comment by aburn** [comment]
Thank you!
