### ISSUE TITLE
Cannot statically link openssl on Windows / vcpkg

### ISSUE THREAD

**Issue by AregevDev** [sfackler/rust-openssl#1063]
I am trying to link openssl's static libraries installed by vcpkg. I am using the MSVC toolchain on Windows 10.
No matter what I do, openssl-sys is dynamically linking the libraries.

My steps:
Running `vcpkg install openssl:x64-windows-static`
Setting the environment variable `OPENSSL_STATIC` to 1 in the environment variable interface
Performing a cargo build, compiles and runs well
Running the app manually from CMD, cannot find the DLLs

I want to build a compact executable and not include any DLLs in distribution

Thanks 😊

**Comment by sfackler** [comment]
You need to set `RUSTFLAGS=-Ctarget-feature=+crt-static`:

https://docs.rs/vcpkg/0.2.6/vcpkg/
