### ISSUE TITLE
Add a feature that makes vendored builds fail

### ISSUE THREAD

**Issue by hvenev** [sfackler/rust-openssl#1085]
It might be a good idea to force a build failure if something depends on `openssl-sys/vendored`.

**Comment by sfackler** [comment]
Cargo features are supposed to be additive, and only the final application crate should be enabling the vendored feature anyway. What's the use case for wanting this?

**Comment by hvenev** [comment]
I want to make sure that nothing I use depends on `openssl-sys/vendored`.

**Comment by hvenev** [comment]
I guess I could patch openssl-src to be an empty crate.
