### ISSUE TITLE
undefined reference to `CRYPTO_set_id_callback', linking to libssl 1.1

### ISSUE THREAD

**Issue by bvinc** [sfackler/rust-openssl#1098]
```
in function `openssl_sys::init::set_id_callback':
openssl-sys-0.9.43/src/lib.rs:142: undefined reference to `CRYPTO_set_id_callback'
          collect2: error: ld returned 1 exit status
```

The function `CRYPTO_set_id_callback` was deprecated in libssl 1.0

https://linux.die.net/man/3/crypto_set_id_callback

Ubuntu 19.04 uses libssl 1.1 and so can't build anything using rust-openssl.

**Comment by sfackler** [comment]
We only use CRYPT_set_id_callback when we think we're linking against 1.0.x. You probably have some stray 1.0.x headers on your system that gcc's finding before the 1.1.x headers.

**Comment by bvinc** [comment]
Hmm..  That's very possible.  Let me make sure and I'll get back to you.

**Comment by bvinc** [comment]
I just updated my system and got this error when I did `cargo build`. `cargo clean` fixed it.  I guess the header files were being cached somewhere?  I'll close this.
