### ISSUE TITLE
BUG: new session callback missing

### ISSUE THREAD

**Issue by animalsiknow** [sfackler/rust-openssl#1115]
Hello,

I have code that make [the assertion mentioned in the title](https://github.com/sfackler/rust-openssl/blob/d861eb16dd127870a68c6355a78170495a468f93/openssl/src/ssl/callbacks.rs#L358) fail. The weird thing is that it only happens when I pass the callback directly as such

```rust
let session_store_0 = Arc::clone(session_store);
builder.set_new_session_callback(move |ssl, session| session_store_0.insert(ssl, session));
```

Alternatively, if I build the callback in another function, my application works fine

```rust
fn build_new_session_callback(
    session_store: &Arc<SessionStore>,
) -> impl Fn(&mut ssl::SslRef, ssl::SslSession) {
    let session_store = Arc::clone(session_store);
    move |ssl, session| session_store.insert(ssl, session)
}

builder.set_new_session_callback(build_new_session_callback(session_store));
```

I suspect that the issue is how `TypeId` interacts with closures. I added some tracing to see what `TypeId` is generated. This is the one in [`set_new_session_callback`](https://github.com/sfackler/rust-openssl/blob/d861eb16dd127870a68c6355a78170495a468f93/openssl/src/ssl/mod.rs#L1394-L1418):
```
[/Users/simon/Source/github.com/sfackler/rust-openssl/openssl/src/ssl/mod.rs:1416] std::any::TypeId::of::<F>() = TypeId {
    t: 3694631760449667781,
}
[/Users/simon/Source/github.com/sfackler/rust-openssl/openssl/src/ssl/mod.rs:1417] std::intrinsics::type_name::<F>() = "[closure@src/cert/context/builder.rs:70:42: 70:98 session_store_0:std::sync::Arc<cert::SessionStore>]"
```

This is the one in [`raw_new_session`](https://github.com/sfackler/rust-openssl/blob/d861eb16dd127870a68c6355a78170495a468f93/openssl/src/ssl/callbacks.rs#L347-L365):
```
[/Users/simon/Source/github.com/sfackler/rust-openssl/openssl/src/ssl/callbacks.rs:355] std::any::TypeId::of::<F>() = TypeId {
    t: 17026941024949866994,
}
[/Users/simon/Source/github.com/sfackler/rust-openssl/openssl/src/ssl/callbacks.rs:356] std::intrinsics::type_name::<F>() = "[closure@src/cert/context/builder.rs:70:42: 70:98 session_store_0:std::sync::Arc<cert::SessionStore>]"
```

When the closure is passed directly to `set_new_session_callback`, it may have some extra information that gets lost when it is passed as a type argument to `raw_new_session`? This would explain why wrapping the creation of the closure in a function like `build_new_session_callback` above work: the extra information exists only within the latter, and both `set_new_session_callback` and `raw_new_session` see the same type. Another thing that could confuse the types is that the call to `new_session_callback` is itself in a generic function. I thought it could be an issue with `set_new_session_callback` being instanciated twice because it uses the closure value, but `raw_session_id` incorrectly being instanciated only once because it only uses the closure type. Do closures created in two instanciations of a generic function, and that do not depend on the generic parameter have the same type?

I wrote this test case which seems it could trigger the bug, but it passes:
```
#[cfg(test)]
mod help {
    use std::fmt::Debug;
    use std::os::raw::c_int;

    use crate::ssl::{SslRef, SslSession};

    use super::*;

    pub unsafe extern "C" fn raw_new_session<F>() -> c_int
        where
            F: Fn(&SslRef, SslSession) + 'static + Sync + Send,
    {
        SslContext::cached_ex_index::<F>().as_raw()
    }

    #[inline(never)]
    pub fn set_new_session_callback<F>(f: F) -> (c_int, unsafe extern "C" fn() -> c_int)
        where
            F: Fn(&SslRef, SslSession) + 'static + Sync + Send,
    {
        let server = Server::builder().build();
        let stream = server.client().connect();
        let ssl = stream.ssl();
        let session = ssl.session().unwrap();
        f(ssl, session.to_owned());

        (SslContext::cached_ex_index::<F>().as_raw(), raw_new_session::<F>)
    }

    #[inline(never)]
    pub fn configure_context(x: impl Debug) -> (c_int, unsafe extern "C" fn() -> c_int) {
        dbg!(&x);
        let s = "hello".to_string();
        set_new_session_callback(move |_, _| { println!("{}", s.as_str()); })
    }

    #[test]
    fn help() {
        let (i, f) = configure_context(0u64);
        let (j, g) = configure_context(0usize);

        assert_eq!(i, unsafe { f() });
        assert_eq!(j, unsafe { g() });
    }
}
```

I don't know if the issue is with my code, `rust-openssl`, or even `TypeId`. The documentation on [`TypeId`](https://doc.rust-lang.org/std/any/struct.TypeId.html) does not give a lot of information on its meaning and I'm not knowledgeable enough about Rust to go further.

Thank you

**Comment by animalsiknow** [comment]
One more detail, the bug happens in both debug and release, and on stable and nightly.

**Comment by sfackler** [comment]
Hmm, this seems like it'd be a compiler bug. Do you have some code that does reproduce the issue?

**Comment by animalsiknow** [comment]
> Hmm, this seems like it'd be a compiler bug. Do you have some code that does reproduce the issue?

I wasn't able to reproduce it in a test, but I'll try to extract the SSL code from my application.

**Comment by animalsiknow** [comment]
I created a small application that demonstrates the issue: https://github.com/animalsiknow/issue-1115

**Comment by sfackler** [comment]
Wow, that is *really* weird. I'll investigate!

**Comment by sfackler** [comment]
Ah, this is basically the same as #979 I think!

The code calls `set_new_session_callback` twice - once via `ContextBuilder<SslContextBuilder>` and once via `ContextBuilder<SslAceptorBuilder>`. When the closure is defined in `ContextBuilder::new`, you end up with distinct closure types, but if it's defined in a separate non-generic function there's only one.

The trouble comes when we swap the server's context out in the servername callback, as it's probably doing something like calling the original context's callback with the new context's ex_data or vice versa.

**Comment by sfackler** [comment]
That is the problem: https://github.com/openssl/openssl/blob/7c3a7561b536264b282f604efc959edad18807d7/ssl/ssl_lib.c#L3562

**Comment by animalsiknow** [comment]
Interesting, so only setting the callback for the acceptor would not work either since the ex_data would be completely missing instead of being under the "wrong" key. The workaround of setting the exact same closure type work well enough for now.

Do you still plan to implement [the solution you proposed in #979](https://github.com/sfackler/rust-openssl/issues/979#issuecomment-416338072)? Tell me if you need help with it.

Thanks a lot for looking into this!

**Comment by sfackler** [comment]
I think I'm going to fix it by sticking the session context directly into the SSL's ex_data when we construct it as a temporary work around, and then also file an issue upstream to provide an accessor for the session context.
