### ISSUE TITLE
Add a root metadata key to support cmake-rs

### ISSUE THREAD

**Issue by BusyJay** [sfackler/rust-openssl#1117]
cmake-rs uses key `DEP_OPENSSL_ROOT` to locate the package. It will be helpful if the build script of openssl-sys print a metadata key `cargo:root=install_dir` when vendored features is enabled. So that users can just call `config.register_dep("openssl")` to reuse the package instead of hacking around.

**Comment by sfackler** [comment]
Does cmake not support split installs, where the lib directory isn't in the same place as the include directory?

**Comment by BusyJay** [comment]
It does. But I don't see how is it related to this issue.

**Comment by sfackler** [comment]
Rather than special casing vendored builds, it seems like we should just emit the locations of the include and lib directories separately. The include directory is already done via DEP_OPENSSL_INCLUDE: https://github.com/sfackler/rust-openssl/blob/master/openssl-sys/build/main.rs#L68

**Comment by BusyJay** [comment]
I'm not sure if you can configure the include and library path separately. The default [FindOpenSSL](https://github.com/Kitware/CMake/blob/master/Modules/FindOpenSSL.cmake) module does support different paths by guessing the common path. The only public interface is to configure OPENSSL_ROOT_DIR which is expected to contains both include directory and lib directory.

**Comment by sfackler** [comment]
Oh yeah, that makes sense. If it's not vendored, FindOpenSSL should be able to find it anyway.
