### ISSUE TITLE
[Feature] Expose RFC 3394 (AES_wrap_key) functionality

### ISSUE THREAD

**Issue by russelltg** [sfackler/rust-openssl#1120]
It would be very useful to have access to AES_wrap_key. 

I'm willing to help implement this, but would need a bit of mentoring on how the rust API should be laid out.

**Comment by sfackler** [comment]
I think it'd just look something like this in aes.rs:

```rust
pub fn wrap_key(key: &AesKey, iv: Option<[u8; 8]>, out: &mut [u8], in: &[u8]) -> Result<usize, ErrorStack> { ... }

pub fn unwrap_key(key: &AesKey, iv: Option<[u8; 8]>, out: &mut [u8], in: &[u8]) -> Result<usize, ErrorStack> { ... }
```

With some asserts about the sizes of out and in (in must be a multiple of 8 bytes, and out must be at least 8 bytes larger than in for wrap_key and at least 8 bytes smaller for unwrap_key.
