### ISSUE TITLE
Support LibreSSL v3.0.0

### ISSUE THREAD

**Issue by protoCall7** [sfackler/rust-openssl#1121]
OpenBSD-current is currently shipping with LibreSSL 3.0.0.

openssl-sys 0.9.47 fails to build on LibreSSL newer than 2.9.1.

Please add support for building against LibreSSL 3.0.0.

**Comment by glebpom** [comment]
@sfackler Could you please release the new version of `openssl-sys` with LibreSSL 3.0.0 support?

**Comment by sfackler** [comment]
Done!

**Comment by glebpom** [comment]
Thanks!
