### ISSUE TITLE
cargo build --release promt run pkg_config fail: "`\"pkg-config\" \"--libs\" \"--cflags\" \"openssl\"` did not exit successfully: exit code: 1\n--- stderr\nPackage openssl was not found in the pkg-config search path.\nPerhaps you should add the directory containing `openssl.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'openssl\' found\n"

### ISSUE THREAD

**Issue by chenzhenglin2** [sfackler/rust-openssl#1129]
$HOST = x86_64-unknown-linux-gnu
$TARGET = x86_64-unknown-linux-gnu
openssl-sys = 0.9.47

', /root/.cargo/registry/src/mirrors.ustc.edu.cn-15f9db60536bad60/openssl-sys-0.9.47/build/find_normal.rs:150:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by sfackler** [comment]
https://docs.rs/openssl/0.10.23/openssl/#automatic
