### ISSUE TITLE
Not compiling with i686-linux-android target

### ISSUE THREAD

**Issue by imerkle** [sfackler/rust-openssl#1145]
> --- stdout
> cargo:rustc-cfg=const_fn
> cargo:rerun-if-env-changed=I686_LINUX_ANDROID_OPENSSL_LIB_DIR
> I686_LINUX_ANDROID_OPENSSL_LIB_DIR unset
> cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
> OPENSSL_LIB_DIR unset
> cargo:rerun-if-env-changed=I686_LINUX_ANDROID_OPENSSL_INCLUDE_DIR
> I686_LINUX_ANDROID_OPENSSL_INCLUDE_DIR unset
> cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
> OPENSSL_INCLUDE_DIR unset
> cargo:rerun-if-env-changed=I686_LINUX_ANDROID_OPENSSL_DIR
> I686_LINUX_ANDROID_OPENSSL_DIR unset
> cargo:rerun-if-env-changed=OPENSSL_DIR
> OPENSSL_DIR unset
> run pkg_config fail: "Cross compilation detected. Use PKG_CONFIG_ALLOW_CROSS=1 to override"
> 
> --- stderr
> thread 'main' panicked at '
> 

> Could not find directory of OpenSSL installation, and this `-sys` crate cannot
> proceed without this knowledge. If OpenSSL is installed and this crate had
> trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
> compilation process.
> 
> Make sure you also have the development packages of openssl installed.
> For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.
> 
> If you're in a situation where you think the directory *should* be found
> automatically, please open a bug at https://github.com/sfackler/rust-openssl
> and include information about your system as well as this message.
> 

> $HOST = x86_64-unknown-linux-gnu
> $TARGET = i686-linux-android
> openssl-sys = 0.9.48
> 

On adding `OPENSSL_DIR` it says `OpenSSL library directory does not exist: /usr/include/openssl/lib`

**Comment by sfackler** [comment]
You need to point `OPENSSL_DIR` to a directory that contains an OpenSSL distribution cross compiled for Android. You can alternatively enable the `vendored` feature to have the crate build one for you.
