### ISSUE TITLE
Is the goal to rewrite library calls in pure Rust?

### ISSUE THREAD

**Issue by kevinburke** [sfackler/rust-openssl#1146]
Hi,
Is it a goal of this project to eventually rewrite (some of/all) the library calls in plain Rust? Or is this always going to remain a wrapper around the C library?

**Comment by sfackler** [comment]
The goal of this project is to provide a safe interface to OpenSSL.

**Comment by shinmao** [comment]
@sfackler I am still interested in this question. To get a tradeoff between the goal of this project (providing a safe interface) and avoiding unnecessary rewriting API in C. How did you decide on the rewriting steps? For example, rewriting specific API in pure Rust, or some other API should be kept in C and called with ffi. Could you share some of your ideas in your free time? Thanks!

**Comment by shinmao** [comment]
@Skepfyr Thanks for the response. My question is that if we just aim to provide a thin wrapper on top of OpenSSL in C, we won't be able to get Rust's benefit of memory safety because the core features (e.g., memory management) are still in C. Is my assumption correct?

**Comment by Skepfyr** [comment]
We appear to be able to achieve both, have a look at the API but it seems to me that it's succeeded at being lightweight and reasonably idiomatic Rust.
