### ISSUE TITLE
RustCrypto Traits

### ISSUE THREAD

**Issue by AxelNennker** [sfackler/rust-openssl#1148]
Have you considered to implement rust-openssl so that it implements these traits?
https://github.com/RustCrypto/traits

**Comment by sfackler** [comment]
OpenSSL's APIs don't align cleanly with rust-crypto's.

**Comment by AxelNennker** [comment]
I was on vacation when you commented and closed this. Thanks for looking into it.
Do you see a chance that somebody from the contributors agrees to adjust the trait to allow openssl's implementation of e.g. sha256 align cleanly?
https://github.com/RustCrypto/traits/graphs/contributors

I think the Rust cryptography ecosystem would benefit if we had a common set of traits e.g. for digests

**Comment by newpavlov** [comment]
@sfackler 
Can you be more concrete? After a cursory look I think implementing [`digest`](https://docs.rs/digest) traits should be fairly trivial.

Either way, we are open to API changes, next version changes are discussed in RustCrypto/traits#43.

**Comment by sfackler** [comment]
The Hasher type uses fallible methods and has a non-fixed output size https://docs.rs/openssl/0.10.25/openssl/hash/struct.Hasher.html

**Comment by newpavlov** [comment]
You always can panic if initialization has failed or algorithm has returned a wrong number of bytes (I don't think the latter should be possible in practice though). We may add fallible initialization methods in future, since they are also can be useful if algorithm is executed on an external hardware.

Also, algorithms in the [`sha`](https://docs.rs/openssl/0.10.25/openssl/sha/index.html) module do not have those issues.

**Comment by sfackler** [comment]
What is the "wrong number" of bytes? `Hasher::new(MessageDigest::sha1())` will return 20 bytes, while `Hasher::new(MessageDigest::sha256())` will return 32 bytes.

**Comment by newpavlov** [comment]
You said it yourself:
>Hasher type <..> has a non-fixed output size
So type system does not enforce the fact that `Hasher::new(MessageDigest::sha256())` returns 32 bytes, so you'll have to check it during runtime.

**Comment by sfackler** [comment]
```rust
impl Digest for Hasher {
    type OutputSize = /* what goes here? */
}
```

**Comment by newpavlov** [comment]
You should not implement `Digest` for `Hasher`, instead you need to define ZST types for each supported algorithm and implement `Digest` for them using `Hasher` under the hood. A good starting point would be to implement `digest` traits for types in the `sha` module.

Also note that you should not implement `Digest` trait directly, it's just a convinience wrapper around `Input`, `FixedOutput`, and `Reset` traits (i.e. you should implement them and `Digest` will be implemented via the [blanket impl](https://docs.rs/digest/0.8.1/src/digest/digest.rs.html#48-86)).

**Comment by newpavlov** [comment]
To be clear: I do not argue that RustCrypto traits should be implemented as part of the `openssl` crate, just trying to clarify the API. Even as an optional dependencies, I guess many will not like having RustCrypto crates in the `openssl` dependency tree even in an optional, disabled by default form. So doing it in a separate "bridge" crate probably will be a better approach.

**Comment by AxelNennker** [comment]
Something like https://github.com/RustCrypto/hashes/blob/master/sha2/src/sha256.rs#L92
