### ISSUE TITLE
DTLS MTU does not properly handled

### ISSUE THREAD

**Issue by HyeonuPark** [sfackler/rust-openssl#1155]
I'm using `openssl` crate for DTLS-SRTP key exchange mechanism, and I found that it uses 288 bytes as the maximum outbound packet size. As a result, handshake packets are fragmented which may increase the chance of handshake loss.

DTLS MTU handling is done via the callback function passed from `BIO_meth_set_ctrl` function, with `BIO_CTRL_DGRAM_*` family of commands. It seems that rust-openssl crate just ignores these commands currently.

Do you have some plan to handle it? If you don't have one yet, I can suggest three ways to implement this feature in `openssl` crate.

1. Implement MTU discovery feature

    It seems like the most ideal way IMO, though it can be hard. I can't say how hard it would be as I don't investigate this way that much, but at least it seems [openssl has some code for it](https://github.com/openssl/openssl/blob/8c47e55ee69500e31e80458682c6e022294cd0be/crypto/bio/bss_dgram.c#L454).

1. Allow users to configure MTU size

    Simply let users configure MTU size. Based on my small experiment it's just enough to respond to `BIO_CTRL_DGRAM_QUERY_MTU` command, so just add another if arm to the [ctrl function](https://github.com/sfackler/rust-openssl/blob/4c1891cc1085282acd8fa9820d81fb84d87b6e4e/openssl/src/ssl/bio.rs#L137), and blindly returns user-provided value, fallback to zero or some default value if not configured.

1. Always returns google-selected default MTU size

    This is the simplest one: always return `1200` for it. [Google uses it as default MTU size for WebRTC](https://groups.google.com/forum/#!topic/discuss-webrtc/gH5ysR3SoZI) so it should be OK for most use cases.

**Comment by sfackler** [comment]
I think option 2 seems cleanest.

**Comment by TimonPost** [comment]
I have a question around this topic, so I am currently implementing [DTLSv1_listen](https://github.com/TimonPost/udp-dtls/issues/2), although, I keep getting the error 

`ErrorStack([Error { code: 336978321, library: "SSL routines", function: "DTLSv1_listen", reason: "fragmented client hello", file: "../ssl/d1_lib.c", line: 623 }])`.

I am searching for solutions, and some say I have to set the MTU size, so I tried this PR, but it does not work. 

First, they said I could use: 

```
SSL_CTX_set_options(ctx, SSL_OP_NO_QUERY_MTU); 
```
and 
```
SSL_set_mtu(ssl, <big_value_here>);
```

Questions: 

1. How does this PR change any kind of MTU setting, from what I can tell I can only see that it changes a struct field. 
2. Any idea why this can happen?
