### ISSUE TITLE
Multiple encryptions/decryption without initing the Crypter

### ISSUE THREAD

**Issue by YangZhou1997** [sfackler/rust-openssl#1156]
Hi community, 

I am using openssl-rust for decrypting each network packet. From my measurement in the following code, the Crypter initing will cost 0.5us per packet while the real decryption and authentication take 3us. I was wondering is there any function that can reset the inner encryption/decryption state of AES-GCM Crypter, so that I do not need to create a new Crypter for each packet. 

Thanks in advance! 
Yang

```
#[inline]
pub fn my_decrypt_gcm(
    aad: &[u8],
    data: &[u8],
    tag: &[u8]
) -> Result<Vec<u8>, ErrorStack> {
    let mut out = vec![0; data.len() + 16];
    let start = Instant::now();

    let cipher = Cipher::aes_128_gcm();
    let mut c = Crypter::new(cipher, Mode::Decrypt, AES_KEY, Some(AES_IV)).unwrap();
    
    let duration = start.elapsed();
    println!("DEC: {:?}", duration);
    
    c.aad_update(aad)?;
    let count = c.update(data, &mut out)?;
    c.set_tag(tag)?;
    let rest = c.finalize(&mut out[count..])?;
    out.truncate(count + rest);

    let duration = start.elapsed();
    println!("DEC: {:?}", duration);

    Ok(out)
}
```

**Comment by sfackler** [comment]
We could add a method to reset the crypter, but I don't know how much it would actually save, since the key and IV would have to be passed in again.

Also, you should be aware that using the same key and IV to encrypt two messages catastrophically breaks AES-GCM. A hardcoded IV is not a good way to go.

**Comment by sfackler** [comment]
The new CipherCtx type provides direct access to the underlying OpenSSL functions.
