### ISSUE TITLE
how to check if a certificate is expired

### ISSUE THREAD

**Issue by Geal** [sfackler/rust-openssl#1157]
the [X509 struct](https://docs.rs/openssl/0.10.24/openssl/x509/struct.X509.html) has [not_after and not_before](https://docs.rs/openssl/0.10.24/openssl/x509/struct.X509.html#method.not_after) methods to get the certificates validity dates.
But how should the [Asn1Time](https://docs.rs/openssl/0.10.24/openssl/asn1/struct.Asn1Time.html) type be used?
My main use case is in the code managing a list of certificates, deciding which ones to load, and I want to manage expired certificates separately, but apparently I can't compare a `Asn1Time` to the current date

**Comment by sfackler** [comment]
I think we should add `Eq`/`Ord` impls for Asn1Time backed by `ASN1_TIME_diff`.

**Comment by axos88** [comment]
So the original issue seems to be fixed. But how about converting the Asn1TimeRef to std::time::SystemTime?

Right now the best I see is to convert it to string, and parse it.... Umm?

**Comment by axos88** [comment]
```
        let expiry: &Asn1TimeRef = cert.not_after();
        let threshold = Asn1Time::days_from_now(0).unwrap();

         if (expiry < threshold) { 
            panic!("OMG EXPIRED!")
         }   
```

**Comment by Cl00e9ment** [comment]
> So the original issue seems to be fixed. But how about converting the Asn1TimeRef to std::time::SystemTime?

I found this way to convert an `Asn1TimeRef` to a `SystemTime`:

```rust
fn asn1_time_to_system_time(time: &Asn1TimeRef) -> Result<SystemTime, ErrorStack> {
    let unix_time = Asn1Time::from_unix(0)?.diff(time)?;
    Ok(SystemTime::UNIX_EPOCH + Duration::from_secs(unix_time.days as u64 * 86400 + unix_time.secs as u64))
}
```
