### ISSUE TITLE
OpenSSL library not recognised

### ISSUE THREAD

**Issue by jithendaraa** [sfackler/rust-openssl#1159]
Was trying to compile fortanix-sgx-tools while the following error popped up:

`error: failed to run custom build command for` **openssl-sys v0.9.49**

`Caused by:`
  `process didn't exit successfully:` **C:\Users\jithe\AppData\Local\Temp\cargo-install9xRp5T\release\build\openssl-sys-6d154abb64a6e1ef\build-script-main** `(exit code: 101)
--- stdout`
`cargo:rustc-cfg=const_fn`
`cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_MSVC_OPENSSL_LIB_DIR`
`X86_64_PC_WINDOWS_MSVC_OPENSSL_LIB_DIR unset`
`cargo:rerun-if-env-changed=OPENSSL_LIB_DIR`
`OPENSSL_LIB_DIR unset`
`cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_MSVC_OPENSSL_INCLUDE_DIR`
`X86_64_PC_WINDOWS_MSVC_OPENSSL_INCLUDE_DIR unset`
`cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR`
`OPENSSL_INCLUDE_DIR unset`
`cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_MSVC_OPENSSL_DIR`
`X86_64_PC_WINDOWS_MSVC_OPENSSL_DIR unset`
`cargo:rerun-if-env-changed=OPENSSL_DIR`
`OPENSSL_DIR = C:\OpenSSL-Win64`

`--- stderr`
`thread 'main' panicked at 'OpenSSL library directory does not exist: C:\OpenSSL-Win64\lib', `**C:\Users\jithe\.cargo\registry\src\github.com-1ecc6299db9ec823\openssl-sys-0.9.49\build/main.rs:52:9**
`note: run with` **RUST_BACKTRACE=1** `environment variable to display a backtrace.`

`warning: build failed, waiting for other jobs to finish...
error: failed to compile` **fortanix-sgx-tools v0.2.0**`, intermediate artifacts can be found at `**C:\Users\jithe\AppData\Local\Temp\cargo-install9xRp5T**

`Caused by:
  build failed`

**Path Variables**
`OPENSSL_DIR: C:\OpenSSL-Win64`
`OPENSSL_CONF: C:\Programs Files (x86)\OpenSSL-Win32\bin\openssl.cnf`

**Comment by sfackler** [comment]
Does `C:\OpenSSL-Win64\lib` exist? `OPENSSL_DIR` needs to point to a directory that has `lib` and `include` subdirectories containing the OpenSSL libraries and headers respectively.

**Comment by jithendaraa** [comment]
Yep, it exists. OPENSSL_DIR points to a directory that contains bin, lib and include subdirs pointing to .exe, libraries and headers respectively

**Comment by jithendaraa** [comment]
Thanks, the lib and include folders weren't present before. Once I got them in place, it worked
