### ISSUE TITLE
Multiple UDP-connections with DTLS?

### ISSUE THREAD

**Issue by TimonPost** [sfackler/rust-openssl#1162]
For a [project](https://github.com/TimonPost/udp-dtls), I want to set up DTLS over UDP. I get stuck on the part how to handle 'multiple' connections over a UDP socket. The scenario is that there is a server that can have multiple connections that are not known in advance. I have tried to look for examples, and for issues in the past. I got it to work with a single known connection.

- [tests.rs](https://github.com/sfackler/rust-openssl/commit/0b1c2a10487dcec813b75cfc21e8804ae10ebe1b#diff-68644088d256285b8c671d01a528ee58)
- [issue 1](https://github.com/sfackler/rust-openssl/issues/528)
- [issue 2](https://github.com/sfackler/rust-openssl/issues/985)

The advice was "If you want to use the same socket for all of them, you'll need to have some extra state which routes based on the peer address I suppose", would you like to go into this and give more details? I don't really have a good idea what you mean by this.

**Comment by sfackler** [comment]
I think @Ralith has done this for a QUIC implementation, you might want to ask them.

**Comment by sfackler** [comment]
The [DTLSv1_listen](https://www.openssl.org/docs/man1.1.1/man3/SSL_stateless.html) function's documentation talks about how this is generally done. We don't currently expose that method, but I can add that.

**Comment by Ralith** [comment]
QUIC actually doesn't use DTLS at all, but rather interweaves itself with the TLS state machine in a fairly invasive manner, providing its own transport and framing in place of the TLS record layer.

**Comment by TimonPost** [comment]
I am [working ](https://github.com/sfackler/rust-openssl/compare/master...TimonPost:dtls_listen?expand=1) on a [solution ](https://github.com/TimonPost/udp-dtls/compare/multiple_connections?expand=1) using ` DTLSv1_listen`. I almost have a working example up and running.  However, I could use some help.

My work is based on: multiple connections C example:
https://web.archive.org/web/20150814081716/http://sctp.fh-muenster.de/dtls-samples.html

I did an implementation that throws an error when the client connects to the server. 

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorStack([Error { code: 336978320, library: "SSL routines", function: "DTLSv1_listen", reason: "cookie gen callback failure", file: "ssl\\d1_lib.c", line: 700 }])'
```

I have a few questions about this:

1. What does that error mean?
2. What is the difference between: DLS_method(), DLS_server_method(), DLS_client_method(). 
rust-openssl does not provide support to select this option, however, the above-linked example does use this.

**Comment by sfackler** [comment]
DTLS_method supports both client and server connections, while the other methods only support one or the other.
