### ISSUE TITLE
Failes to compile on ubuntu latest with openssl 1.1.1

### ISSUE THREAD

**Issue by Licenser** [sfackler/rust-openssl#1164]
compiling on ubuntu-latest w/ openssl 1.1.1 (default) results in the follwoing error:

```
  process didn't exit successfully: `/code/target.cov/debug/build/openssl-ae4e715c32d1a697/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Unable to detect OpenSSL version', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.9.24/build.rs:16:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```
```
root@9488cd9f064b:/code# openssl version
OpenSSL 1.1.1  11 Sep 2018
```

**Comment by sfackler** [comment]
Do you have openssl headers and pkg-config installed?

**Comment by Licenser** [comment]
It is using openssl10:
```
cargo tree | grep openssl
│       ├── openssl v0.10.24
│       │   └── openssl-sys v0.9.49
├── openssl v0.10.24 (*)
```

**Comment by Licenser** [comment]
I stand corrected somewhere a old version snuck in! The wonder of multi crate projects :/ Sorry.

**Comment by Licenser** [comment]
I stand doubly corrected, all sub crates use openssl v10.* I misread a -sys as a 
```
cargo tree --all | grep openssl | grep -v -- '-sys'
│       ├── openssl v0.10.24
│       ├── openssl v0.10.24
├── openssl v0.10.24
    ├── openssl v0.10.24
```

**Comment by Licenser** [comment]
@sfackler could we re-open this as I was overly enthusiastic about declaring it an old version?

**Comment by sfackler** [comment]
It is definitely an old version:

> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.9.24/build.rs

**Comment by Licenser** [comment]
Good point, I did some additional digging and it turns out that a sub crate includes a old version of native-tls, which on osx doesn't depend on openssl, but on linux does. Sneaky! Thanks for your help :)
