### ISSUE TITLE
Could not find directory of OpenSSL installation,

### ISSUE THREAD

**Issue by worikgh** [sfackler/rust-openssl#1168]

**Comment by sfackler** [comment]
Do you have OpenSSL headers and pkg-config installed?

**Comment by worikgh** [comment]
Yes.  
I fixed it by:
`PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig/` at the start of my command.
I could not figure out how to delete a issue I opened on GitHub so just deleted the text.
