### ISSUE TITLE
openssl-sys readme is misleading about version support

### ISSUE THREAD

**Issue by FauxFaux** [sfackler/rust-openssl#1169]
The `openssl-sys` readme, visible on https://crates.io/crates/openssl-sys , says:

> The current supported release is 0.10. .. After a new release, the previous major version will be partially supported with bug fixes for 3 months, after which support will be dropped entirely.

Unfortunately, 0.9 is the currently supported version of `openssl-sys`, and 0.10 does not exist (and doesn't need to?).

**Comment by sfackler** [comment]
Ah yeah, that should say that 0.10 is the supported `openssl` version, and 0.9 is the supported `openssl-sys` version.
