### ISSUE TITLE
Add support for compiling on ubuntu without needing pkg-config/libssl-dev

### ISSUE THREAD

**Issue by jrmuizel** [sfackler/rust-openssl#1177]
pkg-config and libssl-dev aren't installed by default, so it would be nice if we could fallback to making an assumption about where libssl will lives so that the native-tls crate has a similar ease-of-use on linux as it does on other platforms.

**Comment by sfackler** [comment]
We need libssl-dev to know what version of OpenSSL we're linking against. I'm not really interested in maintaining a mapping of every version of every Linux distro's OpenSSL configuration.

If you want to avoid installing pkg-config you can enable the `vendored` feature to build OpenSSL from scratch instead.
