### ISSUE TITLE
when will we build openssl successfully?

### ISSUE THREAD

**Issue by swoopertr** [sfackler/rust-openssl#1182]

**Comment by sfackler** [comment]
I don't understand your question.

**Comment by swoopertr** [comment]
i mean build-failing. the real reason i want to use actix-web. And it contains rust-openssl package. Cant build.

**Comment by sfackler** [comment]
There are many reasons a build can fail. Can you provide some information about how your build is failing?

**Comment by swoopertr** [comment]
this is interesting, i have old version of rust which is 1.35 and tomorrow i updated to 1.39. doesnt work. Today its works. thanks anyway.
