### ISSUE TITLE
Request to expose SSL_CTX_set1_groups_list and SSL_CTX_set1_sigalgs_list

### ISSUE THREAD

**Issue by JRF63** [sfackler/rust-openssl#1186]
Possibly related to #947. I think those (and related) functions are currently the only way to restrict key-exchange/signatures to Curve448 and Curve25519.

```C
// SSL_CTX* ctx = ...;
SSL_CTX_set1_groups_list(ctx, "X25519"); // limit ECDH to Curve25519
SSL_CTX_set1_sigalgs_list(ctx, "ed448"); // likewise ECDSA to Curve448
```

I have a more complete example in C if needed.

**Comment by sfackler** [comment]
Seems reasonable to me! I'll throw something together today hopefully.
