### ISSUE TITLE
Impossible to convert Signature Vec<u8> into a string

### ISSUE THREAD

**Issue by ogonbat** [sfackler/rust-openssl#1188]
Hi All

I have the following method to get the signature from an HashSet of String messages

`

         pub fn sign_message(messages: HashSet<&String>, key_path: &str) -> Result<Vec<u8>, ErrorStack>{

            let private_key = read_private_key(key_path);

            let mut signer = Signer::new(MessageDigest::sha256(), &private_key).unwrap();

            for message in messages {

                 let bytes_message = message.clone();

                 signer.update(bytes_message.as_bytes());

            }

            signer.sign_to_vec()

        }
`
the return is a Result with the Vec<u8> and i want to transform in a String in this way:

`

    let signature = sign_message(hash_peer, "key");
    match signature {
        Ok(sig_correct) => {
           let signature_string = String::from_utf8(sig_correct);
           ........

`
The String::from_utf8 return an error because seems that the Binary Vector is not well formatted.

Do you have experienced something like that?
i do something wrong?

Thanks in advance for your help

**Comment by sfackler** [comment]
The signature is a buffer of raw bytes. If you want to encode it as a string, you'll need to decide how exactly you want to do that. Do you want to hex encode it? base64 encode it? etc.

**Comment by ogonbat** [comment]
Hi @sfackler 

thanks for your reply.
I need to send the signature to an external node and i want to send it as a "text" format and from that reconvert to a signature "object" for a validation.
I hope i have explained why i need to convert it to a String.

**Comment by sfackler** [comment]
Again, if you want to encode raw bytes as a string, you need to decide what encoding you want to use. There are crates available for many common formats like [hex](https://crates.io/crates/hex) and [base64](https://crates.io/crates/base64).

**Comment by ogonbat** [comment]
Yes you are right I have used hex and all work well now,

Thanks for your help :-)
