### ISSUE TITLE
openssl_errors::openssl_errors!{} expansion triggers clippy::empty_enum pedantic lint

### ISSUE THREAD

**Issue by arsing** [sfackler/rust-openssl#1189]
```rust
openssl_errors::openssl_errors! {
    library Error("my_crate") {
        functions { FOO("foo"); }
        reasons { BAR("bar"); }
    }
}
```

expands to:

```rust
enum Error { }
impl ::openssl_errors::Library for Error {
...
```

This empty enum triggers the [`clippy::empty_enum`](https://rust-lang.github.io/rust-clippy/master/index.html#empty_enum) pedantic lint.

It would be nice if the macro emitted `#[allow(clippy::empty_enum)]` on it.

---

Workaround:

```rust
#[allow(clippy::empty_enum)]
mod errors {
    openssl_errors::openssl_errors! {
        pub(super) library Error("my_crate") {
            functions { FOO("foo"); }
            reasons { BAR("bar"); }
        }
    }
}
use errors::Error;
```

(The mod is needed because just applying the `#[allow]` to the macro invocation doesn't help, which is to be expected.)

**Comment by sfackler** [comment]
That seems like a pretty dubious lint (`!` isn't even stable as a type yet so the recommendation on that page isn't even actionable!).

**Comment by arsing** [comment]
Yes, I agree, but I've come to expect such from the pedantic clippy lints.

Also, I just noticed there's an easier workaround, because of https://github.com/sfackler/rust-openssl/blob/69b0092028534e0a19ba986059b4ec84e536b20e/openssl-errors/src/lib.rs#L202

**Comment by sfackler** [comment]
Yeah, you should be able to add the annotation yourself.
