### ISSUE TITLE
Yank version with "*" deps

### ISSUE THREAD

**Issue by kornelski** [sfackler/rust-openssl#1199]
An old version of `openssl-sys` has dependencies specified with `"*"` version requirement (`pkg-config = "*"`).

Crates with such vague dependency versions became unusable, because `*` allows picking too-new semver-incompatible dependencies.
It also breaks Cargo's `minimal-versions` feature, because `*` requirement allows picking very very old dependencies that aren't compatible with Rust 1.0.

Because this old version of `openssl-sys` is unusable and may cause problems for Cargo, I suggest yanking it:

```bash
cargo yank --vers 0.0.1
```

**Comment by sfackler** [comment]
That version is from 2014. I don't believe anyone is using it.
