### ISSUE TITLE
[Q] problem statically link rust project on armv7 with musl

### ISSUE THREAD

**Issue by iav** [sfackler/rust-openssl#1211]
I want to build rust project for armv7  statically linked. Project uses postgresql.
Currently it works as it should for x64 platform. Building uses docker container, there staticaly builds with `musl-gcc openssl, zlib` and `libpq`, then rust  project for `x86_64-unknown-linux-musl`, and it's ok. [x64 builder dockerfile](https://github.com/emk/rust-musl-builder/blob/master/Dockerfile)

Now I take x86 dockerfile, replace platform-related info from x86 to arm, and try to run on raspberry pi 3b+.
Seems I have to make additional configuration or workaround, because I get error on rust build:
```
$ CC=musl-gcc cargo build -v
.....
   Compiling diesel_migrations v1.4.0
     Running `rustc --crate-name diesel_migrations /home/rust/.cargo/registry/src/github.com-1ecc6299db9ec823/diesel_migrations-1.4.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C debuginfo=2 --cfg 'feature="default"' -C metadata=a4204e3fa8a28b14 -C extra-filename=-a4204e3fa8a28b14 --out-dir /home/rust/src/target/armv7-unknown-linux-musleabihf/debug/deps --target armv7-unknown-linux-musleabihf -L dependency=/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/deps -L dependency=/home/rust/src/target/debug/deps --extern migrations_internals=/home/rust/src/target/armv7-unknown-linux-musleabihf/debug/deps/libmigrations_internals-de855e7d9dd7a0d3.rmeta --extern migrations_macros=/home/rust/src/target/debug/deps/libmigrations_macros-bca2427864d91745.so --cap-lints allow -C target-feature=+crt-static -C link-arg=-lgcc -C link-arg=-lssl -C link-arg=-lcrypto -L native=/musl/lib`
error: /home/rust/src/target/debug/deps/libmigrations_macros-bca2427864d91745.so: undefined symbol: SSL_CTX_free
  --> /home/rust/.cargo/registry/src/github.com-1ecc6299db9ec823/diesel_migrations-1.4.0/src/lib.rs:82:1
   |
82 | extern crate migrations_macros;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Howshould I do all things correct?

Test program and Dockerfile I place there: https://github.com/iav/test2

**Comment by sfackler** [comment]
I'm not sure off the top of my head.

**Comment by iav** [comment]
Error was:
`error: /home/rust/src/target/debug/deps/libmigrations_macros-bca2427864d91745.so: undefined symbol: SSL_CTX_free`
` SSL_CTX_free` located in openssl library. I think it means something wrong with openssl crateand openssl library integration. But I am not sure. Possible error with `libmigrations_macros` and related libraries configuration.

How can I test openssl-sys and openssl.a configured correctly?

**Comment by sfackler** [comment]
That error is produced by the linker, which doesn't have anything to do with this library.

**Comment by iav** [comment]
Sure.
It means linker called with wrong env variables, or libraries created with wrong way. I not call for linker manualy, it's a rust and crate magic.
Can I see someway what linker try to link in real — with all defaults?

**Comment by iav** [comment]
Will libmigrations_macros crate use own data how to link with libssl.a, or will use data from openssl-sys?
I first ask from diesel authors, but they point me to openssl crate...

**Comment by sfackler** [comment]
openssl-sys tells the linker at most 2 things: to link the `crypto` and `ssl` libraries, and to look in an extra directory for those libraries if they aren't in the default search paths. That's it.

**Comment by iav** [comment]
In my case of a cross-compilation and static linking — should it be path with host dynamic libraries (/usr/lib, *.so, glibc-based) or TARGET (/musl/lib, *.so or *.a, musl-based)? Now I build in /musl musl-based openssl static and dynamic, but nothing changed.

**Comment by sfackler** [comment]
libmigrations-macros is I believe a compiler plugin so that's going to be compiled for the host, not the target.
