### ISSUE TITLE
Asn1TimeRef vs Asn1Time

### ISSUE THREAD

**Issue by axos88** [sfackler/rust-openssl#1220]
Shouldn't `Asn1Time` implement `Borrow<Asn1TimeRef>`? Currently it's possible to print an Asn1TimeRef, but not an Asn1Time.

**Comment by sfackler** [comment]
`Asn1Time` does implement `Borrow<Asn1TimeRef>`: https://docs.rs/openssl/0.10.26/openssl/asn1/struct.Asn1Time.html

**Comment by axos88** [comment]
That's odd:

```
        let expiry: &Asn1TimeRef = cert.not_after();
        let threshold = Asn1Time::days_from_now(cfg.ttl_secs as u32 / 86400).unwrap();

        format!("{}", expiry);
        format!("{} {}", expiry, threshold);
```

```
error[E0277]: `openssl::asn1::Asn1Time` doesn't implement `std::fmt::Display`
  --> src/<snip>/acme.rs:72:34
   |
72 |         format!("{} {}", expiry, &threshold);
   |                                  ^^^^^^^^^^ `openssl::asn1::Asn1Time` cannot be formatted with the default formatter
```

**Comment by sfackler** [comment]
format doesn't call Borrow. You'd need to do `&*threshold` to get down to an Asn1TimeRef. We should probably implement Display directly for Asn1Time though.

**Comment by axos88** [comment]
Sorry, I edited my code, might have answered to the wrong version

**Comment by axos88** [comment]
&*threshold works though.

**Comment by axos88** [comment]
But why? :)

**Comment by sfackler** [comment]
It uses the Deref impl to get a &Asn1TimeRef from an Asn1Time. Asn1TimeRef implements Display so it works with format.

**Comment by axos88** [comment]
Ah right, I was confusing Borrow with Deref.
