### ISSUE TITLE
envelope decryption should use `EVP_DecryptInit_ex()` and `EVP_DecryptFinal_ex()` for symmetric key encryption

### ISSUE THREAD

**Issue by vandenoever** [sfackler/rust-openssl#1223]
Currently, `openssl::envelope::Open` uses `EVP_OpenInit()`, `EVP_DecryptUpdate()`, and `EVP_OpenFinal()`. The openssl documentation says that

`EVP_OpenInit()`, `EVP_OpenUpdate()`, and `EVP_OpenFinal()`

or

`EVP_DecryptInit_ex()`, `EVP_DecryptUpdate()`, and `EVP_DecryptFinal_ex()`

can be used together.

Currently, the openssl binding does not seem to support using envelopes encryption and decryption with symmetric keys.

**Comment by sfackler** [comment]
EVP_OpenUpdate is just a macro for EVP_DecryptUpdate: https://github.com/openssl/openssl/blob/2ee4a50ab92020dc49383d5aa644397edac4a59a/include/openssl/evp.h#L543.
