### ISSUE TITLE
process didn't exit successfully

### ISSUE THREAD

**Issue by Sajjad-Taghinezhad** [sfackler/rust-openssl#1224]
hi 
when i use reqwest in my dependencies and run cargo show this error 

Caused by:
  process didn't exit successfully: `/home/*****/WorkSpace/Programming/Rust/target/debug/build/openssl-sys-a0c7088479c7c326/build-script-main` (exit code: 101)
--- stdout
cargo:rustc-cfg=const_fn
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR
X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR unset
cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
OPENSSL_LIB_DIR unset
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR
X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR unset
cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
OPENSSL_INCLUDE_DIR unset
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR
X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR unset
cargo:rerun-if-env-changed=OPENSSL_DIR
OPENSSL_DIR unset
run pkg_config fail: "`\"pkg-config\" \"--libs\" \"--cflags\" \"openssl\"` did not exit successfully: exit code: 1\n--- stderr\nPackage openssl was not found in the pkg-config search path.\nPerhaps you should add the directory containing `openssl.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'openssl\' found\n"

--- stderr
thread 'main' panicked at '

Could not find directory of OpenSSL installation, and this `-sys` crate cannot
proceed without this knowledge. If OpenSSL is installed and this crate had
trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
compilation process.

Make sure you also have the development packages of openssl installed.
For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.

If you're in a situation where you think the directory *should* be found
automatically, please open a bug at https://github.com/sfackler/rust-openssl
and include information about your system as well as this message.

$HOST = x86_64-unknown-linux-gnu
$TARGET = x86_64-unknown-linux-gnu
openssl-sys = 0.9.53

', /home/****/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.53/build/find_normal.rs:150:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Please tell me what to do
Thank You
Sajjad

**Comment by sfackler** [comment]
Like the error message says, you need to have the OpenSSL development package installed.

**Comment by Sparkenstein** [comment]
I was facing the same issue. In my case, I solved it with installing `pkg-config` on Ubuntu. Also make sure you have `libssl-dev` installed. to find your openssl directory, you can run `openssl version -d` just in case you want to set `OPENSSL_DIR` env variable

**Comment by Sajjad-Taghinezhad** [comment]
> Like the error message says, you need to have the OpenSSL development package installed.



> I was facing the same issue. In my case, I solved it with installing `pkg-config` on Ubuntu. Also make sure you have `libssl-dev` installed. to find your openssl directory, you can run `openssl version -d` just in case you want to set `OPENSSL_DIR` env variable

thank you for helping.

**Comment by creater303** [comment]
l nave meet the same problem l have installed openssl 
thanks a lot
