### ISSUE TITLE
How to implement set_servernam_callback / set_clienthello_callback cor

### ISSUE THREAD

**Issue by axos88** [sfackler/rust-openssl#1228]
What is the correct way to create the ssl context in the client_hello_callback? There doesn't seem to be a way to unwrap an SslAcceptor into an SslContext. I can Deref it, but build needs to move the value, a reference is not enough. Do I need to create one from scratch?

I'm trying to implement SNI. This is what I have so far:
```
            let mut ssl: SslAcceptorBuilder = SslAcceptor::mozilla_intermediate(SslMethod::tls())?;

            ssl.set_private_key_file(unimplemented!(), SslFileType::PEM);
            
            ssl.set_client_hello_callback(|mut sslref, mut sslalert| {               
                info!("servername = {:?}", sslref.servername(NameType::HOST_NAME));

                //1.
                let mut builder = SslAcceptor::mozilla_intermediate(SslMethod::tls()).unwrap();
                builder.set_private_key_file(unimplemented!(), SslFileType::PEM);
                builder.set_certificate_chain_file(unimplemented!());

                let mut builder = builder.into_ssl_context_builder(); // This function doesn't exist

                //2.
                let mut builder = SslContextBuilder::from_context(sslref.ssl_context());// This function doesn't exist
                builder.set_certificate_chain_file(unimplemented!());

                sslref.set_ssl_context(builder.build());
                Ok(ClientHelloResponse::SUCCESS)
            });
```

**Comment by sfackler** [comment]
It seems reasonable to add methods on `SslConnector`/`SslAcceptor` to get a reference to the inner `SslContext`.

**Comment by axos88** [comment]
Gotcha, thanks. So I'd need to fork & create a PR for that, I guess. 

Btw, do I need to create a whole new context in the callback, or would most of the settings, such as ciphers, etc. be inherited from the "parent" context?

I find openssl documentation extremely lacking, to the point which is frightening...

**Comment by sfackler** [comment]
I think you'd typically create the set of contexts at application start, and just select the right one and slot it in in your callback.

Yep, the state of OpenSSL's documentation is not great. I pretty often just go to the source code to figure out exactly what something's doing.

**Comment by axos88** [comment]
Gotcha thanks. I want to be able to change and add new certificates on the fly, as files are saved to disk, so I can't prepare a store at application start, unfortunately.

**Comment by axos88** [comment]
I've added the code I'll submit the PR after I get it working.
