### ISSUE TITLE
symm::Crypter::set_tag_len() does not work for AES CCM

### ISSUE THREAD

**Issue by egonny** [sfackler/rust-openssl#1237]
The [OpenSSL manpages](https://www.openssl.org/docs/man1.1.1/man3/EVP_DecryptFinal_ex.html#GCM-and-OCB-Modes) specify for `EVP_CTRL_AEAD_SET_TAG` that 

> The tag length can only be set before specifying an IV.

Since `Crypter` always sets its key and IV in `Crypter::new()`, it is impossible for `Crypter::set_tag_len()` to have any effect.

If you change the [test_aes128_ccm](https://github.com/sfackler/rust-openssl/blob/78012267960737944747e87e995d1eaa22c5b4fc/openssl/src/symm.rs#L1279) to have an `actual_tag` with a different length that 12 (the default length), like this 

    let mut actual_tag = [0; 10];

we should get an assertion error on the line

    assert_eq!(tag, hex::encode(actual_tag));

but instead, the test will error on the `unwrap()` a few lines before that

    running 1 test
    thread 'symm::tests::test_aes128_ccm' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorStack([])', openssl\src\symm.rs:1289:19

For some reason this only impacts CCM, not GCM.

**Comment by egonny** [comment]
To verify my theory, I patched `ffi::EVP_CTRL_GCM_SET_TAG` into `Crypter::new()`, after which the test with an adjusted tag length no longer fails.

**Comment by sfackler** [comment]
The new CipherCtx provides direct bindings to individual functions which should avoid this issue.
