### ISSUE TITLE
Incorrect encoding in extensions (SAN) 

### ISSUE THREAD

**Issue by dangerousplay** [sfackler/rust-openssl#1240]
Hi, I have observed a bug when creating a Subject Alternative Name (SAN) DNS, it seems like it expects an `IA5String` according to [RFC 5280](https://tools.ietf.org/html/rfc5280#section-4.2.1.6) and a `UTF-8` is used instead which leads to an incorrect encoding.

From the RFC section about Subject Alternative Names:
```
   SubjectAltName ::= GeneralNames

   GeneralNames ::= SEQUENCE SIZE (1..MAX) OF GeneralName

   GeneralName ::= CHOICE {
        otherName                       [0]     OtherName,
        rfc822Name                      [1]     IA5String,
        dNSName                         [2]     IA5String,
        x400Address                     [3]     ORAddress,
        directoryName                   [4]     Name,
        ediPartyName                    [5]     EDIPartyName,
        uniformResourceIdentifier       [6]     IA5String,
        iPAddress                       [7]     OCTET STRING,
        registeredID                    [8]     OBJECT IDENTIFIER }
```

Here is a simple code to reproduce the problem:
```rust
 let builder = X509Builder::new().unwrap();

//Create a SAN dummy field
    let test = SubjectAlternativeName::new()
        .dns("*.example.com")
        .build(&builder.x509v3_context(None, None))
        .unwrap();

//Trying to parse as UTF-8
    test.data().as_utf8().unwrap();
```

**Comment by sfackler** [comment]
Are you sure that's exactly the code required to reproduce the issue? `SubjectAlternativeName::build` returns an `X509Extension` type, which doesn't have a `data` method.

**Comment by dangerousplay** [comment]
> Are you sure that's exactly the code required to reproduce the issue? `SubjectAlternativeName::build` returns an `X509Extension` type, which doesn't have a `data` method.

Sorry, the issue is actually related to the pull request #1095.

**Comment by sfackler** [comment]
It probably makes more sense to just comment on that PR then, rather than opening an issue for a feature that hasn't landed yet.

**Comment by dangerousplay** [comment]
Sure, thank you.
