### ISSUE TITLE
PKey::private_key_to_pem_pkcs8() producing different data to PKey::private_key_to_der()

### ISSUE THREAD

**Issue by Ben-Lichtman** [sfackler/rust-openssl#1244]
Disclaimer, maybe there's something I'm missing where this isn't a bug but should actually be that way. I am not experienced with openssl usage in the first place. Anyway, on to what I think might be an issue:

I have generated an openssl::rsa::Rsa key pair using openssl and converted that into an openssl::pkey::PKey.

Next I want to get the actual bytes of the key out (to use as a rustls::PrivateKey). I wasn't sure whether ther best way to do this was to use the PKey::private_key_to_der() function, or to go through PEM using PKey::private_key_to_pem_pkcs8() then decoding that output... I assumed that the data outputted by both would be the same, however upon inspection this wasn't the case.

When I use PKey::private_key_to_pem_pkcs8(), then base64 decode the contained ascii, I get exactly the same contained bytes as when I use PKey::private_key_to_der() except the private_key_to_pem_pkcs8() has an extra 26 (always 26) bytes at the header that is not present in the der bytes.

Is this normal behaviour? What are the extra 26 bytes for?

**Comment by Ben-Lichtman** [comment]
As an addition to this, If I use PKey::rsa() and then use RSA::private_key_to_pem() I get the same data as the DER. What is the extra data that PKey is adding to the head?

**Comment by sfackler** [comment]
As the documentation states, private_key_to_pem_pkcs8 produces a PKCS#8 PrivateKeyInfo structure, while private_key_to_der produces the raw underlying key type's encoding: https://docs.rs/openssl/0.10.28/openssl/pkey/struct.PKeyRef.html#method.private_key_to_pem_pkcs8.

**Comment by Ben-Lichtman** [comment]
Thanks for the helpful reply. As an OpenSSL newbie I’m still a little hazy on what this actually means.

I found this document by ietf which shows the grammar of PrivateKeyInfo https://tools.ietf.org/html/rfc5208
It has a version number, algorithm identifier, key as octets, and attributes.

If I am understanding correctly the der data only contains the Key as octets, and the rest of the metadata is not there? Does this mean the RSA to pem function is just storing the key data as a base64 encoded pem file?

I think my confusion is over the phrase “key type’s encoding” and exactly what this means... And the difference between pem and pkcs8...

**Comment by sfackler** [comment]
PEM is a format for storing binary data as base64 along with a header and footer identifying what it is: https://en.wikipedia.org/wiki/Privacy-Enhanced_Mail.

**Comment by Ben-Lichtman** [comment]
Ok, I think I understand now, but please tell me if i'm wronge:

- PEM is just -----header stuff-----\n base64(some data) \n-----footerstuff-----

- PKCS8 is an abstract spec which specifies how the key is stored - this means the key along with some associated metadata in a given order.

- DER is how the PKCS8 key is actually stored as a binary format.

- Usually when you encounter a PEM key, that is the DER data that has been base64 encoded into the PEM format.

Is this correct?

**Comment by sfackler** [comment]
That sounds right.

**Comment by Ben-Lichtman** [comment]
Ok thanks, I'll close this issue
