### ISSUE TITLE
A feature to vendor openssl only on windows?

### ISSUE THREAD

**Issue by coolreader18** [sfackler/rust-openssl#1251]
As I was setting up CI to install openssl with vcpkg on windows, I thought it might be nice to avoid that trouble in CI, but also for anyone who wants to just try out our project on windows; it can turn people away to have to spend like 5-10 minutes figuring out how to install openssl on windows, either through the msi available online or through vcpkg, with `VCPKGRS_DYNAMIC=1` enabled as well. However, on linux distributions, it's usually as easy as `packagemanager install openssl`. Would a feature for `rust-openssl` like `vendored_on_windows` be a good idea? (I make this proposal here only because I don't think it's possible to conditionally enable cargo features based on a `cfg()`; it has to be something in this crate.)

**Comment by sfackler** [comment]
I don't really want to start introducing single-platform features like this, but a potential alternative could be to have e.g. an environment variable that disables vendoring even when the feature is turned on.

**Comment by sfackler** [comment]
There are also some newly-finished unstable features in cargo that improve it's handling of features, though I don't know if this particular context is covered.

**Comment by coolreader18** [comment]
The environment variable seems like a good solution to me, maybe `RUST_OPENSSL_NO_VENDOR`? I'll look into implementing that, if that's okay.

**Comment by sfackler** [comment]
I think we'd call it `OPENSSL_NO_VENDOR` to line up with the other environment variables, but yeah.
