### ISSUE TITLE
Building on Alpine Linux and systest

### ISSUE THREAD

**Issue by kirillt** [sfackler/rust-openssl#1262]
Hey, the following Dockerfile:
```
FROM alpine
RUN apk add git cargo pkgconfig openssl openssl-dev
RUN git clone https://github.com/sfackler/rust-openssl /build
RUN cd /build && cargo build --release
```
produces the following error:
```
error: failed to run custom build command for `systest v0.1.0 (/build/systest)`

Caused by:
  process didn't exit successfully: `/build/target/release/build/systest-9a76ac7552bababf/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'unknown os/family width: x86_64-alpine-linux-musl', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/ctest-0.2.22/src/lib.rs:1117:9
```

I glanced closed issues with Alpine in this repo. It seems that it was building without special manipulation. But I am not an expert, probably I am missing something simple.

**Comment by sfackler** [comment]
That panic is coming from the ctest crate - you'd probably want to file this over there.

**Comment by kirillt** [comment]
Alpine uses a bit different target (`alpine` instead of `unknown`).
The workaround is by the link: https://github.com/gnzlbg/ctest/issues/95
