### ISSUE TITLE
openssl-sys not finding correct library names after vckpg install

### ISSUE THREAD

**Issue by Charles-Schleich** [sfackler/rust-openssl#1267]
Should `openssl-sys` be looking for libraries named `libcrypto-1_1` and `libssl-1_1` ? 
I don't know if vcpkg recently changed the naming convention of openssl libraries ?

Because getting `openssl-sys` to build is a isn't 100% smooth.  Ive only managed by doing the following:  

Installing `vcpkg`, (https://docs.microsoft.com/en-us/cpp/build/vcpkg#installation)
then running `vcpkg install openssl`
then setting `setx VCPKGRS_DYNAMIC 1`
then going into `\vcpkg\installed\x86-windows\bin\` and renaming 
`libcrypto-1_1` and `libssl-1_1` to `libcrypto` and `libssl` 
And its that last part i don't like all that much.  

I only have 
```
PS>vcpkg list
openssl-windows:x86-windows                        1.1.1d-2
openssl:x86-windows                                1.1.1d
```

Is there a better way of going about building this library on windows ?

**Comment by sfackler** [comment]
`cargo update`

https://github.com/sfackler/rust-openssl/pull/1238
