### ISSUE TITLE
AES OCB mode

### ISSUE THREAD

**Issue by hargoniX** [sfackler/rust-openssl#1268]
In #864 was a very brief mention of OCB mode, apart from that I can't find anything in the issue tracker, hence my question, are there any plans to include OCB mode into this crate / any reason it is not there already?

If the reason it isn't there yet is just that nobody thought about picking it up yet I'd happily look into it.

**Comment by sfackler** [comment]
There's no particular reason it's omitted - feel free to add!

**Comment by hargoniX** [comment]
A question regarding tests, I am seeing [this](https://github.com/openssl/openssl/blob/master/test/recipes/30-test_evp_data/evpciph.txt#L1064`)  set of test data in OpenSSL it only contains tests for 128 bits though. I also did find [this](https://web.cs.ucdavis.edu/~rogaway/ocb/ocb-test.htm) page by the inventor of OBC mode. However I can't see any aad data in the values provided here so I'm a little unsure on how to work with this test data. Would someone be able to tell me?

**Comment by sfackler** [comment]
Adding a test with OpenSSL's values seems fine I think.
