### ISSUE TITLE
How to generate random RSA key pair

### ISSUE THREAD

**Issue by junky89** [sfackler/rust-openssl#1273]
Hi,

I've been trying to generate a random RSA key pair using rust openssl, but without success. I'm always generating the same key pair. I can't figure out how rand generation fits in here. What I have (always generating the same) is:

```
let rsa = Rsa::generate(2048).unwrap();
let public_rsa = rsa.public_key_to_pem().unwrap();
let private_rsa = rsa.private_key_to_pem().unwrap();
```

Any direction/example on how this can be done would be much appreciated.

**Comment by sfackler** [comment]
How are you determining that the key pair is always the same?

**Comment by junky89** [comment]
I'm just printing it to console (pem version). Every X minutes I generate a new key pair and print the public one. Always the same. Even across builds and executions.  
My guess is that I have to somehow seed the random generator (in c openssl there is a RAND_seed function, but I can't match it to rust). I can not figure out how to proceed.

**Comment by sfackler** [comment]
This test passes for me:

```rust
    #[test]
    fn generate_is_different() {
        let a = Rsa::generate(2048).unwrap().private_key_to_pem().unwrap();
        let b = Rsa::generate(2048).unwrap().private_key_to_pem().unwrap();

        assert_ne!(a, b);
    }
```

**Comment by junky89** [comment]
Solved. It was a problem with my OS installation. As you told, no need to RAND_seed. Every generated rsa is different now. 

Thank you.
