### ISSUE TITLE
Consider removing upper bound on compatible LibreSSL versions

### ISSUE THREAD

**Issue by ruuda** [sfackler/rust-openssl#1278]
There is this part in `build/main.rs` that stops compilation with `version_error()`, if the LibreSSL version is not one of the listed ones. This means that whenever a new minor version of LibreSSL is released, this crate needs to add support for it, and make a new release too.

This presents a challenge when packaging applications that transitively depend on `rust-openssl`. Applications will have `rust-openssl` pinned in their `Cargo.lock`. So now when there is a new LibreSSL version, first `rust-openssl` needs to add support for it and release a new version, and then the application needs to update to a newer version of `rust-openssl` and release a new version, and only that version will build against the new LibreSSL.

If a distribution ships a new version of LibreSSL before the application gets a chance to update, then the application no longer compiles.

What exacerbates this problem is that [there is a new LibreSSL branch every 6 months](https://www.libressl.org/releases.html). It takes some time for updates to propagate to the end application, say one month, so on a distribution that ships the latest LibreSSL, the application is broken 1/6 of the time. Of course, if there really is a breaking change, there is no way around that. But at least for 3.1, no code changes were required.

I traced back the history of that check to try and understand why it is there in the first place, and I found that it was introduced in https://github.com/sfackler/rust-openssl/pull/636, with the note

> Turns out LibreSSL breaks ABI compatibility across minor releases

As far as I can tell, LibreSSL version numbers do not have any meaning apart from the patch number. I don’t think the version should be interpreted as major.minor, it is just a decimal number that increments with 0.1 at every release. I don’t know if this is an official policy, but all past LibreSSL versions follow this pattern, as do the version numbers of the upstream OpenBSD project. The LibreSSL releases page refers to these as *branches*, e.g. 3.1.0 is the first version of the 3.1 branch.

So I am wondering, is there any technical reason that prevents compatible future releases from compiling with an older `rust-openssl`? If not, would you consider relaxing the check?

<sub>I ran into this when [trying to update LibreSSL in Nixpkgs](https://github.com/NixOS/nixpkgs/pull/88195), which would break the `wasm-pack` package because it depends on a `rust-openssl` incompatible with LibreSSL 3.1.</sub>

**Comment by sfackler** [comment]
The upper bound is present because LibreSSL still exposes structure layouts in its ABI (4 years after OpenSSL figured this out). #909 tracks moving away from direct field access when possible. There are still a few blocks such as BN_is_negative, which is still a macro that directly accesses the `neg` field in LibreSSL: https://github.com/libressl-portable/openbsd/blob/6fae21e36285ddcb23747ee185e772a70f5d3386/src/lib/libcrypto/bn/bn.h#L448

**Comment by reynoldsbd** [comment]
This is a pretty big show-stopper for those of us using OpenBSD -current, and it's not clear that the accessor solution will be ready in the near future. @sfackler would you be open to allowing advanced users to opt out of this version check, e.g. by setting an environment variable?

If you think this is reasonable, I'd be happy to submit a PR with the change!

**Comment by sfackler** [comment]
I think it would be reasonable for the LibreSSL people to get their shit together, but that's not going to happen.

I am at best ambivalent to the idea of an environment variable that would bypass these safety checks. If it happened, it would have to look like `I_WANT_UNSUPPORTED_VERSIONS_OF_LIBRESSL_TO_CORRUPT_MY_PROCESSES_MEMORY=1` or something like that.
