### ISSUE TITLE
Vendored build of LibreSSL?

### ISSUE THREAD

**Issue by dubiousjim** [sfackler/rust-openssl#1283]
Would you be open to a PR enabling vendored builds of LibreSSL? I've implemented this on my dev machine (running OSX 10.10), and the build process seems straightforward there. My implementation adds a feature `vendored-libre` to `openssl` and `openssl-sys`, which brings in an external package `libressl-src`, modeled after `openssl-src`.

I think there wouldn't be any change to the licensing: it looks like LibreSSL is under the same "OpenSSL license" that OpenSSL is.

I haven't learned how your ci system works, so someone would have to help with that. And for all I know, it may be that configuring and building LibreSSL needs more tweaking to handle some of the targets you support.

**Comment by sfackler** [comment]
This library is focused on supporting OpenSSL. LibreSSL is supported because it vaguely resembles an old, unsupported version of OpenSSL, but I'm not planning on supporting it beyond that.

**Comment by dubiousjim** [comment]
I understand. But your reply could be read as: you'd consider a PR that enables this functionality, but don't want to commit any ongoing support to LibreSSL. If it breaks or stops working, too bad.

Or you could be counting even such a PR as more support for LibreSSL than you're prepared to give.

I expect you meant the latter, but I'm not sure. Can you clarify?

**Comment by sfackler** [comment]
I don't want to add a feature that I am actively not going to support.

**Comment by dubiousjim** [comment]
Ok, thanks and understood. I'll fork then.

**Comment by dubiousjim** [comment]
Hope it's ok for me to re-open this for a moment. My replacement for `openssl-src` is [libressl-src](https://github.com/dubiousjim/libressl-src). Currently it declares its `package.name` as `"openssl-src"` so that it can be used in a `patch.crates-io` section (as explained in the [README](https://github.com/dubiousjim/libressl-src/blob/master/README.md)).

There are three things you guys could choose to do:

* Nothing
* Add a note to the doc comments for `openssl` under the "Vendored" heading, saying something like "It's also possible to do a vendored build of LibreSSL instead of OpenSSL; see [here](https://github.com/dubiousjim/libressl-src) for details (and direct any support questions to the maintainer of that package)."
* Add a new feature to `openssl` and `openssl-sys`, something like "vendored-libre", that works just like "vendored" except that it depends on "libressl-src" instead of "openssl-src". If you're willing to do that, I'll make my package properly name itself (`package.name = "libressl-src"`) and publish it to crates.io. (Am just waiting on the maintainer of [autotools](https://lib.rs/crates/autotools) to publish some recent changes in his git.) I can submit a PR to you guys with the (very minimal) changes to this repository needed to implement.

I hope you'll reconsider whether you're willing to do the last of these, as it would be cleanest. But if not, OK. Would you then be willing at least to do the second, so that others who might want a vendored LibreSSL can find my package, and don't have to reinvent my work.

**Comment by sfackler** [comment]
Again, the `vendored` feature there for people that just want the thing to build. I do not want to support configuration beyond that.
