### ISSUE TITLE
Can't reproduce signature verification from CLI

### ISSUE THREAD

**Issue by fuchsnj** [sfackler/rust-openssl#1285]
I have the hash of a file that I'm trying to verify against a signature. I can verify this successfully with the openssl CLI (shown below). I wrote what I _think_ is the equivalent Rust program to do the exact same verification, but am failing to get it to verify. 

The 3 files used (hash, signature, pubkey) are attached if anyone wants to reproduce.
[data.zip](https://github.com/sfackler/rust-openssl/files/4720612/data.zip)

I apologize if I'm just making a simple mistake, but as far as I can tell it looks like an issue with this library currently.

using the openssl CLI
```console
$ openssl version
OpenSSL 1.1.1f  31 Mar 2020
$ openssl pkeyutl -in hash.bin -inkey publickey.pem -pubin -verify -sigfile signature.bin
Signature Verified Successfully

```

Rust program
```rust
println!("{}", openssl::version::version());

let mut public_key_bytes = vec![];
std::fs::File::open("publickey.pem").unwrap().read_to_end(&mut public_key_bytes).unwrap();
let public_key = openssl::pkey::PKey::public_key_from_pem(&public_key_bytes).unwrap();

let mut hash_result = vec![];
std::fs::File::open("hash.bin").unwrap().read_to_end(&mut hash_result).unwrap();

let mut signature= vec![];
std::fs::File::open("signature.bin").unwrap().read_to_end(&mut signature).unwrap();

let mut verifier = openssl::sign::Verifier::new_without_digest(&public_key).unwrap();
let verify_result = verifier.verify_oneshot(&signature, &hash_result);
println!("Verify result: {:?}", verify_result);
```
```toml
[dependencies]
openssl = "0.10.29"
```
Output of Rust program
```console
OpenSSL 1.1.1f  31 Mar 2020
Verify result: Ok(false)
```

**Comment by sfackler** [comment]
The Verifier type uses the `EVP_DigestVerifyInit` family of functions that first hash input data and then verify the signature of the hash, while the pkeyutl app uses the `EVP_verify_init` family of functions which skip the hashing step and directly work with the input.

**Comment by sfackler** [comment]
The OpenSSL 3.0.0 alpha has a new `-rawin` parameter to `pkeyutl` that makes it behave like Verifier.

**Comment by fuchsnj** [comment]
Makes sense. Thanks for taking a look at this. Are there any plans to support the `EVP_verify_init` family of functions in this library? For my use case, I can't use `EVP_DigestVerifyInit`

**Comment by sfackler** [comment]
Definitely happy to add support. #1279 may be relevant.
