### ISSUE TITLE
Build failure in windows

### ISSUE THREAD

**Issue by smcclosr** [sfackler/rust-openssl#1286]
Hi I was trying to do a build and getting this error:

thread 'main' panicked at '

Could not find directory of OpenSSL installation, and this `-sys` crate cannot
proceed without this knowledge. If OpenSSL is installed and this crate had
trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
compilation process.

Make sure you also have the development packages of openssl installed.
For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.

If you're in a situation where you think the directory *should* be found
automatically, please open a bug at https://github.com/sfackler/rust-openssl
and include information about your system as well as this message.

$HOST = x86_64-pc-windows-gnu
$TARGET = x86_64-pc-windows-gnu
openssl-sys = 0.9.57

It looks like you're compiling for MinGW but you may not have either OpenSSL or
pkg-config installed. You can install these two dependencies with:

pacman -S openssl-devel pkg-config

and try building this crate again.

**Comment by sfackler** [comment]
Have you tried following the instructions in that message?

**Comment by smcclosr** [comment]
Yes, I installed msys2, ran it and did the command pacman command, and it installed openssl-sys, but not sure how those files are related to this rust module.

**Comment by sfackler** [comment]
This rust module exposes an interface to OpenSSL. You need to have a copy of OpenSSL if you want to use it. Alternatively, you can enable the `vendored` feature in Cargo.toml to build your own copy:

```toml
[dependencies]
openssl = { version = "0.10", features = ["vendored" ] }
```

**Comment by smcclosr** [comment]
That looks like it fixed the problem,  I will feed this correction back to the the author of the package I am using, Thanks!!
