### ISSUE TITLE
Homebrew installed OpenSSL is not found again, even after setting OPENSSL_DIR

### ISSUE THREAD

**Issue by Timmmm** [sfackler/rust-openssl#1291]
When I do this:

```
export OPENSSL_DIR=/usr/local/opt/openssl
cargo install cargo-edit
```

It gives this error

```
running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "/usr/local/opt/openssl/include/openssl" "-Wall" "-Wextra" "-E" "build/expando.c"
cargo:warning=build/expando.c:1:10: fatal error: 'openssl/opensslv.h' file not found
cargo:warning=#include <openssl/opensslv.h>
cargo:warning=         ^~~~~~~~~~~~~~~~~~~~
cargo:warning=1 error generated.
exit code: 1

--- stderr
thread 'main' panicked at '
Header expansion error:
Error { kind: ToolExecError, message: "Command \"cc\" \"-O3\" \"-ffunction-sections\" \"-fdata-sections\" \"-fPIC\" \"-m64\" \"-I\" \"/usr/local/opt/openssl/include/openssl\" \"-Wall\" \"-Wextra\" \"-E\" \"build/expando.c\" with args \"cc\" did not execute successfully (status code exit code: 1)." }

Failed to find OpenSSL development headers.
```

I did install it through Brew:

```
 ~ brew info openssl
openssl@1.1: stable 1.1.1g (bottled) [keg-only]
Cryptography and SSL/TLS Toolkit
https://openssl.org/
/usr/local/Cellar/openssl@1.1/1.1.1g (8,059 files, 18MB)
  Poured from bottle on 2020-06-02 at 18:59:02
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/openssl@1.1.rb
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl@1.1/certs

and run
  /usr/local/opt/openssl@1.1/bin/c_rehash

openssl@1.1 is keg-only, which means it was not symlinked into /usr/local,
because macOS provides LibreSSL.

If you need to have openssl@1.1 first in your PATH run:
  echo 'export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"' >> ~/.zshrc

For compilers to find openssl@1.1 you may need to set:
  export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
  export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"
```

And the files are there:

```
~ ls /usr/local/opt/openssl/include/openssl/opensslv.h
/usr/local/opt/openssl/include/openssl/opensslv.h
```

However it's not exactly looking in the right place. I set

    OPENSSL_DIR=/usr/local/opt/openssl

But then it compile with

    -I /usr/local/opt/openssl/include/openssl

And then `#includes`

    #include <openssl/opensslv.h>

Something is going wrong with the include path. It should be

    -I $OPENSSL_DIR/include

This is on a completely fresh install of MacOS 10.15.5.

**Comment by Timmmm** [comment]
The code in `find_normal.rs` looks correct, and it looks like it should work even if I don't set `OPENSSL_DIR`, but not setting it gives the same results. This is really weird.

**Comment by sfackler** [comment]
You should not need to set any environment variables at all to use a Homebrew-installed OpenSSL. From the behavior it looks like you have the `OPENSSL_INCLUDE_DIR` environment variable set to `/usr/local/opt/openssl/include/openssl`.

**Comment by Timmmm** [comment]
Ahhh yes that's annoying - some other build system I use needs that and uses the same env var but with a different value! Sorry for the noise!

**Comment by dcow** [comment]
Don't know if it's related, but `brew` will report a value for `brew --prefix openssl` regardless of whether the openssl cask is installed or not. I thought it was a bug when I ran into the behavior since it seems the openssl-sys crate is expecting that command to work like a drop-in replacement for `pkg-config`: https://github.com/Homebrew/brew/issues/10261.
