### ISSUE TITLE
Question: Is there a way to access SslRef for a connection in actix-web 0.7?

### ISSUE THREAD

**Issue by crusty-dave** [sfackler/rust-openssl#1295]
I would like to be able to determine which version and cipher is used for a given connection.

Struct openssl::ssl::Ssl

fn get_current_cipher<'a>(&'a self) -> Option<SslCipher<'a>>

fn version(&self) -> &'static str[−]
Returns the name of the protocol used for the connection, e.g. "TLSv1.2", "SSLv3", etc.

Thanks in advance,
-Dave

**Comment by sfackler** [comment]
That sounds like a question for the actix developers.
