### ISSUE TITLE
set_new_session_callback() doesn't seem to be working

### ISSUE THREAD

**Issue by crusty-dave** [sfackler/rust-openssl#1296]
I don't see my log message when it should be getting invoked.  I do see the log that I called set_new_session_callback().

```
    fn new_session_cb(
        ssl_ref: &mut SslRef,
        session: SslSession,
    ) {
        const FN_NAME: &str = "new_session_cb";

        let version = ssl_ref.version2();
        let ciphers = ssl_ref.client_hello_ciphers();
        let my_session = session.clone();
        warn!("{} received new session, ssl ver: {:?}, ciphers {:?}, session {:?}",
              FN_NAME, &version, ciphers, my_session.id());
    }

        warn!("{} set new session callback", FN_NAME);
        ssl.set_session_cache_mode(SslSessionCacheMode::SERVER);
        ssl.set_new_session_callback(Self::new_session_cb);
```

Am I missing something or is it a bug?

Note that the callback definition also seems to be incorrect, it seems that the callback should return a bool based on the following documentation:

The new_session_cb() is called whenever a new session has been negotiated and session caching is enabled (see SSL_CTX_set_session_cache_mode(3)). The new_session_cb() is passed the ssl connection and the nascent ssl session sess. Since sessions are reference-counted objects, the reference count on the session is incremented before the callback, on behalf of the application. If the callback returns 0, the session will be immediately removed from the internal cache and the reference count released. If the callback returns 1, the application retains the reference (for an entry in the application-maintained "external session cache"), and is responsible for calling SSL_SESSION_free() when the session reference is no longer in use.

**Comment by sfackler** [comment]
By default OpenSSL uses tickets for session caching which don't require any server-side state so thet server side session callback is never invoked. You can call `ssl.set_options(SslOptions::NO_TICKET)` to have OpenSSL switch to the mode that does involve server-side state and your callback will be invoked.

Your callback is provided with the SslSession by value, so the wrapper callback always returns 1: https://github.com/sfackler/rust-openssl/blob/1b64b68ac44bfe7a33b234e10684c3d9552a7538/openssl/src/ssl/callbacks.rs#L368.

**Comment by crusty-dave** [comment]
Thanks, that resolved my issue.

**Comment by rohitjoshi** [comment]
@sfackler  Session reuse no longer working with OpenSSL 1.1.1. Would you recommend to  use `ssl.set_options(SslOptions::NO_TICKET)`

I use below command:
```
echo | openssl s_client -connect 0.0.0.0:20900 -reconnect > /dev/null | grep 'New\|Reuse'
```
