### ISSUE TITLE
possible conflicts with other crates?

### ISSUE THREAD

**Issue by keepsimple1** [sfackler/rust-openssl#1297]
I'm using `openssl` and [`quiche`](https://crates.io/crates/quiche) in the same Rust package, the final build fails to link due to missing symbols in `openssl`.  Because `quiche` uses `BoringSSL`, I was wondering if there are possible conflicts when using `openssl` mixed with BoringSSL ? Is there any known issue regarding that?

When I use the same openssl related code without quiche, the build was successful. I've asked the question in `quiche` [repo](https://github.com/cloudflare/quiche/issues/560) but did not get responses yet. Let me know if this is not the right place to ask.

The error I got is something like this:
```
 = note: /usr/bin/ld: /home/myproject/target/debug/deps/libopenssl-b9de86a917260a58.rlib(openssl-b9de86a917260a58.openssl.e9esesv9-cgu.4.rcgu.o): in function `openssl::symm::Crypter::finalize':
          /home/myproject/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.10.29/src/symm.rs:587: undefined reference to `EVP_CipherFinal'
```
The crates I used:

quiche = "0.4.0"
openssl = "0.10"

**Comment by sfackler** [comment]
Yes, you cannot link against both boringssl and openssl at the same time. I believe boringssl has the ability to prefix all of its symbols, but I don't know if quiche can deal with that.
