### ISSUE TITLE
Trouble compiling on MSYS2

### ISSUE THREAD

**Issue by justinmoon** [sfackler/rust-openssl#1300]
I'm trying to build [libtor](https://github.com/MagicalBitcoin/libtor) for Windows. Seemed like [MSYS2 ](https://www.msys2.org/) is the best option (open to alternatives!). Here's my [example project](https://github.com/justinmoon/runlibtor) which I'm trying to build below.

I installed the MSYS2 "openssl", "openssl-devel" & "pkg-config" packages.

```
$ pkg-config --cflags openssl
-IC:/msys64/mingw64/include

$ pkg-config --libs openssl
-LC:/msys64/mingw64/lib -lssl -lcrypto
```

Based ^^ and [the docs](https://docs.rs/openssl/0.10.29/openssl/#manual), I would assume that the following would work:

```
$ OPENSSL_DIR=/mingw64 cargo run
...
thread 'main' panicked at 'OpenSSL libdir at `C:\msys64\home\justin\runlibtor\target\debug\build\openssl-sys-05e3c077a4469148\out\openssl-build\install\lib` does not contain the required files to either statically or dynamically link OpenSSL', C:\Users\justin\.cargo\registry\src\github.com-1ecc6299db9ec823\openssl-sys-0.9.54\build/main.rs:316:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by sfackler** [comment]
Setting OPENSSL_DIR disables the use of pkg-config.

The file path in the error message seems to point to the `vendored` Cargo feature being enabled, but something going wrong with its setup. If that's enabled, OPENSSL_DIR is ignored anyway.
