### ISSUE TITLE
Create SslStream from Ssl without calling connect() or accept()

### ISSUE THREAD

**Issue by crdumoul** [sfackler/rust-openssl#1301]
I'm looking for a way to create an SslStream from an Ssl struct without having to call connect() or accept() on an Ssl or SslStreamBuilder. Looking through the various API docs, I don't see a way to do this.

The background on this is as follows:
- I will be creating the socket and doing the SSL handshake in one process before handing the connection off to another process.
- I'm using a modified OpenSSL library where I'm able to serialize a connection (SSL struct) and pass it off, along with the socket file descriptor, to another process.
- Therefore, I want to be able to create an Ssl and SslStream without trying to redo the handshake process.

**Comment by sfackler** [comment]
I think it'd be plausible to add an `pub unsafe fn from_raw_parts(ssl: *mut openssl_sys::SSL, stream: S) -> SslStream<S>`? It would need to set up the BIOs internally.

**Comment by crdumoul** [comment]
That seems pretty straightforward, so I'll give it a try. If it works out I'll try to create a pull request with the change.

**Comment by sfackler** [comment]
It should just basically involve taking this function, renaming it, changing the argument from `Ssl` to `SSL`, and making it public and unsafe: https://github.com/sfackler/rust-openssl/blob/master/openssl/src/ssl/mod.rs#L3464

**Comment by crdumoul** [comment]
@sfackler I'm gonna go ahead and close this issue now that the associated pull request has been merged.
Thanks for your help getting this feature added.
Do you know when the next release of the openssl crate is expected?

**Comment by sfackler** [comment]
Published!
