### ISSUE TITLE
Cannot Build on Ubuntu 20.04

### ISSUE THREAD

**Issue by chorman0773** [sfackler/rust-openssl#1302]
I am currently having issues building on ubuntu 20.04, both using system openssl and using a custom-built copy. Setting OPENSSL_DIR=/usr/local (where openssl is installed), setting it to `/usr` (where the distro packages are installed) and leaving OPENSSL_DIR unset all cause the same failure.

The pertinent output from cargo is at <https://gist.github.com/chorman0773/2fc064147bb98e43491cec9eac6bf1cf> (all variations of above return output which is not significantly different).

**Comment by sfackler** [comment]
That error message looks like what would happen if you're trying to build against the not-yet-released 3.0.0 version of OpenSSL, which is not currently supported: #1263

**Comment by chorman0773** [comment]
That would be what my source build is (so I don't need to deal with the broken license of older version), however I have confirmed the distro package (which is the only installation available via /usr) is at version 1.1.1f, and that recieves the same error.

**Comment by sfackler** [comment]
What are the contents of `/usr/include/openssl/opensslv.h`?

**Comment by chorman0773** [comment]
```c
/*
 * Copyright 1999-2020 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef HEADER_OPENSSLV_H
# define HEADER_OPENSSLV_H

#ifdef  __cplusplus
extern "C" {
#endif

/*-
 * Numeric release version identifier:
 * MNNFFPPS: major minor fix patch status
 * The status nibble has one of the values 0 for development, 1 to e for betas
 * 1 to 14, and f for release.  The patch level is exactly that.
 * For example:
 * 0.9.3-dev      0x00903000
 * 0.9.3-beta1    0x00903001
 * 0.9.3-beta2-dev 0x00903002
 * 0.9.3-beta2    0x00903002 (same as ...beta2-dev)
 * 0.9.3          0x0090300f
 * 0.9.3a         0x0090301f
 * 0.9.4          0x0090400f
 * 1.2.3z         0x102031af
 *
 * For continuity reasons (because 0.9.5 is already out, and is coded
 * 0x00905100), between 0.9.5 and 0.9.6 the coding of the patch level
 * part is slightly different, by setting the highest bit.  This means
 * that 0.9.5a looks like this: 0x0090581f.  At 0.9.6, we can start
 * with 0x0090600S...
 *
 * (Prior to 0.9.3-dev a different scheme was used: 0.9.2b is 0x0922.)
 * (Prior to 0.9.5a beta1, a different scheme was used: MMNNFFRBB for
 *  major minor fix final patch/beta)
 */
# define OPENSSL_VERSION_NUMBER  0x1010106fL
# define OPENSSL_VERSION_TEXT    "OpenSSL 1.1.1f  31 Mar 2020"

/*-
 * The macros below are to be used for shared library (.so, .dll, ...)
 * versioning.  That kind of versioning works a bit differently between
 * operating systems.  The most usual scheme is to set a major and a minor
 * number, and have the runtime loader check that the major number is equal
 * to what it was at application link time, while the minor number has to
 * be greater or equal to what it was at application link time.  With this
 * scheme, the version number is usually part of the file name, like this:
 *
 *      libcrypto.so.0.9
 *
 * Some unixen also make a softlink with the major version number only:
 *
 *      libcrypto.so.0
 *
 * On Tru64 and IRIX 6.x it works a little bit differently.  There, the
 * shared library version is stored in the file, and is actually a series
 * of versions, separated by colons.  The rightmost version present in the
 * library when linking an application is stored in the application to be
 * matched at run time.  When the application is run, a check is done to
 * see if the library version stored in the application matches any of the
 * versions in the version string of the library itself.
 * This version string can be constructed in any way, depending on what
 * kind of matching is desired.  However, to implement the same scheme as
 * the one used in the other unixen, all compatible versions, from lowest
 * to highest, should be part of the string.  Consecutive builds would
 * give the following versions strings:
 *
 *      3.0
 *      3.0:3.1
 *      3.0:3.1:3.2
 *      4.0
 *      4.0:4.1
 *
 * Notice how version 4 is completely incompatible with version, and
 * therefore give the breach you can see.
 *
 * There may be other schemes as well that I haven't yet discovered.
 *
 * So, here's the way it works here: first of all, the library version
 * number doesn't need at all to match the overall OpenSSL version.
 * However, it's nice and more understandable if it actually does.
 * The current library version is stored in the macro SHLIB_VERSION_NUMBER,
 * which is just a piece of text in the format "M.m.e" (Major, minor, edit).
 * For the sake of Tru64, IRIX, and any other OS that behaves in similar ways,
 * we need to keep a history of version numbers, which is done in the
 * macro SHLIB_VERSION_HISTORY.  The numbers are separated by colons and
 * should only keep the versions that are binary compatible with the current.
 */
# define SHLIB_VERSION_HISTORY ""
# define SHLIB_VERSION_NUMBER "1.1"


#ifdef  __cplusplus
}
#endif
#endif                          /* HEADER_OPENSSLV_H */
```
Is an exact copy of the file.

**Comment by sfackler** [comment]
Er, sorry, `/usr/local/include/openssl/opensslv.h`. From the error message, as far as I can tell, that must be the 3.0.0 headers.

**Comment by chorman0773** [comment]
```c
/*
 * WARNING: do not edit!
 * Generated by Makefile from ../include/openssl/opensslv.h.in
 *
 * Copyright 1999-2020 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef OPENSSL_OPENSSLV_H
# define OPENSSL_OPENSSLV_H
# pragma once

# ifdef  __cplusplus
extern "C" {
# endif

/*
 * SECTION 1: VERSION DATA.  These will change for each release
 */

/*
 * Base version macros
 *
 * These macros express version number MAJOR.MINOR.PATCH exactly
 */
# define OPENSSL_VERSION_MAJOR  3
# define OPENSSL_VERSION_MINOR  0
# define OPENSSL_VERSION_PATCH  0

/*
 * Additional version information
 *
 * These are also part of the new version scheme, but aren't part
 * of the version number itself.
 */

/* Could be: #define OPENSSL_VERSION_PRE_RELEASE "-alpha.1" */
# define OPENSSL_VERSION_PRE_RELEASE "-alpha4-dev"
/* Could be: #define OPENSSL_VERSION_BUILD_METADATA "+fips" */
/* Could be: #define OPENSSL_VERSION_BUILD_METADATA "+vendor.1" */
# define OPENSSL_VERSION_BUILD_METADATA ""

/*
 * Note: The OpenSSL Project will never define OPENSSL_VERSION_BUILD_METADATA
 * to be anything but the empty string.  Its use is entirely reserved for
 * others
 */

/*
 * Shared library version
 *
 * This is strictly to express ABI version, which may or may not
 * be related to the API version expressed with the macros above.
 * This is defined in free form.
 */
# define OPENSSL_SHLIB_VERSION 3

/*
 * SECTION 2: USEFUL MACROS
 */

/* For checking general API compatibility when preprocessing */
# define OPENSSL_VERSION_PREREQ(maj,min)                                \
    ((OPENSSL_VERSION_MAJOR << 16) + OPENSSL_VERSION_MINOR >= ((maj) << 16) + (min))

/*
 * Macros to get the version in easily digested string form, both the short
 * "MAJOR.MINOR.PATCH" variant (where MAJOR, MINOR and PATCH are replaced
 * with the values from the corresponding OPENSSL_VERSION_ macros) and the
 * longer variant with OPENSSL_VERSION_PRE_RELEASE_STR and
 * OPENSSL_VERSION_BUILD_METADATA_STR appended.
 */
# define OPENSSL_VERSION_STR "3.0.0"
# define OPENSSL_FULL_VERSION_STR "3.0.0-alpha4-dev"

/*
 * SECTION 3: ADDITIONAL METADATA
 *
 * These strings are defined separately to allow them to be parsable.
 */
# define OPENSSL_RELEASE_DATE ""

/*
 * SECTION 4: BACKWARD COMPATIBILITY
 */

# define OPENSSL_VERSION_TEXT "OpenSSL 3.0.0-alpha4-dev "

/* Synthesize OPENSSL_VERSION_NUMBER with the layout 0xMNN00PPSL */
# ifdef OPENSSL_VERSION_PRE_RELEASE
#  define _OPENSSL_VERSION_PRE_RELEASE 0x0L
# else
#  define _OPENSSL_VERSION_PRE_RELEASE 0xfL
# endif
# define OPENSSL_VERSION_NUMBER          \
    ( (OPENSSL_VERSION_MAJOR<<28)        \
      |(OPENSSL_VERSION_MINOR<<20)       \
      |(OPENSSL_VERSION_PATCH<<4)        \
      |_OPENSSL_VERSION_PRE_RELEASE )

# ifdef  __cplusplus
}
# endif

# include <openssl/macros.h>
# ifndef OPENSSL_NO_DEPRECATED_3_0
#  define HEADER_OPENSSLV_H
# endif

#endif                          /* OPENSSL_OPENSSLV_H */
```
Is the 3.0.0 file.

I would add that the error message persists, even when I have guaranteed use of 1.1.1f. 
The only possibility I can think of is that the `/usr/local/include` header is above `/usr/include` in priority under clang.

**Comment by sfackler** [comment]
> I would add that the error message persists, even when I have guaranteed use of 1.1.1f.

You are clearly not guaranteeing use of 1.1.1f if it is finding the 3.0.0 header file.

**Comment by chorman0773** [comment]
Well, I have confirmed that its 1.1.1f at the OPENSSL_DIR. However the fact
it's using the version in /usr/local rather than the explicitly specified
version implies that I would need to remove the 3.0.0 version, however I
would rather not as I need it for compatibility with other applications
(specifically as a test for applications which include openssl, but I am
building using the system provided library, as 3.0.0 is the one I can
distribute the easiest based on licensing requirements).

**Comment by sfackler** [comment]
I would generally recommend against having two competing copies of OpenSSL installed to "global" system paths. The openssl-sys build script just calls out to `cc` with the specified include directory as a `-I` flag, so if cc isn't picking up the right thing I don't think there's much I can do about that.

**Comment by chorman0773** [comment]
The problem is that I have no control over the system installation, and I can't remove my custom installation, as I do have compiled stuff that is linked against it (I build a lot of programs and libraries from source), some which I'd prefer not to rebuild.
Ah yay, I absolutely love having two programs which are incompatible only because of the dependencies.

**Comment by sfackler** [comment]
You haven't shown me the build output when trying to use the installation in /opt, but if it is fact the case that it produces exactly the same error and `-I /usr/include` is in fact being passed to `cc` in the failing build, then I don't think there's really anything more that can be done on the openssl-sys side of things.

**Comment by chorman0773** [comment]
I don't have an installation in `/opt` (I don't generally use that tree).  If you were refering to `/usr`, that output can be found here. 
https://gist.github.com/chorman0773/49aa88aaa8fd8f8cc07e130c1223d604.

My problem is that I'm building openssl through other projects outside of my control, in this case, cargo-make. I also have the problem when building `rustbook` which means I spend about 4 hours building rust, only to be told at install something is borked.
I can probably fix the errors on cargo-install, simply by setting the vendored feature of openssl. I'm not sure if a similar workarround will work for rust itself (something tells me it won't be as easy as passing a feature flag to x.py).

As mentioned, removing the install in `/usr/local` is a non-starter for me. I'd have to rebuild half of my tools, which would expend a significant amount of time doing nothing. 
I could look at the code and see if I can figure out how to fix it (otherwise I could try patching the opensslv.h and put the macro in the form I expect).

**Comment by chorman0773** [comment]
Running with `--verbose` in CFLAGS confirms my theory that the `/usr/local` install is trumping the `/usr` install.
> cargo:warning=ignoring duplicate directory "/usr/include"
> cargo:warning=  as it is a non-system directory that duplicates a system directory
...
> cargo:warning=#include <...> search starts here:
> cargo:warning= /usr/local/include
> cargo:warning= /usr/local/lib/clang/11.0.0/include
> cargo:warning= /usr/include/x86_64-linux-gnu
> cargo:warning= /usr/include

When I force `/usr/include` to the top of the search order with `-isystem /usr/include` in CFLAGS, or use a different root, I get an entirely different error (I symlinked everything for the 1.1.1f into `/opt`): <https://gist.github.com/chorman0773/923c809241f576cfb8f1b035691a1c9b>.

**Comment by sfackler** [comment]
I don't think there's really anything that can be done then, unfortunately.
