### ISSUE TITLE
windows 10： failed to run custom build command for `openssl-sys v0.9.58`

### ISSUE THREAD

**Issue by Foredoomed** [sfackler/rust-openssl#1304]
C:\Users\abc\Documents\rust>cargo build
   Compiling openssl-sys v0.9.58
   Compiling rand_os v0.1.3
   Compiling rand_jitter v0.1.4
   Compiling num-traits v0.2.12
error: failed to run custom build command for `openssl-sys v0.9.58`

Caused by:
  process didn't exit successfully: `C:\Users\lakala\Documents\rust\target\debug\build\openssl-sys-0935686155dc6fb8\build-script-main` (exit code: 101)
--- stdout
cargo:rustc-cfg=const_fn
cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_MSVC_OPENSSL_LIB_DIR
X86_64_PC_WINDOWS_MSVC_OPENSSL_LIB_DIR unset
cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
OPENSSL_LIB_DIR unset
cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_MSVC_OPENSSL_INCLUDE_DIR
X86_64_PC_WINDOWS_MSVC_OPENSSL_INCLUDE_DIR unset
cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
OPENSSL_INCLUDE_DIR unset
cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_MSVC_OPENSSL_DIR
X86_64_PC_WINDOWS_MSVC_OPENSSL_DIR unset
cargo:rerun-if-env-changed=OPENSSL_DIR
OPENSSL_DIR unset
note: vcpkg did not find openssl: Could not find library in Vcpkg tree package openssl is not installed for vcpkg triplet x64-windows-static-md

--- stderr
thread 'main' panicked at '

Could not find directory of OpenSSL installation, and this `-sys` crate cannot
proceed without this knowledge. If OpenSSL is installed and this crate had
trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
compilation process.

Make sure you also have the development packages of openssl installed.
For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.

If you're in a situation where you think the directory *should* be found
automatically, please open a bug at https://github.com/sfackler/rust-openssl
and include information about your system as well as this message.

$HOST = x86_64-pc-windows-msvc
$TARGET = x86_64-pc-windows-msvc
openssl-sys = 0.9.58

It looks like you're compiling for MSVC but we couldn't detect an OpenSSL
installation. If there isn't one installed then you can try the rust-openssl
README for more information about how to download precompiled binaries of
OpenSSL:

https://github.com/sfackler/rust-openssl#windows

', C:\Users\lakala\.cargo\registry\src\github.com-1ecc6299db9ec823\openssl-sys-0.9.58\build\find_normal.rs:157:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

warning: build failed, waiting for other jobs to finish...
error: build failed

cargo.toml:

[dependencies]
actix-web = "2.0.0"
actix-web-httpauth = { git = "https://github.com/actix/actix-web-httpauth" }
chrono = { version = "0.4.10", features = ["serde"] }
derive_more = "0.99.2"
diesel = { version = "1.4.2", features = ["postgres","uuidv07", "r2d2", "chrono"] }
dotenv = "0.15.0"
futures = "0.3.1"
r2d2 = "0.8.8"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
actix-service = "1.0.1"
alcoholic_jwt = "1.0.0"
reqwest = "0.9.22"
actix-rt = "1.0.0"

**Comment by sfackler** [comment]
Do you have OpenSSL installed?

**Comment by kuqmua** [comment]
same thing on windows. openssl installed, system variable works correctly, i can use openssl, writing "openssl" command in cmd. i tried to set X86_64_PC_WINDOWS_MSVC_OPENSSL_LIB_DIR, OPENSSL_LIB_DIR, X86_64_PC_WINDOWS_MSVC_OPENSSL_INCLUDE_DIR, OPENSSL_INCLUDE_DIR, X86_64_PC_WINDOWS_MSVC_OPENSSL_DIR, OPENSSL_DIR - no result. same error

**Comment by nataliescottdavidson** [comment]
I'm having this issue as well after installing OpenSSL with Chocolatey,
