### ISSUE TITLE
Add getter for x509 certificate version

### ISSUE THREAD

**Issue by robin-kunzler** [sfackler/rust-openssl#1308]
The x509 certificate version can be set e.g. using [set_version](https://docs.rs/openssl/0.10.30/openssl/x509/struct.X509Builder.html#method.set_version). 

However, as far as I understand, there is currently no way of reading the x509 certificate version. Openssl provides the function [get_version](https://www.openssl.org/docs/man1.1.0/man3/X509_get_version.html). Would it make sense to also add this to the Rust API?

**Comment by sfackler** [comment]
PRs welcomed!

**Comment by igorty** [comment]
AFAIU no one's going to add `X509Ref::version()` yet. If so, will take care of next weekend.

**Comment by max-heller** [comment]
@sfackler this can be closed now, no?
