### ISSUE TITLE
Support LibreSSL version 3.2.1

### ISSUE THREAD

**Issue by missytake** [sfackler/rust-openssl#1309]
In https://github.com/sfackler/rust-openssl/blob/70b21ed67154c77655f3fcfe87b57c7bc5db1777/openssl-sys/build/main.rs#L224, the available versions are hard coded. Is it sufficient to just add the following line in this place?

```
            (3, 2, 1) => ('3', '2', '1'),
```

Or what else would be necessary?

## My Actual Problem

The problem I'm trying to solve is a bit more far-fetched. I'm trying to compile the [DeltaChat core node bindings](https://github.com/deltachat/deltachat-node) on openBSD 6.7-current.

```
# openssl version                                                                                                                          
LibreSSL 3.2.1
```

The error into which I'm running is:

```
error: failed to run custom build command for `openssl-sys v0.9.58`

Caused by:
  process didn't exit successfully: `/var/lib/publicgroups/deltachat-node-bot-base/node_modules/deltachat-node/deltachat-core-rust/target/release/build/openssl-sys-3bae68278b5d1c7b/build-script-main` (exit code: 101)
--- stdout
cargo:rustc-cfg=const_fn
cargo:rerun-if-env-changed=X86_64_UNKNOWN_OPENBSD_OPENSSL_NO_VENDOR
X86_64_UNKNOWN_OPENBSD_OPENSSL_NO_VENDOR unset
cargo:rerun-if-env-changed=OPENSSL_NO_VENDOR
OPENSSL_NO_VENDOR unset

--- stderr
thread 'main' panicked at 'don't know how to configure OpenSSL for x86_64-unknown-openbsd', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-src-111.10.0+1.1.1g/src/lib.rs:197:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

cargo failed with code 101
```

So I'm not entirely sure whether this would solve the issue, but it's probably a good idea regardless.

**Comment by GrbavaCigla** [comment]
Same problem on Gentoo with libressl 3.2.2.

**Comment by ndalliard** [comment]
Just ran into the same problem on OpenBSD 6.8-current compiling another program.

Two days ago [libressl 3.3.0](https://www.libressl.org/releases.html) was released, maybe that will solve the problem and can be used in #1333?
