### ISSUE TITLE
Windows : OpenSSL library directory does not exist: "C:\Program Files\OpenSSL-Win64\lib" (but it does, and contains the right files)

### ISSUE THREAD

**Issue by Teln0** [sfackler/rust-openssl#1320]
When I run `cargo build --release` on windows, after having set OPENSSL_DIR, OPENSSL_LIB_DIR and OPENSSL_INCLUDE_DIR, I get the following output :

error: failed to run custom build command for `openssl-sys v0.9.58`

Caused by:
  process didn't exit successfully: `(path to my program)` (exit code: 101)
--- stdout
cargo:rustc-cfg=const_fn
cargo:rerun-if-env-changed=I686_PC_WINDOWS_MSVC_OPENSSL_LIB_DIR
I686_PC_WINDOWS_MSVC_OPENSSL_LIB_DIR unset
cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
OPENSSL_LIB_DIR = "C:\Program Files\OpenSSL-Win64\lib"
cargo:rerun-if-env-changed=I686_PC_WINDOWS_MSVC_OPENSSL_INCLUDE_DIR
I686_PC_WINDOWS_MSVC_OPENSSL_INCLUDE_DIR unset
cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
OPENSSL_INCLUDE_DIR = "C:\Program Files\OpenSSL-Win64\include"

--- stderr
thread 'main' panicked at 'OpenSSL library directory does not exist: "C:\Program Files\OpenSSL-Win64\lib"', (path to my program)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed.

BUT, C:\Program Files\OpenSSL-Win64\lib DOES EXIST and contains all the right files. I'm running the cmd as administrator.
I installed openssl with the precompiled binaries.

**Comment by sfackler** [comment]
It looks like you have quotes in the value of the environment variable.
