### ISSUE TITLE
Segmentation fault with String when computing base64

### ISSUE THREAD

**Issue by Jonathas-Conceicao** [sfackler/rust-openssl#1325]
The following examples causes a segfault:
```Rust
fn main() {
    let src = "";
    let res = openssl::base64::decode_block(src).unwrap().to_vec();
    println!("Static: {:?}", res);

    let src = String::from("");
    let res = openssl::base64::decode_block(&src).unwrap().to_vec();
    println!("Dynamic: {:?}", res);
}
```
[playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=84f1cdc483a12f7a346fdaa4c1bcad88)

The first computed base64, which uses a `static str` works, but the second, which uses a borrowed str from a `String` causes a segfault. This happens with openssl crate 0.10 and from master branch here on git as well.

**Comment by sfackler** [comment]
This was fixed upstream, but seems reasonable to add a workaround here as well: https://github.com/openssl/openssl/issues/12143.
