### ISSUE TITLE
openssl-sys constantly being rebuilt on Nix(OS)

### ISSUE THREAD

**Issue by Litarvan** [sfackler/rust-openssl#1326]
On [NixOS](https://nixos.org/), to build openssl-sys you must be in a temporary environment where pkg-config and openssl are presents and their environment variables too (such as PKG_CONFIG_PATH), using `nix-shell -p pkg-config openssl --run 'cargo build'`.

Previously, running this command once to build the crate was enough, I could then leave the environment and use cargo commands normally. But now (probably since a recent update ?) every time I leave the shell, and use cargo run/build, the crate gets recompiled (and fails because pkg-config is missing). Apparently, the fact the PKG_CONFIG_PATH environment variable changed triggers that rebuild.

As my IDE runs clippy on the fly (and so, without the appropriate environment to build openssl-sys), this feature becomes unusable as soon as openssl-sys gets in my project dependencies :/ I also can't use the run button from my IDE anymore.

What changed in the build process so that it has to rely on such environment variables ? Is there any workaround ?
Thanks by advance

**Comment by sfackler** [comment]
That is due to https://github.com/rust-lang/pkg-config-rs/pull/105.

**Comment by Litarvan** [comment]
Oh ok, thanks !
