### ISSUE TITLE
Does not compile on termux on Android (aarch64)

### ISSUE THREAD

**Issue by matu3ba** [sfackler/rust-openssl#1327]
**Describe the bug you encountered:**
Problem occured on installation of  cargo-update
`Could not find directory of OpenSSL installation`

**Describe what you expected to happen:**
openssl building

**What version of `rust-openssl` are you using?**

openssl-sys v0.9.58

**Which operating system / distribution are you on?**
Unix: Linux 4.4.226-lineageos aarch64 and *no lsb_release* (Android)

Appended logfile.
[err_install_cargo-update.txt](https://github.com/sfackler/rust-openssl/files/5012573/err_install_cargo-update.txt)

**Comment by sfackler** [comment]
Install pkg-config.

**Comment by matu3ba** [comment]
@sfackler Fixed the issue, thanks. It is inconvenient that pkg-config compiles fine, but is not usable.
