### ISSUE TITLE
Support bindings to EVP_PKEY_get1_(ED|X)(25519|448) functions

### ISSUE THREAD

**Issue by breard-r** [sfackler/rust-openssl#1334]
As part of the OpenSSL 3.0.0 support (#1263), I would like to suggest the implementation of bindings to the new  `EVP_PKEY_get1_ED25519`, `EVP_PKEY_get1_ED448`, `EVP_PKEY_get1_X25519` and `EVP_PKEY_get1_X448` functions (openssl/openssl@7c664b1f1b5f60bf896f5fdea5c08c401c541dfe)). As far as I know, this should be done in the `openssl::pkey::PKey` struct along with the other `EVP_PKEY_get1_` bindings.

**Comment by sfackler** [comment]
Feel free to open a PR against the openssl-300 branch if you'd like! Otherwise I can take a look at some point.

**Comment by breard-r** [comment]
Seems like those functions has been reverted in openssl/openssl@25b16562d386bfd30c7059366d09864260d9f271.
