### ISSUE TITLE
Static linking of OpenSSL when using `sqlx` and `sqlx-macros`

### ISSUE THREAD

**Issue by emk** [sfackler/rust-openssl#1337]
Thank you for maintaining the Rust OpenSSL crates!

I'm the maintainer of [rust-musl-builder](https://github.com/emk/rust-musl-builder), a Docker image used for building static Rust binaries that include `openssl` and `diesel`. I'm currently working to add support for [sqlx](https://github.com/launchbadge/sqlx), and I've run into an interesting challenge: https://github.com/launchbadge/sqlx/issues/670

In a nutshell, `sqlx` includes an `sqlx-macros` package that connects to the database at compile-time. It does this to validate prepared statements, supporting syntax checking of SQL, and type-checking of prepared statement arguments. But this means that it winds up linking against `openssl-sys` twice:

1. `sqlx-macros` links against `openssl-sys` and glibc at compile time. Rust insists that procedural macros are _always_ shared libraries.
2. `sqlx` links against `openssl-sys` and muslc-libc in the final binary, which is static.

Unfortunately, this means that we need to keep track of two versions of OpenSSL: a shared glibc version for macros, and a static  musl-libc version for the final binary. And `OPENSSL_STATIC` doesn't offer enough control over `openssl-sys` to make this work.

I'm not sure what the ideal fix is here. I've proposed several solutions to the `sqlx` maintainers in https://github.com/launchbadge/sqlx/issues/670, and I don't even know if a fix is _possible_ at the level of `sqlx`. So I'm very much open to suggestions. If you _do_ think that this problem is best fixed at the `openssl-sys` level, please let me know, and I'll try to figure out the details and prepare a PR.

Once again, thank you for maintaining the `openssl` crate! It has brought a lot of value to Rust community.

**Comment by sfackler** [comment]
All of the environment variables can be prefixed with the target architecture, so you can set `X86_64_UNKNOWN_LINUX_MUSL_OPENSSL_STATIC=1` which will only apply to the build for `sqlx`, not `sqlx-macros`: https://docs.rs/openssl/0.10.30/openssl/#manual.

**Comment by emk** [comment]
Thank you! Preliminary testing suggests that `X86_64_UNKNOWN_LINUX_MUSL_OPENSSL_STATIC=1` works.

I will be updating `rust-musl-builder` accordingly and re-running the full test test suite. If it works, I'll close this issue. And with any luck, anybody using `rust-musl-builder` should be able to use `sqlx` (or other libraries using `openssl-sys` at compile time) without issues.

**Comment by emk** [comment]
I have updated `rust-musl-builder` to set:

```
X86_64_UNKNOWN_LINUX_MUSL_OPENSSL_DIR=/usr/local/musl/
X86_64_UNKNOWN_LINUX_MUSL_OPENSSL_STATIC=1
```

This makes `sqlx` work very nicely, out of the box. It's still necessary to use [`cargo sqlx prepare`](https://github.com/launchbadge/sqlx/tree/master/sqlx-cli) to avoid connecting to a database at buid time.

**Comment by Rizary** [comment]
@emk sorry for tagging you, but I came across this issue when trying to build static rust binary. May I ask whether you have an example of doing `cargo sqlx prepare` or not in your repo? I couldn't find where should I run the command.
