### ISSUE TITLE
set_psk_client_callback should reject empty PSK identity

### ISSUE THREAD

**Issue by terorie** [sfackler/rust-openssl#1352]
As part of Rust's safety guarantees, the `openssl` crate should reject invalid function inputs that would lead to memory allocation problems.

When writing an empty identity string in `set_psk_client_callback` (or not writing any at all), OpenSSL 1.1.1f calls `CRYPTO_memdup` with length set to zero in `tls_construct_ctos_early_data`. This is an invalid allocation call, and `CRYPTO_memdup` will complain that it can't perform the operation. Setting the identity hint to a non-empty string results in a successful `CRYPTO_memdup` call.

Maybe this is a bug in OpenSSL though. Their documentation does not suggest that the hint parameter must not be empty.

In any case, I would suggest adding a check in the Rust wrapper code and throwing an error such as "PSK identity hint is empty".

### Additional Info

Code sample

```rust
// Send PSK to server.
ssl_connector_builder.set_psk_client_callback(move |_, _, _identity, psk_bytes| {
    let key = key_psk.bytes();
    assert!(
        psk_bytes.len() >= PSK_LEN,
        "OpenSSL PSK client callback does not fit 32 byte PSK"
    );
    psk_bytes[..PSK_LEN].copy_from_slice(&key[..]);
    Ok(32usize)
});
```

LLDB confirming that `CRYPTO_memdup` is called with zero length (register `rsi` is the second argument).

![memdup](https://user-images.githubusercontent.com/21371810/95032780-0f956780-06bc-11eb-8ab4-89f03580df21.png)

The error chain returned is also a bit confusing: `malloc failure` and `internal error`.

```
Failure(MidHandshakeSslStream {
stream: SslStream {
stream: TcpStream { addr: 127.0.0.1:34948, peer: 127.0.0.1:8080, fd: 6 },
ssl: Ssl { state: "error", verify_result: X509VerifyResult { code: 0, error: "ok" } } },
error: Error {
code: ErrorCode(1),
cause: Some(Ssl(ErrorStack([Error {
code: 252129345,
library: "common libcrypto routines",
function: "CRYPTO_memdup",
reason: "malloc failure"
 file: "../crypto/o_str.c", line: 66
},
Error {
code: 337715268,
library: "SSL routines",
function: "tls_construct_ctos_early_data",
reason: "internal error",
file: "../ssl/statem/extensions_clnt.c", line: 819 }]))) } })
```

**Comment by stbuehler** [comment]
> As part of Rust's safety guarantees, the `openssl` crate should reject invalid function inputs that would lead to memory allocation problems.

But openssl does handle the invalid (empty) `identity`, it's just that the error code/message isn't very helpful. So calling this a "memory allocation problem" stretches the meaning of those words, especially as you started this talking about "Rust's safety guarantees".

In short: this isn't about memory safety, just about a more useful error. Imho this is an openssl issue, and a rust workaround would be wrong.

**Comment by sfackler** [comment]
This just seems like an OpenSSL issue, and as @stbuehler noted the fact that an error is returned implies that there is not a memory safety issue.
