### ISSUE TITLE
README instructions for compiling openssl-1.1.0f from source don't quite work

### ISSUE THREAD

**Issue by BartMassey** [sfackler/rust-openssl#1354]
Sadly, downloading the `openssl-1.1.0f.tar.gz` as described in the `README` and trying to configure it as described doesn't quite work: there's a bug in that source code's `Configure` script related to changes in `perl` libraries. Running the following script (adapted from [here](https://github.com/wazuh/wazuh/issues/4054#issuecomment-553453743)) on the source before trying to configure it will fix the problem. I haven't reported an upstream bug against `openssl` because it likely won't be fixed in the supplied source tarball anyhow.

```sh
sed -i "s#'File::Glob' => qw/glob/;#'File::Glob' => qw/bsd_glob/;#g" test/recipes/90-test_fuzz.t
sed -i "s#'File::Glob' => qw/glob/;#'File::Glob' => qw/bsd_glob/;#g" test/recipes/80-test_ssl_new.t
sed -i "s#'File::Glob' => qw/glob/;#'File::Glob' => qw/bsd_glob/;#g" test/recipes/40-test_rehash.t
sed -i "s#'File::Glob' => qw/glob/;#'File::Glob' => qw/bsd_glob/;#g" test/build.info
sed -i "s#'File::Glob' => qw/glob/;#'File::Glob' => qw/bsd_glob/;#g" test/run_tests.pl
sed -i "s#'File::Glob' => qw/glob/;#'File::Glob' => qw/bsd_glob/;#g" util/process_docs.pl
sed -i "s#'File::Glob' => qw/glob/;#'File::Glob' => qw/bsd_glob/;#g" Configure
```

Ugly, I know — suggestions appreciated. Thanks much for writing such a clear `README` for `rust-openssl`: it makes things a lot easier.

**Comment by sfackler** [comment]
I have no involvement with openssl's build logic. You should file an issue on them.
