### ISSUE TITLE
Providing recent API even for older backends

### ISSUE THREAD

**Issue by stbuehler** [sfackler/rust-openssl#1365]
Hi,

would it be reasonable to handle compatibility with older openssl/libressl versions in `openssl-sys` instead of having frontends to check the actual openssl/libressl version?

Frontends need to be flexible enough to handle `const` vs `mut` pointers depending on openssl/libressl versions, but apart from that it would be nice if struct accessors and various functions that got renamed are always available with a "standard" signature.

Examples:
- `OPENSSL_sk_num` vs `sk_num` (unclear which name is better...)
- `ASN1_STRING_get0_data` vs `ASN1_STRING_data`
- `BN_get_rfc2409_prime_768` vs `get_rfc2409_prime_768`
- `EVP_MD_CTX_new` vs `EVP_MD_CTX_create`
- `HMAC_CTX_new` and `HMAC_CTX_free` (simply add alloc/free on top)
- `CRYPTO_malloc` and `CRYPTO_free` (and perhaps others) could also use a "standard" signature (need new names in rust for compat reasons though).
- all the getters and setters in the `openssl` crate dealing with structs in older versions

Obviously certain features require more recent openssl/libressl versions and can't be provided; and it should be clear the provided functions have the expected semantics (probably by "copying" the openssl C code to rust).

**Comment by sfackler** [comment]
`openssl-sys` is supposed to be a direct mirror of the OpenSSL headers. In some cases, OpenSSL provides macros to ease upgrades and those would be fine to mirror with functions in openssl-sys, but I don't want to go beyond what the native library exposes.

**Comment by stbuehler** [comment]
Ok :)
