### ISSUE TITLE
Set ASN1 object to PRINTABLESTRING / (string_mask = nombstr)

### ISSUE THREAD

**Issue by JoshuaNitschke** [sfackler/rust-openssl#1370]
Hi,

I have a need to make certificate where the CommonName, Org, OrgUnit are PRINTABLESTRING instead of UTFSTRING.  I am willing to tackle this if the maintainer would give some pointers as to where the function should be implemented in the rust-openssl library.  If there is already a way to do this, I apologize for making an issue and would appreciate some guidance.

From looking at the openssl source code, I believe we just need to add a binding to:
[ASN1_STRING_set_default_mask_asc(const char *p)](https://github.com/openssl/openssl/blob/225c9660a5a3435d9bcfc9166b9f79f132996249/crypto/asn1/a_strnid.c#L48)

Here is the example of the output of a certificate made through the rust-openssl library, as you see the dnqualifier is set to `PRINTABLESTRING` but the other objects are not.  I need all these `UTF8STRING` objects to be `PRINTABLESTRING`.

**openssl asn1parse -inform PEM -in test.pem** 
```
    0:d=0  hl=4 l=1121 cons: SEQUENCE          
    4:d=1  hl=4 l= 841 cons: SEQUENCE          
    8:d=2  hl=2 l=   3 cons: cont [ 0 ]        
   10:d=3  hl=2 l=   1 prim: INTEGER           :02
   13:d=2  hl=2 l=   8 prim: INTEGER           :51C8A26799DA5F8A
   23:d=2  hl=2 l=  13 cons: SEQUENCE          
   25:d=3  hl=2 l=   9 prim: OBJECT            :sha256WithRSAEncryption
   36:d=3  hl=2 l=   0 prim: NULL              
   38:d=2  hl=2 l= 126 cons: SEQUENCE          
   40:d=3  hl=2 l=  21 cons: SET               
   42:d=4  hl=2 l=  19 cons: SEQUENCE          
   44:d=5  hl=2 l=   3 prim: OBJECT            :organizationName
   49:d=5  hl=2 l=  12 prim: UTF8STRING        :orgName.com
   63:d=3  hl=2 l=  21 cons: SET               
   65:d=4  hl=2 l=  19 cons: SEQUENCE          
   67:d=5  hl=2 l=   3 prim: OBJECT            :organizationalUnitName
   72:d=5  hl=2 l=  12 prim: UTF8STRING        :orgUnitName
   86:d=3  hl=2 l=  39 cons: SET               
   88:d=4  hl=2 l=  37 cons: SEQUENCE          
   90:d=5  hl=2 l=   3 prim: OBJECT            :commonName
   95:d=5  hl=2 l=  30 prim: UTF8STRING        :issuerCommonName
  127:d=3  hl=2 l=  37 cons: SET               
  129:d=4  hl=2 l=  35 cons: SEQUENCE          
  131:d=5  hl=2 l=   3 prim: OBJECT            :dnQualifier
  136:d=5  hl=2 l=  28 prim: PRINTABLESTRING   :R66XA5Aq8mXHW1bno8B7gllO/Ac=
```

**Comment by sfackler** [comment]
It seems like ideally there'd be some other API that would do this which didn't involve messing with global state.

**Comment by JoshuaNitschke** [comment]
@sfackler I dug into the openssl documentation a little more and was able to achieve what I wanted by passing in the type value for [PRINTABLESTRING (19)](https://github.com/openssl/openssl/blob/a829b735b645516041b55746e013692babd8cd31/include/openssl/asn1.h.in#L75) [X509_NAME_add_entry_by_txt](https://www.openssl.org/docs/man1.1.0/crypto/X509_NAME_add_entry_by_txt.html)
