### ISSUE TITLE
openssl error in zokrates

### ISSUE THREAD

**Issue by smithsen** [sfackler/rust-openssl#1379]
Hi,

I am facing a problem in executing the command 
"cargo +nightly -Z package-features build --release --package zokrates_cli --features="libsnark"
I get the error,
 cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  run pkg_config fail: "`\"pkg-config\" \"--libs\" \"--cflags\" \"openssl\"` did not exit successfully: exit code: 1\n--- stderr\nPackage openssl was not found in the pkg-config search path.\nPerhaps you should add the directory containing `openssl.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'openssl\' found\n"

  --- stderr
  thread 'main' panicked at '

  Could not find directory of OpenSSL installation, and this `-sys` crate cannot
  proceed without this knowledge. If OpenSSL is installed and this crate had
  trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
  compilation process.

  Make sure you also have the development packages of openssl installed.
  For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.

  If you're in a situation where you think the directory *should* be found
  automatically, please open a bug at https://github.com/sfackler/rust-openssl
  and include information about your system as well as this message.

  $HOST = x86_64-unknown-linux-gnu
  $TARGET = x86_64-unknown-linux-gnu
  openssl-sys = 0.9.58

  ', /home/smith/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.58/build/find_normal.rs:157:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed

I do not understand how to fix this as I when I do "sudo apt-get install -y openssl", I get 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
openssl is already the newest version (1.1.1-1ubuntu2.1~18.04.6).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.

Please let me know how can I fix this or where am I going wrong

Thanks!

**Comment by sfackler** [comment]
> Make sure you also have the development packages of openssl installed.
> For example, libssl-dev on Ubuntu or openssl-devel on Fedora.

**Comment by smithsen** [comment]
smith@smith-Inspiron-3542:~$ sudo apt-get install libssl-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libssl-dev is already the newest version (1.1.1-1ubuntu2.1~18.04.6).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.

Seems like both libssl-dev and openssl are there. But now I get another different error,
smith@smith-Inspiron-3542:~$ cargo +nightly -Z package-features build --release --package zokrates_cli --features="libsnark"
error: could not find `Cargo.toml` in `/home/smith` or any parent directory
Don't understand how to fix this or how the problem ended up here

**Comment by sfackler** [comment]
You are in the wrong directory.
