### ISSUE TITLE
Switch from lazy_static to once_cell

### ISSUE THREAD

**Issue by jplatte** [sfackler/rust-openssl#1399]
Other crates are slowly moving from lazy_static to once_cell, notably tokio did so in 0.3. Would you accept a PR that does the same thing for this crate?

**Comment by sfackler** [comment]
Assuming it builds on Rust 1.34, sure!

**Comment by jplatte** [comment]
Hrm, apparently the current release has an [MSRV of 1.36.0](https://docs.rs/once_cell/1.5.2/once_cell/#minimum-supported-rustc-version) and MSRV updates are not considered breaking changes like for many other crates ([including lazy_static](https://github.com/rust-lang-nursery/lazy-static.rs#minimum-supported-rustc)). Would that MSRV bump be a big deal to you?

**Comment by sfackler** [comment]
I tend to bump the MSRV as dependencies do. Going to 1.36 seems fine. You'll just need to tweak this line in the PR: https://github.com/sfackler/rust-openssl/blob/master/.github/workflows/ci.yml#L66
