### ISSUE TITLE
Building with Working FIPS Support

### ISSUE THREAD

**Issue by bmgxyz** [sfackler/rust-openssl#1404]
I'm trying to build a Rust program that uses OpenSSL in FIPS mode. After following the FIPS Object Module build instructions and the documentation for `rust-openssl`, I've written a simple program that calls `openssl::fips:enable` and checks the return value of `openssl:fips::enabled`. So far, `enabled()` has always returned `false`, which indicates that the FIPS power up self test or signature verification have failed.

I've verified that my copy of `fipscanister.o` in `libcrypto.a` has the proper HMAC, so I doubt the OpenSSL / FIPS build process is failing. Instead, the problem appears to be in the signature verification. FIPS requires that the build process embed the HMAC-SHA-1 of `fipscanister.o` in the final executable. The source tree contains a Bash script called `fipsld` that acts as a passthrough compiler for this purpose. It also contains a Perl script called `incore` that claims to do this embedding, although it hasn't worked for me yet. There are also many other tools and undocumented options that I don't yet understand.

These tools assume that the end user is building a C program. **How can I modify this process to use `cargo` and `rustc`, without violating FIPS restrictions?** My goal is for my test program to return `true`, indicating that the self test and signature verification both succeeded.

I have tried many different approaches already, including:

 - specifying a custom linker for `cargo` in `.cargo/config`
 - passing down various environment variables through `cargo make`, such as `FIPSLD_CC`
 - using `incore` to embed the correct signature in the final executable
 - modifying the `rust-openssl` build scripts
 - combinations of the above, and other ideas too foolish to mention
 - ...

I'm not sure what else to try, and there seems to be nothing on the Web about this problem. **Has anyone successfully built a working Rust program with OpenSSL and FIPS support?**

If it helps, I'm using OpenSSL 1.0.2u and OpenSSL-FIPS 2.0.16. I'm using an older version of OpenSSL because I read on their website that this is the newest version with FIPS support. It looks now like that may not be true and that 1.1.1 works as well, but the central problem remains either way.

I appreciate any attention or help that anyone can provide.

**Comment by sfackler** [comment]
The method recommended by the FIPS user guide (dynamically linking to a FIPS capable OpenSSL installation) works without issue in my testing.

`fipsld` will not work with a normal Cargo build process as it expects the final compiler invocation to be the one that links to libcrypto, while libcrypto is actually bundled into openssl-sys.rlib in a Cargo build. If you really want to statically link, you can probably build all of your Rust code into a staticlib and then do a final linking step manually with `fipsld`.

**Comment by bmgxyz** [comment]
Thanks for your swift reply. It reassures me to know that at least dynamic linking is possible or even easy.

I'm still failing to get Rust going, and strangely a similar C program that I wrote against the same OpenSSL installation seems to work fine. Here's a minimal example:

First, I set `OPENSSL_DIR="/home/<...>/openssl-1.0.2u/"` and `FIPSDIR="/home/<...>/openssl-fips-2.0.16/"`. These are the locations of my FIPS-capable OpenSSL and FIPS Object Module installations, respectively. For both tests, I will use the same installation.

`fips_test.c`

```c
#include <stdio.h>
#include <openssl/crypto.h>

int main() {
    int result = FIPS_mode_set(1);

    if (result == 1) {
        printf("FIPS mode enabled\n");
    } else {
        unsigned long err = ERR_get_error();
        printf("Failed to enable FIPS mode: %lx\n", err);
    }
}
```

This compiles and runs without any obvious problems.

```
$ env FIPSLD_CC=gcc $FIPSDIR/bin/fipsld -o c_fips_test fips_test.c $OPENSSL_DIR/lib/libcrypto.a -I $OPENSSL_DIR/include/ -ldl
fips_test.c: In function ‘main’:
fips_test.c:10:29: warning: implicit declaration of function ‘ERR_get_error’; did you mean ‘lh_MEM_error’? [-Wimplicit-function-declaration]
         unsigned long err = ERR_get_error();
                             ^~~~~~~~~~~~~
                             lh_MEM_error
fips_test.c: In function ‘main’:
fips_test.c:10:29: warning: implicit declaration of function ‘ERR_get_error’; did you mean ‘lh_MEM_error’? [-Wimplicit-function-declaration]
         unsigned long err = ERR_get_error();
                             ^~~~~~~~~~~~~
                             lh_MEM_error
$ ./c_fips_test 
FIPS mode enabled
```

I confess that I don't know much about C, so I'm mostly feeling around in the dark. But this seems to work.

Rust is a different story:

`src/main.rs`

```rust
use openssl::fips::{enable};

fn main() {
    match enable(true) {
        Ok(_) => println!("FIPS mode enabled"),
        Err(error) => println!("Failed to enable FIPS mode: {}", error)
    };
}
```

`Cargo.toml`

```
[package]
name = "rust-fips-test"
version = "0.1.0"
edition = "2018"

[dependencies]
openssl-sys = "0.9"
openssl = "0.10"
```

```
$ cargo clean
$ env OPENSSL_DIR=$OPENSSL_DIR cargo run
...
Failed to enable FIPS mode: OpenSSL error
```

Notably, when I `run` with `-vv`, I see `[openssl-sys 0.9.60] OPENSSL_DIR = $OPENSSL_DIR` in the build output, with the literal string in place of the variable I wrote there. This gives me some confidence that Rust is really pulling in my intended OpenSSL installation, not any other stuff that might be on my system in the usual places. I suspect that my mistake is still in omitting the signature injection step—which `fipsld` takes care of in the C example—but I don't know how to fix that yet.

My questions:

1. What am I doing wrong in the Rust build process, if the C process is working?
2. How can I further unpack the `error` that `enable()` returns? I see that it's an `ErrorStack`, but when I run its `errors()` method and print the result I only see an empty array `[]`.
3. I left `OPENSSL_STATIC` unset on purpose to try to link dynamically. But I noticed that the output binary doesn't change (the hashes are identical in both cases) when I set `OPENSSL_STATIC=1`. What am I missing in this context?

Thanks for your help.

**Comment by bmgxyz** [comment]
> Your C build is statically linking to OpenSSL with fipsld, which as I noted above, is just not really going to work cleanly with the way Cargo builds things.

Okay, that makes sense. Static linking is a soft requirement for my application, so I will probably end up attempting what you mentioned before about emitting object code from `rustc`/`cargo` and using `fipsld` in the end. Although I'm mostly speaking phonetically on that right now.

> Did your OpenSSL build actually produce dynamic libraries?

Good point. No, it hadn't. But I've since added `shared` to the `./config` step for my OpenSSL build, and now I see `$OPENSSL_DIR/lib/lib{ssl,crypto}.so`, among others in subdirectories.

> That should be fixed by 62afbbe.

Yes, I'm tracking `master` now. Thanks for pushing that change. My test program (lightly modified) now shows:

```
Failed to enable FIPS mode: [Error { code: 252104805, library: "common libcrypto routines", function: "FIPS_mode_set", reason: "fips mode not supported", file: "o_fips.c", line: 93 }]
```

The FOM User Guide says:

> "fips mode not supported"
> You likely linked against a non-FIPS Capable library.
> Ensure `config fips <options>` was executed when configuring.

I don't understand this error because I'm already running what I believe to be the correct FOM / FIPS OpenSSL build steps. Copied from my `cargo make` tasks:

```bash
# remove and re-extract OpenSSL
cd ${OPENSSL_DIR}
rm -rf ./bin ./include ./lib ./src
tar xf ${OPENSSL_NAME}.tar.gz
mv ${OPENSSL_NAME}/ src/

# remove and re-extract FOM
cd ${FIPSDIR}
rm -rf ./bin ./include ./lib ./src
tar xf ${FIPSNAME}.tar.gz
mv ${FIPSNAME}/ src/

# build FOM
cd ${FIPSDIR}/src
./config
make
make install

# build FIPS-capable OpenSSL
cd ${OPENSSL_DIR}/src
./config fips shared --prefix=${OPENSSL_DIR} --with-fipsdir=${FIPSDIR}
make depend
make
make install
```

`cargo make` sets some environment variables for all tasks, like `OPENSSL_DIR` and `FIPSDIR`, but just for good measure I pass `--with-fipsdir=${FIPSDIR}`.

1. Are there more steps in the FIPS-capable OpenSSL build process for dynamic linking? I didn't see any in the FOM User Guide, but maybe I missed something.
2. Is seeing the correct value of `OPENSSL_DIR` in `cargo build -vv` output enough to safely assume that `cargo` is picking up the correct OpenSSL installation? I'm concerned that it's not, which might explain why I'm getting this "FIPS unsupported" error.
3. Do you have any further suggestions / thoughts on this problem?

**Comment by sfackler** [comment]
Does `ldd` indicate that your Rust program is linking to your FIPS OpenSSL at runtime?

**Comment by bmgxyz** [comment]
No, it doesn't:

```
$ ldd target/debug/rust-fips-test
        linux-vdso.so.1 (0x00007ffffd3f3000)
        libssl.so.1.0.0 => /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007facda8be000)
        libcrypto.so.1.0.0 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007facda47a000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007facda262000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007facd9e71000)
        /lib64/ld-linux-x86-64.so.2 (0x00007facdad83000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007facd9c52000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007facd9a4e000)
```

which answers (2) above.

I still see the correct value of `OPENSSL_DIR` in the `cargo` output. I also followed the relevant logic in the `openssl-sys` build scripts and everything seemed like it should work, given my input.

Any ideas?

**Comment by sfackler** [comment]
LD_LIBRARY_PATH controls the paths the dynamic linker searches - you'll need to set that to point to the lib directory of your OpenSSL build.

**Comment by bmgxyz** [comment]
That fixed it.

```
$ LD_LIBRARY_PATH=${OPENSSL_DIR}/lib ./target/debug/rust-fips-test 
FIPS mode enabled
```

**Thank you.** You have helped me a lot.

Now I'm pursuing the static linking method you mentioned before. I've created a static archive with this command:

```
OPENSSL_DIR=$OPENSSL_DIR cargo rustc -- --crate-type=staticlib
```

The static archive appears at `target/debug/deps/librust_fips_test-<ID>.a`. It contains over 250 object files, many of which appear to be numbered pieces of larger libraries.

But I think this command is wrong, because it still links `openssl` and `openssl-sys`. If I pass this archive to `fipsld` along with my FIPS-capable `libcrypto.a`, it will fail because of the overlap, and maybe other reasons.

Some ideas I have:

 - remove `openssl` and `openssl-sys` objects from the static archive before passing to `fipsld`
 - build a different archive out of the contents of `target/debug/deps/` without `openssl` and `openssl-sys`
 - tell `cargo` / `rustc` to preprocess, compile, and assemble everything in the dependency tree, but only link objects unrelated to `openssl*`, leaving the references "dangling" until I can link them up to the proper FIPS-capable objects later with `fipsld`

The first two seem difficult and error-prone, and I'm not sure how to learn about the third, or if it's even possible / reasonable. Is there a simpler way? Overall, what process do you recommend for static linking?

Thank you again for your help.

**Comment by sfackler** [comment]
One very hacky option is to set the `OPENSSL_LIBS` environment variable to the empty string. That will prevent openssl-sys from actually linking to libssl and libcrypto, allowing you to do it at the end with fipsld and the staticlib.

**Comment by bmgxyz** [comment]
It looks like setting `OPENSSL_LIBS=""` may indeed have prevented `cargo` from linking `libcrypto.a` and `libssl.a`, but it isn't clear. I compared the original archive with `OPENSSL_DIR=$OPENSSL_DIR` to the new archive with just `OPENSSL_LIBS=""`. Both outputs of `ar t librust-fips-test-024ed65c2050598a.a` contain the same lines, but the `sha1sum`s of the archives do not match, and the empty libs archive is about 1 MB smaller.

But when I try to link `libcrypto.a` and `libssl.a` manually with `fipsld` I get hundreds of `undefined reference` errors.

```
$ env FIPSLD_CC=gcc $FIPSDIR/bin/fipsld -o rust_fips_test ./target/debug/deps/librust_fips_test-024ed65c2050598a.a $OPENSSL_DIR/lib/libcrypto.a $OPENSSL_DIR/lib/libssl.a -ldl
(many undefined reference errors)
collect2: error: ld returned 1 exit status
```

Maybe my `fipsld` command is wrong?

Some examples of the errors:

```
./target/debug/deps/librust_fips_test-024ed65c2050598a.a(openssl-aa047f9217d1e7ab.openssl.1fmxuqkh-cgu.10.rcgu.o): In function `openssl::dh::Dh<openssl::pkey::Params>::from_pqg':
/home/<...>/.cargo/git/checkouts/rust-openssl-41da9d20ce19f5aa/62afbbe/openssl/src/dh.rs:65: undefined reference to `DH_set0_pqg'
```

```
$OPENSSL_DIR/lib/libssl.a(t1_enc.o): In function `tls1_change_cipher_state':
t1_enc.c:(.text+0xa09): undefined reference to `COMP_CTX_free'
t1_enc.c:(.text+0xa26): undefined reference to `COMP_CTX_new'
t1_enc.c:(.text+0xb09): undefined reference to `COMP_CTX_free'
t1_enc.c:(.text+0xb2a): undefined reference to `COMP_CTX_new'
```

Notably, there aren't any errors related to `libcrypto`, unless I omit the `-ldl` flag.

**Comment by sfackler** [comment]
Because LD Is Old, you need to pass it arguments in topological order. Because libssl depends on libcrypto, you'll need to swap the order of those two in your fipsld call.

**Comment by bmgxyz** [comment]
I didn't know about the topological sort limitation of `ld`. Thanks for pointing it out. I never would have thought of it.

I tried swapping `libcrypto.a` and `libssl.a`, but I got the same errors:

```
$ env FIPSLD_CC=gcc $FIPSDIR/bin/fipsld -o rust_fips_test ./target/debug/deps/librust_fips_test-024ed65c2050598a.a ${OPENSSL_DIR}lib/libssl.a ${OPENSSL_DIR}lib/libcrypto.a -ldl
(kaboom)
```

I also tried moving `librust_fips_test` to the end, but that didn't have any effect either.

I read [here](https://stackoverflow.com/questions/34164594/gcc-ld-method-to-determine-link-order-of-static-libraries/34168951#34168951) that `gold` and `lld` don't have this topological ordering limitation, so I tried them both by replacing the symlink on my system at `/usr/bin/ld`. In both cases, I saw similar errors to the ones I saw with `ld`. For example, `lld` gives this error first, followed by many others like it:

```
ld: error: undefined symbol: EVP_MD_CTX_free
>>> referenced by sign.rs:121 (/home/<...>/.cargo/git/checkouts/rust-openssl-41da9d20ce19f5aa/62afbbe/openssl/src/sign.rs:121)
>>>               openssl-aa047f9217d1e7ab.openssl.1fmxuqkh-cgu.11.rcgu.o:(_$LT$openssl..sign..Signer$u20$as$u20$core..ops..drop..Drop$GT$::drop::h5a9f62b1fd891321) in archive ./target/debug/deps/librust_fips_test-024ed65c2050598a.a
>>> referenced by sign.rs:413 (/home/<...>/.cargo/git/checkouts/rust-openssl-41da9d20ce19f5aa/62afbbe/openssl/src/sign.rs:413)
>>>               openssl-aa047f9217d1e7ab.openssl.1fmxuqkh-cgu.11.rcgu.o:(_$LT$openssl..sign..Verifier$u20$as$u20$core..ops..drop..Drop$GT$::drop::hb36511d3a385647b) in archive ./target/debug/deps/librust_fips_test-024ed65c2050598a.a
>>> referenced by hash.rs:347 (/home/<...>/.cargo/git/checkouts/rust-openssl-41da9d20ce19f5aa/62afbbe/openssl/src/hash.rs:347)
>>>               openssl-aa047f9217d1e7ab.openssl.1fmxuqkh-cgu.4.rcgu.o:(_$LT$openssl..hash..Hasher$u20$as$u20$core..ops..drop..Drop$GT$::drop::h72bf20f49f03eb7e) in archive ./target/debug/deps/librust_fips_test-024ed65c2050598a.a
```

In that same StackOverflow answer, the author explains that it's possible to use `nm` to dump a list of symbols from each archive and then perform the topological sort on that. This seems like the long way around. But just poking around I can see that some of the `undefined symbol`s really seem to be missing, while others are in the archives like they should be. Some others also seem to have similar symbols with `D` inserted at the beginning. Take a few examples:

```bash
$ nm -go ${OPENSSL_DIR}lib/lib{crypto,ssl}.a | grep EVP_MD_CTX_free
$ nm -go ${OPENSSL_DIR}lib/lib{crypto,ssl}.a | grep OPENSSL_cipher_name
$ nm -go ${OPENSSL_DIR}lib/lib{crypto,ssl}.a | grep SSL_CTX_new
${OPENSSL_DIR}lib/libssl.a:ssl_lib.o:00000000000020d0 T SSL_CTX_new

# also some near misses
$ nm -go ${OPENSSL_DIR}lib/lib{crypto,ssl}.a | grep TLS_method
${OPENSSL_DIR}lib/libssl.a:d1_meth.o:0000000000000020 T DTLS_method
${OPENSSL_DIR}lib/libssl.a:d1_lib.o:                 U DTLS_method
$ nm -go ${OPENSSL_DIR}lib/lib{crypto,ssl}.a | grep TLS_server_method
${OPENSSL_DIR}lib/libssl.a:d1_srvr.o:0000000000000fe0 T DTLS_server_method
```

I'm not sure how to interpret the `D*` symbols. I thought maybe they were the dynamic versions of their static counterparts, but I don't think that makes any sense.

It confuses me that some symbols are indeed missing, while others aren't, and still others have slightly different names.

**Comment by sfackler** [comment]
EVP_MD_CTX_free was added in 1.1.0, so it seems like openssl-sys is building against a different copy of OpenSSL than then FIPS one. Make sure you're pointing it in the right direction via PKG_CONFIG_PATH or OPENSSL_DIR when running the cargo build.

**Comment by bmgxyz** [comment]
Ah, right, I forgot to mention that I saw errors with `OPENSSL_DIR=${OPENSSL_DIR} OPENSSL_LIBS=""`. I removed `OPENSSL_DIR=${OPENSSL_DIR}` for testing and then forgot to add it back.

Here's the error I get with both environment variables set:

```
$ cargo clean; OPENSSL_LIBS="" OPENSSL_DIR=${OPENSSL_DIR} cargo rustc --verbose -- --crate-type=staticlib
...
error: failed to run custom build command for `openssl-sys v0.9.60 (https://github.com/sfackler/rust-openssl#62afbbe1)`
...
thread 'main' panicked at 'OpenSSL libdir at `${OPENSSL_DIR}/lib` does not contain the required files to either statically or dynamically link OpenSSL', /home/<...>/.cargo/git/checkouts/rust-openssl-41da9d20ce19f5aa/62afbbe/openssl-sys/build/main.rs:326:13
```

It looks like the build script isn't happy with empty `OPENSSL_LIBS` because it determines the linking mode based on the contents of `libdir`. That value ultimately comes from `OPENSSL_LIBS` or `${OPENSSL_DIR}/lib` in `find_normal.rs`. What confuses me further is that the directory it complains about (`${OPENSSL_DIR}/lib`) really does have the static archives in it:

```
$ ls ${OPENSSL_DIR}/lib
engines      libcrypto.so        libssl.a   libssl.so.1.0.0
libcrypto.a  libcrypto.so.1.0.0  libssl.so  pkgconfig
```

But in this case we don't care about that anyway.

I applied this diff to try to get around the logic temporarily:

```diff
diff --git a/openssl-sys/build/main.rs b/openssl-sys/build/main.rs
index 6fdeda78..0fccf3a9 100644
--- a/openssl-sys/build/main.rs
+++ b/openssl-sys/build/main.rs
@@ -93,7 +93,7 @@ fn main() {
         },
     };
 
-    let kind = determine_mode(Path::new(&lib_dir), &libs);
+    /*let kind = determine_mode(Path::new(&lib_dir), &libs);
     for lib in libs.into_iter() {
         println!("cargo:rustc-link-lib={}={}", kind, lib);
     }
@@ -104,7 +104,7 @@ fn main() {
         println!("cargo:rustc-link-lib=dylib=crypt32");
         println!("cargo:rustc-link-lib=dylib=ws2_32");
         println!("cargo:rustc-link-lib=dylib=advapi32");
-    }
+    }*/
 }
 
 fn check_rustc_versions() {
```

but that resulted in `undefined reference` errors:

```
$ cargo clean; OPENSSL_LIBS="" OPENSSL_DIR=${OPENSSL_DIR} cargo rustc --verbose -- --crate-type=staticlib
...
Compiling rust-fips-test v0.1.0 (/home/<...>/)
...
error: linking with `cc` failed: exit code: 1
...
  = note: ld: error: undefined symbol: FIPS_mode_set                                                                                                                                                        
          >>> referenced by fips.rs:14 (rust-openssl/openssl/src/fips.rs:14)                                                                                                                                
          >>>               openssl-a76f43dbd4f52656.1sxjikaulvs5y29r.rcgu.o:(openssl::fips::enable::ha450c74345136009) in archive /home/<...>/target/debug/deps/libopenssl-a76f43dbd4f52656.rlib  
                                                                                                                                                                                                            
          ld: error: undefined symbol: ERR_get_error_line_data                                                                                                                                              
          >>> referenced by error.rs:112 (rust-openssl/openssl/src/error.rs:112)                                                                                                                            
          >>>               openssl-a76f43dbd4f52656.54hvlr71gkko9n7e.rcgu.o:(openssl::error::Error::get::hdcc8c4744a631a90) in archive /home/<...>/target/debug/deps/libopenssl-a76f43dbd4f52656.r
lib
...
Caused by:                                                
  process didn't exit successfully: `rustc --crate-name rust_fips_test --edition=2018 src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode
=no -C debuginfo=2 --crate-type=staticlib -C metadata=95e1b161252dc5e4 -C extra-filename=-95e1b161252dc5e4 --out-dir /home/<...>/target/debug/deps -C incremental=/home/<...>/target/debug/incremental -L dependency=/home/<...>/target/debug/deps --extern openssl=/home/<...>/target/debug/deps/libopenssl-a76f43dbd4f52656.rlib -L native=${OPENSSL_DIR}/lib` (exit code: 1)
```

There weren't as many missing symbols, only 11 this time. (There wasn't any indication that the output was truncated.) The missing symbols were:

```
FIPS_mode_set
ERR_get_error_line_data
ERR_lib_error_string
ERR_func_error_string
ERR_reason_error_string
CRYPTO_set_id_callback
SSL_library_init
SSL_load_error_strings
OPENSSL_add_all_algorithms_noconf
CRYPTO_num_locks
CRYPTO_set_locking_callback
```

Clearly my change wasn't right, but I wonder if a different one would work better, even just for my use case.

I also tried passing `OPENSSL_STATIC=1`, but I got a different error:

```
$ cargo clean; OPENSSL_LIBS="" OPENSSL_DIR=${OPENSSL_DIR} OPENSSL_STATIC=1 cargo rustc --verbose -- --crate-type=staticlib
...
     Running `/home/<...>/target/debug/build/openssl-e082209008cc14ec/build-script-build`
...
error: empty library name given via `-l`

error: aborting due to previous error

error: could not compile `openssl-sys`

Caused by:
  process didn't exit successfully: `rustc --crate-name openssl_sys /home/<...>/.cargo/git/checkouts/rust-openssl-41da9d20ce19f5aa/62afbbe/openssl-sys/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=969d803268f450bb -C extra-filename=-969d803268f450bb --out-dir /home/<...>/target/debug/deps -L dependency=/home/<...>/target/debug/deps --extern libc=/home/<...>/target/debug/deps/liblibc-be9a78567febb1ba.rmeta --cap-lints allow -L native=${OPENSSL_DIR}/lib --cfg const_fn --cfg 'osslconf="OPENSSL_NO_KRB5"' --cfg 'osslconf="OPENSSL_NO_RFC3779"' --cfg ossl101 --cfg ossl102 --cfg ossl102f --cfg ossl102h -l static=` (exit code: 1)
```

which makes sense because `-l static=` shouldn't be valid.

**Comment by sfackler** [comment]
Unless you are manually replacing your actual OpenSSL dir with `${OPENSSL_DIR}`, the error message claims that `OPENSSL_DIR` is set to the literal string `${OPENSSL_DIR}`, which is most likely not the name of the directory containing your FIPS build.

**Comment by sfackler** [comment]
I pushed a commit up to fix the handling of an empty OPENSSL_LINK. With that, this Dockerfile succeeds.

```dockerfile
FROM rust:1.49.0-slim

RUN set -eux; \
        apt-get update; \
        apt-get install -y curl make perl-modules; \
        rm -rf /var/lib/apt/lists/*;

RUN set -eux; \
        curl -L https://www.openssl.org/source/openssl-fips-2.0.16.tar.gz | tar xzf -; \
        cd openssl-fips-2.0.16; \
        FIPSDIR=/openssl-fips ./config; \
        make; \
        make install;

RUN set -eux; \
        curl -L https://www.openssl.org/source/old/1.0.2/openssl-1.0.2u.tar.gz | tar xzf -; \
        cd openssl-1.0.2u; \
        ./config fips shared --prefix=/openssl-fips --with-fipsdir=/openssl-fips; \
        make; \
        make install_sw;

RUN set -eux; \
        mkdir -p foo/src; \
        cd foo; \
        echo '\
[package]\n\
name = "foo"\n\
version = "0.1.0"\n\
authors = []\n\
edition = "2018"\n\
[lib]\n\
crate-type = ["staticlib"]\n\
[dependencies]\n\
openssl = { git = "https://github.com/sfackler/rust-openssl" }\n\
' >> Cargo.toml; \
        echo '#[no_mangle]\n\
pub fn rust_main() {\n\
        openssl::fips::enable(true).unwrap();\n\
        println!("success");\n\
}\n\
' >> src/lib.rs; \
        OPENSSL_STATIC=1 OPENSSL_LIBS="" OPENSSL_DIR=/openssl-fips cargo build;

RUN set -eux; \
        echo '\
void rust_main();\n\
int main() {\n\
        rust_main();\n\
}\n\
' >> shim.c; \
        CC=gcc FIPSDIR=/openssl-fips /openssl-fips/bin/fipsld -L foo/target/debug -L /openssl-fips/lib shim.c -Wl,-static -lfoo -lssl -lcrypto -o fips-test -Wl,-Bdynamic -lc -ldl -pthread; \
        ldd fips-test; \
        ./fips-test;
```

**Comment by bmgxyz** [comment]
**Success.** I pulled the logic in your Dockerfile out onto my test system, and now everything compiles and is happy:

```
$ ./fips-test
FIPS mode enabled
```

Thank you for your help. My next task will be to modify this process to get it working under Windows, but you've already given me more than enough information to get started.

Closing now since you've resolved my issue. Thanks again. :+1:

**Comment by sfackler** [comment]
Nice!
