### ISSUE TITLE
Cross-compiling to unknown-linux-musl on Manjaro (archlinux) fails

### ISSUE THREAD

**Issue by jonahbron** [sfackler/rust-openssl#1405]
When running `cargo build` on my system for a project (that indirectly depends on openssl-sys), I'm getting the error below.  I installed the packages that it said to have for arch (`openssl` and `pkg-config`).  The error first says that I need to install a sysroot for the target platform, but the error below talks about not being able to find OpenSSL.  These seem contradictory.  My guess is that the first error is the correct one, and the second one is being accidentally triggered.

Which error should I trust is the real problem?

```
  run pkg_config fail: "pkg-config has not been configured to support cross-compilation.\n\n                Install a sysroot for the target platform and configure it via\n                PKG_CONFIG_SYSROOT_DIR and PKG_CONFIG_PATH, or install a\n                cross-compiling wrapper for pkg-config and set it via\n                PKG_CONFIG environment variable."

  --- stderr
  thread 'main' panicked at '

  Could not find directory of OpenSSL installation, and this `-sys` crate cannot
  proceed without this knowledge. If OpenSSL is installed and this crate had
  trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
  compilation process.

  Make sure you also have the development packages of openssl installed.
  For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.

  If you're in a situation where you think the directory *should* be found
  automatically, please open a bug at https://github.com/sfackler/rust-openssl
  and include information about your system as well as this message.

  $HOST = x86_64-unknown-linux-gnu
  $TARGET = x86_64-unknown-linux-musl
  openssl-sys = 0.9.60
```

**Comment by sfackler** [comment]
If you are trying to cross compile, you need a copy of OpenSSL cross compiled for your target.

**Comment by jonahbron** [comment]
That makes sense.  I've managed to avoid this problem entirely by doing the compilation in a specialized container.  Thanks!

https://github.com/clux/muslrust
