### ISSUE TITLE
Don't use borrowed values in Signer struct

### ISSUE THREAD

**Issue by tomleavy** [sfackler/rust-openssl#1412]
I ran into an issue where I can't assign the Signer struct to one of my own structs because it does not take ownership over the key that you pass into it. The compiler gives a message saying 

assignment requires that `pkey` is borrowed for `'a

Removing the necessity for a named lifetime and holding ownership of the key so that you can pass the Signer struct around would make it a lot easier to work with

**Comment by sfackler** [comment]
The ownership of Signer reflects the ownership of the underlying OpenSSL APIs.

**Comment by tomleavy** [comment]
@sfackler sorry for my ignorance when it comes to how C APIs and Rust interact, but is it possible to keep the pointer to the underlying OpenSSL pkey on the heap so that it can be owned by the Signer struct and released on drop?

**Comment by sfackler** [comment]
Sure - you could make something like that with a struct that stores both values and a bit of unsafe code to ensure the signer drops before the key.

**Comment by tomleavy** [comment]
I found a way around it, will close
