### ISSUE TITLE
Not building on Fedora 33

### ISSUE THREAD

**Issue by jatin-cbs** [sfackler/rust-openssl#1418]
I do have all packages installed from the fedora repository openssl openssl-devel rust cargo  
Exact version - 
openssl-1.1.1i-3.fc33 

it shows `error: failed to run custom build command for `openssl v0.9.24` rust`  
tried with reqwest as a dependency.

**Comment by sfackler** [comment]
openssl v0.9 is over 3 years out of date, and does not support OpenSSL 1.1.1. You should upgrade your reqwest dependency.

**Comment by jatin-cbs** [comment]
@sfackler  Its the latest version reqwest = "0.11.1"

**Comment by sfackler** [comment]
Yeah, it looks like kitsu has many old dependencies that are pulling in that version of openssl.
