### ISSUE TITLE
Get BigNum pointer

### ISSUE THREAD

**Issue by FrankC01** [sfackler/rust-openssl#1424]
Is it possible to get the BigNum as pointer?

E.g:
```rust
let a = BigNum::from_u32(2).unwrap();
let a_ptr = a.as_ptr() as *const _ as u64;
```

**Comment by sfackler** [comment]
Yes, using the ForeignType trait: https://docs.rs/openssl/0.10.32/openssl/bn/struct.BigNum.html#impl-ForeignType

**Comment by FrankC01** [comment]
Trying to `use` that complains it's a private crate?

For what I am trying to accomplish, I need the pointer to the BigNum and it's length (inclusive of the actual number length in bytes), to make a call to a block-chain system call. On the other side of the call I can re-instantiate to a BigNumRef.

Any insight?

**Comment by sfackler** [comment]
Do you want a pointer to the OpenSSL BN data type, or the actual numeric representation? If it's the latter, use https://docs.rs/openssl/0.10.32/openssl/bn/struct.BigNum.html#method.to_vec.

**Comment by FrankC01** [comment]
The pointer to the BN data type is what I was looking for.

**Comment by sfackler** [comment]
```toml
[dependencies]
foreign-types = "0.3"
```

```rust
use foreign_types::ForeignType;

let a = BigNum::from_u32(2).unwrap();
let a_ptr = a.as_ptr();
```

**Comment by FrankC01** [comment]
Great... can I presume that the length that the `a_ptr` points to is the size of BigNum plus a.num_bytes() or is `a.num_bytes()` all I need?

**Comment by sfackler** [comment]
That is not a thing you can assume - the BN type is opaque in OpenSSL. You should use to_vec/from_slice if you want to extract the value of the number for reassembly elsewhere.

**Comment by FrankC01** [comment]
Thank you!
