### ISSUE TITLE
Handle lack of ssl on windows in build script

### ISSUE THREAD

**Issue by djrenren** [sfackler/rust-openssl#143]
This should be possible right?
Manual intervention really gets in the way of the magic that is cargo packages

**Comment by sfackler** [comment]
Could you clarify what you mean by "handle"? Installation of native dependencies seems a bit out of scope for a buildscript. It's not like it currently shells out to apt-get, yum, pacman, etc on Linux if OpenSSL's not installed.

**Comment by djrenren** [comment]
I don't see the issue with fetching a local prebuilt copy of openssl if it's not present.

On other platforms there is a defined method of fetching the dependencies. On windows, rust bundles all of the gnutools with install rather than requiring a user-configured msys install. It makes sense that libraries should follow that precedent and not require manual intervention with the msys install.

**Comment by djrenren** [comment]
or better, have a openssl-win package that contains the prebuilts and use it as a platform dependent dependency.

**Comment by sfackler** [comment]
openssl-sys dynamically links to OpenSSL, which isn't going to work very well if the libraries are sitting in a random directory. I'm *especially* hesitant to shove a local copy somewhere because it's really important that the installation of OpenSSL that we're linking to is updated by the user as new versions are released that patch critical vulnerabilities.

**Comment by djrenren** [comment]
Hmmm the dynamic linking is certainly a problem... but as for keeping the binary up to date, I doubt most windows developers want to go through that hassle again.

besides, for any sort of distribution on windows you couldn't rely on dynamic linking to a preinstalled library.

**Comment by sfackler** [comment]
I would hope that developers would go through the hassle, since the alternative is releasing a product with known vulnerabilities that, for example, let you [remotely extract the server's private key](http://heartbleed.com/).

**Comment by djrenren** [comment]
Why not automate the process? that way whenever I update rust-openssl I get the most recent version of openssl which the package should be tracking anyway. I don't see the downside.
