### ISSUE TITLE
Question: X509Lookup::add_dir()

### ISSUE THREAD

**Issue by pavlicekcn** [sfackler/rust-openssl#1432]
Hey.
I'd like to add directory for openSSL to check for certs. In documentation I found this:
https://docs.rs/openssl/0.10.32/openssl/x509/store/struct.X509Lookup.html
I have hard time understanding it. What I tried is this:
```Rust
let mut x = openssl::x509::store::X509Lookup::hash_dir();
openssl::x509::store::X509LookupRef::add_dir(*x, "/etc/ssl/certs", openssl::ssl::SslFiletype::PEM)
```

I don't understand how I can get `X509LookupRef<HashDir>` struct? `X509Lookup::hash_dir()` returns `&'static X509LookupMethodRef<HashDir`. I thought there would be some kind of trick for that with Deref trait but I can't figure it out.

Sorry, my knowledge regarding SSL and certs is pretty basic. Any help much appreciated.

**Comment by sfackler** [comment]
```rust
let mut builder = X509StoreBuilder::new()?;
builder.add_lookup(X509Lookup::hash_dir())?
    .add_dir("/etc/ssl/certs", SslFiletype::PEM)?;
let store = builder.build();
```

**Comment by aaronenberg** [comment]
Hi,
I am trying to construct an X509Store this way but I am not getting any certs. I'm not sure if I'm using this method correctly but here is what I tried:
```rust
let mut builder = X509StoreBuilder::new()?;
builder
    .add_lookup(store::X509Lookup::hash_dir())?
    .add_dir("/example/certs", SslFiletype::PEM)?;
let store = builder.build();

for x509_obj_ref in store.objects().iter() {
    if let Some(x509) = x509_obj_ref.x509() {
        ... // never executed
    }
}
```

The directory has been rehashed with `openssl rehash /example/certs` as well.
I am able to get certs when using the default load locations though.
Am I missing something here?
