### ISSUE TITLE
Return values are not checked

### ISSUE THREAD

**Issue by manuels** [sfackler/rust-openssl#144]
At least in the crypto module a lot of return values are not checked which may result in catastrophic failures:

E.g.
https://github.com/sfackler/rust-openssl/blob/master/src/crypto/pkey.rs#L72
https://github.com/sfackler/rust-openssl/blob/master/src/crypto/pkey.rs#L94
https://github.com/sfackler/rust-openssl/blob/master/src/crypto/pkey.rs#L102

**Comment by gkoz** [comment]
I'm hacking on a redesign of the `crypto` module and adding error handling is planned too.

**Comment by manuels** [comment]
great!

**Comment by gkoz** [comment]
You might not want to close the issue just yet :)

**Comment by lakechfoma** [comment]
I started adding error checking in symm.rs before finding this issue. Just wondering how the redesign is going now that its been a few weeks, and if I can contribute at all? At least by replacing some return types with Result

**Comment by gkoz** [comment]
@lakechfoma Here's the PR https://github.com/sfackler/rust-openssl/pull/154

**Comment by sfackler** [comment]
Pkey should be checking for errors in the right places now.
