### ISSUE TITLE
How can I build with the vendored feature and the no-asm Configure argument?

### ISSUE THREAD

**Issue by arthurgreef** [sfackler/rust-openssl#1441]
Hi I cannot figure out how to add arguments to the Configure arguments. I'd like to add a no-asm argument. 

running "perl" "./Configure" "--prefix=/mnt/c/Users/arthurgr/work/github/rust-openssl/target/wasm32-wasi/debug/build/openssl-sys-fd0a4d8719790c00/out/openssl-build/install" "no-dso" "no-shared" "no-ssl3" "no-unit-test" "no-comp" "no-zlib" "no-zlib-dynamic" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "gcc" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "--target=wasm32-wasi"

Thanks.

**Comment by sfackler** [comment]
Why do you want to do this in the first place?

**Comment by FrankC01** [comment]
I'm working with @arthurgreef to build to the `wasm32-wasi` target.

**Comment by sfackler** [comment]
You would probably want to make a change to openssl-src to support that target.

**Comment by FrankC01** [comment]
Able to get rust-openssl to build with `--target wasm32-wasi` after changes to `openssl-src-rs` as per:
https://github.com/alexcrichton/openssl-src-rs/issues/88
