### ISSUE TITLE
Building with vendored feature and wasi target does not produce a wasm file

### ISSUE THREAD

**Issue by arthurgreef** [sfackler/rust-openssl#1443]
When I build with the following command I do not get a wasm file generated.

cargo build --features vendored --manifest-path ./openssl-sys/Cargo.toml --target wasm32-wasi

Am I missing something?

Thanks.

**Comment by sfackler** [comment]
I don't think this is specific to rust-openssl. You would probably be better off asking somewhere like /r/rust or users.rust-lang.org.
