### ISSUE TITLE
【Help】NO_TLSV1_3 

### ISSUE THREAD

**Issue by silence-coding** [sfackler/rust-openssl#1453]
Why is NO_TLSV1_3 set in the mozilla_intermediate method? Are there any hidden problems? Can I simply clear_options off the tag?

**Comment by sfackler** [comment]
The mozilla_intermediate constructor corresponds to a version of the Mozilla standards from before TLS 1.3 was added, and doesn't specify that 1.3 should be enabled. You should be fine just enabling it, but you may instead want to use the mozilla_intermediate_v5 constructor which corresponds to the current version of the standards which *does* define 1.3 support: https://wiki.mozilla.org/Security/Server_Side_TLS#Intermediate_compatibility_.28recommended.29

https://docs.rs/openssl/0.10.33/openssl/ssl/struct.SslAcceptor.html#method.mozilla_intermediate_v5

**Comment by silence-coding** [comment]
@sfackler Thank!
