### ISSUE TITLE
Wrong shared libary is linked

### ISSUE THREAD

**Issue by Bergmann89** [sfackler/rust-openssl#1461]
Hi,

I'm trying to link my Rust application against a custom build version of openssl v3.0.0 by pointing `OPENSSL_DIR`, `OPENSSL_LIB_DIR` and `OPENSSL_INCLUDE_DIR` to my custom build openssl library. Unfortunately Rust is linking my application against the openssl library installed in my system library paths. Is there any possibility to tell Rust to link against my custom version of openssl?

Best regards,
Bergmann89.

**Comment by sfackler** [comment]
You only need to set OPENSSL_DIR, fyi. OPENSSL_LIB_DIR and OPENSSL_INCLUDE_DIR only need to be used if the install is "split" with headers and libraries in different places.

OpenSSL 3.0.0 is only supported on the ossl-300 branch on the repo since it is still an alpha.

Setting OPENSSL_DIR should be all that's necessary. What is the output of the openssl-sys build script? It should be in `target/debug/build/openssl-sys-<lots of numbers here>/output`.

**Comment by Bergmann89** [comment]
The actual problem is, that a other crate of my application adds `/usr/lib/x86_64-linux-gnu` to the linker search path, before openssl-sys adds the path I passed with `OPENSSL_LIB_DIR`. So the linker uses the openssl library installed in my system instead the custom one. 

The output of the build script seemse to be ok:
```
cargo:rustc-cfg=const_fn
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR
X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR unset
cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
OPENSSL_LIB_DIR = /rootfs/openssl-3.0.0-alpha14/usr/local/lib
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR
X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR unset
cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
OPENSSL_INCLUDE_DIR = /rootfs/openssl-3.0.0-alpha14/usr/local/include
cargo:rustc-link-search=native=/rootfs/openssl-3.0.0-alpha14/usr/local/lib
cargo:include=/rootfs/openssl-3.0.0-alpha14/usr/local/include
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = None
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
CRATE_CC_NO_DEFAULTS = None
DEBUG = Some("true")
CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "/rootfs/openssl-3.0.0-alpha14/usr/local/include" "-Wall" "-Wextra" "-E" "build/expando.c"
exit code: 0
cargo:rustc-cfg=osslconf="OPENSSL_NO_SSL3_METHOD"
cargo:conf=OPENSSL_NO_SSL3_METHOD
cargo:rustc-cfg=ossl101
cargo:rustc-cfg=ossl102
cargo:rustc-cfg=ossl102f
cargo:rustc-cfg=ossl102h
cargo:rustc-cfg=ossl110
cargo:rustc-cfg=ossl110f
cargo:rustc-cfg=ossl110g
cargo:rustc-cfg=ossl110h
cargo:rustc-cfg=ossl111
cargo:rustc-cfg=ossl111b
cargo:rustc-cfg=ossl111c
cargo:rustc-cfg=ossl300
cargo:version_number=30000000
cargo:version=300
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIBS
X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIBS unset
cargo:rerun-if-env-changed=OPENSSL_LIBS
OPENSSL_LIBS unset
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_STATIC
X86_64_UNKNOWN_LINUX_GNU_OPENSSL_STATIC unset
cargo:rerun-if-env-changed=OPENSSL_STATIC
OPENSSL_STATIC unset
cargo:rustc-link-lib=dylib=ssl
cargo:rustc-link-lib=dylib=crypto
```

**Comment by sfackler** [comment]
I think you'd need to get the other library to stop adding that to the search path then, unfortunately. It looks like it should be part of the linker's default search path anyway.

**Comment by Bergmann89** [comment]
If its part of the default search path, this would not fix the problem. Isn't there any rusty solution to solve this problem? I've already tried to pass the whole path of the library to the linker, bust cargo doesn't let me :/

**Comment by sfackler** [comment]
It would fix your problem since the linker looks in explicitly specified paths before looking in the default paths.
