### ISSUE TITLE
rust-openssl may be unsound due to calls to `getenv`

### ISSUE THREAD

**Issue by xerxes12354** [sfackler/rust-openssl#1465]
I was looking at the time crate wondering why the [time crate didn't give offsets](https://github.com/time-rs/time/issues/293), and I stumbled upon [this thread on Internals](https://internals.rust-lang.org/t/function-to-hold-lock-on-execution-environment-for-ffi/13702/22). This seems like a big problem so I went looking for FFI crates where this could be a problem.

https://www.openssl.org/docs/manmaster/man7/openssl-env.html, it looks like this wrapper has a data race when `set_env` is called in another thread.

**Comment by sfackler** [comment]
Is this fact actionable in any way?

**Comment by jhpratt** [comment]
@sfackler No. Rust provides no way to execute code with the environment locked, as it's not exposed by stdlib in any manner.
