### ISSUE TITLE
mk_certs.rs example uses 'private key' in set_pubkey

### ISSUE THREAD

**Issue by chathaway-codes** [sfackler/rust-openssl#1467]
In the [mk_certs.rs] example, there are a few places where set_pubkey is called as:

```
    let privkey = PKey::from_rsa(rsa)?;
    // stuff
    cert_builder.set_pubkey(&privkey)?;
```

It's not clear to me that this is the correct thing to do based on my very limited understanding of openssl; it looks like we are provided a private key as a 'public key' to OpenSSL.

The private key implements pkey::HasPublic through pkey::Private, and in [set_pubkey] it looks like we just pass a pointer to the private key in.

What am I missing here?

[mk_certs.rs]: https://github.com/sfackler/rust-openssl/blob/master/openssl/examples/mk_certs.rs#L38
[set_pubkey]: https://docs.rs/openssl/0.10.34/src/openssl/x509/mod.rs.html#302-307

**Comment by sfackler** [comment]
`privkey` is a value that contains both a public and private key.

**Comment by chathaway-codes** [comment]
Thanks for the clarification;  that makes sense. Proposed #1468 which just changes the name of the variables in the example to be a bit more clear.
