### ISSUE TITLE
Feature request: SSL_peek

### ISSUE THREAD

**Issue by NerLOR** [sfackler/rust-openssl#1472]
The `TcpStream` type already implements `.peek()`, OpenSSL also has a peek function: `SSL_peek`. It would be great for the `SslStream` type to have a `.peek()` method.

**Comment by sfackler** [comment]
Sure, PRs welcomed, or I can add it at some point.

**Comment by uniqueNullptr2** [comment]
I was just about to take a crack at this and noticed that ssl_peek is already implemented.
#1473 added the feature
