### ISSUE TITLE
Cannot find directory of openssl installation

### ISSUE THREAD

**Issue by andrewasd** [sfackler/rust-openssl#1482]
`If you're in a situation where you think the directory *should* be found
  automatically, please open a bug at https://github.com/sfackler/rust-openssl
  and include information about your system as well as this message.

  $HOST = x86_64-unknown-linux-gnu
  $TARGET = x86_64-unknown-linux-musl
  openssl-sys = 0.9.63`

im running on kubuntu 21.04

i installed openssl with the following commands:
sudo apt-get install pkg-config libssl-dev as 
reported in the following 
https://docs.rs/openssl/0.10.34/openssl/

**Comment by sfackler** [comment]
You are cross compiling, so pkg-config is not going to work. You either need to compile a copy of OpenSSL built for MUSL, or use the `vendored` Cargo feature to have the crate build a copy for you.

**Comment by andrewasd** [comment]
thanks i solved, if anyone needs i found instructions from here 
https://qiita.com/liubin/items/6c94f0b61f746c08b74c
