### ISSUE TITLE
Getting error "no protocols available" when client is using SslVersion::SSL3

### ISSUE THREAD

**Issue by panpur** [sfackler/rust-openssl#1483]
Hello,

I'm using rust-openssl 0.10.34.
I've compiled & installed SSLv3 enabled OpenSSL 1.1.1.
I've tested that it's working in CLI:

> openssl s_client -connect ecu.bonitana.com:443 -ssl3
CONNECTED(00000003)
depth=0 CN = ecu.bonitana.com

But getting error when testing with this code:
`               let mut ssl_config = SslConnector::builder(SslMethod::tls()).unwrap();
                 ssl_config.set_max_proto_version(Some(SslVersion::SSL3)).unwrap();
                 ssl_config.set_min_proto_version(Some(SslVersion::SSL3)).unwrap();
`

Here's the error: 

> Error { code: ErrorCode(1), cause: Some(Ssl(ErrorStack([Error { code: 337539263, library: "SSL routines", function: "tls_construct_client_hello", reason: "no protocols available", file: "ssl/statem/statem_clnt.c", line: 1113 }]))) }

Am I missing anything?

Thanks

**Comment by sfackler** [comment]
You may need to also call `ssl_config.clear_flags(SslOptions::NO_SSLV3)`? Although I would **seriously** question why anyone would be using SSLv3 in 2021.

**Comment by panpur** [comment]
I think you meant `clear_options`, anyway it's working now. 
Thanks!
