### ISSUE TITLE
Is there a way to encrypt/decrypt in place?

### ISSUE THREAD

**Issue by FH0** [sfackler/rust-openssl#1484]
https://docs.rs/openssl/0.10.34/openssl/symm/index.html

For example, I need encrypt 100 bytes data. Allocate 116 bytes, the last 16 bytes are used for `tag`.
```rust
let mut buf = vec![0u8; 116];
encrypt_aead_in_place(cipher, &key, iv, &aad, &mut buf);
```

**Comment by manojgop** [comment]
It'll be nice to have this in-place encrypt/decrypt feature.

**Comment by redpandamonium** [comment]
This would be a great addition. Especially if have a cipher with an 8 bit block length. There really is little reason to allocate temporary storage for that.
