### ISSUE TITLE
symm::decrypt Unexpected Panic!

### ISSUE THREAD

**Issue by WalterSmuts** [sfackler/rust-openssl#1485]
## [Rust playground example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=0b25be2be76f93af419d012dad4016b6)

When attempting to decrypt the following `Vec<u8>`:
```
data: [9, 18, 48, 170, 222, 62, 179, 48, 219, 170, 67, 88, 248, 141, 42, 108]
```
With key:
```
key: [89, 69, 76, 76, 79, 87, 32, 83, 85, 66, 77, 65, 82, 73, 78, 69]
```
I get a panic:
```
panicked at 'called `Result::unwrap()` on an `Err` value: ErrorStack([Error { code: 101077092, library: "digital envelope routines", function: "EVP_DecryptFinal_ex", reason: "bad decrypt", file: "../crypto/evp/evp_enc.c", line: 564 }])'
```
This is the first block of [cryptopals challenge 9](https://cryptopals.com/sets/2/challenges/10). I've found two examples of people who've solve the challenges in rust but seems to do so by abusing the library:
### [JoshMcguigan](https://github.com/JoshMcguigan/cryptopals/blob/master/src/utils/encrypt.rs#L34-L43)
Seems to call only the `update` method once and ignores the return value of `0`.
### [aopicier](https://github.com/aopicier/cryptopals-rust/blob/master/aes/src/lib.rs#L191-L205)
Pads the single block by an entirely new block, completely filled with padding.

I'm not sure if aopicier approach is correct according to the openssl library spec. Could be, but this seems really confusing if it is and feels like something the library should be handling. Perhaps it's an edge case that the rust wrapper can handle?

**Comment by sfackler** [comment]
The decrypt function assumes that the ciphertext uses PKCS#7 padding, but the one cryptopals provides is not. We should update the documentation for the function to state that.

**Comment by WalterSmuts** [comment]
I was aware about the PKCS#7 padding requirement because [the previous challenge](https://cryptopals.com/sets/2/challenges/9) was to implement it. I wasn't aware that the edge-case for a single block of data was to pad it with an entire block of padding, but looking at [the document defining the spec](https://datatracker.ietf.org/doc/html/rfc2315#section-10.3), that's exactly the case:
```
        2.   Some content-encryption algorithms assume the
             input length is a multiple of k octets, where k > 1, and
             let the application define a method for handling inputs
             whose lengths are not a multiple of k octets. For such
             algorithms, the method shall be to pad the input at the
             trailing end with k - (l mod k) octets all having value k -
             (l mod k), where l is the length of the input. In other
             words, the input is padded at the trailing end with one of
             the following strings:

                      01 -- if l mod k = k-1
                     02 02 -- if l mod k = k-2
                                 .
                                 .
                                 .
                   k k ... k k -- if l mod k = 0                        <----------- This line

             The padding can be removed unambiguously since all input is
             padded and no padding string is a suffix of another. This
             padding method is well-defined if and only if k < 256;
             methods for larger k are an open issue for further study.
```

I guess this is exactly what the challenge was trying to teach. You can't just cut up ciphertext and expect it to be valid, even in the case of ecb decrypting.

### Side note
[The go aes library](https://golang.org/pkg/crypto/aes/) seems to handle the edge case gracefully. [Here's it being used](https://github.com/ellemouton/cryptopals/blob/master/set2/aes_cbc.go#L15) to solve the same challenge without the need for padding the ciphertext retro-actively.

**Comment by sfackler** [comment]
Sure, but this library wraps OpenSSL, not the go AES library.
