### ISSUE TITLE
Can't fetch secp256k1 when use this library on Mac OS

### ISSUE THREAD

**Issue by fCorleone** [sfackler/rust-openssl#1486]
I try to use this library to make a TLS connect with a server. The server, however, need secp256k1 to make the handshake. When I try my code on Linux, it worked. While on Mac OS, the connection failed. The reason is that the client did not support secp256k1!!

**Comment by sfackler** [comment]
It sounds like your OpenSSL installation on Mac OS doesn't support secp256k1.

**Comment by fCorleone** [comment]
Is there any way to fix this? I need to update my openssl? Or maybe I just need to install secp256k1?

**Comment by sfackler** [comment]
You would need to update your openssl.

**Comment by fCorleone** [comment]
Thank you for your suggestion! I have updated my openssl and for now its version is 3.0.0. I use the following command:
`openssl ecparam -list_curves` and find that openssl has supported secp256k1 for now. However, the packet I sent with rust-openssl still didn't support secp256k1.

**Comment by sfackler** [comment]
The released version of rust-openssl doesn't support 3.0.0 yet, so it seems like you are linking against some other OpenSSL installation.

**Comment by fCorleone** [comment]
Where can I find the code of rust-openssl that link the Openssl in my system? How can I check which openssl I'm linking against?

**Comment by sfackler** [comment]
You can run `otool -L <path to binary>` to see which libraries it is linked to.

**Comment by fCorleone** [comment]
Thank you for your help. I use otool to see the linked library, and the result is :
```
/usr/local/lib/libssl.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
	/usr/local/lib/libcrypto.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.250.1)
	/usr/lib/libresolv.9.dylib (compatibility version 1.0.0, current version 1.0.0)
```
I built the openssl from the source code and the binary tool: `openssl `supports `secp256k1`. But the dylib still does not support the algorithm.

**Comment by sfackler** [comment]
Did you install your build of OpenSSL to /usr/local/lib?

**Comment by fCorleone** [comment]
Yes, I used `make install` and all the dynamic libraries are installed into /usr/local/lib.

**Comment by sfackler** [comment]
The libraries it is linked against are from an OpenSSL 1.1.0 or 1.1.1 install, not a 3.0.0 install. If you have a 3.0.0 copy installed on top of it, then things may be getting confused. I am not sure how you would disentangle yourself from that situation.
