### ISSUE TITLE
SslStream doesn't implement Clone (anymore)

### ISSUE THREAD

**Issue by TobTobXX** [sfackler/rust-openssl#1489]
This issue was already raised and fixed in #6 back in 2014, but since then the interface of `SslStream` has regressed again.

Since version 0.8.0, `SslStream` doesn't implement `Clone` anymore. In version 0.7.14, it still had `impl<S: Clone + Read + Write> Clone for SslStream<S>`.

**Comment by sfackler** [comment]
The clone implementation added in 2014 was fundamentally broken. OpenSSL does not support that operation.

**Comment by TobTobXX** [comment]
Hmm... But then there's no way to construct a `BufReader` from an `SslStream`, while still keeping a reference to write to it?

**Comment by sfackler** [comment]
You can write through the BufReader.

**Comment by TobTobXX** [comment]
Indeed :facepalm:, thank you for pointing that out.

For the future reader, this works:
```rust
let reader = BufReader::new(stream);
let mut line = String::new();
reader.read_line(&mut line)?;
writeln!(reader.get_mut(), "Hello")?;
reader.read_line(&mut line)?;
```
