### ISSUE TITLE
openssl-sys 0.9.64 broke semver by removing `PEM_read_bio_X509_CRL`

### ISSUE THREAD

**Issue by Skepfyr** [sfackler/rust-openssl#1490]
It's all in the title really, my build has broken since `openssl-sys 0.9.64` was released because `PEM_read_bio_X509_CRL` has been removed. I attempted to follow the git history of how it got removed but got thoroughly confused.

**Comment by sfackler** [comment]
Sorry about that! I think this accidentally got deleted in the PR adding support for OpenSSL 3.0.0. I will add it back and cut a new release.
