### ISSUE TITLE
  error occurred: Failed to find tool. Is `x86_64-linux-android-clang` installed?

### ISSUE THREAD

**Issue by wojiaoyanxin** [sfackler/rust-openssl#1500]
Caused by:
  process didn't exit successfully: `/Users/qitmac000948/qunar_lib/qp_sdk/cargo/target/release/build/bspatch-a45937197450934e/build-script-build` (exit code: 1)
  --- stdout
  TARGET = Some("x86_64-linux-android")
  OPT_LEVEL = Some("z")
  HOST = Some("x86_64-apple-darwin")
  CC_x86_64-linux-android = None
  CC_x86_64_linux_android = None
  TARGET_CC = None
  CC = None
  CFLAGS_x86_64-linux-android = None
  CFLAGS_x86_64_linux_android = None
  TARGET_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  running: "x86_64-linux-android-clang" "-Oz" "-DANDROID" "-ffunction-sections" "-fdata-sections" "-fPIC" "-static" "-Wall" "-Wextra" "-o" "/Users/qitmac000948/qunar_lib/qp_sdk/cargo/target/x86_64-linux-android/release/build/bspatch-5109bb3d6d59aa59/out/src/blocksort.o" "-c" "src/blocksort.c"

  --- stderr

  error occurred: Failed to find tool. Is `x86_64-linux-android-clang` installed?

**Comment by sfackler** [comment]
I cannot answer that question for you. Do you have x86_64-linux-android-clang installed?

**Comment by wojiaoyanxin** [comment]
> 我不能为你回答这个问题。你安装了 x86_64-linux-android-clang 吗？

yes,i install,but cannot find it
