### ISSUE TITLE
Something wrong with ecda signature verification

### ISSUE THREAD

**Issue by nikarh** [sfackler/rust-openssl#1502]
Hi,
I'm trying to implement ECDSA signature generation and verification according to the [examples](https://github.com/sfackler/rust-openssl/blob/master/openssl/src/ecdsa.rs#L189) in code and found that verification always returns true, if we verify using the public key of the key pair but different payload with the same prefix.

Am I doing something wrong?

```rust

mod test {
    #[test]
    fn sign_and_verify() {
        let group = EcGroup::from_curve_name(Nid::SECT571K1).unwrap();
        let private_key = EcKey::generate(&group).unwrap();
        let public_key = get_public_key(&group, &private_key).unwrap();

        let data1 = r#"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"#;
        let signature = EcdsaSig::sign(data1.as_bytes(), &private_key).unwrap();

        let data2 = r#"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBB"#;

        let valid = signature.verify(data2.as_bytes(), &public_key).unwrap();

        assert_ne!(data1, data2);
        // This assertion should pass, but it fails.
        assert!(!valid);
    }
}
```

**Comment by sfackler** [comment]
That API is the low level interface that expects to sign the hash of some data, not the raw data itself. Presumably, its internals truncate the input at some length. If you e.g. use `AAAAAAA` and `AAABBBB` instead you will see the correct result. OpenSSL recommends the use of the higher level EVP APIs in almost all cases, which are exposed via the `sign` module: https://docs.rs/openssl/0.10.35/openssl/sign/index.html
