### ISSUE TITLE
error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by crusty-dave** [sfackler/rust-openssl#1505]
When I try to put my Ubuntu 20.04 executable in a Docker container, I get the following errors when I try to run it:

/app/my-app: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
/app/my-app: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
/app/my-app: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
/app/my-app: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

I have tried building with and without "vendored" to try to get a static linkage, but to no avail.

Note that I am *not* building the app in Docker, I am just trying to use the binaries in Docker from a build on Ubuntu 20.04 under WSL 2.

openssl = { version="0.10", features = ["vendored"]}

Why is it linking to such an old version of the library.

Prior to building I have done the following:

```
apt update
apt install clang
apt install openssl (probably redundant with libssl-dev below)
apt install libssl-dev
apt install pkg-config
```

I have even tried a symbolic link in my Dockerfile, but still no joy:

```
# syntax=docker/dockerfile:1
FROM ubuntu:20.04
RUN apt update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends pkg-config \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends openssl \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends libssl-dev \
    && true

COPY \
    ./my-app \
    ./my-app.d \
     /app/

RUN ls -l /usr/lib/x86_64-linux-gnu/*ssl*
RUN ln -s /usr/lib/x86_64-linux-gnu/libssl.so.1.1 /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0
RUN env
RUN ls -l /usr/lib/x86_64-linux-gnu/*ssl*

WORKDIR /app
CMD /app/my-app
```

 ---> Running in 0ce30a03126e
-rw-r--r-- 1 root root 1016494 Apr 28 00:37 /usr/lib/x86_64-linux-gnu/libssl.a
lrwxrwxrwx 1 root root      13 Apr 28 00:37 /usr/lib/x86_64-linux-gnu/libssl.so -> libssl.so.1.1
lrwxrwxrwx 1 root root      39 Jul 13 19:46 /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0 -> /usr/lib/x86_64-linux-gnu/libssl.so.1.1
-rw-r--r-- 1 root root  598104 Apr 28 00:37 /usr/lib/x86_64-linux-gnu/libssl.so.1.1

I would actually prefer to use dynamic linking, but in either case it seems to be linking with libssl.so.1.0.0.

**Comment by sfackler** [comment]
It's linking against libssl.1.0.0 because that's what's present on the system it's built on.

What do you mean specifically when you say that building with the vendored feature doesn't work?

**Comment by crusty-dave** [comment]
Sorry, it built, but I had the same error.

Is there a "correct" way to purge old installed versions of libssl?

Thanks,
-Dave

**Comment by sfackler** [comment]
So if you run `cargo clean`, enable the `vendored` Cargo feature, and then rebuild, your application is still dynamically linked to OpenSSL?

I'm not sure that there is a great way to clean up libraries that were manually installed in global system directories on Linux.

**Comment by crusty-dave** [comment]
I think I may have been getting bitten by Docker holding onto old versions.

I had a new build server ready to go, so I set it up and I still saw the same issue (libssl.so.1.0.0: cannot open shared object file).  So I deleted my container and image and recreated it with the image from the new build server, then the problem went away.

I just tried vendored again, checking with ldd I don't see a dynamic linkage, it is likely that something stale in Docker was the underlying problem.

ldd my-app
        linux-vdso.so.1 (0x00007fffd4f08000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f6a934e0000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f6a934bd000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f6a934a0000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6a932a0000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f6a9435f000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f6a93151000)

Thanks,
-Dave
