### ISSUE TITLE
    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "TLS_method" referenced by "/data/app/com.example.qp-ed-9Tzd1SSxFhpR5wmYWpA==/lib/arm64/libqp_sdk.so"...

### ISSUE THREAD

**Issue by wojiaoyanxin** [sfackler/rust-openssl#1506]
if use

reqwest::blocking::get("")

will throw

java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "TLS_method" referenced by "/data/app/com.example.qp-sWD2WjYCCGMinMCH9r_ZRg==/lib/arm/libqp_sdk.so"...

on android

**Comment by sfackler** [comment]
You need to ensure the appropriate version of OpenSSL is available to your application.

**Comment by wojiaoyanxin** [comment]
> 您需要确保您的应用程序可以使用适当版本的 OpenSSL。



> You need to ensure the appropriate version of OpenSSL is available to your application.

**Comment by wojiaoyanxin** [comment]
> You need to ensure the appropriate version of OpenSSL is available to your application.

Does Android client need to install OpenSSL dynamic library???

**Comment by sfackler** [comment]
I don't really know how Android applications are structured.
