### ISSUE TITLE
openssl-sys-0.9.65/src/lib.rs:170: undefined reference to `SSL_library_init'

### ISSUE THREAD

**Issue by marcbrevoort-cyberhive** [sfackler/rust-openssl#1509]
More recent versions of OpenSSL (1.1.0 and up) appear to have SSL_library_init defined as a macro in ssl.h, rather than as a function in the linked object. This causes linking to fail on more recent versions of openssl.

The openssl rust bindings seem to always use SSL_library_init() which doesn't work if that function is defined as a macro in a C header file rather than in the library.

https://wiki.openssl.org/index.php/Library_Initialization suggests doing something like
```
#if OPENSSL_VERSION_NUMBER < 0x10100000L
SSL_library_init();
#else
OPENSSL_init_ssl(0, NULL);
#endif
```
The rust wrapper https://github.com/sfackler/rust-openssl/blob/master/openssl-sys/src/lib.rs has two init mechanisms,
but both use SSL_library_init() which forces the linker to look for this symbol when it may not exist in the library.

**Comment by sfackler** [comment]
It sounds like you are compiling against headers from OpenSSL 1.0.x and then linking against OpenSSL 1.1.x.

**Comment by sfackler** [comment]
The 1.1.x logic in openssl-sys uses OPENSSL_init_ssl, not SSL_library_init: https://github.com/sfackler/rust-openssl/blob/master/openssl-sys/src/lib.rs#L114
