### ISSUE TITLE
Bug with AES-CBC

### ISSUE THREAD

**Issue by tomleavy** [sfackler/rust-openssl#1518]
If you pass a 32 byte input into the `encrypt` function you get a 48 byte output. My understanding is that when using CBC the output length should be rounded to a multiple of the 16 byte block size. Since the 32 byte input is a multiple of 16, the final output should be 32 bytes.

**Comment by sfackler** [comment]
Can you provide a self contained example of this behavior?

**Comment by tomleavy** [comment]
It seems I am incorrect and that PKCS#5 padding in openssl will add a full block of 0 padding even if the input perfectly fills the block size. Closing
