### ISSUE TITLE
ECDSA r and s parameters don't seem to have the proper length all the time

### ISSUE THREAD

**Issue by erikh** [sfackler/rust-openssl#1520]
so with this example, where key is an `EcKey<Private>`, I am able to generate a r or s parameter which has a length of 31 bytes, not 32. I am not a crypto person so I apologize if I have done this incorrectly, but I made a best attempt to do it properly. I get the feeling this is an off-by-one in the length calculation or generation of the vector via `to_vec()`.

This is tripping up a later validation where I check if `v` len is 64. Running 10k rounds of this code shows it in about 100 rounds or less.

Again, I'm really sorry if I made a mistake here. Some assistance would be useful, happy to make patches or diagnose more stuff.

```rust
                let digest = sha256(to_sign.as_bytes());
                let signature = EcdsaSig::sign(&digest, &key)?;

                let r = signature.r().to_vec();
                let s = signature.s().to_vec();

                eprintln!("digest: {}, r: {}, s: {}", digest.len(), r.len(), s.len());

                let mut v = Vec::with_capacity(r.len() + s.len());
                v.extend_from_slice(&r);
                v.extend_from_slice(&s);

                eprintln!("v: {}", v.len());
```

**Comment by erikh** [comment]
```rust
                if decoded.len() != 64 {
                    eprintln!("decoded len: {}", decoded.len());
                    return Err(JWSValidationError::SignatureDecode);
                }

                let r = BigNum::from_slice(&decoded[0..32])?; ‣r: BigNum
                let s = BigNum::from_slice(&decoded[32..64])?; ‣s: BigNum

                let signature = ‣signature: EcdsaSig
                    EcdsaSig::from_private_components(r, s).expect("could not program components");

                Ok(signature.verify(&digest, &key)?)
```

my verification code for posterity's sake. I also tried padding with nulls and got nowhere.

**Comment by erikh** [comment]
curve is Nid::SECP256K1, probably an extremely important detail for the lengths. :)

**Comment by sfackler** [comment]
This just directly exposes the OpenSSL APIs and I am not super familiar with ECDSA, but it doesn't seem totally surprising to me that it would not always produce numbers that have a bit set in byte 32. They may just be smaller than that.

**Comment by erikh** [comment]
yeah i guess I misunderstood the encoding here anyway. gonna close this, sorry for the noise.

**Comment by erikh** [comment]
ok, so fwiw padding from the front solved my problem. just for any other noobs out there looking for answers to this problem.
