### ISSUE TITLE
Allow openssl-sys to not link to dynamic libraries

### ISSUE THREAD

**Issue by tomleavy** [sfackler/rust-openssl#1526]
I am building a node module using Neon, and Node.js https://neon-bindings.com/ 

Since Node exports it's own OpenSSL symbols based on what it was linked against, the ones linked in from openssl-sys are conflicting. You can see with a call to `ldd index.node` generated by cargo build that libssl and libcrypto are both listed.

Is there already a work around I can do to purposefully not link in the libssl and libcrypto dynamic libraries when building this node module based on the openssl / openssl-sys crates?

**Comment by sfackler** [comment]
The crate minimally needs access to the headers associated with the OpenSSL it's linking to. You can use environment variables to override the library names the crate will link to: https://docs.rs/openssl/0.10.36/openssl/#manual

**Comment by tomleavy** [comment]
Thanks that helped me figure it out

In case anyone else runs into this the following  `build.rs` will allow you to compile a node native module that uses this crate and doesn't conflict with internal Node symbols.

```rust
use std::env;

fn main() {
    // Set env variable to not link openssl so that the node version is used
    env::set_var("OPENSSL_LIBS", "");

    // Tell cargo to allow undefined dynamic links for openssl
    println!("cargo:rustc-cdylib-link-arg=-undefined");
    println!("cargo:rustc-cdylib-link-arg=dynamic_lookup")
}
```
