### ISSUE TITLE
Opposite of OPENSSL_NO_VENDOR?

### ISSUE THREAD

**Issue by leo60228** [sfackler/rust-openssl#1527]
(sorry if there's already an issue, I couldn't find one from searching)

I do not want building via Cargo to rely on what libraries I have installed system-wide. I would like an option like `OPENSSL_VENDOR=1` I can set globally.

**Comment by sfackler** [comment]
Enable the `vendored` Cargo feature.

**Comment by leo60228** [comment]
I'm looking for something I can set system-wide. Since the crate already finds openssl via global state (pkg-config), I don't see an issue with allowing global state to enable vendoring openssl.

**Comment by sfackler** [comment]
That isn't really possible, since openssl-sys's dependency on openssl-src is optional and only pulled in when the vendored feature is enabled.
