### ISSUE TITLE
Memory-leaks when using set_tmp_rsa_callback or set_tmp_ecdh

### ISSUE THREAD

**Issue by maxammann** [sfackler/rust-openssl#1529]
Hello,

I'm using OpenSSL 1.0.1 and 1.0.2 for fuzzing purposes. Because I want to test ephemeral key exchanges I'm using  
`set_tmp_rsa_callback` or `set_tmp_ecdh`: 

## Example

```rust
ctx_builder.set_tmp_ecdh_callback(|_, _, _| {
    openssl::ec::EcKey::from_curve_name(openssl::nid::Nid::SECP384R1)
});

ctx_builder.set_tmp_rsa_callback(|_, is_export, keylength| openssl::rsa::Rsa::generate(keylength));
```
## Leaks

This causes the following memory leaks (truncated for better readability):

```
Indirect leak of 16 byte(s) in 2 object(s) allocated from:
    #0 0x7fac17891279 in __interceptor_malloc /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x55e820acf1f1 in CRYPTO_malloc /home/max/projects/fuzzing/tlspuffin/target/x86_64-unknown-linux-gnu/debug/build/openssl-sys-c14835427abcb1ba/out/openssl-build/build/src/crypto/mem.c:346
...
    #8 0x55e820b1c887 in EC_KEY_new_by_curve_name /home/max/projects/fuzzing/tlspuffin/target/x86_64-unknown-linux-gnu/debug/build/openssl-sys-c14835427abcb1ba/out/openssl-build/build/src/crypto/ec/ec_key.c:98
    #9 0x55e820a5a6a0 in openssl::ec::EcKey$LT$openssl..pkey..Params$GT$::from_curve_name::h36d9171448647ffb deps/rust-openssl/openssl/src/ec.rs:777
..
    #13 0x55e8206aca3b in openssl::ssl::SslStream$LT$S$GT$::do_handshake::h3562fd9adb9b6979 /home/max/projects/fuzzing/tlspuffin/deps/rust-openssl/openssl/src/ssl/mod.rs:3664
```

```
Indirect leak of 8 byte(s) in 1 object(s) allocated from:
    #0 0x7fac17891279 in __interceptor_malloc /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x55e820acf1f1 in CRYPTO_malloc /home/max/projects/fuzzing/tlspuffin/target/x86_64-unknown-linux-gnu/debug/build/openssl-sys-c14835427abcb1ba/out/openssl-build/build/src/crypto/mem.c:346
...
    #5 0x55e820b260e2 in rsa_builtin_keygen /home/max/projects/fuzzing/tlspuffin/target/x86_64-unknown-linux-gnu/debug/build/openssl-sys-c14835427abcb1ba/out/openssl-build/build/src/crypto/rsa/rsa_gen.c:156
    #6 0x55e820b260e2 in RSA_generate_key_ex /home/max/projects/fuzzing/tlspuffin/target/x86_64-unknown-linux-gnu/debug/build/openssl-sys-c14835427abcb1ba/out/openssl-build/build/src/crypto/rsa/rsa_gen.c:101
    #7 0x55e820a5bbc1 in openssl::rsa::Rsa$LT$openssl..pkey..Private$GT$::generate_with_e::h2eddb9be42edb89c deps/rust-openssl/openssl/src/rsa.rs:598
...
    #11 0x55e8206aca3b in openssl::ssl::SslStream$LT$S$GT$::do_handshake::h3562fd9adb9b6979 /home/max/projects/fuzzing/tlspuffin/deps/rust-openssl/openssl/src/ssl/mod.rs:3664
```

## Workaround

```
ctx_builder.set_tmp_rsa(openssl::rsa::Rsa::generate(512).as_ref().unwrap())?;
ctx_builder.set_tmp_ecdh(openssl::ec::EcKey::from_curve_name(openssl::nid::Nid::SECP384R1).as_ref().unwrap())?;
```
(I implemented set_tmp_rsa on my own)

I'm not sure how to use the API correctly without memory leaks. I think this is not possible though.
I also do not know what a EcKeyRef exactly is so I'm a little bit lost with debugging. Reference counting by OpenSSL is also going on in the background I suppose.

**Comment by sfackler** [comment]
Looking at the OpenSSL source, it seems like the callback signature should actually be

```rust
F: for<'a> Fn(&'a mut SslRef, bool, u32) -> Result<&'a EcKeyRef<Params>, ErrorStack> + 'static + Sync + Send,
```

However, the callback functions have been deprecated for a very long time and don't even exist in any versions of OpenSSL newer than 1.0.2, so I think it might be better to just deprecate the Rust versions as well.

**Comment by maxammann** [comment]
I'd agree if I would not use this crate for fuzzing wildly used versions of openssl :sweat_smile: 

OpenSSL 1.0 is still used a lot and these callbacks are the only way to implement ephemeral key exchanges for multiple key lenghts.

I actually tried to use EcKeyRef but failed :/

**Comment by sfackler** [comment]
1.0.1 is EOLed even from extended support distros like CentOS iirc. The next version of this crate is going to drop support for it as well.

`SSL_CTX_set1_curves` was added in 1.0.2 and is the new way to do this according to the OpenSSL people. I can expose that tonight.

**Comment by maxammann** [comment]
Oke, yeah maybe we should just remove the feature right away. I think you are right that the goal of this library should be to support only "supported TLS libs".

For me there is no need for `SSL_CTX_set1_curves`. You can also choose exactly one curve via set_tmp_ecdh.
For RSA this is slightly more complicated because you want to have multiple key lengths available. In fact RSA ephemeral is probably very very bad to use :D

**Comment by sfackler** [comment]
Ephemeral RSA key exchange can only be used with export ciphers, so I would hope that no one is using it!

**Comment by maxammann** [comment]
thanks!
