### ISSUE TITLE
Can not cross compile from Ubuntu 21.04 to windows

### ISSUE THREAD

**Issue by GeneL** [sfackler/rust-openssl#1533]
cargo build  --target=x86_64-pc-windows-gnu  
   Compiling unicode-normalization v0.1.19
   Compiling openssl-sys v0.9.67
   Compiling lock_api v0.1.5
   Compiling getrandom v0.1.16
   Compiling winapi v0.3.9
   Compiling crossbeam-utils v0.7.2
   Compiling miniz_oxide v0.4.4
   Compiling num-traits v0.2.14
   Compiling memoffset v0.5.6
   Compiling indexmap v1.7.0
   Compiling httparse v1.5.1
   Compiling typemap v0.3.3
   Compiling num_cpus v1.13.0
error: failed to run custom build command for `openssl-sys v0.9.67`

Caused by:
  process didn't exit successfully: `/home/???/Rust/opcua-master/target/debug/build/openssl-sys-d39b26ec25ad50f1/build-script-main` (exit status: 101)
  --- stdout
  cargo:rustc-cfg=const_fn
  cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_GNU_OPENSSL_LIB_DIR
  X86_64_PC_WINDOWS_GNU_OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
  OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_GNU_OPENSSL_INCLUDE_DIR
  X86_64_PC_WINDOWS_GNU_OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
  OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_GNU_OPENSSL_DIR
  X86_64_PC_WINDOWS_GNU_OPENSSL_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_DIR
  OPENSSL_DIR unset

  --- stderr
  thread 'main' panicked at '

  Could not find directory of OpenSSL installation, and this `-sys` crate cannot
  proceed without this knowledge. If OpenSSL is installed and this crate had
  trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
  compilation process.

  Make sure you also have the development packages of openssl installed.
  For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.

  If you're in a situation where you think the directory *should* be found
  automatically, please open a bug at https://github.com/sfackler/rust-openssl
  and include information about your system as well as this message.

  $HOST = x86_64-unknown-linux-gnu
  $TARGET = x86_64-pc-windows-gnu
  openssl-sys = 0.9.67

  ', /home/???/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.67/build/find_normal.rs:174:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by sfackler** [comment]
You need a copy of OpenSSL built for your target.
