### ISSUE TITLE
OpenSSL not found on Windows

### ISSUE THREAD

**Issue by kletterstein** [sfackler/rust-openssl#1542]
`cargo build` fails on my Windows 10 as openssl could not be found. However, it is installed in `c:\Program Files\OpenSSL-Win64`. The Distributor is http://slproweb.com/products/Win32OpenSSL.html. If only installations installed using vcpkg are supported, could you mention this in the docs?

Thanks and thanks for great crate!
Bernd

My system info is:
```
$HOST = x86_64-pc-windows-msvc
$TARGET = x86_64-pc-windows-msvc
openssl-sys = 0.9.67
```

The command output is:
```
λ cargo build
   Compiling openssl-sys v0.9.67
   Compiling atty v0.2.14
   Compiling clap v2.33.3
error: failed to run custom build command for `openssl-sys v0.9.67`

Caused by:
  process didn't exit successfully: `c:\Users\krietens\Projects\rust-openssl\target\debug\build\openssl-sys-9a902e1719db51b3\build-script-main` (exit code: 101)
  --- stdout
  cargo:rustc-cfg=const_fn
  cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_MSVC_OPENSSL_LIB_DIR
  X86_64_PC_WINDOWS_MSVC_OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
  OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_MSVC_OPENSSL_INCLUDE_DIR
  X86_64_PC_WINDOWS_MSVC_OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
  OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_MSVC_OPENSSL_DIR
  X86_64_PC_WINDOWS_MSVC_OPENSSL_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_DIR
  OPENSSL_DIR unset
  note: vcpkg did not find openssl: Could not look up details of packages in vcpkg tree could not read status file updates dir: Das System kann den angegebenen Pfad nicht finden. (os error 3)

  --- stderr
  thread 'main' panicked at '

  Could not find directory of OpenSSL installation, and this `-sys` crate cannot
  proceed without this knowledge. If OpenSSL is installed and this crate had
  trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
  compilation process.

  Make sure you also have the development packages of openssl installed.
  For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.

  If you're in a situation where you think the directory *should* be found
  automatically, please open a bug at https://github.com/sfackler/rust-openssl
  and include information about your system as well as this message.

  $HOST = x86_64-pc-windows-msvc
  $TARGET = x86_64-pc-windows-msvc
  openssl-sys = 0.9.67


  It looks like you're compiling for MSVC but we couldn't detect an OpenSSL
  installation. If there isn't one installed then you can try the rust-openssl
  README for more information about how to download precompiled binaries of
  OpenSSL:

  https://github.com/sfackler/rust-openssl#windows

  ', C:\Users\krietens\.cargo\registry\src\github.com-1ecc6299db9ec823\openssl-sys-0.9.67\build\find_normal.rs:174:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
```

Note: The URL in the output (https://github.com/sfackler/rust-openssl#windows) is not valid any more!

**Comment by sfackler** [comment]
https://docs.rs/openssl/0.10.36/openssl/#manual

**Comment by jonhoo** [comment]
For anyone who stumbles into this issue because their GitHub Actions CI [starts failing](https://github.com/jonhoo/rust-imap/actions/runs/3976941645/jobs/6817735435) on Windows when depending on `openssl`/`openssl-sys` with an error like
```
note: vcpkg did not find openssl: Could not find Vcpkg tree: No vcpkg installation found. Set the VCPKG_ROOT environment variable or run 'vcpkg integrate install'
```
I [fixed this](https://github.com/jonhoo/rust-imap/pull/253/commits/846a68121cb8bb7e9059ebcb5281ad06ff5e9435) by taking a page out of [this package's CI config](https://github.com/sfackler/rust-openssl/blob/master/.github/workflows/ci.yml#L93-L94) along with a conditional [on the `runner` context](https://docs.github.com/en/actions/learn-github-actions/contexts#runner-context) to give the following stanza at the top of my `steps`:
```yaml
    steps:
      - run: echo "VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT" | Out-File -FilePath $env:GITHUB_ENV -Append
        if: runner.os == 'Windows'
      - run: vcpkg install openssl:x64-windows-static-md
        if: runner.os == 'Windows'
```

**Comment by leonheess** [comment]
> This has to do with the `openssl-sys` dependency. Looking at their [docs](https://docs.rs/crate/openssl-sys/0.9.19) was a little more helpful than `rust-openssl` docs. I had a lot of trouble with getting `vcpkg` working and cooperating.
> 
> What worked for me was using [chocolatey](https://chocolatey.org/) to install [openssl](https://community.chocolatey.org/packages/openssl) which installs to `C:\Program Files\OpenSSL-Win64` by default. Following the `openssl-sys` docs knowing this I set some environment variables to match `OPENSSL_DIR=C:\Program Files\OpenSSL-Win64` and created a folder called `ca` to hold the ca certificate from Mozilla that `rust-openssl` uses from [here](https://curl.se/docs/caextract.html) and set the environment variable to match `SSL_CERT_FILE=C:\Program Files\OpenSSL-Win64\ca\cacert.pem`.
> 
> After this I just had to do `cargo build` and it worked. VS Code also started highlighting properly again as this also broke that extension for me. Hope this helps.

I am getting:

    OpenSSL libdir at `["C:\\Program Files\\OpenSSL-Win64\\lib"]` does not contain the required files to either statically or dynamically link OpenSSL

**Comment by leonheess** [comment]
I fixed it with:

    choco install openssl
    $env:OPENSSL_DIR = "C:\Program Files\OpenSSL-Win64";
    $env:OPENSSL_STATIC = "true";

**Comment by Jackjackca** [comment]
An easy way is using `vcpkg` (a Microsoft package installer for Windows) to install openssl and set 3 environment variables. This allows Cargo to build crate that depends on openssl. 
After you have vcpkg installed, run: `vcpkg install openssl`
Then set environment variables:
`X86_64_PC_WINDOWS_MSVC_OPENSSL_LIB_DIR =  <Your_vcpkg_installation_path>\vcpkg\packages\openssl_x64-windows\lib`
`X86_64_PC_WINDOWS_MSVC_OPENSSL_INCLUDE_DIR = <Your_vcpkg_installation_path>\vcpkg\packages\openssl_x64-windows\include`
`X86_64_PC_WINDOWS_MSVC_OPENSSL_DIR = <Your_vcpkg_installation_path>\vcpkg\packages\openssl_x64-windows`
Remember to restart ternimal before cargo build.

**Comment by itsthedevman** [comment]
> I fixed it with:
> 
> ```
> choco install openssl
> $env:OPENSSL_DIR = "C:\Program Files\OpenSSL-Win64";
> $env:OPENSSL_STATIC = "true";
> ```

If anyone is still experiencing issues after trying this, also try adding:
```
$env:OPENSSL_LIB_DIR = 'C:\Program Files\OpenSSL-Win64\lib\VC\x64\MD';
```
Source: https://github.com/sfackler/rust-openssl/issues/766#issuecomment-2050533376

**Comment by BadMachine** [comment]
Still fails
