### ISSUE TITLE
Bumping openssl to 3.x is breaking builds and should maybe be a minor version bump

### ISSUE THREAD

**Issue by toidiu** [sfackler/rust-openssl#1549]
This commit bumps the vendor-ed version of openssl: https://github.com/sfackler/rust-openssl/commit/e5999ccf4a203fcbe41723923334ba18eaf1e159

However the version of [openssl-sys](https://crates.io/crates/openssl-sys) was only bumped from `0.9.68` to `0.9.69` (a patch version update). I am unfamiliar with the project but maybe this should be a minor version bump rather than a patch update?

**Comment by sfackler** [comment]
> The OpenSSL version will generally track the newest OpenSSL release, and changes to the version are not considered breaking changes.
 
https://docs.rs/openssl/0.10.38/openssl/#vendored

**Comment by toidiu** [comment]
Ack, thanks for the response!

**Comment by danni-m** [comment]
@sfackler The upgrade probably caused an issue with `kube-rs` on macos:
https://github.com/kube-rs/kube-rs/issues/691

**Comment by Stargateur** [comment]
BTW, 0.x.y, x is major and y is minor, there is no patch for <1 version
