### ISSUE TITLE
Documentation for `Pkcs12::builder` is incorrect for OpenSSL 3

### ISSUE THREAD

**Issue by kazk** [sfackler/rust-openssl#1552]
> **PKCS#12 API updates**
>
> The default algorithms for pkcs12 creation with the PKCS12_create() function were changed to more modern PBKDF2 and AES based algorithms. The default MAC iteration count was changed to PKCS12_DEFAULT_ITER to make it equal with the password-based encryption iteration count. The default digest algorithm for the MAC computation was changed to SHA-256. The pkcs12 application now supports -legacy option that restores the previous default algorithms to support interoperability with legacy systems.
> https://www.openssl.org/docs/man3.0/man7/migration_guide.html#PKCS-12-API-updates

OpenSSL 3 changed the default encryption algorithms to `Nid::AES_256_CBC`. https://github.com/openssl/openssl/commit/762970bd686c4aa8ea7169e7f76d5a4ce665da93

https://github.com/sfackler/rust-openssl/blob/15f263eb7eb61bc241ddc8bc0e5d79b68cb37936/openssl/src/pkcs12.rs#L74-L79

A user reported a [problem on macOS](https://github.com/kube-rs/kube-rs/issues/691) after a recent patch bump, and apparently the Security Framework fails to import modern PKCS#12. https://openradar.appspot.com/FB8988319

**Comment by sfackler** [comment]
Fixed in db2b0d79. I'm also adding support to load providers (like the legacy provider that would support the old algorithms), but need to figure out what to do about https://github.com/openssl/openssl/issues/16970 first.
