### ISSUE TITLE
Build fails with error due to errant compiler flag -Brepro on MSVC x64 platform 

### ISSUE THREAD

**Issue by MironAtHome** [sfackler/rust-openssl#1565]
![image](https://user-images.githubusercontent.com/18360184/142392371-77795be3-42ac-4742-ae71-b5dc2023c0c7.png)

Anyone with knowledge how this call gets constructed during build?
I run search in the project and couldn't find it in the files, will have to retrace it.
Any assistance in the meantime greatly appreciated.

Microsoft C/C++ compiler version from Visual Studio 2017: 
![image](https://user-images.githubusercontent.com/18360184/142267253-95d3d402-ad1d-4c79-9078-3d490eed9138.png)

**Comment by MironAtHome** [comment]
Additional information.
Per GitHub issue
https://github.com/alexrp/zig-msbuild-sdk/issues/38
/brepro is used as an command line argument to linker to make generated code deterministic. However, per this blog entry: 
https://geoffchappell.com/studies/msvc/link/link/options/brepro.htm
this argument is not valid when generating object file, the case in this issue.
It's pretty difficult to retrace how the build is producing scripts and is invoking compiler. An assistance from feature owner would be very much apprecaited.

**Comment by sfackler** [comment]
I am not particularly familiar with how old versions of MSVC behave. However, systest is only used for testing, and shouldn't be needed to depend on the project.

**Comment by MironAtHome** [comment]
@sfackler  can you please advise what generates commands sent to cl.exe ( MSVC C/C++ compiler )?
I can fix it. That way I can keep tests.

**Comment by MironAtHome** [comment]
set CFG_DISABLE_CROSS_TESTS=1
prior
cargo build --target x86_64-pc-windows-msvc
unblocked.
Thanks for suggestion to disable test. Variable is provided in cargo repository
\crates\cargo-test-support\src\cross_compile.rs
line #25
block reads
```
    match env::var("CFG_DISABLE_CROSS_TESTS") {
        Ok(ref s) if *s == "1" => return true,
        _ => {}
    }
```

**Comment by MironAtHome** [comment]
@sfackler  still, please provide guidance how to get to that -Brepro to make it conditional.
So far couldn't find it anywhere.

**Comment by sfackler** [comment]
https://github.com/JohnTitor/ctest2

**Comment by sfackler** [comment]
The test runs successfully on MSVC in CI: https://github.com/sfackler/rust-openssl/runs/4273919752?check_suite_focus=true
