### ISSUE TITLE
`IP address mismatch` - How to avoid verifying IP?

### ISSUE THREAD

**Issue by broccolihighkicks** [sfackler/rust-openssl#1572]
I want to replicate the Postgres CLI option `verify-ca` in my Rust code (to connect from Rust to a PG server).

Apparently this is enough to provide security ("trust any server that provides a cert that is signed by this CA")

https://cloud.google.com/sql/docs/postgres/connect-admin-ip#connect-ssl
> An SSL mode of verify-full is not required; verify-ca is enough because the CA is instance-specific.

*** 
I am using `builder.set_ca_file(file_path)`.

And get the error:
```
verify_result: X509VerifyResult { code: 64, error: "IP address mismatch" }
```

How can I disable just this IP check, but keep the other verify assertions?

Also, would this make it equal to the `verify-ca` [Postgres option](https://www.postgresql.org/docs/9.1/libpq-ssl.html)?

***

```rust
// This works, but is it the same as PG's `verify-ca` option?
let mut connector_openssl: MakeTlsConnector = MakeTlsConnectorOpenSSL::new(x);

connector_openssl.set_callback(|connect_config, domain| {
    connect_config.set_verify_hostname(false);
    Ok(())
});
```

**Comment by sfackler** [comment]
I am not familiar with Postgres's behavior but disabling hostname verification seems like the thing to do.
