### ISSUE TITLE
openssl-sys 0.9.71 causes slow startup

### ISSUE THREAD

**Issue by matklad** [sfackler/rust-openssl#1576]
Another openssl issue which I am logging here mostly to help the next person.

The symptom is that upgrade to openssl-sys 0.9.17 made startup of various things at nearcore much slower, especially if startup happens concurrently in tests. Where slower is 20 milliseconds->  1 second. 

The culprit is the `SSL_CTX_set_default_verify_pathsi` function, which was fast in openssl 1.1.1, but easily takes half a second in 3.0.0. Here's someone else facing the same issue: https://www.spinics.net/lists/openssl-users/msg14308.html.

It... doesn't seem like we can do anything about this? This is done per-context, so it's not something we can cache in a global or something.

**Comment by sfackler** [comment]
Can you share the context between tests?

**Comment by matklad** [comment]
In theory, yes, in practice, not really -- it's some telemetry code deep in the guts which isn't really setup for sharing things, and the underlying http lib we use seem to create a fresh context unconditionally (it's possible to override it later)

https://docs.rs/actix-http/2.2.1/src/actix_http/client/connector.rs.html#72

**Comment by sfackler** [comment]
I may end up just reverting the vendored OpenSSL to 1.1.1 until 3 becomes more robust.

**Comment by matklad** [comment]
`1.1.1` is still fully suporter, right?  As in, it will get patches for vulnerabilities, if any. 

If that's the case, then reverting to 1.1.1 by default and hiding 3.0.0 behind a feature flag or something seems reasonable

**Comment by sfackler** [comment]
Yep, 1.1.1 is the current LTS release and will be supported through September 2023.

**Comment by sfackler** [comment]
openssl-sys 0.9.72 downgrades the vendored OpenSSL back to 1.1.1.

**Comment by sehz** [comment]
Suprised that 0.9.71 was upgrade to OpenSSL 3.0.0.  I would expect that crate version to be bump up to at least: 0.10

**Comment by sfackler** [comment]
Due to the way that Cargo handles -sys crates, bumping openssl-sys to 0.10 would be somewhat catastrophic to the ecosystem.
