### ISSUE TITLE
Is there a way to set encrypted key with passphrase to ssl acceptor

### ISSUE THREAD

**Issue by powerory** [sfackler/rust-openssl#1585]
In this example code, not encrypted key file(key.pem) is used.
https://github.com/sfackler/rust-openssl/blob/b3dde76ea28ca5e54ce6341927c96679b9921153/openssl/src/ssl/mod.rs#L36

But when I tried to set private key which is encrypted by aes256 with passphrase, 
following prompt requests entering passphrase. (maybe from openssl)

Enter PEM pass phrase:

Is there a way to set encrypted key with passphrase while building ssl acceptor?

**Comment by sfackler** [comment]
Use https://docs.rs/openssl/latest/openssl/pkey/struct.PKey.html#method.private_key_from_pem_passphrase and https://docs.rs/openssl/latest/openssl/ssl/struct.SslContextBuilder.html#method.set_private_key

**Comment by powerory** [comment]
> Use https://docs.rs/openssl/latest/openssl/pkey/struct.PKey.html#method.private_key_from_pem_passphrase and https://docs.rs/openssl/latest/openssl/ssl/struct.SslContextBuilder.html#method.set_private_key

It works well!
Thank you for your guide:)
