### ISSUE TITLE
How to use X509StoreContext::chain()?

### ISSUE THREAD

**Issue by dtivel** [sfackler/rust-openssl#1587]
It [appears](https://github.com/sfackler/rust-openssl/blob/16f65124674afd935b52ba6e6b10f963fb440968/openssl/src/x509/mod.rs#L98-L101) that `X509StoreContext::chain()` can only be called within `X509StoreContext::init(...)`'s `with_context` closure.  However, attempting to do so raises compiler error [E0502](https://doc.rust-lang.org/error-index.html#E0502).

```rust
use openssl::{x509::{store::X509Store, X509StoreContext, X509}, stack::Stack};

fn repro(trust_store: &X509Store, certificate: &X509, chain: &Stack<X509>) {
    let mut store_context: X509StoreContext = X509StoreContext::new().unwrap();

    // cannot borrow `store_context` as immutable because it is also borrowed as mutable
    // immutable borrow occurs here rustc(E0502)
    // lib.rs(11, 5): mutable borrow occurs here
    // lib.rs(14, 30): second borrow occurs due to use of `store_context` in closure
    // lib.rs(11, 19): mutable borrow later used by call
    store_context.init(&trust_store, &certificate, &chain, |c| {
        c.verify_cert();

        if let Some(chain) = store_context.chain() {
        }

        Ok(())
    });
}
```

Should [`X509StoreContext::chain(...)`](https://github.com/sfackler/rust-openssl/blob/16f65124674afd935b52ba6e6b10f963fb440968/openssl/src/x509/mod.rs#L186) take `&mut self` instead?  Am I doing something wrong?

**Comment by sfackler** [comment]
Call `c.chain()` instead.

**Comment by dtivel** [comment]
Wonderful!  Thanks, @sfackler!
