### ISSUE TITLE
Borrowed Types Must Not Be Opaque

### ISSUE THREAD

**Issue by bkstein** [sfackler/rust-openssl#1614]
rust-openssl imports many OpenSSL types using the foreign_function crate. The imported types come in
two flavors: owned and borrowed (e.g. Pkcs7 and Pkcs7Ref). While the owned type can be implemented to
have full access to the underlying C structures, the borrowed type is `Opaque`. This means: if you
work with a borrowed OpenSSL object, it is impossible to access the C struct members.
OpenSSL does not always offer access functions to the structs. E.g. `PKCS7`, `X509_ATTRIBUTE` or
`ASN1_TYPE` can only be used, if it is possible to access the struct members directly. However, if such an
object is borrowed in rust-openssl, this is not possible.
This blocks further extension of this great library.

## Example

I would like to implement `Asn1Type` to wrap OpenSSLs `ASN1_TYPE`. `Asn1Type` should provide access to
`type` and `value` as given in the C-struct:
```C
typedef struct asn1_type_st {
    int type;
    union {
        char *ptr;
        ASN1_BOOLEAN boolean;
        ASN1_STRING *asn1_string;
        ASN1_OBJECT *object;
        /// ... skipping some members here
    } value;
} ASN1_TYPE;
```

An `Asn1TypeRef` shall be returned from `Pkcs7SignerInfo::get_signed_attribute(nid: Nid);`. I want to
check the `typ`, e.g.

```rust
let asn1typeref = signer_info.get_signed_attribute(*nid::PKI_STATUS);
let t = asn1typeref.typ();
                   ^^^^^^^---- this can't be implemented in a borrowed type, as it is 'Opaque'!
				   
```

As `signer_info` owns the attribute, therefore I can't return an `Asn1Type`, it must be a (borrowed) `Asn1TypeRef`.

## Conclusion

I don't see a way out of this, if we stick with the current opaque implementation in crate foreign-types.
I propose to make the borrowed type non-opaque. This might also be helpful for other ffi implementations.

**Comment by sfackler** [comment]
https://docs.rs/foreign-types-shared/0.1.1/foreign_types_shared/trait.ForeignTypeRef.html#method.as_ptr will give you a raw pointer to the OpenSSL type that you can load fields from.

**Comment by bkstein** [comment]
Thanks, that's good news. However, it pokes a hole in the opacity of the borrowed types, right ;)

**Comment by sfackler** [comment]
Opacity is not the goal.

**Comment by sfackler** [comment]
You wouldn't be able to use borrowed as a reference type with that definition - there are too many levels of indirection.
