### ISSUE TITLE
Core dumped in alpine runtime

### ISSUE THREAD

**Issue by AltF02** [sfackler/rust-openssl#1620]
This issue is related to https://github.com/seanmonstar/reqwest/issues/1528

It seems that the build and link works with `libressl-dev` but causes an runtime error? I'm guessing this has something to do with openssl-sys as rustls works fine.

Details can be found at the linked issue

Thanks!

**Comment by sfackler** [comment]
Alpine docker images dynamically link to MUSL, while Rust's musl target statically links to it by default. If you mix these two behaviors (i.e. by pulling Alpine's OpenSSL) you can see crashes. Either tell rustc to not statically link MUSL (some `-C` flag with `-crt-static` I think?) or build OpenSSL with a static MUSL as well.

**Comment by AltF02** [comment]
Ah makes sense, cheers!
