### ISSUE TITLE
Trying to use SSLv3

### ISSUE THREAD

**Issue by jacobtread** [sfackler/rust-openssl#1625]
I am trying to make a game server emulator for a game but the networking for that game only supports SSLv3

![image](https://user-images.githubusercontent.com/33708767/165917940-9ca099d8-814f-4097-bc78-eedcc9b7b541.png)
The game connection ^ 

I tried to fix this using 
![image](https://user-images.githubusercontent.com/33708767/165918045-75976be6-25d8-448f-b064-448b54fc0e81.png)

But when the client attempts to connect I get the following error
`Failure(MidHandshakeSslStream { stream: SslStream { stream: TcpStream { addr: 127.0.0.1:42127, peer: 127.0.0.1:54080, socket: 272 }, ssl: Ssl { state: "error", verify_result: X509VerifyResult { code: 0, error: "ok" } } }, error: Error { code: ErrorCode(1), cause: Some(Ssl(ErrorStack([Error { code: 337678732, library: "SSL routines", function: "tls_early_post_process_client_hello", reason: "version too low", file: "ssl\\statem\\statem_srvr.c", line: 1686 }]))) } })`

And if I modify it so that in the min and max proto versions I only have ssl3
![image](https://user-images.githubusercontent.com/33708767/165918275-f7a7982d-034e-4ed8-9f8c-6e0c9581b0c6.png)

I get the following error
``Failure(MidHandshakeSslStream { stream: SslStream { stream: TcpStream { addr: 127.0.0.1:42127, peer: 127.0.0.1:54311, socket: 296 }, ssl: Ssl { state: "error", verify_result: X509VerifyResult { code: 0, error: "ok" } } }, error: Error { code: ErrorCode(1), cause: Some(Ssl(ErrorStack([Error { code: 167772556, library: "SSL routines", function: "tls_early_post_process_client_hello", reason: "version too low", file: "ssl\\statem\\statem_srvr.c", line: 1657 }]))) } })```

**Comment by sfackler** [comment]
I would assume your OpenSSL installation wasn't built with SSLv3 support.

**Comment by jacobtread** [comment]
Uhh i've tried cross compiling for windows using my ubuntu wsl install with the enable-ssl3 flag but after setting the environment variable for the openssl dir and building I get this error 'OpenSSL libdir at `C:\Program Files\OpenSSL\lib` does not contain the required files to either statically or dynamically link OpenSSL', any ideas how to fix?

**Comment by jacobtread** [comment]
The command I used to compile it is:
./Configure --cross-compile-prefix=x86_64-w64-mingw32- mingw64 enable-ssl3 && sudo make && sudo make install

**Comment by jacobtread** [comment]
![image](https://user-images.githubusercontent.com/33708767/165950361-0913d931-dc6c-413f-9f31-af909828c472.png)

**Comment by sfackler** [comment]
Are you compiling with the mingw target in Windows or the msvc target? I am not super familiar with Windows, but I don't think MSVC will be able to use those libraries.

**Comment by jacobtread** [comment]
Okay I fixed that issue but im still getting "no protocols available" even after building with "enable-ssl3"

**Comment by jacobtread** [comment]
Okay I fixed that link error it was because I was using 32bit instead of 64bit but im still getting the same issue as before

setting the max protocol version to SSL3 gives "no protocols available" and setting the max to TLS1_3 gives "version too low"
