### ISSUE TITLE
OpenSSL 3.0 on Ubuntu 22.04; error: libssl.so.1.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by dawid-nowak** [sfackler/rust-openssl#1633]
I am getting a build failure when building my project on Ubuntu 22.04. 
![image](https://user-images.githubusercontent.com/25728428/167506891-b5cf396e-a19b-4bfc-bc97-309a16e99fbc.png)

It looks like Ubuntu moved to ssl 3.0 so the libraries are called libssl.so.3 instead of libssl.so.1.1.

When I symlink libssl.so.3 to libssl.so.1.1 everything builds fine.

**Comment by sfackler** [comment]
You probably need to do a `cargo clean` and rebuild to make openssl-sys pick up the new installation.

**Comment by dawid-nowak** [comment]
yup, that indeed solved my problem
