### ISSUE TITLE
Types with `up_ref` are dangerous

### ISSUE THREAD

**Issue by Skepfyr** [sfackler/rust-openssl#1636]
Reproducer:
```rust
use std::os::raw::{c_int, c_long};

use color_eyre::Result;
use crossbeam::thread;
use foreign_types::ForeignType;
use openssl::x509::X509;

fn main() -> Result<()> {
    color_eyre::install()?;

    let x509_a = X509::builder()?.build();
    let x509_b = x509_a.as_ref().to_owned();

    println!("a: {}, b: {}", x509_a.version(), x509_b.version());

    thread::scope(|s| {
        s.spawn(|_| {
            for _ in 0..10_000 {
                let version = x509_a.version() as c_long;
                unsafe {
                    X509_set_version(x509_a.as_ptr(), version + 1);
                }
            }
        });
        s.spawn(|_| {
            for _ in 0..5_000 {
                let version = x509_b.version() as c_long;
                unsafe {
                    X509_set_version(x509_b.as_ptr(), version + 1);
                }
            }
        });
    })
    .unwrap();

    println!("a: {}, b: {}", x509_a.version(), x509_b.version());

    Ok(())
}

extern "C" {
    fn X509_set_version(x: *mut openssl_sys::X509, version: c_long) -> c_int;
}
```
This prints a number <1500 twice.

I couldn't quite decide if this is unsoundness or not, as it requires unsafe code, however I can easily see some C library calling the set methods and causing some very confusing data races and non-local effects. This all stems from OpenSSLs multithreading support of "don't use the same object from multiple threads at the same time". Theoretically these types should be `!Send` but the C code can send them between threads so that might not help.

**Comment by Skepfyr** [comment]
Good point about `Send`, that approach makes sense and is roughly what I was expecting. Would it be sensible to document this on `X509` and `X509_STORE`? (I think those are the only types with up_ref?)

**Comment by sfackler** [comment]
I'm not sure I want to get into the business of documenting everything that unsafe code needs to understand about OpenSSL.

**Comment by Skepfyr** [comment]
Fair enough.
