### ISSUE TITLE
Building openssl rust bindings ends with errors.

### ISSUE THREAD

**Issue by Dvergatal** [sfackler/rust-openssl#1643]
Hi all,
I am trying to build iotedged from https://github.com/Azure/iotedge with openssl 3.0.3 in yocto 4.0. The problem with iotedged is, that it uses older openssl rust bindings, but I have solved this issue, with changing all dependencies and now I'm facing a completely different issue.

Mainly speaking, when rust openssl-0.10.39 is building, it hangs due to errors like this:
```bash
     Running `/work/build/tmp-glibc/work/core2-64-WelotecGmbH-linux/iotedge-daemon/1.1.13-r0/build/target/release/build/hsm-sys-a7e2069e76e469c7/build-script-build`
error: expected `,`
   --> /usr/src/debug/iotedge-daemon/1.1.13-r0/cargo_home/bitbake/openssl-0.10.39/src/macros.rs:94:40
    |
94  |                   let len = crate::cvt($f(::foreign_types::ForeignTypeRef::as_ptr(self),
    |  ________________________________________^
95  | |                                         ptr::null_mut()))?;
    | |________________________________________________________^
    |
   ::: /usr/src/debug/iotedge-daemon/1.1.13-r0/cargo_home/bitbake/openssl-0.10.39/src/cms.rs:123:5
```
The same happens to me with 0.10.40. I'm attaching the full log:
[log.do_compile.3827546.log](https://github.com/sfackler/rust-openssl/files/8766430/log.do_compile.3827546.log)

Maybe someone was facing this kind of issues?
.

**Comment by sfackler** [comment]
That's a strange error. What does `rustc --version` return?

**Comment by Dvergatal** [comment]
> That's a strange error. What does `rustc --version` return?
rustc 1.59.0

**Comment by sfackler** [comment]
It looks like the crate is vendored into `cargo_home/bitbake`. How was that done? Are the files in there exactly identical to the actual 0.10.39 release?

**Comment by Dvergatal** [comment]
The recipe is downloading the crates and i can even pack it for you and import here.

**Comment by Dvergatal** [comment]
[openssl-0.10.39.zip](https://github.com/sfackler/rust-openssl/files/8766628/openssl-0.10.39.zip)

**Comment by sfackler** [comment]
It looks like the main branch is using openssl 0.10 - https://github.com/Azure/iotedge/blob/main/edgelet/iotedge/Cargo.toml#L29.

It also seems like the build process for the iotedge crate is just straight cargo build with no vendoring going on. If there's extra stuff going on in the build process, that may be the issue.

**Comment by Dvergatal** [comment]
The iotedge in master is from v2 and we are still using v1. The newest is 1.1.13.

>It also seems like the build process for the iotedge crate is just straight cargo build with no vendoring going on. If there's extra stuff going on in the build process, that may be the issue.

From what i see it doesn't patch the crate, it is just being built but for some reason i got this error which is useless for me...

**Comment by Dvergatal** [comment]
Hmmm shouldn't it be, that openssl-macros shall be compiled first?

**Comment by Dvergatal** [comment]
Ok i have finally succeded to build openssl :dancers:  The problem was caused by old dependencies for serde_derive which were pulling me old proc-macro2.
