### ISSUE TITLE
ssl connect example in documentation does not work

### ISSUE THREAD

**Issue by finalclass** [sfackler/rust-openssl#1650]
I'm in a process of learning rust so forget me if I'm missing something obvious.

I'm trying to run this example on my local computer:
https://docs.rs/openssl/latest/openssl/ssl/index.html#examples

I've created a new project with: `cargo new ssl-test`
In the `Cargo.toml` I have this:

```toml
[package]
name = "ssl-test"
version = "0.1.0"
edition = "2021"

[dependencies]
openssl = { version = "0.10.40", features = ["vendored"] }
```

In `src/main.rs` I have this:

```rust
fn main() {
    use openssl::ssl::{SslConnector, SslMethod};
    use std::io::{Read, Write};
    use std::net::TcpStream;

    let connector = SslConnector::builder(SslMethod::tls()).unwrap().build();

    let stream = TcpStream::connect("google.com:443").unwrap();
    let mut stream = connector.connect("google.com", stream).unwrap();

    stream.write_all(b"GET / HTTP/1.0\r\n\r\n").unwrap();
    let mut res = vec![];
    stream.read_to_end(&mut res).unwrap();
    println!("{}", String::from_utf8_lossy(&res));
}
```

When I run this code with `cargo run` it works fine.
However when I try to run the same program by calling the executable: `./target/debug/ssl-test` I get this error:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Failure(MidHandshakeSslStream { stream: SslStream { stream: TcpStream { addr: 192.168.3.30:50192, peer: 172.217.16.14:443, fd: 3 }, ssl: Ssl { state: "error", verify_result: X509VerifyResult { code: 20, error: "unable to get local issuer certificate" } } }, error: Error { code: ErrorCode(1), cause: Some(Ssl(ErrorStack([Error { code: 337047686, library: "SSL routines", function: "tls_process_server_certificate", reason: "certificate verify failed", file: "ssl/statem/statem_clnt.c", line: 1919 }]))) } })', src/main.rs:9:62
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

`cargo` must be adding something but I can't figure out what it is.

I'm on Arch Linux.

**Comment by sfackler** [comment]
The vendored OpenSSL installation doesn't have any default trusted root certificates. You can either disable the vendored feature to pick up your system's OpenSSL, or use something like https://docs.rs/openssl-probe/latest/openssl_probe/fn.probe.html to look through the system for where the root certificates live.

**Comment by finalclass** [comment]
Thanks it worked!
Do you know maybe why it was working fine with `cargo run` ?

**Comment by sfackler** [comment]
Cargo internally uses openssl-probe, and the configuration it sets unfortunately leaks out into processes Cargo spawns.

**Comment by finalclass** [comment]
Thanks for your answer. For reference, this is what I did to fix that:

Cargo.toml

```toml
[dependencies]
openssl = "0.10.40"
openssl-probe = "0.1.2"
```

And in the code:
```rust
extern crate openssl_probe;

fn main() {
    openssl_probe::init_ssl_cert_env_vars();
     ...
```
