### ISSUE TITLE
SSL_CTX_set_alpn_select_cb deprecation message wrong?

### ISSUE THREAD

**Issue by klensy** [sfackler/rust-openssl#1654]
Function `SSL_CTX_set_alpn_select_cb` was deprecated:
https://github.com/sfackler/rust-openssl/blob/bba1712865cc87ab1617cf03a8f79b6b0f518dcb/openssl-sys/src/ssl.rs#L593-L595

But it looks like it should suggest use `SSL_CTX_set_alpn_select_cb__fixed_rust` instead?

**Comment by sfackler** [comment]
Oops, yeah.
