### ISSUE TITLE
failed to run custom build command for `openssl-sys v0.9.75 - RockyLinux 8.6

### ISSUE THREAD

**Issue by toastxc** [sfackler/rust-openssl#1667]
I've tried compiling for Rocky Linux on kernel v4.18 but cargo errors.
I have installed openssl and other SSL development packages but it has not solved the problem

`thread 'main' panicked at '

  Could not find directory of OpenSSL installation, and this `-sys` crate cannot
  proceed without this knowledge. If OpenSSL is installed and this crate had
  trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
  compilation process.

  Make sure you also have the development packages of openssl installed.
  For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.

  If you're in a situation where you think the directory *should* be found
  automatically, please open a bug at https://github.com/sfackler/rust-openssl
  and include information about your system as well as this message.

  $HOST = x86_64-unknown-linux-gnu
  $TARGET = x86_64-unknown-linux-gnu
  openssl-sys = 0.9.75
`

 I apologize in advanced if there is already an issue open for this.

**Comment by jcamiel** [comment]
Hi, 

Maybe related to this problem, I can't build a sample binary with `openssl-sys 0.10.41`.

I've this error:

```
error: process didn't exit successfully: `rustc -vV` (exit status: 1)
--- stderr
rustc: /usr/lib/libc.so.6: version `GLIBC_2.36' not found (required by /usr/lib/libLLVM-14.so)
rustc: /usr/lib/libc.so.6: version `GLIBC_2.36' not found (required by /usr/lib/libstdc++.so.6)
```

To reproduce:
- use latest Archlinux image `docker run -it archlinux`
- install rust (for instance `pacman -S rust`)
- create a sample, add openssl-sys as a dependency and build
```
$ cargo init foo
$ cd foo
$ cargo add openssl-sys
$ cargo build
```
The build failed with this error:

```
error: process didn't exit successfully: `rustc -vV` (exit status: 1)
--- stderr
rustc: /usr/lib/libc.so.6: version `GLIBC_2.36' not found (required by /usr/lib/libLLVM-14.so)
rustc: /usr/lib/libc.so.6: version `GLIBC_2.36' not found (required by /usr/lib/libstdc++.so.6)
```

I can provide more information if you need and could help to test things, 

Thanks for your crates !

**Comment by jcamiel** [comment]
Hi,
I've solved my issue by installing the latest version of `glib`:

```
$ pacman -Sy glibc
```

So everything is ok, sorry for the noise one this issue!

**Comment by toastxc** [comment]
I tried doing the same thing, installing glibc-devel but this didn't solve the issue. 
`error: failed to run custom build command for `openssl-sys v0.9.75`
`

**Comment by ohsayan** [comment]
+1. We're getting the same error when building on Debian/Ubuntu/Fedora, when going from an earlier version to 0.9.75. You can see the attached trace for a full log: [err.txt](https://github.com/sfackler/rust-openssl/files/9275311/err.txt)

**Comment by sfackler** [comment]
@ohsayan that error is not specific to this library. It seems like something is broken with your Rust install.

@toastxc do you have pkg-config? Can you paste the entire output?

**Comment by toastxc** [comment]
```
  --- stdout
  cargo:rustc-cfg=const_fn
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR
  X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
  OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR
  X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
  OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR
  X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_DIR
  OPENSSL_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=OPENSSL_STATIC
  cargo:rerun-if-env-changed=OPENSSL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  run pkg_config fail: "`\"pkg-config\" \"--libs\" \"--cflags\" \"openssl\"` did not exit successfully: exit status: 1\nerror: could not find system library 'openssl' required by the 'openssl-sys' crate\n\n--- stderr\nPackage openssl was not found in the pkg-config search path.\nPerhaps you should add the directory containing `openssl.pc'\nto the PKG_CONFIG_PATH environment variable\nPackage 'openssl', required by 'virtual:world', not found\n"

  --- stderr
  thread 'main' panicked at '

  Could not find directory of OpenSSL installation, and this `-sys` crate cannot
  proceed without this knowledge. If OpenSSL is installed and this crate had
  trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
  compilation process.

  Make sure you also have the development packages of openssl installed.
  For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.

  If you're in a situation where you think the directory *should* be found
  automatically, please open a bug at https://github.com/sfackler/rust-openssl
  and include information about your system as well as this message.

  $HOST = x86_64-unknown-linux-gnu
  $TARGET = x86_64-unknown-linux-gnu
  openssl-sys = 0.9.75
```

**Comment by sfackler** [comment]
>   run pkg_config fail: "`\"pkg-config\" \"--libs\" \"--cflags\" \"openssl\"` did not exit successfully: exit status: 1\nerror: could not find system library 'openssl' required by the 'openssl-sys' crate\n\n--- stderr\nPackage openssl was not found in the pkg-config search path.\nPerhaps you should add the directory containing `openssl.pc'\nto the PKG_CONFIG_PATH environment variable\nPackage 'openssl', required by 'virtual:world', not found\n"

You need to install whatever OpenSSL development package contains its pkg-config file.

**Comment by toastxc** [comment]
Installing openssl-devel fixed it... I thought I had already installed this and perhaps I did on another machine
sorry

**Comment by damiensawyer** [comment]
On Debian, ```sudo apt install libssl-dev``` worked for me.

**Comment by newtonjose** [comment]
Any one has that problem on Arch? Try the suggestion of @jcamiel unfortunately no success

**Comment by jcamiel** [comment]
Hi,
We’re building our project in our ci (using an ArchLinux image), it seems fine to me now, maybe it can help you:

The GitHub action:

https://github.com/Orange-OpenSource/hurl/blob/b16702dadd15e2e75dcb696ed96d77f1743ace57/.github/workflows/test.yml#L65

Our build script for Arch:

https://github.com/Orange-OpenSource/hurl/blob/master/bin/install_prerequisites_archlinux.sh

**Comment by lei-cheung** [comment]
for mac:

```shell
brew install openssl@3
export export OPENSSL_DIR=$(brew --prefix openssl)
export PKG_CONFIG_ALLOW_CROSS=1
export PKG_CONFIG_PATH=$(brew --prefix)/opt/openssl@1.1/lib/pkgconfig
`

```toml
[dependencies]
jni = { version = "0.19", default-features = false }
hickory-resolver = "0.24.0"
reqwest = { version = "0.11.23", features = ["blocking"] }
openssl-sys = "0.9.98"
```

**Comment by ladyki2323** [comment]
> On Debian, `sudo apt install libssl-dev` worked for me.

Works on Ubuntu 22.04, too

**Comment by elimisteve** [comment]
This solved it for me on Alpine:

```bash
doas apk add openssl-devel
```

**Comment by tm-ahad** [comment]
i am getting the same error by trying to compile for x86_64_unknown_linux_gnu on windows

**Comment by shitcodebykaushik** [comment]
Guys i am having the  same issue .

**Comment by crossedheadx** [comment]
> ```shell
> openssl-devel
> ```

Same on Fedora under distrobox

```bash
sudo dnf install -y  openssl-devel
```

**Comment by 99bond** [comment]
sudo apt install libssl-dev
sudo apt install pkg-config

It work in Ubuntu 24.04.2LTS
