### ISSUE TITLE
Update project to not rely on the old paths feature 'old_path'

### ISSUE THREAD

**Issue by frewsxcv** [sfackler/rust-openssl#167]
It's going to eventually go away. Should switch sometime soon

**Comment by sfackler** [comment]
I'm going to switch the library as a whole from old_path and old_io to path and io, but not until the new IO system stabilizes a bit.

**Comment by frewsxcv** [comment]
SGTM :+1:

**Comment by frewsxcv** [comment]
This was fixed in https://github.com/sfackler/rust-openssl/pull/184
