### ISSUE TITLE
Vulnerability RUSTSEC-2022-0032

### ISSUE THREAD

**Issue by mihaigalos** [sfackler/rust-openssl#1671]
Hi, I might have stumbled across a vulnerability in `openssl-sys`:

```bash
$ cargo audit # in my downstream crate

Crate:         openssl-src
Version:       111.21.0+1.1.1p
Title:         AES OCB fails to encrypt some bytes
Date:          2022-07-05
ID:            RUSTSEC-2022-0032
URL:           https://rustsec.org/advisories/RUSTSEC-2022-0032
Solution:      Upgrade to >=111.22, <300.0 OR >=300.0.9
Dependency tree: 
openssl-src 111.21.0+1.1.1p
```
Not sure how this happened, here's a deptree:
```bash
$ cargo tree
..
│   │   │   └── openssl-sys v0.9.75
│   │   │       └── libc v0.2.126
│   │   │       [build-dependencies]
│   │   │       ├── autocfg v1.1.0
│   │   │       ├── cc v1.0.73
│   │   │       ├── openssl-src v111.21.0+1.1.1p
```
I see you're depending on [`openssl-src`](https://github.com/sfackler/rust-openssl/blob/eb747eb8131bb10fffc58e102bfa1ab956c5b817/openssl-sys/Cargo.toml#L25), and that is `v111`. Is this implicityl using "latest", or where does the minor+patch versions come from (21.0+..)?
Can you please publish a version without that vulnerability? Thank you.

**Comment by sfackler** [comment]
Run `cargo update`.
