### ISSUE TITLE
Support openssl > 3.0.0 and misleading error

### ISSUE THREAD

**Issue by donkeyteethUX** [sfackler/rust-openssl#1675]
On Ubuntu 22.04, `apt install libssl-dev` will install openssl 3.0.2 which is not yet supported by `rust-openssl`. Are there any blockers to supporting newer versions? Also, in this scenario the error from the build script indicates missing header files (not a version mismatch) and unhelpfully suggests reinstalling the unsupported version.

```
 Failed to find OpenSSL development headers.

  You can try fixing this setting the `OPENSSL_DIR` environment variable
  pointing to your OpenSSL installation or installing OpenSSL headers package
  specific to your distribution:

      # On Ubuntu
      sudo apt-get install libssl-dev
```

Perhaps at least the error could be improved?
Installing and building with 1.1.1 works as expected.

**Comment by sfackler** [comment]
OpenSSL 3 is already supported. What is the full output of the build process?

**Comment by donkeyteethUX** [comment]
I was using `rust-openssl v0.9.43` because it's pinned by `curl-rust`. The latest version does work :+1:. Fwiw I thought any `openssl` versions beyond 3.0.0 weren't supported because of this comment: https://github.com/sfackler/rust-openssl/blob/4d392c96da22825f7e15781968df145d8e5fe681/openssl-sys/build/main.rs#L153 Looks like the code should actually accept any 3.x.x version though.
