### ISSUE TITLE
BIO_s_mem on rust

### ISSUE THREAD

**Issue by konradmoesch** [sfackler/rust-openssl#1697]
Hi,
Instead of the `TcpStream`, I need a non-blocking memory stream, similar to `BIO_s_mem`. However, this seems to not be implemented in rust?
The reason I need this alternate stream is that I want to use rust-openssl on traffic transmitted over USB instead of TCP.
I have found a somewhat working implementation in cpp using such a memory BIO (and then reading/writing from the bio buffer to usb and vise versa)
Is this also possible using rust-openssl, and if so, how? This crate seems to not implement these BIOs

Thank you!

**Comment by sfackler** [comment]
This crate works with types implementing the Rust `Read` and `Write` traits. You can define a type implementing those that buffers data internally.

**Comment by konradmoesch** [comment]
Okay thanks, will try that.
So there is not type that does this in this or other crates, I simply define it myself? And then use it with the `connect` methods etc as the `Stream` parameter?

**Comment by sfackler** [comment]
Yep

**Comment by konradmoesch** [comment]
Thanks

**Comment by konradmoesch** [comment]
Hi again, sorry, I think I'm still doing sth wrong using it.
I implemented a rudimentary in-memory-stream using Vec<u8> and it seems that `do_handshake()` does write some data into this vector.
However, `do_handshake()` returns a `Error { code: ErrorCode(1), cause: Some(Ssl(ErrorStack([Error { code: 537362500, library: "BIO routines", function: "bio_read_intern", reason: "internal error", file: "crypto/bio/bio_lib.c", line: 281 }]))) }`
The same error is thrown when i use `read()` or `ssl_read()` on the stream.
From trying to debug, I can see that `read()` is called on the underlying MemoryStream vector, but always with a buf param of length 5.

I assume `read()` is called in `do_handshake()` to get the response? So I might need to store the data in two different vectors (one where openssl writes data that I can then transmit over usb and the other one that stores the response data from usb and is `read()` from inside openssl)

But I think the issue that all `read()`s from openssl fail and use a `buf` param of length 5 might be unrelated

**Comment by sfackler** [comment]
> I assume `read()` is called in `do_handshake()` to get the response? So I might need to store the data in two different vectors

Yes

**Comment by konradmoesch** [comment]
I tried using a `Cursor<Vec<u8>>` as an alternative to BIO_s_mem in cpp, which looks promising so far.
In the cpp code that I found, `BIO_read` (`BIO_write`) is used to get and write to this in-memory-buffer.
I am now able to send a ssl handshake via USB (calling `do_handshake` on a  `openssl::ssl::SslStream<Cursor<Vec<u8>>>` and then reading the contents of the underlying cursor and writing it to the USB device)
For the response, I use the following workflow: reading the response bytes from USB -> clearing the contents of the internal `Cursor<Vec<u8>>` ->writing them into the internal `Cursor` -> calling `do_handshake()` on the `SslStream`again.
But I get a `Ssl(ErrorStack([Error { code: 336130315, library: "SSL routines", function: "ssl3_get_record", reason: "wrong version number", file: "ssl/record/ssl3_record.c", line: 331 }]))`, which, according to https://github.com/openssl/openssl/blob/01b533540a555fc3a9eee4957c3feec1168cd709/ssl/record/ssl3_record.c#L331 might mean that the SSL handshake response does not correctly reach the SslStream (and therefore cannot be used withing openssl)?

Is my approach clearing and writing into the `Cursor` wrong? If I understand correctly, the concept of two BIOs in cpp requires only one Stream (TcpStream or Cursor) in rust, which can be written and read from?
Do you maybe have an idea where the problem could be? I tried capturing and analysing the USB (SSL handshake) traffic, which looks good until this point

**Comment by sfackler** [comment]
You can't use a single buffer for both directions of stream. You need to have one buffer for incoming data and another for outgoing data.

**Comment by manio** [comment]
@konradmoesch I have exactly same use case as you. In my case I have to encapsulate SSL handshake and all transmission in specific frames and send them to USB and TCP. If you did this (on two buffers as @sfackler told you) is your work available on github or elsewhere so I can take a quick look and implement something similar?

**Comment by manio** [comment]
If someone comes across the same problem, here is my implementation for this:
https://github.com/manio/aa-proxy-rs/blob/main/src/mitm.rs#L45
Maybe not optimal, but it's working :)
