### ISSUE TITLE
QUESTION: Why is the FIPS module disabled on ossl300?

### ISSUE THREAD

**Issue by ssosik** [sfackler/rust-openssl#1702]
Hi! Please pardon me if I'm missing something obvious -

in [`openssl/src/lib.rs` ](https://github.com/sfackler/rust-openssl/blob/master/openssl/src/lib.rs#L155) it looks like the FIPS module is specifically disabled when using OpenSSL 3.0. Can you help me understand the reason behind this?

Thank you!

**Comment by sfackler** [comment]
Those APIs were removed in OpenSSL 3.0.0. You instead use the provider APIs to load the fips provider: https://github.com/sfackler/rust-openssl/blob/master/openssl/src/provider.rs

**Comment by ssosik** [comment]
Ah, thank you for the quick response!
