### ISSUE TITLE
Does rust-openssl using openss.cnf files from local Openssl-3 installation

### ISSUE THREAD

**Issue by Pankul94** [sfackler/rust-openssl#1712]
I am new to RUST and trying my hands on rust-openssl.

Openssl-3 now has a concept of providers which provide the implementation of cryptographic algorithms and there is fips provider which is 140-2 validated. Openssl-3 also comes with a config file where you can mention the providers that are to be loaded when calling openssl binary.

For my testing, I have built a version of Openssl-3 on my machine and I have exported `OPENSSL_DIR` to point to the local directory to ensure that my local version of Openssl is used which is built with `enable-fips` flag.  My openssl.cnf file is using fips provider.

I used the sample code provided for MdCtx and modified it to calculate md5 digest:

```
use openssl::md::Md;
use openssl::md_ctx::MdCtx;

fn main() {
    let mut ctx = MdCtx::new().unwrap();
    ctx.digest_init(Md::md5()).unwrap();
    ctx.digest_update(b"Some Crypto Text").unwrap();
    let mut digest = [0; 16];
    ctx.digest_final(&mut digest).unwrap();

    assert_eq!(
        digest,
        *b"\xed\x7a\x6c\xa8\xa1\x23\x0d\x85\x95\x4f\x6f\xf2\x43\xc1\x1c\x3f",
    );
}
```

I am getting an error:
> Thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorStack([Error { code: 50856204, library: "digital envelope routines", function: "inner_evp_generic_fetch", reason: "unsupported", file: "crypto/evp/evp_fetch.c", line: 349, data: "Global default library context, Algorithm (MD5 : 102), Properties ()" }, Error { code: 50331782, library: "digital envelope routines", function: "evp_md_init_internal", reason: "initialization error", file: "crypto/evp/digest.c", line: 252 }])', src/main.rs:6:28

I then changed my openssl.cnf file and used the default provider and then I was able to run the program without any issues.

So I think rust-openssl will use the openssl.cnf file and use the provider listed. Is that right?

**Comment by sfackler** [comment]
MD5 is not fips compliant. If you are correctly picking up the fips module, than it is expected that trying to use MD5 would fail.

**Comment by CfirTsabari** [comment]
@Pankul94 are you using the feature: `vendored` or not?
