### ISSUE TITLE
Error formatting issues

### ISSUE THREAD

**Issue by rukai** [sfackler/rust-openssl#1715]
I investigated the formatting of `openssl::error::Error` and observed 3 bugs:
1. fmt::Display of `openssl::ssl::error::Error` and the error it returns via `.source()` are identical.
This results in weird looking error chains where the same error is repeated twice.
Internally what happens is `openssl::ssl::error::Error` forwards its formatting logic onto its inner source value.
We either need to return None for `.source()`, or provide a much more vague error for the parent error to avoid the error being confusingly duplicated.
2. fmt::Display implementation does not provide enough context for a human to make sense of it.
3. the data field is never populated due to passing a NULL pointer for `data` and `flags` to `ERR_get_error_all` as documented here: https://www.openssl.org/docs/man3.0/man3/ERR_get_error_line_data.html

I will be opening PRs for some of these shortly.

**Comment by sfackler** [comment]
3. It is not passing a null pointer to ERR_get_error_all, it is passing a pointer to a null pointer that ERR_get_error_all will fill in. The data field is absolutely populated and is in fact tested here for example: https://github.com/sfackler/rust-openssl/blob/master/openssl-errors/tests/test.rs#L59-L74

**Comment by rukai** [comment]
1. I cant think of a suitable solution.
If we set .source() to None then the user loses access to the inner values.
If we make the parent error return a generic message like "SSL error" then this causes a silent breaking change where everyone who only used the parent error suddenly gets really bad error messages.

2. was rejected https://github.com/sfackler/rust-openssl/pull/1716

3. You are absolutely right, I'm not used to reading C API's, my bad.
I am suspicious there might be something broken here as another python application using openssl was able to report extra information in a specific openssl failure case that isnt included in the error my application received from openssl-rs in that same case. (and I am yet to see a single `data() == Some` in any of the errors I get)
But that is just a suspicion on my part and I dont have anything else to go on, so lets consider this invalid.

## My solution
For anyone who comes across this issue, this was my solution.
It uses anyhow but you should be able to easily adjust it to your own error types.
It keeps the same information provided in the Display trait but formats it in a human readable way.
```rust
// Always use these openssl_* conversion methods instead of directly directly converting to anyhow

pub fn openssl_ssl_error_to_anyhow(error: openssl::ssl::Error) -> anyhow::Error {
    if let Some(stack) = error.ssl_error() {
        openssl_stack_error_to_anyhow(stack.clone())
    } else {
        anyhow!("{error}")
    }
}

pub fn openssl_stack_error_to_anyhow(error: openssl::error::ErrorStack) -> anyhow::Error {
    let mut anyhow_stack: Option<anyhow::Error> = None;
    for inner in error.errors().iter().rev() {
        let anyhow_error = openssl_error_to_anyhow(inner.clone());
        anyhow_stack = Some(match anyhow_stack {
            Some(anyhow) => anyhow.context(anyhow_error),
            None => anyhow_error,
        });
    }
    match anyhow_stack {
        Some(anyhow_stack) => anyhow_stack,
        None => anyhow!("{error}"),
    }
}

pub fn openssl_error_to_anyhow(error: openssl::error::Error) -> anyhow::Error {
    let mut fmt = String::new();
    write!(fmt, "error 0x{:08X} ", error.code()).unwrap();
    match error.reason() {
        Some(r) => write!(fmt, "'{}", r).unwrap(),
        None => write!(fmt, "'Unknown'").unwrap(),
    }
    if let Some(data) = error.data() {
        write!(fmt, ": {}' ", data).unwrap();
    } else {
        write!(fmt, "' ").unwrap();
    }
    write!(fmt, "occurred in ").unwrap();
    match error.function() {
        Some(f) => write!(fmt, "function '{}' ", f).unwrap(),
        None => write!(fmt, "function 'Unknown' ").unwrap(),
    }
    write!(fmt, "in file '{}:{}' ", error.file(), error.line()).unwrap();
    match error.library() {
        Some(l) => write!(fmt, "in library '{}'", l).unwrap(),
        None => write!(fmt, "in library 'Unknown'").unwrap(),
    }

    anyhow!(fmt)
}
```

You can also see it in use at: https://github.com/shotover/shotover-proxy/pull/891
