### ISSUE TITLE
Attempt to use the 'ParsedPkcs12.chain' member for keystores without a key chain results in segfault

### ISSUE THREAD

**Issue by ancwrd1** [sfackler/rust-openssl#1721]
I have reproduced it by attempting to read the Java truststore file (PKCS12 with only certificates, no private key chains).

Code example:

```rust
let pkcs12 = Pkcs12::from_der(data)?;
let parsed = pkcs12.parse(password)?;
if let Some(chain) = parsed.chain {
    for cert in chain {
        println!("{:?}", cert.subject_name()); // <-- SEGFAULT
    }
}
```
The chain is returned as `Some` value and the X509 cert in there has a null internal pointer (checked it in the debugger).

**Comment by sfackler** [comment]
Do you have an example PKCS12 archive I can use to test?

**Comment by ancwrd1** [comment]
Sure, here is the (zipped) file which triggers this behavior. Password is 'changeit'.
[truststore.zip](https://github.com/sfackler/rust-openssl/files/9926795/truststore.zip)

**Comment by sfackler** [comment]
Hmm, I can't reproduce that crash:

```rust
   #[test]
    fn chain() {
        let der = include_bytes!("/Users/sfackler/Downloads/truststore.p12");
        let pkcs12 = Pkcs12::from_der(der).unwrap();
        let parsed = pkcs12.parse("changeit").unwrap();
        for cert in &parsed.chain.unwrap() {
            println!("{:?}", cert.subject_name());
        }
    }
```

```
running 1 test
[domainComponent = "lan", domainComponent = "home", domainComponent = "inforce", commonName = "inforce-W12K-CA"]
test pkcs12::test::chain ... ok
```

**Comment by ancwrd1** [comment]
Ah, I think it's not the `parsed.chain`, but `parsed.cert`.
Try `println!("{:?}", parsed.cert.subject_name());`

**Comment by sfackler** [comment]
Ok, yeah I see. We'll have to deprecate `ParsedPkcs12` and make a new version with an optional cert and private key.

**Comment by ancwrd1** [comment]
Thanks. FYI, the current (ugly) workaround is to check if private key has zero bits size, then the cert is assumed to not be valid.
