### ISSUE TITLE
Does bindgen features can works with openssl 3.0?

### ISSUE THREAD

**Issue by iamwwc** [sfackler/rust-openssl#1722]
I'm try keep `rust-openssl` bindgen feature on to build forked `openssl 3.0`(https://github.com/Tongsuo-Project/Tongsuo based on openssl v3). But in `openssl 3.0`, there no `EVP_seed_cbc`. rust-openssl not wrap it in `#[cfg(ossl300)]` which cause build failed

https://github.com/sfackler/rust-openssl/blob/9dae5d879f1ae452ac8370ed4dead86a6dfc0a3b/openssl/src/symm.rs#L303

![image](https://user-images.githubusercontent.com/24750337/199714558-a24f4966-44d0-410b-863f-f2b4b32e4d40.png)

**Comment by sfackler** [comment]
OpenSSL 3 does have SEED ciphersuites: https://github.com/openssl/openssl/blob/openssl-3.0.7/include/openssl/evp.h#L1128.

This library is designed to support OpenSSL, BoringSSL, and LibreSSL. If you're trying to use it with some other modified fork of OpenSSL, it may not compile.

**Comment by iamwwc** [comment]
Sorry, It's my fault. babassl is not full compatible with openssl 3.0, having some functions removed https://github.com/Tongsuo-Project/Tongsuo/pull/218
