### ISSUE TITLE
Test test_connect_with_srtp_ctx()  vs fn test_connect_with_srtp_ssl()

### ISSUE THREAD

**Issue by cameronelliott** [sfackler/rust-openssl#1731]
This is sort of an openssl newbie question, excuse me.

Regarding these two test funcs:
- test_connect_with_srtp_ctx()
- test_connect_with_srtp_ssl()

In comparing these two functions, they appear to basically do the same thing.
The _ssl() version checks that the SRTP profiles did get applied, but that doesn't seem too important.

*I am just trying to understand which model is better to start with*

Would the _ctx() model be better when your defaults apply to *all* ssl connections that will be created?

Would the _ssl() model be better when you might need to have different defaults on a per-SSL connection basis?

After reviewing the diffs of these two funcs, and https://www.openssl.org/docs/man1.1.1/man7/ssl.html,
that is my best understanding of the main difference between these two test examples.

Thank you for any clarification.
Also, thank you for creating rust-openssl, it's an impressive work.

**Comment by sfackler** [comment]
The usual approach is to configure the SslCtx except for things that you want to vary per connection which would happen on the Ssl object.
