### ISSUE TITLE
PKCS#12 Create without pkey or cert

### ISSUE THREAD

**Issue by jxtur** [sfackler/rust-openssl#1734]
The current bindings do not have support for building a PKCS#12 archive without a `pkey` or `cert` entry.

The OpenSSL docs state that either entry can be set `NULL` in order to do this.
https://www.openssl.org/docs/man1.0.2/man3/PKCS12_create.html

**Comment by Skepfyr** [comment]
This is very strongly related to #1721

**Comment by jxtur** [comment]
> This is very strongly related to #1721

Seems to be a separate issue, but related with respect to the treatment of `pkey` and `cert` in PKCS#12.

I've locally modified the `Pkcs12Builder::build` function to have the signature: 
```rust
    #[corresponds(PKCS12_create)]
    pub fn build<T>(
        self,
        password: &str,
        friendly_name: &str,
        pkey: Option<&PKeyRef<T>>,
        cert: Option<&X509Ref>,
    ) -> Result<Pkcs12, ErrorStack>
```
and loading a `ptr::null_mut()` when `cert` or `pkey` are `None`. This has allowed me to generate PKCS#12 archives that can loaded with the OpenSSL binary. However, due to #1721 the changes can't be properly validated using this library.
