### ISSUE TITLE
Release for LibreSSL 3.6.1 support?

### ISSUE THREAD

**Issue by oherrala** [sfackler/rust-openssl#1738]
The PR for adding support for LibreSSL 3.6.1 has been merged (https://github.com/sfackler/rust-openssl/pull/1720). A release would be needed to get this supported.

**Comment by sfackler** [comment]
Yep, I will cut one today

**Comment by sfackler** [comment]
Done!

**Comment by oherrala** [comment]
Thanks @sfackler! You are the best!
