### ISSUE TITLE
Switch Ssl Stream to new IO

### ISSUE THREAD

**Issue by seanmonstar** [sfackler/rust-openssl#174]
No rush, just wish to track as it blocks hyper from updating as well. 

(or I guess I could make newtype wrappers and unblock myself...)

**Comment by sfackler** [comment]
This is completed on a branch - I'll probably push a new release today or tomorrow but I want to do a tiny bit more testing to make sure it still works.

https://github.com/sfackler/rust-openssl/tree/breaks

**Comment by sfackler** [comment]
Released v0.5.0 which ports to new IO.
