### ISSUE TITLE
rust-openssl lack SSL_CTRL_CHAIN_CERT define to add certificate chain content

### ISSUE THREAD

**Issue by iamwwc** [sfackler/rust-openssl#1742]
Hi, I want to add extra certificate chain content to SslRef. But it seems rust-openssl don't have `SSL_CTRL_CHAIN_CERT`

https://github.com/openssl/openssl/blob/6ea44d07a7d0acb4af9eab15d9b4a76227f55f4e/include/openssl/ssl.h.in

**Comment by sfackler** [comment]
PRs welcome

**Comment by iamwwc** [comment]
please review this pr https://github.com/sfackler/rust-openssl/pull/1743
