### ISSUE TITLE
Deperecated functions not marked with OPENSSL_NO_DEPRECATED_3_0

### ISSUE THREAD

**Issue by amitma1** [sfackler/rust-openssl#1745]
here's a list of deprecated functions which are not marked as such by the cfg (openssl 3):

```
openssl::aes::aes_ige
openssl::bn::BigNumRef::pseudo_rand_range
openssl::bn::BigNumRef::pseudo_rand
openssl::bn::BigNumRef::is_prime
openssl::bn::BigNumRef::is_prime_fasttest
```

linking against openssl built with `no-deprecated` leads to linking errors

**Comment by wiktor-k** [comment]
I guess this ticket can be closed (as the PR has been merged).
