### ISSUE TITLE
Crate should document dependency on system package `libssl-dev`

### ISSUE THREAD

**Issue by bobhy** [sfackler/rust-openssl#1759]
Ref #1663, https://stackoverflow.com/questions/65553557/why-rust-is-failing-to-build-command-for-openssl-sys-v0-9-60-even-after-local-in and probably many others.

System package `openssl` is installed by default on lots of platforms, but usually developer package `libssl-dev` is not.  It would be good for the readme to document installing the dev package!

**Comment by sfackler** [comment]
Like this documentation? https://docs.rs/openssl/latest/openssl/#automatic
