### ISSUE TITLE
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: TryFromIntError(())'

### ISSUE THREAD

**Issue by hzqd** [sfackler/rust-openssl#1765]
Hello, I'm using openssl to encrypt a huge file (at least 3 GB)

Getting panic message:

`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: TryFromIntError(())', C:\Users\aoko\.cargo\registry\src\github.com-xxx\openssl-0.10.45\src\cipher_ctx.rs:565:50`

Any suggestion for me?

**Comment by sfackler** [comment]
You can't encrypt more than 2GB per call to cipher_update. You'll need to split it up into multiple chunks.

**Comment by Skepfyr** [comment]
@sfackler This seems a bit surprising, is there are reason that function doesn't just loop over the input in chunks? I expect most Rust users would expect it to work for any usizes. Alternatively we could document this limit, there's no indication in the current docs this method might panic.
