### ISSUE TITLE
Building a static binary for armv6 or lower causes a dynamic link to libatomic.

### ISSUE THREAD

**Issue by BlackDex** [sfackler/rust-openssl#1779]
Hello there,

I'm running into an issue building a static library using a custom static build OpenSSL v3.
When the `CARGO_CFG_TARGET_POINTER_WIDTH` is 32, it will always link dynamically to libatomic.

This causes my static musl builds to fail, because it suddenly has a dynamic link to libatomic.
For my builds i add a `RUSTFLAGS` which contain the path directly to this library, for example `RUSTFLAGS='-Clink-arg=/usr/local/musl/arm-unknown-linux-musleabi/lib/libatomic.a -Clink-arg=-s'`

I didn't need this for OpenSSL before, but more because of MiMalloc which also links to libatomic under water.

Is there some way that you can add some check or an extra `env` check to **not** dynamically link `libatomic` in some cases?
That would solve my compile issue.

**Comment by sfackler** [comment]
This may not be necessary anymore - the associated OpenSSL issue has been closed: https://github.com/sfackler/rust-openssl/blob/8621407a3268071e30312dfe40098b574554ea1f/openssl-sys/build/main.rs#L125-L133

**Comment by BlackDex** [comment]
Ah! Well i can confirm that commenting that part out on a armv6 cross build seems to work just fine, even without the atomic link.

I still need to add the link for MiMalloc though, but that is out of the scope of this crate.
