### ISSUE TITLE
ICE

### ISSUE THREAD

**Issue by daogangtang** [sfackler/rust-openssl#178]
Compiling openssl-sys v0.5.1
/home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sync/mutex.rs:177:37: 180:2 error: internal compiler error: debuginfo: Could not find scope info for node NodeExpr(Expr { id: 4548, node: ExprStruct(Path { span: Span { lo: BytePos(4576204), hi: BytePos(4576215), expn_id: ExpnId(4294967295) }, global: false, segments: [PathSegment { identifier: StaticMutex#0, parameters: AngleBracketedParameters(AngleBracketedParameterData { lifetimes: [], types: [], bindings: [] }) }] }, [Field { ident: Spanned { node: lock#0, span: Span { lo: BytePos(1770102), hi: BytePos(1770106), expn_id: ExpnId(4294967295) } }, expr: Expr { id: 4549, node: ExprPath(None, Path { span: Span { lo: BytePos(4576228), hi: BytePos(4576243), expn_id: ExpnId(4294967295) }, global: false, segments: [PathSegment { identifier: sys#0, parameters: AngleBracketedParameters(AngleBracketedParameterData { lifetimes: [], types: [], bindings: [] }) }, PathSegment { identifier: MUTEX_INIT#0, parameters: AngleBracketedParameters(AngleBracketedParameterData { lifetimes: [], types: [], bindings: [] }) }] }), span: Span { lo: BytePos(4576228), hi: BytePos(4576243), expn_id: ExpnId(4294967295) } }, span: Span { lo: BytePos(4576222), hi: BytePos(4576243), expn_id: ExpnId(4294967295) } }, Field { ident: Spanned { node: poison#0, span: Span { lo: BytePos(1770129), hi: BytePos(1770135), expn_id: ExpnId(4294967295) } }, expr: Expr { id: 4550, node: ExprPath(None, Path { span: Span { lo: BytePos(4576257), hi: BytePos(4576274), expn_id: ExpnId(4294967295) }, global: false, segments: [PathSegment { identifier: poison#0, parameters: AngleBracketedParameters(AngleBracketedParameterData { lifetimes: [], types: [], bindings: [] }) }, PathSegment { identifier: FLAG_INIT#0, parameters: AngleBracketedParameters(AngleBracketedParameterData { lifetimes: [], types: [], bindings: [] }) }] }), span: Span { lo: BytePos(4576257), hi: BytePos(4576274), expn_id: ExpnId(4294967295) } }, span: Span { lo: BytePos(4576249), hi: BytePos(4576274), expn_id: ExpnId(4294967295) } }], None), span: Span { lo: BytePos(4576204), hi: BytePos(4576277), expn_id: ExpnId(4294967295) } })
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: run with `RUST_BACKTRACE=1` for a backtrace
thread 'rustc' panicked at 'Box<Any>', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/diagnostic.rs:129

mike@mike-T410s:~/workspace/bamboors$ rustc -V
rustc 1.0.0-nightly (3b3bb0e68 2015-03-04) (built 2015-03-05)

**Comment by sfackler** [comment]
You're running into https://github.com/rust-lang/rust/issues/23053. You can disable debuginfo as a work around in the short term.

**Comment by sfackler** [comment]
This is fixed in the latest nightly.
