### ISSUE TITLE
Build breaks in openssl-sys 0.9.79 without any error messages

### ISSUE THREAD

**Issue by yurivict** [sfackler/rust-openssl#1781]
[log](https://people.freebsd.org/~yuri/qdrant-0.11.6.log)

FreeBSD 13.1

**Comment by Skepfyr** [comment]
Are you sure that's your issue? Further up the output you posted there's this:
> [librocksdb-sys 0.8.0+7.4.4] thread 'main' panicked at 'Unable to find libclang: "couldn't find any valid shared libraries matching: ['libclang.so', 'libclang.so.*'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', /wrkdirs/usr/ports/databases/qdrant/work/qdrant-0.11.6/cargo-crates/bindgen-0.60.1/src/lib.rs:2172:31
[librocksdb-sys 0.8.0+7.4.4] stack backtrace:
[librocksdb-sys 0.8.0+7.4.4]    0: rust_begin_unwind
[librocksdb-sys 0.8.0+7.4.4]    1: core::panicking::panic_fmt
[librocksdb-sys 0.8.0+7.4.4]    2: core::result::unwrap_failed
[librocksdb-sys 0.8.0+7.4.4]    3: core::result::Result<T,E>::expect
[librocksdb-sys 0.8.0+7.4.4]    4: core::ops::function::FnOnce::call_once
[librocksdb-sys 0.8.0+7.4.4]    5: lazy_static::lazy::Lazy<T>::get::{{closure}}
[librocksdb-sys 0.8.0+7.4.4]    6: std::sync::once::Once::call_once::{{closure}}
[librocksdb-sys 0.8.0+7.4.4]    7: std::sys_common::once::futex::Once::call
[librocksdb-sys 0.8.0+7.4.4]    8: std::sync::once::Once::call_once
[librocksdb-sys 0.8.0+7.4.4]    9: <bindgen::ensure_libclang_is_loaded::LIBCLANG as core::ops::deref::Deref>::deref
[librocksdb-sys 0.8.0+7.4.4]   10: bindgen::ensure_libclang_is_loaded
[librocksdb-sys 0.8.0+7.4.4]   11: bindgen::Bindings::generate
[librocksdb-sys 0.8.0+7.4.4]   12: bindgen::Builder::generate
[librocksdb-sys 0.8.0+7.4.4]   13: build_script_build::bindgen_rocksdb
[librocksdb-sys 0.8.0+7.4.4]   14: build_script_build::main
[librocksdb-sys 0.8.0+7.4.4]   15: core::ops::function::FnOnce::call_once
[librocksdb-sys 0.8.0+7.4.4] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: failed to run custom build command for `librocksdb-sys v0.8.0+7.4.4`
> 
> Caused by:
  process didn't exit successfully: `/wrkdirs/usr/ports/databases/qdrant/work/target/release/build/librocksdb-sys-e4764593fb2bacf7/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'Unable to find libclang: "couldn't find any valid shared libraries matching: ['libclang.so', 'libclang.so.*'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', /wrkdirs/usr/ports/databases/qdrant/work/qdrant-0.11.6/cargo-crates/bindgen-0.60.1/src/lib.rs:2172:31
  stack backtrace:
     0: rust_begin_unwind
     1: core::panicking::panic_fmt
     2: core::result::unwrap_failed
     3: core::result::Result<T,E>::expect
     4: core::ops::function::FnOnce::call_once
     5: lazy_static::lazy::Lazy<T>::get::{{closure}}
     6: std::sync::once::Once::call_once::{{closure}}
     7: std::sys_common::once::futex::Once::call
     8: std::sync::once::Once::call_once
     9: <bindgen::ensure_libclang_is_loaded::LIBCLANG as core::ops::deref::Deref>::deref
    10: bindgen::ensure_libclang_is_loaded
    11: bindgen::Bindings::generate
    12: bindgen::Builder::generate
    13: build_script_build::bindgen_rocksdb
    14: build_script_build::main
    15: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...

**Comment by yurivict** [comment]
You are right.
Sorry, I didn't look too well.
