### ISSUE TITLE
Issues with current implementation of `X509_PURPOSE` constants

### ISSUE THREAD

**Issue by bkstein** [sfackler/rust-openssl#1782]
I'm in the process of updating my PR #1598 branch and hit a problem with the implementation of `X509_PURPOSE_xxx` constants (https://github.com/sfackler/rust-openssl/blob/2c0c391f8abea99abdf016175d5d7c257891541d/openssl/src/x509/verify.rs#L197).
First, these are currently implemented as `bitflags!`, but the way I see it, these constants are no bitflags. It compiles, but people might try to `|` the flags.
Second, there is an OpenSSL version restriction (`#[cfg(ossl102)]`) on the constants, but these constants already existed in 0.9.8 (and probably even earlier, but that's the oldest version I have checked out).
I wouldn't complain, but I have also implemented `X509_PURPOSE_xxx` in PR #1598 and now I have a conflict: shall I keep the existing version or shall I replace it with mine?

**Comment by sfackler** [comment]
Yeah, those definitely shouldn't be bitflags. Fortunately, there hasn't been a release with that type added yet, so we can just change it.

**Comment by bkstein** [comment]
I will make a PR for this. I also think, it is better to move the `X509_PURPOSE` definitions from x509/verify.rs to x509/mod.rs, as it is also used by store.rs (`X509StoreBuilderRef::set_purpose()`).

**Comment by bkstein** [comment]
Should be fixed with #1788.
