### ISSUE TITLE
Enforce static link by setting env OPENSSL_STATIC failed

### ISSUE THREAD

**Issue by sammyne** [sfackler/rust-openssl#1792]
## Problem
It seems that rust-openssl cannot be statically linked with env `OPENSSL_STATIC` set in [.cargo/config.toml](.cargo/config.toml) under project root.

## Prerequisite
- openssl: 0.10.42

For reproduction, a github repo has been made as https://github.com/sammyne/rust-openssl-cannot-link-statically, and steps for reproductions go as follow.

### 1. Start the container as building env
```bash
docker run -it --rm     \
  -v $PWD:/workspace    \
  -w /workspace         \
  rust:1.65.0-bullseye  \
  bash
```

### 2. Build the project within the started container
```bash
cargo build
```

### 3. Check linkage with ldd
```bash
ldd target/debug/rust-openssl-cannot-link-statically
```

Got output log as

```bash
        linux-vdso.so.1 (0x00007ffc00d2c000)
        libssl.so.1.1 => /usr/lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007ff37e652000)
        libcrypto.so.1.1 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007ff37e35e000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007ff37e358000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007ff37e33e000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ff37e31c000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff37e147000)
        /lib64/ld-linux-x86-64.so.2 (0x00007ff37e745000)
```

where libssl.a and libcrypto.a should be used instead of libssl.so.1.1 and libcrypto.so.1.1.

Really appreciate if someone could help me out~

**Comment by sfackler** [comment]
It looks like you are running into https://github.com/rust-lang/pkg-config-rs/issues/102.

**Comment by juliusl** [comment]
For anyone else that might've arrived here,

When you specify `OPENSSL_STATIC`, you need to include `OPENSSL_LIB_DIR` and `OPENSSL_INCLUDE_DIR` if you want to avoid the pkg-config behavior. When you specify `OPENSSL_LIB_DIR` you need to give it the directory with the `*.a` files. Other search results may say to use `/usr/lib` or `/usr/lib64` but for example on ubuntu 22.04 it should be `/usr/lib/x86_64-linux-gnu`.

For example,

`OPENSSL_STATIC=1 OPENSSL_LIB_DIR=/usr/lib/x86_64-linux-gnu OPENSSL_INCLUDE_DIR=/usr/include/openssl cargo build`

Note that this will likely be different if you're cross-compiling from the same image.
