### ISSUE TITLE
rust-lld: error: unable to find library -lssl and -lcrypto

### ISSUE THREAD

**Issue by gc-victor** [sfackler/rust-openssl#1794]
Hi, any idea what the problem could be?

The project is using attohttpc as a dependency, but it looks like the error is from this library. 

```
$ cargo build --target wasm32-wasi --release

error: linking with `rust-lld` failed: exit status: 1
...
= note: 
rust-lld: error: unable to find library -lssl
rust-lld: error: unable to find library -lcrypto
```

.cargo.toml
```
OPENSSL_DIR = "/usr"
OPENSSL_LIB_DIR ="/usr/lib"
OPENSSL_INCLUDE_DIR ="/usr/include"
```

I have checked: `pkg-config --libs --cflags openssl` and it prints `-lssl -lcrypto`

**Comment by sfackler** [comment]
Do you have a copy of OpenSSL built for WASM in /usr/lib?

**Comment by gc-victor** [comment]
> Do you have a copy of OpenSSL built for WASM in /usr/lib?

No, I don't have it. I guess that I'm doing it wrong

**Comment by sfackler** [comment]
You're going to need that to be able to use this library. I'm not sure what the status of building OpenSSL for WASM is - see #1016.

**Comment by gc-victor** [comment]
Thanks for the support!
