### ISSUE TITLE
Build fails on Windows 10

### ISSUE THREAD

**Issue by bohdaq** [sfackler/rust-openssl#1800]
I'm trying to [build a project](https://github.com/bohdaq/rust-tls-server) on a new Windows 10 install

> cargo build --release

and getting the error:

![cargo_build_log](https://user-images.githubusercontent.com/1307140/213899871-695c4b08-ba36-4958-826b-94a406a6ea46.png)

### Windows version:
Windows 10 Home
22H2
‎03.‎01.‎2023
19045.2486
Windows Feature Experience Pack 120.2212.4190.0

### Hardware:
DESKTOP-3OTAJNQ
Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz   3.20 GHz
16,0 GB
597FEB25-3D31-4280-BB8D-545F523EF20D
00326-10000-00000-AA022

### Strawberry Perl:
Summary of my perl5 (revision 5 version 32 subversion 1) configuration:
   
  Platform:
    osname=MSWin32
    osvers=10.0.19042.746
    archname=MSWin32-x64-multi-thread
    uname='Win32 strawberry-perl 5.32.1.1 #1 Sun Jan 24 15:00:15 2021 x64'
    config_args='undef'
    hint=recommended
    useposix=true
    d_sigaction=undef
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=undef
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='gcc'
    ccflags =' -DWIN32 -DWIN64 -D__USE_MINGW_ANSI_STDIO -DPERL_TEXTMODE_SCRIPTS -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DUSE_PERLIO -fwrapv -fno-strict-aliasing -mms-bitfields'
    optimize='-s -O2'
    cppflags='-DWIN32'
    ccversion=''
    gccversion='8.3.0'
    gccosandvers=''
    intsize=4
    longsize=4
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='long long'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='g++'
    ldflags ='-s -L"C:\Users\bohda\STRAWB~1\perl\lib\CORE" -L"C:\Users\bohda\STRAWB~1\c\lib"'
    libpth=C:\Users\bohda\STRAWB~1\c\lib C:\Users\bohda\STRAWB~1\c\x86_64-w64-mingw32\lib C:\Users\bohda\STRAWB~1\c\lib\gcc\x86_64-w64-mingw32\8.3.0
    libs= -lmoldname -lkernel32 -luser32 -lgdi32 -lwinspool -lcomdlg32 -ladvapi32 -lshell32 -lole32 -loleaut32 -lnetapi32 -luuid -lws2_32 -lmpr -lwinmm -lversion -lodbc32 -lodbccp32 -lcomctl32
    perllibs= -lmoldname -lkernel32 -luser32 -lgdi32 -lwinspool -lcomdlg32 -ladvapi32 -lshell32 -lole32 -loleaut32 -lnetapi32 -luuid -lws2_32 -lmpr -lwinmm -lversion -lodbc32 -lodbccp32 -lcomctl32
    libc=
    so=dll
    useshrplib=true
    libperl=libperl532.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_win32.xs
    dlext=xs.dll
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags='-mdll -s -L"C:\Users\bohda\STRAWB~1\perl\lib\CORE" -L"C:\Users\bohda\STRAWB~1\c\lib"'

Characteristics of this binary (from libperl): 
  Compile-time options:
    HAS_TIMES
    HAVE_INTERP_INTERN
    MULTIPLICITY
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_IMPLICIT_CONTEXT
    PERL_IMPLICIT_SYS
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    USE_64_BIT_INT
    USE_ITHREADS
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
  Built under MSWin32
  Compiled at Jan 24 2021 15:05:42
  %ENV:
    PERL="C:\Strawberry\perl\bin"
  @INC:
    C:/Users/bohda/Strawberry/perl/site/lib
    C:/Users/bohda/Strawberry/perl/vendor/lib
    C:/Users/bohda/Strawberry/perl/lib

My user has permissions to Strawberry folder and project folder as well.

I have older Windows install and build works fine there. Also I successfully built project for macOS and Linux.

**Comment by bohdaq** [comment]
Using `rustc 1.66.1 (90743e729 2023-01-10)`

**Comment by sfackler** [comment]
The build failure's coming from the openssl-src crate, so probably best to file this with that project.

**Comment by bohdaq** [comment]
ok

**Comment by bohdaq** [comment]
opened new [issue here ](https://github.com/alexcrichton/openssl-src-rs/issues/176)
