### ISSUE TITLE
Why do these two similar `openssl::{cipher,symm}::Cipher` exist?

### ISSUE THREAD

**Issue by arniu** [sfackler/rust-openssl#1824]

**Comment by sfackler** [comment]
The cipher module is a new API to expose the same kinds of methods as symm but in a more direct way.

**Comment by arniu** [comment]
@sfackler The methods of [`openssl::cipher::Cipher`](https://docs.rs/openssl/0.10.45/openssl/cipher/struct.Cipher.html) return [`CipherRef`](https://docs.rs/openssl/0.10.45/openssl/cipher/struct.CipherRef.html)s, while `openssl::symm::{decrypt,encrypt}` requires a `Cipher`, which can not be created from a `CipherRef`.

**Comment by sfackler** [comment]
The CipherRef types works with `CipherCtx`: https://docs.rs/openssl/latest/openssl/cipher_ctx/struct.CipherCtx.html
