### ISSUE TITLE
Cargo-generate does not build/install, caused by openssl-sys v0.9.80.

### ISSUE THREAD

**Issue by FMFigueroa** [sfackler/rust-openssl#1826]
**Describe the bug**
cargo-generate does not build/install, caused by `openssl v0.9.80`.

**make sure you**
 - I'm on the latest rust version rustup update
 - I'm on the latest cargo-generate version cargo install cargo-generate
 - In case you have an own .gitconfig, provide all sections that contains one of: insteadOf, url
 
**To Reproduce**

 1. `cargo install cargo-generate`
 2. See error

**Expected behavior**
`cargo-generate` should install

**Desktop (please complete the following information):**
- OS: Windows 10
- Build tools: msvc
- Shell: N/A
- `rustc --version`: rustc 1.67.1 (d5a82bbd2 2023-02-07)
- `cargo generate --version`: trying to install 0.18.0
Additional context

```
error: failed to run custom build command for `openssl-sys v0.9.80`

Caused by:
  process didn't exit successfully: `C:\Users\admin\AppData\Local\Temp\cargo-installvQL0U3\release\build\openssl-sys-b10c3ade16499e19\build-script-main` (exit code: 101)
  --- stdout
  cargo:rustc-cfg=const_fn
  cargo:rustc-cfg=openssl
  cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_MSVC_OPENSSL_NO_VENDOR
  X86_64_PC_WINDOWS_MSVC_OPENSSL_NO_VENDOR unset
  cargo:rerun-if-env-changed=OPENSSL_NO_VENDOR
  OPENSSL_NO_VENDOR unset
  running "perl" "./Configure" "--prefix=C:\\Users\\admin\\AppData\\Local\\Temp\\cargo-installvQL0U3\\release\\build\\openssl-sys-4a38ccc4d84b043b\\out\\openssl-build\\install" "--openssldir=SYS$MANAGER:[OPENSSL]" "no-dso" "no-shared" "no-ssl3" "no-unit-test" "no-comp" "no-zlib" "no-zlib-dynamic" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "no-engine" "no-asm" "VC-WIN64A"

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: NotFound, message: "program not found" }', C:\Users\admin\.cargo\registry\src\github.com-1ecc6299db9ec823\openssl-src-111.25.0+1.1.1t\src\lib.rs:497:39
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `cargo-generate v0.18.0`, intermediate artifacts can be found at `C:\Users\admin\AppData\Local\Temp\cargo-installvQL0U3`
```

**Comment by Skepfyr** [comment]
`cargo-generate` depends on the vendored version of OpenSSL by default (you can disable this in the features if you'd like to use your local version of OpenSSL). This means that it uses the openssl-src crate to build OpenSSL, I believe the issue is that you don't have the dependencies required to build the library, specifically perl. The dependencies are documented here: https://docs.rs/openssl/latest/openssl/#vendored.
> The build process requires a C compiler, perl (and perl-core), and make.

**Comment by FMFigueroa** [comment]
Pude hacerlo instalando https://strawberryperl.com/

**Comment by Araxeus** [comment]
```
 thread 'main' panicked at 'called `Result::unwrap()` on an `Err`
```
@Skepfyr Maybe the error handling could be better here? 
It could specifically say that PERL installation was not found
