### ISSUE TITLE
openssl-sys fails to call bindgen correctly

### ISSUE THREAD

**Issue by TheDan64** [sfackler/rust-openssl#1869]
```rust
error[E0599]: no method named `includes` found for mutable reference `&mut Build` in the current scope
   --> /home/dkolsoi/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.84/build/run_bindgen.rs:192:10
    |
192 |         .includes(include_dirs)
    |          ^^^^^^^^ help: there is a method with a similar name: `include`
```

On Ubuntu, with openssl v0.10.49 and openssl-sys v0.9.84

**Comment by sfackler** [comment]
That method definitely exists: https://docs.rs/cc/latest/cc/struct.Build.html#method.includes. What version of `cc` do you have in your dependency graph?

**Comment by TheDan64** [comment]
`cc v1.0.52`

**Comment by TheDan64** [comment]
Updating cc worked, thanks! :)

**Comment by rickyars** [comment]
> Updating cc worked, thanks! :)

can you tell me how you did that? new to rust and this problem is driving me CRAZY
