### ISSUE TITLE
Support TLS Application-Layer Protocol Negotiation (ALPN)

### ISSUE THREAD

**Issue by mlalic** [sfackler/rust-openssl#188]
[ALPN](https://tools.ietf.org/html/rfc7301) is supported by OpenSSL starting from [version 1.0.2](https://www.openssl.org/news/openssl-1.0.2-notes.html). As ALPN is, at least [according to the spec](https://http2.github.io/http2-spec/#discover-https), the only valid way to initiate `https` connections in HTTP/2, it'd be useful to support it.

**Comment by mlalic** [comment]
I'd gladly add this myself, but first a few questions:

- Is it a problem that OpenSSL supports it only since 1.0.2 -- a fairly recent version, not yet available on stable channels of most Linux distros? I'd say hiding it behind a  feature and documenting that the feature can only be used when linking against OpenSSL version >= 1.0.2 should be enough...
- How should ALPN coexist with NPN? The two extensions serve the exact same purpose and NPN is likely to be phased out in the future in favor of ALPN. However, I believe it makes sense to allow clients to explicitly choose which extension(s) they'd like to use for now. Therefore, my suggestion here would be to add a new set of methods analogous to the ones relating to NPN. This way the usage of the two extensions would in no way be related (and they could both be used in the same time or just one of them, depending on what the client prefers).

**Comment by sfackler** [comment]
Yep, adding it behind a feature gate should be fine. I have been meaning to rearchitect the current feature gates so they correspond to openssl versions instead of npn, tlsv1_1 etc which should make it a bit more understandable/easy to deal with.

I agree that supporting NPN and ALPN together's the best route forward.
