### ISSUE TITLE
Why I cannot choose which version of OpenSSL is vendored through feature flags

### ISSUE THREAD

**Issue by CGQAQ** [sfackler/rust-openssl#1903]
Why I cannot choose which version of OpenSSL is vendored through feature flags, instread, it's hard coded as 1.1.1

https://github.com/sfackler/rust-openssl/blob/f9964efe2170f559c4795baadc588151a93bbbb2/openssl-sys/Cargo.toml#L28

**Comment by CGQAQ** [comment]
> Because the vendored feature exists for use cases where you just want a copy of OpenSSL that works. As the documentation states, the specific version is not specified, other than being reasonably modern: https://docs.rs/openssl/latest/openssl/#vendored

So why not give the user a choice between latest 1.x AND latest 3.x

**Comment by CGQAQ** [comment]
> > Because the vendored feature exists for use cases where you just want a copy of OpenSSL that works.
> 
> If the user has specific preferences they should build it themselves.

But isn't the point of the openssl-src is for convenience of build, instead of clone the source myself and use something like autotools to build manually? isn't it?

**Comment by sfackler** [comment]
The point of openssl-src is to be a Rust crate that can compile OpenSSL from source.

**Comment by CGQAQ** [comment]
So the #1904 is consider rejected, it is so upset I have no choice but use my own fork for vendoring 3.x conveniently
