### ISSUE TITLE
How can i convert a pem/der cert into a p7b format

### ISSUE THREAD

**Issue by pkking** [sfackler/rust-openssl#1913]
In [openssl crl2pkcs7](https://github.com/openssl/openssl/blob/master/apps/crl2pkcs7.c), we can convert a PEM format cert into a p7b format, im curious is there any way using `rust-openssl`?

**Comment by sfackler** [comment]
https://docs.rs/openssl/latest/openssl/pkcs7/struct.Pkcs7.html
