### ISSUE TITLE
MSRV 1.48 compatibility problem

### ISSUE THREAD

**Issue by Tarnum-tst** [sfackler/rust-openssl#1914]
MSRV 1.48 is the minimum requirement for compiling current pyca cryptography release (40.0.2)
In file openssl/src/x509/mod.rs line 1708
```
            (-1 | -2, _) => Ok(None),
```
compiler complains: '|' - unstable feature
I am noob in Rust but probably replacing with
```
            (-1, _) => Ok(None),
            (-2, _) => Ok(None),
```
should help to restore compatibility,
Lines 1711-1712
```
            (0 | 1, None) => Err(ErrorStack::get()),
            (c_int::MIN..=-2 | 2.., _) => panic!("OpenSSL should only return -2, -1, 0, or 1 for an extension's criticality but it returned {}", critical),
```
Possible replacement
```
            (0, None) => Err(ErrorStack::get()),
            (1, None) => Err(ErrorStack::get()),
            (c_int::MIN..=-2, _) => panic!("OpenSSL should only return -2, -1, 0, or 1 for an extension's criticality but it returned {}", critical),
            (_, _) => panic!("OpenSSL should only return -2, -1, 0, or 1 for an extension's criticality but it returned {}", critical),
```
Thanks in advance!

**Comment by alex** [comment]
👋 can you explain a bit what you're trying to do? Cryptography 40.0 contains a pinned version of rust-openssl that supports 1.48. Cryptography main has raised its MSRV to 1.56, and correspondingly is pinned to a newer version of rust-openssl.

**Comment by Tarnum-tst** [comment]
@alex 
I have decided to update few crates to current versions (libc, openssl, openssl-sys) in Cargo.lock/Cargo.toml of cryptography 40.0.2 sources. :-)

**Comment by Tarnum-tst** [comment]
No particular reason just wanted to test my own build. :-)

**Comment by alex** [comment]
In any event, unfortunately it's not practical to support MSRV of 1.48 anymore. See https://github.com/sfackler/rust-openssl/pull/1808 for more details.

**Comment by Tarnum-tst** [comment]
Ok.
