### ISSUE TITLE
Make parameter certs optional in pkcs7.sign method?

### ISSUE THREAD

**Issue by TommyLike** [sfackler/rust-openssl#1918]
Currently the sign method is defined as follow:
```rust
    /// Creates and returns a PKCS#7 `signedData` structure.
    ///
    /// `signcert` is the certificate to sign with, `pkey` is the corresponding
    /// private key. `certs` is an optional additional set of certificates to
    /// include in the PKCS#7 structure (for example any intermediate CAs in the
    /// chain).
    #[corresponds(PKCS7_sign)]
    pub fn sign<PT>(
        signcert: &X509Ref,
        pkey: &PKeyRef<PT>,
        certs: &StackRef<X509>,
        input: &[u8],
        flags: Pkcs7Flags,
    ) -> Result<Pkcs7, ErrorStack>
```
Considering the certs are optional can we make it optional in parameter? such as x509 sign(https://docs.rs/openssl/latest/openssl/cms/struct.CmsContentInfo.html#method.sign)

**Comment by sfackler** [comment]
It would have been safe to make the `certs` argument an `Option<&StackRef<X509>>` but that would be a breaking change at this point.

**Comment by TommyLike** [comment]
> It would have been safe to make the `certs` argument an `Option<&StackRef<X509>>` but that would be a breaking change at this point.

thanks, will construct the stack instead.
