### ISSUE TITLE
Implementation of 3.1 or 3.0 version

### ISSUE THREAD

**Issue by 4skl** [sfackler/rust-openssl#1931]
As started by the official OpenSSL website, version 1.0.1, witch is the reported OpenSSL version for witch the api is made are now deprecied so is it an objective to adapt the library to OpenSSL 3.0 or 3.1 ?
> The previous LTS version (the 1.1.1 series) is also available and is supported until 11th September 2023. All older versions (including 1.1.0, 1.0.2, 1.0.0 and 0.9.8) are now out of support and should not be used. Users of these older versions are encouraged to upgrade to 3.1 or 3.0 as soon as possible. Extended support for 1.0.2 to gain access to security fixes for that version is available.

**Comment by sfackler** [comment]
This crate already supports OpenSSL 3.x.x.
