### ISSUE TITLE
Unable to build project on macOS.

### ISSUE THREAD

**Issue by M0hammedImran** [sfackler/rust-openssl#1932]
OpenSSL is not a direct dependency.

https://github.com/sfackler/rust-openssl/blob/c7e89d9b65e16322a429cba0f63ddebf7271488b/openssl-sys/build/run_bindgen.rs#LL142C32-L142C32

![Screenshot 2023-05-23 at 11 12 07](https://github.com/sfackler/rust-openssl/assets/52968617/1c764cd0-ed23-419b-9298-c5b0670a7dec)

**Comment by sfackler** [comment]
It looks like you've somehow ended up with a version of `cc` that is over 3 years old. Run `cargo update`.
