### ISSUE TITLE
error: Failed to find OpenSSL development headers on Ubuntu

### ISSUE THREAD

**Issue by knnmran** [sfackler/rust-openssl#1960]
getting an error when building on Ubuntu 22.04.2 LTS 

notes:
- adding `sudo apt-get install pkg-config libssl-dev` did not help
- please refer to the full error log and script here: https://github.com/psibi/rucredstash/pull/23

 --- stderr
  thread 'main' panicked at '
  Header expansion error:
  Error { kind: ToolExecError, message: "Command \"cc\" \"-O0\" \"-ffunction-sections\" \"-fdata-sections\" \"-fPIC\" \"-g\" \"-fno-omit-frame-pointer\" \"-m64\" \"-I\" \"/usr/include\" \"-Wall\" \"-Wextra\" \"-E\" \"build/expando.c\" with args \"cc\" did not execute successfully (status code exit status: 1)." }

  Failed to find OpenSSL development headers.

  You can try fixing this setting the `OPENSSL_DIR` environment variable
  pointing to your OpenSSL installation or installing OpenSSL headers package
  specific to your distribution:

      # On Ubuntu
      sudo apt-get install libssl-dev
      # On Arch Linux
      sudo pacman -S openssl
      # On Fedora
      sudo dnf install openssl-devel

  See rust-openssl README for more information:

      https://github.com/sfackler/rust-openssl#linux
  ', /home/vsts/.cargo/registry/src/index.crates.io-6f17d22bba15001f/openssl-sys-0.9.60/build/main.rs:141:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

**Comment by sfackler** [comment]
You are using a version of openssl-sys that is 2 years out of date.

**Comment by knnmran** [comment]
i believe openssl-sys is pulled as a part of rusoto_core = "0.48.0". should i open an issue with them to update it to the latest version?

not sure how to proceed here?!

**Comment by sfackler** [comment]
`cargo update`

**Comment by knnmran** [comment]
build was successful!

@sfackler, thank you for another learning experience.
