### ISSUE TITLE
failed to run custom build command for `openssl-sys v0.9.88`

### ISSUE THREAD

**Issue by kalinavladd** [sfackler/rust-openssl#1961]
The following warnings were emitted during compilation:

warning: build/expando.c:1:10: fatal error: 'openssl/opensslv.h' file not found
warning: #include <openssl/opensslv.h>
warning:          ^~~~~~~~~~~~~~~~~~~~
warning: 1 error generated.

error: failed to run custom build command for `openssl-sys v0.9.88`

Caused by:
-- stdout
  cargo:rerun-if-env-changed=X86_64_APPLE_DARWIN_OPENSSL_LIB_DIR
  X86_64_APPLE_DARWIN_OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
  OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=X86_64_APPLE_DARWIN_OPENSSL_INCLUDE_DIR
  X86_64_APPLE_DARWIN_OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
  OPENSSL_INCLUDE_DIR = /usr/local/opt/openssl@3
  cargo:rerun-if-env-changed=X86_64_APPLE_DARWIN_OPENSSL_DIR
  X86_64_APPLE_DARWIN_OPENSSL_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_DIR
  OPENSSL_DIR = /usr/local/openssl
  cargo:include=/usr/local/opt/openssl@3
  cargo:rerun-if-changed=build/expando.c
  OPT_LEVEL = Some("0")
  TARGET = Some("x86_64-apple-darwin")
  HOST = Some("x86_64-apple-darwin")
  cargo:rerun-if-env-changed=CC_x86_64-apple-darwin
  CC_x86_64-apple-darwin = None
  cargo:rerun-if-env-changed=CC_x86_64_apple_darwin
  CC_x86_64_apple_darwin = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64-apple-darwin
  CFLAGS_x86_64-apple-darwin = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64_apple_darwin
  CFLAGS_x86_64_apple_darwin = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  CARGO_CFG_TARGET_FEATURE = Some("cmpxchg16b,fxsr,sse,sse2,sse3,ssse3")
  running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-2" "-fno-omit-frame-pointer" "-m64" "-arch" "x86_64" "-I" "/usr/local/opt/openssl@3" "-Wall" "-Wextra" "-E" "build/expando.c"
  cargo:warning=build/expando.c:1:10: fatal error: 'openssl/opensslv.h' file not found
  cargo:warning=#include <openssl/opensslv.h>
  cargo:warning=         ^~~~~~~~~~~~~~~~~~~~
  cargo:warning=1 error generated.
  exit status: 1

  --- stderr
  thread 'main' panicked at '
  Header expansion error:
  Error { kind: ToolExecError, message: "Command \"cc\" \"-O0\" \"-ffunction-sections\" \"-fdata-sections\" \"-fPIC\" \"-gdwarf-2\" \"-fno-omit-frame-pointer\" \"-m64\" \"-arch\" \"x86_64\" \"-I\" \"/usr/local/opt/openssl@3\" \"-Wall\" \"-Wextra\" \"-E\" \"build/expando.c\" with args \"cc\" did not execute successfully (status code exit status: 1)." }

  Failed to find OpenSSL development headers.

  You can try fixing this setting the `OPENSSL_DIR` environment variable
  pointing to your OpenSSL installation or installing OpenSSL headers package
  specific to your distribution:

      # On Ubuntu
      sudo apt-get install libssl-dev
      # On Arch Linux
      sudo pacman -S openssl
      # On Fedora
      sudo dnf install openssl-devel
      # On Alpine Linux
      apk add openssl-dev

  See rust-openssl documentation for more information:

      https://docs.rs/openssl
  ', /Users/a1/.cargo/registry/src/index.crates.io-6f17d22bba15001f/openssl-sys-0.9.88/build/main.rs:171:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by sfackler** [comment]
This is not correct:

```
OPENSSL_INCLUDE_DIR = /usr/local/opt/openssl@3
OPENSSL_DIR = /usr/local/openssl
```

OPENSSL_INCLUDE_DIR should be set to a directory containing `openssl/opensslv.h` - e.g. `/usr/local/opt/openssl@3/include`.

OPENSSL_DIR is supposed to point to the root directory of an OpenSSL installation - e.g. something that contains `include/openssl/opensslv.h` and `lib/libcrypto.dylib`. It it is set, you probably shouldn't be setting OPENSSL_INCLUDE_DIR as well.
