### ISSUE TITLE
"Cannot open shared object file" on Ubuntu22.04 Arm64

### ISSUE THREAD

**Issue by raindust** [sfackler/rust-openssl#2013]
I compile my app with dependency of openssl 0.10.45, and put it into a docker with Arm64 target file like:
```
FROM --platform=$TARGETPLATFORM ubuntu:22.04

RUN \
	apt-get update && \
	apt-get install ca-certificates pkg-config libssl-dev -y && \
	apt-get clean

RUN mkdir /myapp
COPY app /myapp/
RUN chmod 775 /myapp/app

WORKDIR /myapp
CMD /myapp/app
```

When I run the built docker container it gives me the following error: " /myapp/app: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory"

**Comment by sfackler** [comment]
Ubuntu 22.04 ships OpenSSL 3.0.2, not 1.1.

**Comment by raindust** [comment]
> OpenSSL

I use Ubuntu 20.04 and it works, thanks.
