### ISSUE TITLE
Fails to build on linux-musl-aarch64

### ISSUE THREAD

**Issue by michalszmidt** [sfackler/rust-openssl#2022]
There is another thread of this issue here: https://github.com/rust-lang/rustup/issues/3324
But it seems that those builds fails only with openssl as a dependency.

I've setup a [toy-repo](https://github.com/michalszmidt/musl-aarch64-linking-build-error) with [CirrusCI aarch64 runners](https://cirrus-ci.com/github/michalszmidt/musl-aarch64-linking-build-error) on Alpine.

there are 3 configurations
1. **FAILS** Explicitly selecting openssl: [build log](https://cirrus-ci.com/task/4933387937382400)
2. **FAILS** Bindings-over system tls: [build log](https://cirrus-ci.com/task/6059287844225024)
3. **PASSES** Rustls: [build log](https://cirrus-ci.com/task/5496337890803712)

App does simple dns-over-tls query to example.com

build with `cargo build --release --verbose`
alpine latest stable
rust latest stable from rustup

Thanks in advance!

**Comment by michalszmidt** [comment]
I fetched rust from alpine repo and compilation passed.
See [those builds](https://cirrus-ci.com/build/5079689119662080)

So what we know is:
- Rust fetched from rustup on musl aarch64 will fail with openssl dependency
- Rust fetched from rustup on musl aarch64 without openssl dependency will pass
- Rust fetched from alpine with openssl dependency will pass
- glibc and amd64 combinations will pass

**Comment by sfackler** [comment]
https://github.com/rust-lang/rust/issues/89626

**Comment by michalszmidt** [comment]
I confirm that adding below to cargo.toml works for openssl and native-tls options
[build logs](https://cirrus-ci.com/build/6574372803051520)

```toml
[target.aarch64-unknown-linux-musl]
rustflags = ["-C", "-mno-outline-atomics"]
```

I suppose you didn't apply it for some reason, so I close this issue.
Maybe worth mentioning in wiki?
