### ISSUE TITLE
vcpkg build-dependency now unconditionally pulled in for all targets

### ISSUE THREAD

**Issue by decathorpe** [sfackler/rust-openssl#2031]
It looks like since openssl-sys 0.9.91, the vcpkg dependency is now hard-required, even on targets where it is unused. Would it be possible to cfg-gate the build-dependency and usage of vcpkg in build.rs? For example, it does not make sense for Linux distributions to package the vcpkg crate, but openssl-sys now can't be built without it.

Looking at the PR that introduced this change (https://github.com/sfackler/rust-openssl/pull/1982), it sounds like this is a workaround for host != target environment? If there's no other way to resolve this than to make the build-dependency unconditional, then I'll likely need to apply some downstream patches for openssl-sys for the builds in Fedora Linux.

**Comment by sfackler** [comment]
Yes, it needs to be pulled in for cross-compile workflows.

**Comment by decathorpe** [comment]
Ok :( That's unfortunate. I'll drop the dependency with a downstream patch then. Thanks for confirming!

**Comment by alex** [comment]
As a long term action item, it seems like maybe this scenario could be addressed by making cargo more flexible in declaring host _or_ target build deps?

**Comment by sfackler** [comment]
Yeah more powerful dependency filtering would cover it.

**Comment by micolous** [comment]
> It looks like since openssl-sys 0.9.91, the vcpkg dependency is now hard-required, even on targets where it is unused.

`vcpkg` (and `vcpkg-rs`) can _also_ build for non-Windows _targets_, which may _or may not_ be cross-compiled.

While `rust-openssl` doesn't support that _today_, [it absolutely _could_ be used to build for a Linux target at some point in the future][0] if someone was so inclined (that someone is unlikely to be me, though).

So while I acknowledge the minor absurdity of the situation for a Linux distributor, [even if you _could_ resolve the dependency loop to filter it out by target on a Cargo level][1], it would lead to a similar situation to [what I'm trying to unwrap with the assumption that you wouldn't use `vcpkg` to build for `*-pc-windows-gnu`][3].

If you're building in `cargo`, it's only used as a build dependency, so doesn't bloat anyone's binaries, much like providing OpenSSL via `pkg-config`.

> Would it be possible to cfg-gate the build-dependency and usage of vcpkg in build.rs? For example, it does not make sense for Linux distributions to package the vcpkg crate, but openssl-sys now can't be built without it.

To turn around your suggestion: it does not make sense to have a hard dependency on `pkg-config` on `*-pc-windows-msvc` targets... we should cfg-gate that too! Linux users can just add a `--cfg` flag for that. 😉 

See also: https://github.com/sfackler/rust-openssl/issues/1062

[0]: https://github.com/sfackler/rust-openssl/issues/1984#issuecomment-1624548155
[1]: https://github.com/sfackler/rust-openssl/pull/1982/files#r1244547204
[3]: https://github.com/mcgoo/vcpkg-rs/pull/52
