### ISSUE TITLE
Unable to generate static binaries on Mipsel

### ISSUE THREAD

**Issue by lbl8603** [sfackler/rust-openssl#2038]
RUSTFLAGS='-C target-feature=+crt-static' cargo build --release --target  mipsel-unknown-linux-musl

```
 = note: /usr/lib/gcc-cross/mipsel-linux-gnu/10/../../../../mipsel-linux-gnu/bin/ld: /rust/openss-test1/target/mipsel-unknown-linux-musl/release/deps/libopenssl_sys-2e91ddfeedfe381f.rlib(libcrypto-lib-cryptlib.o): undefined reference to symbol '__vfprintf_chk@@GLIBC_2.3.4'
          /usr/lib/gcc-cross/mipsel-linux-gnu/10/../../../../mipsel-linux-gnu/bin/ld: /usr/mipsel-linux-gnu/lib/libc.so.6: error adding symbols: DSO missing from command line
          collect2: error: ld returned 1 exit status

  = note: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)
```

**Comment by sfackler** [comment]
Glibc does not generally support static linkage.

**Comment by lbl8603** [comment]
Removing 'openssl' allows for successful compilation.
The compilation tool is 'gcc-mipsel-linux-gnu'

**Comment by sfackler** [comment]
Did you build OpenSSL with a static libc?

**Comment by lbl8603** [comment]
OPENSSL_STATIC=1 has been set.

**Comment by lbl8603** [comment]
Compilation can be successful without using '- C target feature=+crt static'
``` 
# The project only relies on openssl
# Compilation command: 'cargo build --release --target  mipsel-unknown-linux-musl'
# Using the ldd command to view
        /lib/ld.so.1 (0x77d4d000)
        libatomic.so.1 => /lib/libatomic.so.1 (0x77a98000)
        libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x77a74000)
        libc.so.6 => /lib/ld.so.1 (0x77d4d000)
```
But I want to compile static binary files.

**Comment by sfackler** [comment]
OPENSSL_STATIC=1 does not control how OpenSSL (i.e. libssl.a and libcrypto.a) were compiled.

**Comment by lbl8603** [comment]
Is the compilation method of OpenSSL controlled by openssl-src

**Comment by sfackler** [comment]
If you are using the vendored feature it is.

Again, statically linking to glibc is heavily discouraged: https://stackoverflow.com/a/57478728. If you want a fully static binary, building against musl libc is a better option.

**Comment by lbl8603** [comment]
Because I need to run it in the router, it will be difficult to use if it is not a static binary file. May I ask if there is any way for him to perform static compilation, and perhaps he needs to change the configuration of 'openssl-sys'?

**Comment by lbl8603** [comment]
Just need AES.

**Comment by sfackler** [comment]
> If you want a fully static binary, building against musl libc is a better option.

**Comment by lbl8603** [comment]
I understand, thank you

**Comment by lbl8603** [comment]
Done, thank you again
