### ISSUE TITLE
SslMethod cfg features

### ISSUE THREAD

**Issue by ghmlee** [sfackler/rust-openssl#204]
I appreciate your open source project. I found this code in src/ssl/mod.rs. I am curious about this cfg features. May I ask you about this? Why should we put these macros to use some advanced(?) ssl methods?

```rust
#[cfg(feature = "tlsv1_1")]
#[cfg(feature = "tlsv1_2")]
#[cfg(feature = "dtlsv1")]
#[cfg(feature = "dtlsv1_2")]
```

**Comment by sfackler** [comment]
The methods tagged with those features were added in versions of OpenSSL newer than 0.9.8 which OSX still ships with so they're opt-in. I should really restructure them so that there are features corresponding to OpenSSL versions directly but haven't gotten around to it.
