### ISSUE TITLE
doesnt built on openbsd -current (soon 7.4)

### ISSUE THREAD

**Issue by labannah9125** [sfackler/rust-openssl#2050]
with the following versions openssl-sys does not built on openbsd

```
% uname -a
OpenBSD openbsd-current.my.domain 7.4 GENERIC.MP#1383 amd64

% openssl version
LibreSSL 3.8.2
```

soon this will be the -stable version of 7.4 and code will no longer built then until fixed

**Comment by sfackler** [comment]
We will support LibreSSL 3.8.2 when it is released.

**Comment by gonzalo-** [comment]
> with the following versions openssl-sys does not built on openbsd
> 
> ```
> % uname -a
> OpenBSD openbsd-current.my.domain 7.4 GENERIC.MP#1383 amd64
> 
> % openssl version
> LibreSSL 3.8.2
> ```
> 
> soon this will be the -stable version of 7.4 and code will no longer built then until fixed

You can only follow here the releases, not the current status.

**Comment by brahin2** [comment]
same issue with new 7.4, also breaks cargo-edit from installing

**Comment by zacknewman** [comment]
> LibreSSL portable hasn't done a release yet, were blocked on that. Once that happens, we can turn around a release quickly.

I don't want to be "that guy", and I genuinely apologize if this comes off as pestering; but [LibreSSL Portable v3.8.2](https://github.com/libressl/portable/releases/tag/v3.8.2) was released yesterday.
