### ISSUE TITLE
Vendored openssl doesn't build on linux-i686

### ISSUE THREAD

**Issue by autarch** [sfackler/rust-openssl#2080]
I'm seeing this in a build here - https://github.com/houseabsolute/ubi/actions/runs/6727000458/job/18284173325

I think the relevant excerpt starts with:

```
2023-11-02T01:13:02.5984053Z   crypto/params.c:259:5: error: duplicate case value
2023-11-02T01:13:02.5984669Z     259 |     case sizeof(int64_t):
2023-11-02T01:13:02.5985141Z         |     ^~~~
``

It's followed by many more similar "duplicate case value" errors.

Maybe this is a known issue with OpenSSL 3 and they've dropped support for this platform?

**Comment by autarch** [comment]
After some more testing I'm seeing the same issue with openssl 0.10.56, so I wonder if instead something has changed in the VM image that GitHub Actions is using, since this same version built just fine previously.

**Comment by Skepfyr** [comment]
Sorry for not getting around to this. I'm going to close this as stale as the logs are gone and I can't see an easy way to repro, if anyone's reading this and hitting the same problem, either comment here or open a new issue with diags and hopefully someone will be able to help.
