### ISSUE TITLE
github action to build my rust app in macos fails because can't find openssl folder

### ISSUE THREAD

**Issue by Masber** [sfackler/rust-openssl#2156]
Dear rust-openssl community,

I am trying to build a release in github for macos, my understanding is that openssl should be detected automatically after installing openssl.

```
  $HOST = x86_64-apple-darwin
  $TARGET = aarch64-apple-darwin
  openssl-sys = 0.9.99
  ```

These are the logs:

https://github.com/eth-cscs/manta/actions/runs/7671057338/job/20908756993

regards

**Comment by sfackler** [comment]
Where did you install your cross-compiled OpenSSL?

> pkg-config has not been configured to support cross-compilation.
> 
>   Install a sysroot for the target platform and configure it via
>   PKG_CONFIG_SYSROOT_DIR and PKG_CONFIG_PATH, or install a
>   cross-compiling wrapper for pkg-config and set it via
>   PKG_CONFIG environment variable.

**Comment by Masber** [comment]
I don't think I have installed it, I saw this https://github.com/sfackler/rust-openssl/blob/master/openssl/src/lib.rs#L31 and tried to replicate, I thought it was enough

**Comment by sfackler** [comment]
Your host is x86_64-apple-darwin and you target is aarch64-apple-darwin. You are absolutely cross compiling.

I don't know how or if homebrew handles that case.

It looks like your `install packages` step didn't run in that build output, FYI>
