### ISSUE TITLE
Empty list in OpenSslErrors

### ISSUE THREAD

**Issue by maximih** [sfackler/rust-openssl#216]
I have a library which is using hyper. On one of my servers running on RHEL 5.2 (using a very old release of libssl - OpenSSL 0.9.8b 04 May 2006) I cannot establish an SSL connection towards another server and I get an emtpy list inside `OpenSslErrors([])` when debug printing the error.

The bubbled error:
`MyError(HttpErr(Ssl(OpenSslErrors([]))))`

I am new to rust and I don't really know how to troubleshoot this issue. I would like the SSL lib to include more details in the Debug implementation to help me pinpoint the problem.

Any suggestion is appreciated.

**Comment by sfackler** [comment]
That is certainly unfortunate. Some things you can try to help figure out what's going on:

* Make a local build of a new OpenSSL version, rebuild your application against that and see what happens. If it connects properly or gives a nonempty list of errors then it could be a bug in OpenSSL that was fixed in the last decade :).
* Try using `openssl s_client` to connect to the problematic server - it may give better diagnostics.
* If none of those are proving helpful, if you can create a smallish reproduction of the issue I can mess around with a copy of RHEL 5.2 on a VM to try to figure out what's wrong.

**Comment by maximih** [comment]
Thanks for your quick answer. I tried the `openssl s_client` and seem to connect successfully:

```
bash-3.2$ openssl s_client -connect <edited>:443
CONNECTED(00000003)
depth=0 <edited>
verify error:num=18:self signed certificate
verify return:1
depth=0 <edited>
verify return:1
---
Certificate chain
 0 s:<edited>
   i:<edited>
---
Server certificate
-----BEGIN CERTIFICATE-----
MIID3jCCAsYCCQCHPze42uRkLTANBgkqhkiG9w0BAQUFADCBsDELMAkGA1UEBhMC
VVMxCzAJBgNVBAgMAk5KMRMwEQYDVQQHDApQaXNjYXRhd2F5MREwDwYDVQQKDAhF
cmljc3NvbjEMMAoGA1UECwwDRUNNMS0wKwYDVQQDDCRzZWxucGNuZWNtd2ViMDEu
c2Vsbi5ldGUuZXJpY3Nzb24uc2UxLzAtBgkqhkiG9w0BCQEWIGVjbS1jaUBtYWls
bWFuLmxtZXJhLmVyaWNzc29uLnNlMB4XDTE1MDUxMjA2NDQzNFoXDTE2MDUxMTA2
NDQzNFowgbAxCzAJBgNVBAYTAlVTMQswCQYDVQQIDAJOSjETMBEGA1UEBwwKUGlz
Y2F0YXdheTERMA8GA1UECgwIRXJpY3Nzb24xDDAKBgNVBAsMA0VDTTEtMCsGA1UE
Awwkc2VsbnBjbmVjbXdlYjAxLnNlbG4uZXRlLmVyaWNzc29uLnNlMS8wLQYJKoZI
hvcNAQkBFiBlY20tY2lAbWFpbG1hbi5sbWVyYS5lcmljc3Nvbi5zZTCCASIwDQYJ
KoZIhvcNAQEBBQADggEPADCCAQoCggEBAKCVvMBVN6c5xFi0nT3RrwSrvECH6YA4
UAMakUHp8pmCtrjH/FyaV22n1ZqzHfvxwmsmYTP2DwQlg+2gd0bsQYsXYIUP6gl6
lcLpEM/mAJoeuCdDY8jt7JeOZ3h6rJXBn4NFXdtGuh19uZ8sfV71ovOldnoR/yiB
+kFInzHaCrebKMV5JXG5K3MNtVw8QwizHoN75fxRazYupDmcQ/JXJzEI16H9YG4l
0Vcb/LsOY7tlW3BMS7LPPJiIhcpHs9uAKaGmAnclZBy084+h1Si3RBN+oYWWQ0RK
m3jZpv1VTU6Y8EwP9MQkv3zfSztuiIIvrI0P368Vqrok5A1oO5hY3c0CAwEAATAN
BgkqhkiG9w0BAQUFAAOCAQEAie79d96/iahevdzAGK20Fr7NoJ4Tv8fOfdpsPABZ
VCFcVRezBHDj6YCx+QNgnMAFMC1OUYk19kMxCFxWOP09iLsN7fsMoC7bC9kYRdMH
jHovtozftOCARO2Pik28l1LUGE3DAhc5Ep0WYeFElGmQt98ZVMbJtbtkQDdntJ8u
I8B3fWaQoqdOa6jI3wZjpyssdNSNlJPfbgBNVzrlqlkwOvWxjCNqOSy102ZWBO5K
42nKGkGbUgNSpoHUO3wXHvYErPi0jTZhtOM6+SaDSpPxCrqDtvFtAqYqyEwniJWV
cYpxy9zFez2szRJKk/+YhpoTmIZkekF19EmY2MOVP9oKxg==
-----END CERTIFICATE-----
subject=<edited>
issuer=<edited>
---
No client certificate CA names sent
---
SSL handshake has read 1910 bytes and written 459 bytes
---
New, TLSv1/SSLv3, Cipher is DHE-RSA-AES256-SHA
Server public key is 2048 bit
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1
    Cipher    : DHE-RSA-AES256-SHA
    Session-ID:
    Session-ID-ctx:
    Master-Key: 9A649E4AED53CF7A8221EB2721D8814E36338DF42A5DD85C5BD33B0F09112F75AA310E98B107EDE9401EE08CA7656B9B
    Key-Arg   : None
    Krb5 Principal: None
    Start Time: 1432279400
    Timeout   : 300 (sec)
    Verify return code: 18 (self signed certificate)
```

I will try to build a newer OpenSSL lib sometime next week.

Thanks

**Comment by maximih** [comment]
I've compiled a newer OpenSSL version and it works like a charm. For reference, I used OpenSSL 1.0.0r. I don't think I want to know what is wrong with the old one. As you said, probably a bug fixed "in the last decade" :).

Thanks for your help

**Comment by sfackler** [comment]
Great!
