### ISSUE TITLE
Stack corruption on module init in `provider_conf_init`

### ISSUE THREAD

**Issue by kvark** [sfackler/rust-openssl#2160]
I'm porting Zed to Linux - https://github.com/zed-industries/zed/pull/7343
It's currently crashing on startup even before `main` is entered.
Call stacks are corrupted until I build with "safestack" sanitizer, in which case it produces the following stack: 
[openssl-crash2-stack.txt](https://github.com/sfackler/rust-openssl/files/14158021/openssl-crash2-stack.txt)

Strace shows the configuration file read as the last thing:
```
openat(AT_FDCWD, "/nix/store/l0rxwrg41k3lsdiybf8q0rf3nk430zr8-openssl-3.0.12/etc/ssl/openssl.cnf", O_RDONLY) = 3
newfstatat(3, "", {st_mode=S_IFREG|0444, st_size=12324, ...}, AT_EMPTY_PATH) = 0
read(3, "#\n# OpenSSL example configuratio"..., 4096) = 4096
read(3, "d attributes must be the same, a"..., 4096) = 4096
read(3, "coding of an extension: beware e"..., 4096) = 4096
read(3, " = $insta::certout # insta.cert."..., 4096) = 36
read(3, "", 4096)                       = 0
close(3)                                = 0
futex(0x7f14c78795d8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x7f14c787961c, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x7f14c7879d7c, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x7f14c7879d74, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x7f14c78795b8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SI_KERNEL, si_addr=NULL} ---
```

I understand that `rust-openssl` is just one of the links in the chain that could go wrong for some reason, in addition to the system configuration (note: 2 out of 2 other users reported the same crash so far), or something off with Zed.
But maybe you have some ideas on how to proceed? Much appreciated!

**Comment by sfackler** [comment]
Nothing from the crates in this repo appear in that stack trace.

**Comment by kvark** [comment]
You are correct, thanks for having a look at this!
Going to follow-up with curl.
