### ISSUE TITLE
OpenSSL not found openssl-sys build failure

### ISSUE THREAD

**Issue by Whales1992** [sfackler/rust-openssl#2181]
If you're in a situation where you think the directory *should* be found
  automatically, please open a bug at https://github.com/sfackler/rust-openssl
  and include information about your system as well as this message.

  $HOST = x86_64-unknown-linux-gnu
  $TARGET = x86_64-unknown-linux-gnu
  openssl-sys = 0.9.100

**Comment by Skepfyr** [comment]
We will need a bunch more information to be able to help debug this. Have you followed the documentation here about how to build this crate https://docs.rs/openssl/latest/openssl/? What Linux distribution are you using? Have you installed pkg-config and the OpenSSL headers?
