### ISSUE TITLE
Failing to find openssl via pkg-config when building

### ISSUE THREAD

**Issue by kylecarow** [sfackler/rust-openssl#2186]
This may not be the exactly correct place to file this issue, feel free to redirect me if that's the case.

I am working with a pyo3 project, a Python-exposed Rust-backend package. I am having trouble building wheels on GitHub Actions using cibuildwheel, where some command (generated by this crate?) is pointing to a pkg-config directory that does not contain openssl.pc: 

```
PKG_CONFIG_PATH contains the following:
     - /usr/local/lib/pkgconfig
```

This workflow used to run fine, but I think a dependency was added to my codebase that depends on this crate.

<details open>
  <summary>GitHub Actions Output (collapsible)</summary>

```
        error: failed to run custom build command for `openssl-sys v0.9.101`
        
        Caused by:
          process didn't exit successfully: `/project/rust/target/release/build/openssl-sys-efaff5fa71405265/build-script-main` (exit status: 101)
          --- stdout
          cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR
          X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR unset
          cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
          OPENSSL_LIB_DIR unset
          cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR
          X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR unset
          cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
          OPENSSL_INCLUDE_DIR unset
          cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR
          X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR unset
          cargo:rerun-if-env-changed=OPENSSL_DIR
          OPENSSL_DIR unset
          cargo:rerun-if-env-changed=OPENSSL_NO_PKG_CONFIG
          cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
          cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
          cargo:rerun-if-env-changed=HOST_PKG_CONFIG
          cargo:rerun-if-env-changed=PKG_CONFIG
          cargo:rerun-if-env-changed=OPENSSL_STATIC
          cargo:rerun-if-env-changed=OPENSSL_DYNAMIC
          cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
          cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
          cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
          cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
          cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
          cargo:rerun-if-env-changed=PKG_CONFIG_PATH
          cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
          cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
          cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
          cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
          cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
          cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
          cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
          cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
          run pkg_config fail:
          pkg-config exited with status code 1
          > PKG_CONFIG_PATH=/usr/local/lib/pkgconfig PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 pkg-config --libs --cflags openssl
        
          The system library `openssl` required by crate `openssl-sys` was not found.
          The file `openssl.pc` needs to be installed and the PKG_CONFIG_PATH environment variable must contain its parent directory.
          PKG_CONFIG_PATH contains the following:
              - /usr/local/lib/pkgconfig
        
          HINT: you may need to install a package such as openssl, openssl-dev or openssl-devel.
        
        
          --- stderr
          thread 'main' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/openssl-sys-0.9.101/build/find_normal.rs:190:5:
        
        
          Could not find directory of OpenSSL installation, and this `-sys` crate cannot
          proceed without this knowledge. If OpenSSL is installed and this crate had
          trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
          compilation process.
        
          Make sure you also have the development packages of openssl installed.
          For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.
        
          If you're in a situation where you think the directory *should* be found
          automatically, please open a bug at https://github.com/sfackler/rust-openssl
          and include information about your system as well as this message.
        
          $HOST = x86_64-unknown-linux-gnu
          $TARGET = x86_64-unknown-linux-gnu
          openssl-sys = 0.9.101
        
        
          note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
        warning: build failed, waiting for other jobs to finish...
        💥 maturin failed
          Caused by: Failed to build a native library through cargo
          Caused by: Cargo build finished with "exit status: 101": `PYO3_ENVIRONMENT_SIGNATURE="cpython-3.10-64bit" PYO3_PYTHON="/opt/python/cp310-cp310/bin/python" PYTHON_SYS_EXECUTABLE="/opt/python/cp310-cp310/bin/python" "cargo" "rustc" "--features" "pyo3/extension-module" "--message-format" "json-render-diagnostics" "--manifest-path" "/project/rust/fastsim-py/Cargo.toml" "--release" "--lib"`
        Error: command ['maturin', 'pep517', 'build-wheel', '-i', '/opt/python/cp310-cp310/bin/python', '--compatibility', 'off'] returned non-zero exit status 1
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
    ERROR: Failed building wheel for fastsim
  Failed to build fastsim
  ERROR: Failed to build one or more wheels
```
</details>

[Workflow file](https://github.com/NREL/fastsim/blob/8ca1b3f8c6ae1a757248852375759374e021de59/.github/workflows/wheels.yaml#L67)

Interestingly, this only fails on linux.

Things I have tried:
- `sudo apt install libssl-dev pkg-config`
  - already installed
  - `find / -name "openssl.pc" 2>/dev/null` returns this list:
    -  /usr/share/miniconda/pkgs/openssl-3.0.12-h7f8727e_0/lib/pkgconfig/openssl.pc
    - /usr/share/miniconda/lib/pkgconfig/openssl.pc
    - /usr/lib/x86_64-linux-gnu/pkgconfig/openssl.pc
  - supplying a path from that list as `PKG_CONFIG_PATH`
    - This doesn't change anything, and the output still shows this:
      ```
       PKG_CONFIG_PATH contains the following:
              - /usr/local/lib/pkgconfig
       ```
     - wondering if this is because the `PKG_CONFIG_PATH` variable seems to be set in the command itself? `PKG_CONFIG_PATH=/usr/local/lib/pkgconfig PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 pkg-config --libs --cflags openssl`
  - supplying a path to `OPENSSL_DIR` itself
    - I could be doing this wrong, but this also didn't work, maybe because the variables are being `unset`??

**Comment by sfackler** [comment]
cibuildwheel runs your build in a Docker container. Are you installing libssl-dev in the host or in that container?

**Comment by kylecarow** [comment]
Aha, didn't know that - that was the missing piece!! I added `yum -y install openssl openssl-devel` to `CIBW_BEFORE_BUILD_LINUX` and it was able to complete the workflow!!

Related:

> Programs and libraries are not installed on the CI runner host, but rather should be installed inside the container - using `yum` for `manylinux2010` or `manylinux2014`, `apt-get` for `manylinux_2_24` and `apk` for `musllinux_1_1`, or manually. The same goes for environment variables that are potentially needed to customize the wheel building.

https://cibuildwheel.readthedocs.io/en/stable/faq/#linux-builds-in-containers

https://cibuildwheel.readthedocs.io/en/stable/options/#before-build

**Comment by lmmx** [comment]
Thanks a bunch for this @kylecarow I'd just like to add to be careful to distinguish between an env var on the job step level and that which is passed into the docker env!

I am using PyO3/maturin-action@v1 which has [settings](https://github.com/PyO3/maturin-action/blob/main/action.yml) which let you pass `docker-options` so for me this looked [like](https://github.com/lmmx/polars-fastembed/blob/196fc1aa07ac66361fdd09cb9909d45e23c8662f/.github/workflows/CI.yml#L60-L75):

```yaml
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          working-directory: rewrite
          target: ${{ matrix.platform.target }}
          args: --release --out dist --find-interpreter
          sccache: ${{ !startsWith(github.ref, 'refs/tags/') }}
          manylinux: auto
          docker-options: "--env CIBW_BEFORE_BUILD_LINUX='${{ env.CIBW_BEFORE_BUILD_LINUX }}'"
        env:
          CIBW_BEFORE_BUILD_LINUX: yum -y install openssl openssl-devel
```

I then saw

> `/usr/bin/docker run --rm --workdir /home/runner/work/polars-fastembed/polars-fastembed/rewrite -e DEBIAN_FRONTEND=noninteractive -e ARCHFLAGS -e _PYTHON_SYSCONFIGDATA_NAME -e ACTIONS_RUNNER_ACTION_ARCHIVE_CACHE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e ACTIONS_RESULTS_URL -e ACTIONS_CACHE_SERVICE_V2 -e CARGO_INCREMENTAL -e CARGO_TERM_COLOR -e SCCACHE_GHA_ENABLED -e RUSTC_WRAPPER -v /home/runner/work/_temp/run-maturin-action.sh:/home/runner/work/_temp/run-maturin-action.sh -v /home/runner/work/polars-fastembed/polars-fastembed:/home/runner/work/polars-fastembed/polars-fastembed` **--env CIBW_BEFORE_BUILD_LINUX='yum -y install openssl openssl-devel'** `quay.io/pypa/manylinux2014_x86_64:latest /home/runner/work/_temp/run-maturin-action.sh`

(That still didn't fix it and I think the issue is actually needing `openssl = { version = "0.10", features = ["vendored"] }` in the Cargo.toml to build on CI but I think this is a separate issue)
