### ISSUE TITLE
DEP_OPENSSL_VERSION_NUMBER not present.

### ISSUE THREAD

**Issue by newholder** [sfackler/rust-openssl#2188]
I follow the [example](https://github.com/sfackler/rust-openssl/blob/master/openssl-errors/build.rs) and it return `Err(NotPresent)`

what i do wrong?

**Comment by sfackler** [comment]
Do you have a dependency on openssl-sys?

**Comment by sfackler** [comment]
Can you provide a self-contained example of a crate that shows the issue?
