### ISSUE TITLE
 Is OpenSSL from_pem()/from_der() leaking memory?

### ISSUE THREAD

**Issue by niahson** [sfackler/rust-openssl#2214]
Greetings, sending peace.

This is really the same code that is posted here [Is OpenSSL from_pem()/from_der leaking memory](https://users.rust-lang.org/t/is-openssl-from-pem-from-der-leaking-memory/108936).  But just in case you do want to click outside, I have attached the `main.rs` and the valgrind report, please have a quick look
[main.rs.txt](https://github.com/sfackler/rust-openssl/files/14826197/main.rs.txt)
[openssl-rust-mem-leak-new.txt](https://github.com/sfackler/rust-openssl/files/14826181/openssl-rust-mem-leak-new.txt)

I write here to ask you guys who wrote the actual crate to **confirm that this not a real memory leak and, most importantly, if there is anything else I can do beyond calling `drop(x509)` to force OpenSSL to free any "global state allocations" before main exits.**?

**Comment by sfackler** [comment]
As I posted in that thread, there is not a real memory leak.

There is no safe way to get OpenSSL to free that memory on shutdown unfortunately.

**Comment by niahson** [comment]
@sfackler Thank you, I will rest it here.
