### ISSUE TITLE
base64::decode_block fails silently on long values

### ISSUE THREAD

**Issue by juliankrieger** [sfackler/rust-openssl#2249]
I was just testing `openssl::base64::decode_block` when I noted decoding fails on longer inputs. The ErrorStack is also empty.

This works:

`eyJ4NWMiOlsiVFVsSlFtMUVRME5CVkRablFYZEpRa0ZuU1VKTlZFRkxRbWRuY1docmFrOVFVVkZFUVdwQmFFMVNPSGRJVVZsRVZsRlJSRVJDV25SWldFNW9URmRPYUV4dFZqUlpWekYzWWtkVmRWa3lPWFJKUlU1Q1RVSTBXRVJVU1RCTlJGbDNUMVJGZWs1RWF6Rk5iRzlZUkZSSk1VMUVXWGRQVkVWNlRrUnJNVTFzYjNkSVJFVmhUVUpuUjBFeFZVVkNVWGRTVFVSQmRGSkVRWFJTVkZWMFVtcEpkRTFFUVhSTlJFbDNWMVJCVkVKblkzRm9hMnBQVUZGSlFrSm5aM0ZvYTJwUFVGRk5Ra0ozVGtOQlFWUXdhREo2ZEZCc1JreEVaVlUzTVdVMllUTlpiVlZoYVVadFpFb3pibTlrVkRaamVYaFFabEpqZFRaUGFHSlJZaTluVkROMVRURmtOemRYVWtsTFdsVmpZVlpzV2pGcVdIUjJUalkzTWtkck9VYzVTVk5CYnpKM2QyRnFRV05DWjA1V1NGSkZSVVpVUVZSbmFFVjNUVU14UlUxRE1VWk9VekZIVFdrd2QwMURNSGROYWtGa1FtZE9Wa2hSTkVWR1oxRlZhQ3RrWnpSa1lWUm9lWE5KYkM5Rll6TnVibXQ1V1VoNVRYQkZkMFIzV1VSV1VqQlVRVkZJTDBKQlZYZEJkMFZDUVVSQllVSm5aM0pDWjBWR1FsRmpRa2xCVVU5aVJ6bHFXVmQ0YjJJelRqQlBhazEzVFVSQmQwTm5XVWxMYjFwSmVtb3dSVUYzU1VSVFFVRjNVbEZKWjJOcmRrUm5SR1ZIUkRoeWRFUmphRmdyYTFWNFkyWldkbTVsUlcxMU9EbE1SRVI2UTNsTmFVSjFiWGREU1ZGRWVUTlVWbTQwZUdoT1RXSjJiMUZhUXl0VlZVMWxSVWxFVGtSc1dXeFBkVGszVms5UE5UUkxaVEZKUVQwOSJdLCJhbGciOiJFUzI1NiJ9`

This fails:

`eyJ4NWMiOlsiVFVsSlFtMVVRME5CVkRablFYZEpRa0ZuU1VKTlZFRkxRbWRuY1docmFrOVFVVkZFUVdwQmFFMVNPSGRJVVZsRVZsRlJSRVJDV25SWldFNW9URmRPYUV4dFZqUlpWekYzWWtkVmRWa3lPWFJKUlU1Q1RVSTBXRVJVU1RCTlJGbDNUMVJGZWs1VVJYZE5NVzlZUkZSSk1VMUVXWGRQVkVWNlRsUkZkMDB4YjNkSVJFVmhUVUpuUjBFeFZVVkNVWGRTVFVSQmRGSkVRWFJTVkZWMFVtcEpkRTFFUVhSTlJFbDNWMVJCVkVKblkzRm9hMnBQVUZGSlFrSm5aM0ZvYTJwUFVGRk5Ra0ozVGtOQlFWUTJVbEpKYzNJME0yeG1VVUo0WmtwSmJWbFhXa2hWZWxSSFprWmhTbUUxU1dsQldFeHpPVmx6UTJGWVRESmhWRXRrSzFGd2RuaGFTWGRtZDJaVlRFZGtkakZMV1RkalYxVjRialpCVmxoUllVdHRkbGcxYnpKM2QyRnFRV05DWjA1V1NGSkZSVVpVUVZSbmFFVjNUVU14UlUxRE1VWk9VekZIVFdrd2QwMURNSGROYWtGa1FtZE9Wa2hSTkVWR1oxRlZjVkJOSzNGRFJrWlJia2Q1V0dSdlJUZFZTRVZ2TVhKeGRHeFJkMFIzV1VSV1VqQlVRVkZJTDBKQlZYZEJkMFZDUVVSQllVSm5aM0pDWjBWR1FsRmpRa2xCVVU5aVJ6bHFXVmQ0YjJJelRqQlBhazEzVFVSQmQwTm5XVWxMYjFwSmVtb3dSVUYzU1VSVFVVRjNVbWRKYUVGUFZ6bGpaSEUzZGxWc1NqaFBUMjU0U0ZGbmFsaGFXRkZWVFZaRFZEQm1ZM2h3YlhaSFNIaFJjMWR3UVdsRlFUbFJXaTlvVFd4V2F5dFZWRXBXT0dkRFVscGtiVWMxU0VwR1JqRjRWRVJ6T0RobFEwODRTV3hwVkc4OSJdLCJhbGciOiJFUzI1NiIsImNyaXQiOlsiY3JlYXRlZF9vbiJdfQ`

**Comment by sfackler** [comment]
The failing string is 1046 bytes, which is not divisible by 4. Unfortunately, the OpenSSL implementation doesn't set a specific error when returning in that case.
