### ISSUE TITLE
Support Openssl for Windows distributed by slproweb.com

### ISSUE THREAD

**Issue by JohnScience** [sfackler/rust-openssl#2251]
Installing OpenSSL from <https://slproweb.com/products/Win32OpenSSL.html> was the only option that worked for me.

I tried various

```
vcpkg install <...>
```

for OpenSSL but I received errors.

I tried installing it with `winget` but received `404 Not Found` errors.

```
winget install ShiningLight.OpenSSL
```

After installing `openssl` from <slproweb.com>, I can use it with the following env variables:

```
set OPENSSL_DIR=%PROGRAMFILES%\OpenSSL-Win64
set OPENSSL_LIB_DIR=%PROGRAMFILES%\OpenSSL-Win64\lib\VC\x64\MD
```

which I got from <https://github.com/sfackler/rust-openssl/issues/766#issuecomment-2050533376>.

For me, it was the only thing that worked.

**Comment by sfackler** [comment]
If it's working, then it seems like it's already supported.

**Comment by JohnScience** [comment]
> If it's working, then it seems like it's already supported.

What I suggest is better support, i.e. so that the directories are discovered automatically.
