### ISSUE TITLE
MSRV issue with c_char

### ISSUE THREAD

**Issue by jmayclin** [sfackler/rust-openssl#2317]
I think the latest release [0.10.67](https://crates.io/crates/openssl/0.10.67) actually requires an MSRV of 1.64 to compile, but is published as 1.63.

We saw the following error in our CI (testing a 1.63 MSRV)
```
 error[E0432]: unresolved import `std::ffi::c_char`
  --> /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.10.67/src/kdf.rs:28:24
   |
28 |         use std::ffi::{c_char, c_void};
   |                        ^^^^^^ no `c_char` in `ffi`

```
[ci link](https://github.com/aws/s2n-tls/actions/runs/11357020440/job/31589206604?pr=4847#step:7:157)

From the documentation, it looks like [c_char](https://doc.rust-lang.org/beta/std/ffi/type.c_char.html) wasn't added until 1.64.

**Comment by Tarnum-tst** [comment]
Having same issue here while building cryptography. i686-pc-windows-gnu with MSRV 1.63
`error[E0432]: unresolved import `std::ffi::c_char`
  --> C:\Users\User\.cargo\registry\src\github.com-1285ae84e5963aae\openssl-0.10.67\src\kdf.rs:28:24
   |
28 |         use std::ffi::{c_char, c_void};
   |                        ^^^^^^ no `c_char` in `ffi``
Solved this by replacing 'use std::ffi::{c_char, c_void};' (line 28, kdfs.rs) with 'use libc::{c_char, c_void};'
