### ISSUE TITLE
Best way to manage modifying SSL_CTX after creation?

### ISSUE THREAD

**Issue by rushilmehra** [sfackler/rust-openssl#2322]
I'm working on adding bindings for ECH related APIs to https://github.com/cloudflare/boring, and I'm curious for your thoughts on the best way to manage cases where an application needs to update `SSL_CTX` after its initial creation. The current pattern is that nothing on `impl SslContextRef` requires a mutable reference, but for rotating a set of ECH configs a server supports, that pattern needs to be broken. Applications can obtain a `&mut SslContextRef` from an `SslRef` by doing `ssl.ssl_context().to_owned().as_mut();`, so is there anything wrong with adding a method on the `SslContextRef` impl that takes `&mut self`?

**Comment by sfackler** [comment]
SslContext is a reference counted type - to_owned just bumps that and returns the same pointer. As a result, you cannot safely mutate the SslContext after creating an Ssl with it.

Why do you think you need to mutate the SslContext in particular? Traditionally you'd either modify the Ssl object or swap the Ssl's SslContext out for another one.

**Comment by rushilmehra** [comment]
We register a set of ECH configs on the server's `SSL_CTX` because it applies to all incoming TLS connections. It's recommended by the RFC to rotate these configurations routinely, so we have logic that manages that and thus needs to update the list registered with boringssl. FWIW, [documentation](https://github.com/google/boringssl/blob/master/include/openssl/ssl.h#L4136-L4168) for the boringssl API says this is safe (and the code does obtain a lock on the ctx): 

> Once |keys| has been passed to this function, it is immutable. Unlike most
|SSL_CTX| configuration functions, this function may be called even if |ctx|
already has associated connections on multiple threads. This may be used to
rotate keys in a long-lived server process.

**Comment by sfackler** [comment]
Oh great, if the method is actually thread safe then it can just be defined taking `&self` directly on `SslContextRef`.

**Comment by rushilmehra** [comment]
Oh interesting, okay. So no need to make it take `&mut Self` for semantic purposes?

**Comment by sfackler** [comment]
That would be indicating that you need unique access to make the call which isn't correct.

**Comment by rushilmehra** [comment]
Makes sense, thanks! Fundamentals :)
