### ISSUE TITLE
Fatal error handling

### ISSUE THREAD

**Issue by elmaxxo** [sfackler/rust-openssl#2334]
Accroding to [the openssl documentation](https://docs.openssl.org/master/man3/SSL_get_error/#return-values), there are 2 fatal errors `SSL_ERROR_SYSCALL`  and `SSL_ERROR_SSL`. After encountering these errors, *no further I/O operations should be performed on the connection and SSL_shutdown() must not be called*. However, `SslStream` doesn't handle these errors separately, which can lead to violations of this condition. Furthermore, in [some cases](https://github.com/sfackler/rust-openssl/blob/538a5cb737e8d83085553cac01643820dc7ff205/openssl/src/ssl/mod.rs#L3730-L3732) `SSL_ERROR_SYSCALL` isn't even treated as an error. 

I'm wondering if there are some reasons for that. Is it intentional?

**Comment by sfackler** [comment]
We don't do any special handling of fatal errors because it's never been a problem.

The SSL_ERROR_SYSCALL special case is due to the behavior of pre-3.0 versions:
> The SSL_ERROR_SYSCALL with errno value of 0 indicates unexpected EOF from the peer.

https://docs.openssl.org/1.1.1/man3/SSL_get_error/#bugs
