### ISSUE TITLE
Extend PKey module to better support DH, DSA, EC

### ISSUE THREAD

**Issue by jethrogb** [sfackler/rust-openssl#234]
The current PKey module is very RSA-centric. Loading of DSA and EC keys is possible, but the following functions implement RSA-specific functionality only:
- gen
- save_pub
- load_pub
- save_priv
- load_priv
- size
- sign_with_hash
- verify_with_hash

load/save should be implemented using `x2y_PUBKEY` and `x2y_PrivateKey` where x/y are i/d or d/i.

These functions are also RSA-centric, but can't work with any of the other algorithms:
- max_data
- encrypt_with_padding
- decrypt_with_padding

**Comment by aij** [comment]
Is anyone working on this? I'd like to use EC.

**Comment by jethrogb** [comment]
I'm not currently, and also not planning to do this within a couple of weeks.

**Comment by awelkie** [comment]
What's the benefit of having one struct for all of the different types of keys? Would this API be better if there were different key structs (`ECKey`, `RSAKey`, `DSAKey`) instead of one `PKey` struct (even if they were just wrappers around a `PKey` pointer)?

**Comment by jethrogb** [comment]
I can be convinced that they should all be different structs, although this makes loading unknown-type key file harder. They should all exhibit similar interfaces though, since they all support some subset of the same common operations:
* parameter generation
* key generation
* encryption/decryption
* signing/verification
* key derivation
* inputting into an SSL struct

I've been looking into this some more and I also think that most of the EVP_PKEY API is the wrong API to export. We should really be looking more at the `EVP_SealInit` and `EVP_SignInit` families of functions. Unfortunately there is no counterpart for `EVP_PKEY_keygen` and `EVP_PKEY_derive` functions, so those need to be exposed at the lower level.

**Comment by bbatha** [comment]
I'd like to help out with this, at least to add DSA keys, and possibly the overarching traits. Though, I'd need some assistance designing the traits.

**Comment by sfackler** [comment]
I believe this has been resolved in the 0.8 rewrite. If anything's still missing, please open new issues!
