### ISSUE TITLE
Implement Ephemeral DH server-side support

### ISSUE THREAD

**Issue by jethrogb** [sfackler/rust-openssl#235]
DHE/ECDHE is currently not supported for servers since there is no way to initialize the server-side DH parameters. This means running servers with DSS or ECDSA keys is also not supported, since all cipher suites with those authentication mechanisms depend on DHE/ECDHE.

The required functions are

- [x] SSL_CTX_set_tmp_dh_callback
- [x] SSL_CTX_set_tmp_dh
- [x] SSL_set_tmp_dh_callback
- [x] SSL_set_tmp_dh

for DHE and 

- [x] SSL_CTX_set_tmp_ecdh_callback
- [x] SSL_CTX_set_tmp_ecdh
- [x] SSL_set_tmp_ecdh_callback
- [x] SSL_set_tmp_ecdh

for ECDHE pre-1.0.2 and

- [x] SSL_CTX_set_ecdh_auto
- [x] SSL_set_ecdh_auto

for ECDHE on 1.0.2 and onwards. It would probably also be a good idea to make available

- [x] get_rfc2409_prime_768 
- [x] get_rfc2409_prime_1024
- [x] get_rfc3526_prime_1536
- [x] get_rfc3526_prime_2048
- [x] get_rfc3526_prime_3072
- [x] get_rfc3526_prime_4096
- [x] get_rfc3526_prime_6144
- [x] get_rfc3526_prime_8192
- [x] EC_KEY_new_by_curve_name

to be able to load the default parameters, although using these 768-bit and 1024-bit values is [not recommended for security reasons](https://weakdh.org)

This depends on #234 to able to pass around EC and DH PKeys.

See for usage of these APIs for example Apache mod_ssl:
https://github.com/apache/httpd/blob/9edfd64/modules/ssl/ssl_engine_kernel.c#L1343-1383 
https://github.com/apache/httpd/blob/9edfd64/modules/ssl/ssl_engine_init.c#L1182-1219

**Comment by sfackler** [comment]
I believe this is now all implemented!
