### ISSUE TITLE
Clarify alternate Windows build procedure

### ISSUE THREAD

**Issue by Zarathustra30** [sfackler/rust-openssl#245]
The alternative procedure for Windows build should be clarified

> You can ... copy the include/openssl directory, libssl32.dll, and libeay32.dll to locations that Cargo can find ...

It would help to list _actual_ locations for where to put the files. The Cargo documentation does not include any information on dynamic linking, so "locations that Cargo can find" is rather opaque, as evidenced by my inability to successfully follow the build procedure.

**Comment by sfackler** [comment]
Did you try the first method of just installing the `mingw-w64-x86_64-toolchain` package in mingw?

**Comment by Zarathustra30** [comment]
I did not. I do not have mingw, and I would prefer to not have to learn another tool while it appears there is a way to build without it.

**Comment by sfackler** [comment]
I'm not totally sure where rustc searches for `dll`s and gcc searches for header files on Windows, unfortunately. The way I've built this library on Windows when not using a mingw-provided openssl is to use the environment variables to explicitly state where the stuff is: `env OPENSSL_LIB_DIR=C:/OpenSSL-Win64 OPENSSL_INCLUDE_DIR=C:/OpenSSL-Win64/include cargo build`.

**Comment by semmaz** [comment]
Even with providing environment variables, rust-openssl still fails to build, mingw works though (after installing toolchain).
This appears to be the issue with [gcc-rs](https://github.com/alexcrichton/gcc-rs/issues/7). I was about to file new issue there, until I discovered it. Should I do that (essentially reopening issue) or just removing alternative build method will be enough?

**Comment by Zarathustra30** [comment]
Removing the alternative build method would be enough to avoid any confusion and close this issue, for the time being. I've updated the report to reflect this.  The build failure [has already been reported](https://github.com/sfackler/rust-openssl/issues/241), so we can keep track of it over there.

However, it would be nice to be able to use SSL without building with mingw, so I think the gcc-rs issue should be reopened.

**Comment by Zarathustra30** [comment]
Okay, now that the alternative to building with MinGW no longer requires MinGW, the original intent of this issue is once again relevant. "Locations that Cargo can find" is too ambiguous, and should be made more specific or removed altogether.

**Comment by sfackler** [comment]
I'm on board with removing that phrase.

**Comment by luser** [comment]
To get this building on Windows with the Win64OpenSSL package I had to do the following:
```
export OPENSSL_LIB_DIR=C:/OpenSSL-Win64/lib
export OPENSSL_INCLUDE_DIR=C:/OpenSSL-Win64/include
export OPENSSL_LIBS=ssleay32:libeay32
```

**Comment by sfackler** [comment]
The 0.9 release has heavily overhauled the library lookup process.
