### ISSUE TITLE
openssl_shim.c doesnt compile under Cygwin

### ISSUE THREAD

**Issue by bvinc83** [sfackler/rust-openssl#248]
```
running: "gcc" "-O0" "-c" "-ffunction-sections" "-fdata-sections" "-g" "-mwin32" "-m32" "-I" "/cygdrive/c/OpenSSL-Win32/include" "-o" "C:\src\rust-openssl\openssl-sys\target\debug\build\openssl-sys-7233f93613c7306a\out\src\openssl_shim.o" "C:\src\rust-openssl\openssl-sys\src/openssl_shim.c"


command did not execute successfully, got: exit code: 1



--- stderr
In file included from /cygdrive/c/OpenSSL-Win32/include/openssl/x509.h:107:0,
                 from /cygdrive/c/OpenSSL-Win32/include/openssl/ssl.h:156,
                 from C:\src\rust-openssl\openssl-sys\src/openssl_shim.c:2:
/cygdrive/c/OpenSSL-Win32/include/openssl/sha.h:184:16: error: expected ‘:’, ‘,’, ‘;’, ‘}’ or ‘__attribute__’ before ‘h’
     SHA_LONG64 h[8];
                ^
thread '<main>' panicked at 'explicit panic', C:\cygwin\home\user\.cargo\registry\src\github.com-121aea75f9ef2ce2\gcc-0.3.11\src\lib.rs:514
stack backtrace:
   1: 0x69ac4dcb - rt::unwind::register::h9c140029fe1f09c6iQw
```

This is the error when compiling under cygwin.

The first revision where this started happening was d0b769c93c623d308c02cb5d86726f4c9607f5f4

The problem is that openssl_shim.c started including ssl.h, but the proper defines are not set for compiling under Cygwin.

The relevant code from sha.h is:

```C
#  define SHA512_CBLOCK   (SHA_LBLOCK*8)
#  if (defined(_WIN32) || defined(_WIN64)) && !defined(__MINGW32__)
#   define SHA_LONG64 unsigned __int64
#   define U64(C)     C##UI64
#  elif defined(__arch64__)
#   define SHA_LONG64 unsigned long
#   define U64(C)     C##UL
#  else
#   define SHA_LONG64 unsigned long long
#   define U64(C)     C##ULL
#  endif

typedef struct SHA512state_st {
    SHA_LONG64 h[8];
```

It appears that the crate "gcc" is adding -mwin32 to the gcc flags.  This is causing ```_WIN32``` to be defined.  However, nothing is defining ```__MINGW32__``` since this is Cygwin.  So SHA_LONG64 is being defined as ```__int64``` instead of ```unsigned long long```.

If I remove the ```-mwin32``` flag, or if I add ```-D__MINGW32__```, then it compiles fine.

**Comment by sfackler** [comment]
Thanks for the investigation! It looks like you should file a bug under the `gcc` crate.

**Comment by bvinc83** [comment]
Yeah, I considered that.  But I'm not sure what the proper way to compile the openssl code under Cygwin is.  I'm guessing that openssl is expecting that under cygwin, _WIN32 is not defined.

gcc-rs adding -mwin32 as a default on Windows does seem like a bad idea.  I'll see what they say.

**Comment by cybergeek94** [comment]
@sfackler See the referenced issue above. Removing the flag fixes the `openssl-sys` build but the crate still won't compile on Windows.
