### ISSUE TITLE
SslStream::{connect, accept} should not return an SslStream<S>

### ISSUE THREAD

**Issue by cmr** [sfackler/rust-openssl#250]
This prevents giving `SslStream` a `RawFd` directly, for example, since it tries to treat it as `SslStream<RawFd>` and `RawFd` does not implement `Read` or `Write`. Instead, a special marker struct should be used that "implements" the relevant traits, since the impls are never used except to appease the type system.

**Comment by sfackler** [comment]
The 99% use case for `SslStream` is to wrap another Rust stream type. Why are you using a `RawFd` directly? Won't a `TcpStream` (with the underlying FD possibly tweaked via `as_raw_fd` or even constructed outright by `from_raw_fd`) suffice?

**Comment by cmr** [comment]
@sfackler `RawFd` is just an example, the exact usecase is with mio, whose `TcpStream` type is not clonable and thus wrapping it in an `SslStream` prevents me from using it in the event loop (since I'm required to move (or uniquely borrow with `&mut`) to satisfy the type requirements).

**Comment by cmr** [comment]
It also seems like a wart that it passes on the type - it never uses that information later, but requires users to have a compatible stream type (which may not always exist, and would need to be written)

**Comment by sfackler** [comment]
Streams created with the `*_generic` methods do call down into the wrapped stream - the fact that streams created with the others don't is an implementation detail.

I would be on board with fleshing out `DirectStream` and making it a public type for use cases that just want to pass in a `RawFd`.

**Comment by cmr** [comment]
Yes, but I'm not suggesting the `*_generic` methods change, just `connect` and `accept`.

**Comment by sfackler** [comment]
The `*_generic` methods are are crutch to work around the lack of specialization. They'll be removed when specialization is implemented.

**Comment by cmr** [comment]
I think the underlying issue ("can't use with mio") has been fixed by now?

**Comment by sfackler** [comment]
Yep
