### ISSUE TITLE
Failed to build at Win7, 64bit, Rust1.2

### ISSUE THREAD

**Issue by ScottHuangZL** [sfackler/rust-openssl#254]
https://users.rust-lang.org/t/i-try-to-build-a-nickel-example-but-gap-at-openssl-sys-0-6-4/2528

Please refer to attached link.
I am try to build a Nickel sample, gap at build openssl, can you help to resolve it?
Thanks.

**Comment by sfackler** [comment]
This portion of the README should be helpful: https://github.com/sfackler/rust-openssl#windows

**Comment by sfackler** [comment]
The 0.9 release has heavily overhauled the library lookup process.
