### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by manuels** [sfackler/rust-openssl#257]
It looks like the last crate release is about two month ago. But in the mean time there were a lot of commits added to rust-openssl.

Do you already have a schedule for the next release?

**Comment by thijsc** [comment]
A version bump would be nice :-)

**Comment by sfackler** [comment]
Ah, yeah, sorry, will push a release

**Comment by sfackler** [comment]
Released v0.6.5

**Comment by manuels** [comment]
Great, thanks, Steve!
