### ISSUE TITLE
How to make this crate play nice with other C code

### ISSUE THREAD

**Issue by thijsc** [sfackler/rust-openssl#264]
I've run into a problem where adding and initializing this crate breaks SSL connections when using the Mongo C driver. Looking at the [code in the driver](https://github.com/mongodb/mongo-c-driver/blob/master/src/mongoc/mongoc-ssl.c#L80) it looks like the C driver is doing similar global initialization and callback registering as the `openssl` crate.

Is there any known strategy to make the `openssl` crate play nice together with C code like this?

**Comment by thijsc** [comment]
I was thinking in a totally wrong direction :-), closing this one.

**Comment by sfackler** [comment]
Are you sure? I could add a `skip_initialization` function for cases like this if the current setup is a problem.

**Comment by thijsc** [comment]
It definitively wasn't the cause of the problem I was debugging, but I'm not ruling out that there might still be thread safety issues for example.

It's very confusing to me how this stuff is actually supposed to work in OpenSSL. You have this handler in the global state that you register callbacks on to lock your thread. I can't deduce from the docs wether it's a supported scenario to have multiple libraries do this, or if you overwrite the callbacks if you do it a second time.

I guess this should be possible since otherwise it would be impossible to use say libcurl doing https requests in the same process with a database connection over ssl?

Wouldn't it cause issues with libraries depending on `rust-openssl` if you skip initialization?
