### ISSUE TITLE
SslStream should return the owned stream when error occurs

### ISSUE THREAD

**Issue by zonyitoo** [sfackler/rust-openssl#271]
Currently, `SslStream::accept` and `SslStream::connect` will move the stream, but if the stream is set as non-blocking, `SSL_ERROR_WANT_WRITE` or `SSL_ERROR_WANT_READ` may occurs. In this circumstance, the stream should not be destroyed, but to be set into the event loop and wait for readable/writable events.

So I suggest the `SslStream` should provide a way to deal with `SSL_ERROR_WANT_WRITE` and `SSL_ERROR_WANT_READ`.

**Comment by sfackler** [comment]
There's now a separate NonblockingSslStream for this kind of use case.
