### ISSUE TITLE
Crypter should take `&mut self` in functions that mutate it's context

### ISSUE THREAD

**Issue by jakerr** [sfackler/rust-openssl#274]
[openssl::crypto::symm::Crypter](http://sfackler.github.io/rust-openssl/doc/v0.6.5/openssl/crypto/symm/struct.Crypter.html) has various functions `pad`, `init`, `update`, `finalize`, that I would expect to take `&mut self` to prevent accidental modification when borrowed. It may not be likely that someone would accidentally call `update` on a `Crypter` that they shouldn't own but I still think that for semantic consistency, APIs should take `&mut self` when they call stateful ffi functions which mutate a context that is held by a wrapper.

Do people agree or is this working as intended?

This would obviously be a breaking change to fix so would require a version bump.

**Comment by sfackler** [comment]
This has been resolved.
