### ISSUE TITLE
Respect potentials for errors from OpenSSL

### ISSUE THREAD

**Issue by nixpulvis** [sfackler/rust-openssl#278]
There are a lot of places where errors get swallowed from OpenSSL, this crate should preserve these, and keep the interfaces in-line with OpenSSL itself.

For example, from `pkey.rs:282-287`:

```rust
 let rv = ffi::RSA_public_encrypt(...);

if rv < 0 as c_int {
    vec!()
} else {
    r.truncate(rv as usize);
    r
}
```
When the documentation for for `RSA_public_encrypt` states:

> On error, -1 is returned; the error codes can be obtained by ERR_get_error.

**Comment by sfackler** [comment]
Yeah, a lot of the stuff on the crypto side is in need of an overhaul.

**Comment by nixpulvis** [comment]
Id be interested in helping out a bit, I'm new to OpenSSL however. Also might be nice to layout the design we'd want ahead of time.

**Comment by sfackler** [comment]
I believe the 0.8 release takes care of all of these issues.
