### ISSUE TITLE
Implement threadid_func

### ISSUE THREAD

**Issue by Manishearth** [sfackler/rust-openssl#281]
According to [this page](https://www.openssl.org/docs/manmaster/crypto/threads.html), `locking_function` and `threadid_func` must be implemented to use multithreaded code safely.

> threadid_func(CRYPTO_THREADID *id) is needed to record the currently-executing thread's identifier into id. The implementation of this callback should not fill in id directly, but should use CRYPTO_THREADID_set_numeric() if thread IDs are numeric, or CRYPTO_THREADID_set_pointer() if they are pointer-based. If the application does not register such a callback using CRYPTO_THREADID_set_callback(), then a default implementation is used - on Windows and BeOS this uses the system's default thread identifying APIs, and on all other platforms it uses the address of errno. The latter is satisfactory for thread-safety if and only if the platform has a thread-local error number facility.

"the address of errno" is afaict an incorrect way of identifying a thread (lldb gives me the same address in both threads -- I don't see _why_ this happens given that errno is in TLS, but ... *shrug*). 

This can cause very scary malloc bugs in openssl.

Code like the following in init would be nice (similar to https://github.com/sfackler/rust-openssl/blob/d9c22137114b61a10105c7c2065e423e33bb456f/openssl-sys/src/lib.rs#L241):

```
extern "C" void my_callback(CRYPTO_THREADID *id) {
   CRYPTO_THREADID_set_numeric(id, (unsigned long)gettid())
}

void init() {
  .....
  CRYPTO_THREADID_set_callback(my_callback)

}
```

I'm not sure if we should be using `gettid()` or the pthread method (the pthread one works on OS X too, which we need since the error is happening on an OS X machine).

cc @larsbergstrom

**Comment by sfackler** [comment]
I had thought that the default implementation was sufficient - do you know if this is due to some recent change in OSX's libc or something?

**Comment by Manishearth** [comment]
Not sure. I have yet to poke more into this (might not even be the root cause of our bug), but at first glance this looks fishy.

**Comment by Manishearth** [comment]
```

void pthreads_thread_id(CRYPTO_THREADID *tid)
{
    CRYPTO_THREADID_set_numeric(tid, (unsigned long)pthread_self());
}


/// ...

CRYPTO_THREADID_set_callback(pthreads_thread_id);
```

is what openssl does in its tests. We should do the same.

**Comment by sfackler** [comment]
We'll need some story for Windows though, right?

**Comment by Manishearth** [comment]
Openssl has the Windows story built in! :smile: 

https://github.com/openssl/openssl/blob/5f0580ccf126a4834a406423e15da5b8a8bdf993/crypto/thr_id.c#L200

**Comment by sfackler** [comment]
Ah cool. Could you open a PR? Otherwise i can probably get to it sometime tonight.

**Comment by Manishearth** [comment]
Right now I'm testing a mac-specific version, will get one done by the end of the day.
