### ISSUE TITLE
Documentation and project status

### ISSUE THREAD

**Issue by jimmycuadra** [sfackler/rust-openssl#291]
I think this project could benefit greatly from some documentation on the goals of the library, what the intended "finished" design might be, what types of stability promises are offered currently if at all, etc. Right now it's very difficult to tell what the state of the project is and what areas are in need of work. I've noticed several APIs in the openssl crate marked as deprecated and the library is still < 1.0, making it seem largely experimental.

**Comment by nixpulvis** [comment]
I agree, some APIs seem weird to me. Understanding if this library wants to try to build nice interfaces or stick closer to the interface of the openssl library would be nice.

**Comment by andrewtj** [comment]
There's a few gaps in the API for my use case that I'd like to address but I'm a bit uncertain about the project status. It looks like a bit of a backlog of issues has developed which probably doesn't help. Is it just you hacking on this @sfackler? Do you need some help? (Even just doing triage on issues or the like.)
