### ISSUE TITLE
Consider some means of supporting Common Crypto on OS X

### ISSUE THREAD

**Issue by alexchandel** [sfackler/rust-openssl#295]
On OS X, Apple has deprecated OpenSSL. While there are workarounds, Apple encourages users to link against the [Common Crypto](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man3/CC_crypto.3cc.html) functions. These actually  have a few advantages, the primary one being that they are in `libSystem.dylib`, and are thus available to all Rust applications without any additional link-time dependencies, unlike OpenSSL. Also, `libSystem.dylib` guarantees binary compatibility.

I'm not how much of the OpenSSL api exists directly within Common Crypto, and some discussion is probably necessary to determine whether some abstraction is necessary outside of this crate.

**Comment by sfackler** [comment]
I'm actually already working on such a library: https://github.com/sfackler/rust-security-framework

I think the long term goal is to have separate libraries that interface with OpenSSL, Security.framework, and Windows's crypto/TLS stuff, and then have a crate that sits on top of those and selects the library based on the target you're compiling for.

**Comment by alexchandel** [comment]
@sfackler good plan.
