### ISSUE TITLE
panicked at 'unexpected error ErrorSyscall with ret -1'

### ISSUE THREAD

**Issue by BenTheElder** [sfackler/rust-openssl#301]
I'm experiencing something like [`this`](https://github.com/sfackler/rust-openssl/issues/224) while working on overhauling the [`slack`](https://github.com/BenTheElder/slack-rs) library.
After running a simple test-bot for a little bit (it varies how long it runs for before crashing, but it's happened multiple times now) I get:
```
thread '<main>' panicked at 'unexpected error ErrorSyscall with ret -1', .cargo/registry/src/github.com-0a35038f75765ae4/openssl-0.6.7/src/ssl/mod.rs:983
```

I plan to catch panics in the bot and log then attempt to reconnect, but I found the previous issue while looking for possible causes and wanted to report it.

I'm on:
```
OSX 10.11.1
OpenSSL 1.0.2d installed with homebrew
Rust 1.4 stable
rust-openssl 0.6.7
```
Using the [`devel`](https://github.com/BenTheElder/slack-rs/tree/devel) branch of the `slack` crate.
Other than the initial login request via hyper, the rest is over a websocket using [`rust-websocket`](https://github.com/cyderize/rust-websocket).

**Comment by sfackler** [comment]
v0.7.2 significantly overhauls the SslStream implementation. This shouldn't be a problem anymore.

**Comment by BenTheElder** [comment]
Quick feedback:
I've just finished the new `slack` release and as part of that updated to all dependencies to their latest versions (`^0.7` for `openssl`). I've had a client running for nearly a day now without any panics so far.
Thanks!

**Comment by sfackler** [comment]
Great, glad to hear it's working!

**Comment by alkis** [comment]
Because of the big changes and the some api deprecations shouldn't this be a version bump?

Also it seems that this broke Mac OS X: https://github.com/housleyjk/ws-rs/issues/17. Do you want me to open a separate bug for it?

**Comment by BenTheElder** [comment]
Not the author or a contributor to `rust-openssl` but:

I think for most rust projects the minor version is used like the major version before `1.x` since `0.x.x` signals "pre-release" status and isn't really considered api stable between minor version yet. At least, that seems to be what I've seen and how I've handled it so far.

As for OS X, I'm using `0.7.2` currently on el capitan. I am however using a different websocket library (`rust-websocket`), so I'd hazard at the websocket library having a bug rather than rust-openssl. I'll leave another comment about that over at the linked `ws-rs` issue.

**Comment by sfackler** [comment]
@alkis you should file a separate bug if you can track it down specifically to the 0.7.1/0.7.2 boundary.
