### ISSUE TITLE
Split openssl-sys into openssl-sys and openssl_shim

### ISSUE THREAD

**Issue by kryptan** [sfackler/rust-openssl#302]
Currently `openssl-sys` can only be configured via environment variables. This is in contrast to the more common way of [overriding build scripts](http://doc.crates.io/build-script.html#overriding-build-scripts) which can be used for most other *-sys crates. It doesn't work for `openssl-sys` because it generates and compiles `libopenssl_shim` library and overriding build script prevents its generation.

To fix this I propose to split `openssl-sys` into two crates: `openssl-sys` and `openssl_shim`.
1. `openssl-sys` defines `links = "openssl"` and build script does everything it does today except generating and compling `libopenssl_shim`.
2. `openssl_shim` depends on `openssl-sys` and defines no `links`. In its build script it builds `libopenssl_shim`; openssl include directory is provided by the `include` variable generated by the `openssl-sys`.

`openssl` will depend on both `openssl-sys` and `openssl_shim`.

This way it will be posible to overwrite build script in `.cargo/config` by providing the following variables: `rustc-link-search`, `rustc-link-lib`, `include`.

**Comment by sfackler** [comment]
I'm actually currently work on this on the breaks branch! https://github.com/sfackler/rust-openssl/tree/breaks

There's some weirdness going on on travis with some test that I have to figure out before being able to roll it out though.

**Comment by sfackler** [comment]
Done in v0.7
