### ISSUE TITLE
Apparent openssl_shim conflicts around HMAC_CTX_copy

### ISSUE THREAD

**Issue by wagenet** [sfackler/rust-openssl#304]
I'm not sure if this is an issue with this project, but it seems like openssl_shim may be causing conflicts.

```
gcc --shared -Wall -o target/dist/i386-linux/libskylight.so target/dist/i386-linux/objs/*.o -lrt -ldl -lpthread -lgcc_s -lc -lm -Wl,--gc-sections -Wl,--version-script ./skylight.map
target/dist/i386-linux/objs/openssl_shim.o: In function `HMAC_CTX_copy':
openssl_shim.c:(.text.HMAC_CTX_copy+0x0): multiple definition of `HMAC_CTX_copy'
target/dist/i386-linux/objs/hmac.o:hmac.c:(.text.HMAC_CTX_copy+0x0): first defined here
/usr/bin/ld: Warning: size of symbol `HMAC_CTX_copy' changed from 181 in target/dist/i386-linux/objs/hmac.o to 147 in target/dist/i386-linux/objs/openssl_shim.o
```

**Comment by sfackler** [comment]
It looks like the headers that the shim is building against are not synchronized with the binary you're linking against - that function will only be defined if OpenSSL's version as reported from its headers is less than 1.0: https://github.com/sfackler/rust-openssl/blob/master/openssl-sys/src/openssl_shim.c#L32

**Comment by wagenet** [comment]
@sfackler hmm, I'm intending to be building against a version greater than 1.0. Presumably, it's picking up the wrong version.

**Comment by wagenet** [comment]
I seem to have done something on my end to resolve this. False alarm I guess.
