### ISSUE TITLE
Make MaybeSslStream clonable

### ISSUE THREAD

**Issue by the-kenny** [sfackler/rust-openssl#308]
Right now I'm using one main thread to send data to a socket and a second thread to read & parse the returned data. 

Without SSL, I can clone the ```TcpStream``` via ```try_clone()```. I can also clone a ```SslStream``` via the same function.

What I can't do is clone ```MaybeSslStream``` which prevents me from implementing optional SSL support.

Is there any chance ```MaybeSslStream``` can get ```try_clone()``` too? If not, is there another way to get that behavior?

Note that #6 was the ticket about ```TcpStream``` implementing ```Clone```.

**Comment by sfackler** [comment]
Should be fine, in the same kind of unfortunate way we do it now for `SslStream<TcpStream>`
