### ISSUE TITLE
X509 cert/key pair generation is nondeterministic

### ISSUE THREAD

**Issue by jimmycuadra** [sfackler/rust-openssl#327]
Given the following program:

```rust
extern crate openssl;

use openssl::nid::Nid;
use openssl::x509::X509Generator;
use openssl::x509::extension::Extension;

fn main() {
    let ca_gen = X509Generator::new()
        .add_extension(Extension::OtherNid(Nid::SubjectKeyIdentifier, "hash".to_owned()))
        .add_extension(Extension::OtherNid(Nid::AuthorityKeyIdentifier, "keyid:always".to_owned()));

    ca_gen.generate().expect("failed to generate CA cert and key");
}
```

Running the program sometimes completes successfully and sometimes panics with:

```
thread '<main>' panicked at 'failed to generate CA cert and key: OpenSslErrors([UnknownError { library: "X509 V3 routines", function: "V2I_AUTHORITY_KEYID", reason: "unable to get issuer keyid" }])', src/libcore/result.rs:757
```

It seems that the order of operations is not deterministic, because OpenSSL is not always able to find a key ID to use for authorityKeyIdentifier. (In this case, it's for a self-signed CA certificate so the subjectKeyIdentifier and AuthorityKeyIdentifier should be the same value: the ID of the CA's own public key.) I've tried it with the two `add_extension` calls in reverse order, and the behavior is the same.

**Comment by jmesmon** [comment]
extensions are internally stored in a hash map prior to being inserted (via signing) into the certificate being generated (this is why the order of insertion is non-deterministic).

Is the issue that there are particular orderings required when inserting certain extensions?

In that case, we'd probably need to adjust the internal tracking of extension additions to keep them in insertion-order.

**Comment by jimmycuadra** [comment]
Conceptually, the requirement for the two extensions shown in my code snippet is that there is a public key associated with the certificate being generated, because the value of both extensions is a hash of that key.

I don't know the details of the implementation so I'm not sure what the exact order of operations it's expecting are, but if the Subject Key Identifier extension *has* to be added before the Authority Key Identifier extension because the former is the only one that actually generates the ID which the latter uses, that would follow what you're describing.

**Comment by jimmycuadra** [comment]
After some more testing and research, I'm pretty sure that the order the extensions are added in is significant and that is the cause of the problem I reported. Here's an example of the same issue being discussed via the Python bindings to OpenSSL: https://stackoverflow.com/questions/14972345/creating-self-signed-certificate-using-pyopenssl.

Is there a reason that the extensions are not added immediately when `add_extension` is called, instead waiting to do it all at once when actually signing the certificate? If not, this issue could be fixed by simply adding them immediately. If it's necessary to defer adding them until the cert is signed, then I could change the implementation to use both a `Vec` and a `HashMap` to preserve both ordering and uniqueness of each extension. Or is there a more efficient way to implement it?

**Comment by jimmycuadra** [comment]
I could implement the fix with the [linked-hash-map](https://github.com/contain-rs/linked-hash-map) crate, except that it doesn't build on stable Rust yet because it uses the `hashmap_hasher` feature, which is very close to being stabilized, but isn't as of Rust 1.6. Also, I'm not sure if the maintainers of rust-openssl have a policy on adding new dependencies.

**Comment by sfackler** [comment]
Linked hash maps are what I would probably jump to as well, but I wouldn't want to pull in that crate until 1.8 lands (hashers are going to be stable in 1.7 and I like to support at least one Rust version back).

In the meantime, a simple `Vec<(Key, Value)>` should work well enough. It'll be inefficient but I don't think people are shoving hundreds of extensions into their certs and it'll be simple at least.
