### ISSUE TITLE
Relicense under dual MIT/Apache-2.0

### ISSUE THREAD

**Issue by cmr** [sfackler/rust-openssl#331]
This issue was automatically generated. Feel free to close without ceremony if
you do not agree with re-licensing or if it is not possible for other reasons.
Respond to @cmr with any questions or concerns, or pop over to
`#rust-offtopic` on IRC to discuss.

You're receiving this because someone (perhaps the project maintainer)
published a crates.io package with the license as "MIT" xor "Apache-2.0" and
the repository field pointing here.

TL;DR the Rust ecosystem is largely Apache-2.0. Being available under that
license is good for interoperation. The MIT license as an add-on can be nice
for GPLv2 projects to use your code.
# Why?

The MIT license requires reproducing countless copies of the same copyright
header with different names in the copyright field, for every MIT library in
use. The Apache license does not have this drawback. However, this is not the
primary motivation for me creating these issues. The Apache license also has
protections from patent trolls and an explicit contribution licensing clause.
However, the Apache license is incompatible with GPLv2. This is why Rust is
dual-licensed as MIT/Apache (the "primary" license being Apache, MIT only for
GPLv2 compat), and doing so would be wise for this project. This also makes
this crate suitable for inclusion and unrestricted sharing in the Rust
standard distribution and other projects using dual MIT/Apache, such as my
personal ulterior motive, [the Robigalia project](https://robigalia.org).

Some ask, "Does this really apply to binary redistributions? Does MIT really
require reproducing the whole thing?" I'm not a lawyer, and I can't give legal
advice, but some Google Android apps include open source attributions using
this interpretation. [Others also agree with
it](https://www.quora.com/Does-the-MIT-license-require-attribution-in-a-binary-only-distribution).
But, again, the copyright notice redistribution is not the primary motivation
for the dual-licensing. It's stronger protections to licensees and better
interoperation with the wider Rust ecosystem.
# How?

To do this, get explicit approval from each contributor of copyrightable work
(as not all contributions qualify for copyright, due to not being a "creative
work", e.g. a typo fix) and then add the following to your README:

```
## License

Licensed under either of

 * Apache License, Version 2.0, ([LICENSE-APACHE](LICENSE-APACHE) or http://www.apache.org/licenses/LICENSE-2.0)
 * MIT license ([LICENSE-MIT](LICENSE-MIT) or http://opensource.org/licenses/MIT)

at your option.

### Contribution

Unless you explicitly state otherwise, any contribution intentionally submitted
for inclusion in the work by you, as defined in the Apache-2.0 license, shall be dual licensed as above, without any
additional terms or conditions.
```

and in your license headers, if you have them, use the following boilerplate
(based on that used in Rust):

```
// Copyright 2016 rust-openssl Developers
//
// Licensed under the Apache License, Version 2.0, <LICENSE-APACHE or
// http://apache.org/licenses/LICENSE-2.0> or the MIT license <LICENSE-MIT or
// http://opensource.org/licenses/MIT>, at your option. This file may not be
// copied, modified, or distributed except according to those terms.
```

It's commonly asked whether license headers are required. I'm not comfortable
making an official recommendation either way, but the Apache license
recommends it in their appendix on how to use the license.

Be sure to add the relevant `LICENSE-{MIT,APACHE}` files. You can copy these
from the [Rust](https://github.com/rust-lang/rust) repo for a plain-text
version.

And don't forget to update the `license` metadata in your `Cargo.toml` to:

```
license = "MIT OR Apache-2.0"
```

I'll be going through projects which agree to be relicensed and have approval
by the necessary contributors and doing this changes, so feel free to leave
the heavy lifting to me!
# Contributor checkoff

To agree to relicensing, comment with :

```
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.
```

Or, if you're a contributor, you can check the box in this repo next to your
name. My scripts will pick this exact phrase up and check your checkbox, but
I'll come through and manually review this issue later as well.
- [ ] @sfackler
- [ ] @manuels
- [x] @vhbit
- [x] @kballard
- [x] @erickt
- [x] @jmesmon
- [x] @cjcole
- [x] @alexcrichton
- [ ] @elly
- [ ] @gkoz
- [x] @DiamondLovesYou
- [x] @mlalic
- [x] @ebfe
- [x] @randombit
- [x] @Geal
- [x] @jedisct1
- [x] @jroesch
- [x] @mvdnes
- [x] @andrew-d
- [x] @Manishearth
- [x] @josephglanville
- [x] @zzmp
- [x] @Cyberunner23
- [x] @aatxe
- [ ] @Noxivs
- [x] @semmaz
- [ ] @pyrho
- [x] @cybergeek94
- [x] @alex
- [ ] @brson
- [ ] @brycefisher
- [x] @chris-morgan
- [x] @Ryman
- [x] @operutka
- [x] @reaperhulk
- [x] @retep998
- [ ] @quentinbaradat
- [ ] @xorpse
- [x] @kinghajj
- [x] @uasi
- [ ] @wg
- [ ] @bheart
- [x] @bozaro
- [x] @bombless
- [ ] @akiss77
- [x] @andor44
- [ ] @ajroetker
- [x] @brunoqc
- [x] @CarlColglazier
- [x] @coyotebush
- [x] @dkhenry
- [x] @davbo
- [x] @ebarnard
- [x] @cheme
- [x] @Kroisse
- [x] @fhartwig
- [x] @Florob
- [x] @glennw
- [x] @isra17
- [x] @jameshurst
- [x] @jamwt
- [x] @yjerem
- [x] @jimmycuadra
- [x] @jtdowney
- [x] @reem
- [x] @larsbergstrom
- [x] @ltratt
- [x] @mbrubeck
- [x] @zr40
- [x] @maximih
- [ ] @miloshadzic
- [x] @Ms2ger
- [x] @nixpulvis
- [x] @nstoddard
- [x] @overminder
- [x] @globin
- [x] @seanmonstar
- [x] @Byron
- [x] @s-panferov
- [ ] @boggle
- [x] @thommay
- [x] @Ummon
- [x] @gentoo90
- [ ] @iseki-masaya
- [x] @panicbit
- [ ] @radare

**Comment by manuels** [comment]
WTF is this? A new kind of spam? You are opening more than 100 issues automatically??

**Comment by cmr** [comment]
@manuels yes, approximately 1600 issues over the course of a few days. please note that many, many people have been appreciative of these issues.

**Comment by erickt** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by cmr** [comment]
Pinging  because of github @-mention limit:

@coyotebush
@dkhenry
@davbo
@ebarnard
@cheme
@Kroisse
@fhartwig
@Florob
@glennw
@isra17
@jameshurst
@jamwt
@yjerem
@jimmycuadra
@jtdowney
@reem
@larsbergstrom
@ltratt
@mbrubeck
@zr40
@maximih
@miloshadzic
@Ms2ger
@nixpulvis
@nstoddard
@overminder
@globin
@seanmonstar
@Byron
@s-panferov
@boggle
@thommay
@Ummon
@gentoo90
@iseki-masaya
@panicbit
@radare

**Comment by erickt** [comment]
@cmr: can you sort this list? It'd be easier to find oneself in it.

**Comment by bozaro** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by cmr** [comment]
@erickt my script is checking people off who include "r+", "I consent", or the recommended boilerplate automatically, you don't need to check yourself off.

**Comment by retep998** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by nixpulvis** [comment]
:+1: seems like a good idea.

**Comment by frewsxcv** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by nixpulvis** [comment]
r+

**Comment by Byron** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by kballard** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by coyotebush** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by Manishearth** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by coyotebush** [comment]
There seem to be three crates ([1](https://crates.io/crates/openssl/) [2](https://crates.io/crates/openssl-sys/) [3](https://crates.io/crates/openssl-sys-extras/)) linked to this repository, not all indicating the same license. It might have been nice to include a link to the crate in question in the original issue?

**Comment by cheme** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by cmr** [comment]
I don't recommend licensing -sys crates differently from the underlying library being bound to.

**Comment by zr40** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by alex** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by Cyberunner23** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by reaperhulk** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by ebarnard** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by aatxe** [comment]
r+

**Comment by larsbergstrom** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by andrew-d** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by dkhenry** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by isra17** [comment]
r+

**Comment by jamwt** [comment]
r+

**Comment by yjerem** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by reem** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by fhartwig** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by panicbit** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by Florob** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by glennw** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by jedisct1** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by ltratt** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by operutka** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by jmesmon** [comment]
r+

**Comment by CarlColglazier** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by maximih** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by davbo** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by Ryman** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by jimmycuadra** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by overminder** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by josephglanville** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by randombit** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by brunoqc** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by chris-morgan** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by nstoddard** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by semmaz** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by cybergeek94** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by jtdowney** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by globin** [comment]
r+

**Comment by kinghajj** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by uasi** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by mlalic** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by thommay** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by vhbit** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by gkoz** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by Geal** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by cjcole** [comment]
r+

**Comment by gentoo90** [comment]
r+

**Comment by Ms2ger** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by Ummon** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by andor44** [comment]
r+

**Comment by mbrubeck** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by seanmonstar** [comment]
r+

**Comment by mvdnes** [comment]
r+

**Comment by DiamondLovesYou** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by jameshurst** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by jroesch** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by bombless** [comment]
r+

**Comment by ebfe** [comment]
r+

**Comment by zzmp** [comment]
r+

**Comment by s-panferov** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by Kroisse** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.

**Comment by brycefisher** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to chose either at their option.
