### ISSUE TITLE
Calling set_ssl_context() twice with the same context causes Undefined Behavior

### ISSUE THREAD

**Issue by jmesmon** [sfackler/rust-openssl#333]
```
pub fn set_ssl_context(&self, ctx: &SslContext) -> SslContext
```

One passes in a `&SslContext`, but gets back an owned `SslContext`. This allows double-freeing of any SslContext, just call `set_ssl_context()` twice with the same context. Can be the same `Ssl`/`self` or a different one.

Right now I'm avoiding this by doing:
```
mem::forget(ssl.set_ssl_context(&ctx));
```

But this probably isn't perfectly correct (I track all my contexts in `Arc`s, and really need to convert them back to `Arc`s to decrease the ref count), but leaking memory is quite a bit better than crashing.

**Comment by jmesmon** [comment]
An idea about solving this:

- write `set_ssl_context<T: Any + AsRef<SslContext>>(&self, ctx: T) -> T`
- Store the `T` in `Ssl` using `SSL_get_ex_new_index()` and friends
- impl `AsRef<SslContext>` for `SslContext` but not for `&SslContext`.
- Problems:
 - we'd need to panic (or otherwise safely fail) if `T` isn't a `T` that we've stored.
 - other than `set_ssl_context()`, we'd need to update `Ssl::new()` and `get_ssl_context()`
- Solves:
 - no double free
 - allows users to select their own way of tracking contexts.

Better idea (but even more api invasive):

- Change `Ssl` to `Ssl<Ctx: Any + AsRef<SslContext>>`
- `set_ssl_context()`/`get_ssl_context()`/`new()` use the parameter type `Ctx`.
- Tracking of Ctx container similar to above.
- Removes issues around differing types of Context containers (user can't try to get one that doesn't exist).

Generally:
 - Both of these still add some overhead (extra `ex_data` in most `Ssl`s, unless there is specialization done for a bare `SslContext`)
 - Bound on `Ctx` (context container) might be inconvenient.

**Comment by sfackler** [comment]
OpenSSL objects maintain an internal object reference count - I think all we'll need to do is to appropriately adjust that.

**Comment by sfackler** [comment]
For example https://github.com/sfackler/rust-openssl/blob/master/openssl/src/ssl/mod.rs#L966

**Comment by jmesmon** [comment]
Ah, yep, that would fix things (and be pretty simple). It wasn't immediately clear that was the case as SslContext doesn't expose a `clone()` method.

I suppose that (not exposing `clone`) is intentional?

**Comment by sfackler** [comment]
I wouldn't necessarily say that it's intentional. I think it should be fine to add? The refcount adjustment logic was added for SNI support, so it's pretty recent.

**Comment by jmesmon** [comment]
Looking at the openssl impl of `SSL_set_SSL_CTX()`, it appears that the refcount of the new ctx is incremented by 1, and the _new_ ctx is the thing returned (I had previously assumed it was returning the old ctx, but it turns out it just frees that one).

It seems like we could avoid this entire issue by just not returning the `SslContext` from `set_ssl_context()` calls.

Appears that the intention of the `SSL_set_SSL_CTX()` is to have the `SSL_CTX *ctx` imply passing ownership of the `ctx` to the function, and then being given back ownership via the return value (I can't find any documentation for `SSL_set_SSL_CTX()`, so this is all guesswork).

That said, if the goal is not to change the API it appears incrementing the refcount should work.
