### ISSUE TITLE
lint raw_pointer_derive has been removed

### ISSUE THREAD

**Issue by sorccu** [sfackler/rust-openssl#335]
May have happened earlier, but at least on nightly-2016-01-18, I'm getting a bunch of warnings saying:

> warning: lint raw_pointer_derive has been removed: using derive with raw pointers is ok

I would submit a PR but I'm not sure how it would affect building on stable Rust, which I don't use.

**Comment by sfackler** [comment]
raw_pointer_derive is only a warning in stable rust, so it should be fine to just remove the `#[allow]`. I'd hold off until the lint change hits stable though, which I think is Thursday.

**Comment by sfackler** [comment]
Closed by #339
