### ISSUE TITLE
pkg-config can't be used when statically linking C openssl libraries 

### ISSUE THREAD

**Issue by yberreby** [sfackler/rust-openssl#351]
On non-Windows targets, if both the `OPENSSL_LIB_DIR` and  `OPENSSL_INCLUDE_DIR` environment variables are undefined at build time, [`openssl-sys`'s build script will use `pkg-config` to discover libssl and libcrypto](https://github.com/sfackler/rust-openssl/blob/master/openssl-sys/build.rs#L14-L31).

The problem is, it [exits early](https://github.com/sfackler/rust-openssl/blob/master/openssl-sys/build.rs#L23) in this case, and [the portion of the code that allows static linking](https://github.com/sfackler/rust-openssl/blob/master/openssl-sys/build.rs#L47-L51) is never reached. The user is therefore forced to specify either `OPENSSL_LIB_DIR` or `OPENSSL_INCLUDE_DIR`, or to forgo static linking.

The `pkg-config` crate [claims to support discovery of static libraries](http://alexcrichton.com/pkg-config-rs/pkg_config/index.html), so it [should be possible](http://alexcrichton.com/pkg-config-rs/pkg_config/struct.Config.html) to modify the build script to use this feature in case only `OPENSSL_STATIC` is passed.

```
$ cargo clean -p openssl-sys
$ env OPENSSL_LIB_DIR=/usr/local/lib/ OPENSSL_STATIC=yes cargo build
   Compiling openssl-sys v0.7.5
   Compiling openssl v0.7.5
   ....
$ otool -L target/debug/extra
target/debug/extra:
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)

$ cargo clean -p openssl-sys
$ env OPENSSL_STATIC=yes cargo build
   Compiling openssl-sys v0.7.5
   ...
$ otool -L target/debug/extra
target/debug/extra:
    /usr/local/opt/openssl/lib/libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
    /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
```

(`otool -L` ~= `ldd` on OS X)

Related issue: https://github.com/sfackler/rust-openssl/issues/183#issuecomment-81686336

**Comment by sfackler** [comment]
Ah yeah, that does look wrong. Should just be a matter of calling `pkg_config::Config::statik` as you pointed out.

**Comment by yberreby** [comment]
@sfackler I wasn't sure `static` would do the trick but I'll try and make a PR then.

**Comment by sfackler** [comment]
It's also worth noting that pkg-config-rs has some weird behavior if pkg-config finds openssl in "system" lib directories - it won't actually request it to be statically linked: https://github.com/alexcrichton/pkg-config-rs/blob/master/src/lib.rs#L222

cc @alexcrichton

**Comment by alexcrichton** [comment]
Yeah it's kind of a problem in general that `pkg-config --static` just dumps *all* dependencies, many of which are system ones (like libz). Unfortunately I don't really know of a way to say "just this package's libs as static libs" or something like that.

**Comment by jmesmon** [comment]
I'm not seeing why we would even want to filter out "system" dependencies: these are real dependencies for the library. You need them. And it isn't correct to try to substitute in other versions of them (for example: trying to mix the system openssl and a locally compiled libz is wrong.

**Comment by sfackler** [comment]
The 0.9 release has heavily overhauled the library lookup process.
