### ISSUE TITLE
How can I switch off the SslStream's retry logic?

### ISSUE THREAD

**Issue by phifty** [sfackler/rust-openssl#354]
The program writes on an SslStream and if the connection is working, all is fine. If the connection is lost, I would expect to operation to fail. Instead it seems, the SslStream retries to write the buffer and blocks during that. How can I disable to logic? Is there a way?

**Comment by sfackler** [comment]
I'm not sure I totally understand what's going on - could you go into a bit more detail? What kind of error is coming out of the downstream socket?

**Comment by phifty** [comment]
There is actually no error coming out - it just hangs when a write on a broken `SslStream` is tried. I would not exclude that the problem is in my code, but it would help to understand what I should expect. Should there be an error if the `SslStream` is broken (the other side closed the connection)? Is there a retry logic? Is there a way to set read/write timeouts (like on `net::TcpStream`)?

**Comment by sfackler** [comment]
What system calls are being made? You can use something like strace to find out.

`SslStream` is just a wrapper around an underlying stream, which you can get access to via the `get_ref` method. If you have an `SslStream<TcpStream>`, you can set a read or write timeout like `my_ssl_stream.get_ref().set_read_timeout(Some(Duration::from_secs(1)))`.

**Comment by phifty** [comment]
Settings the timeout helped. Thanks for that!
