### ISSUE TITLE
Incorporate generic SSL/TLS methods for context initialisation

### ISSUE THREAD

**Issue by ArturoVM** [sfackler/rust-openssl#357]
Hello :)

I'm using rust-openssl in one of my projects, and I noticed that it doesn't support the generic methods that allow protocol re-negotiation as described in the notes section [of this man page](https://www.openssl.org/docs/manmaster/ssl/SSL_CTX_new.html).

I don't know how trivial this would be to implement, but if it merely involves exposing them through the FFI, I'd be glad to make the changes and issue a PR.

Thanks!

**Comment by sfackler** [comment]
You're talking about `TLS_method` I'm guessing? It should be very easy to add, following the pattern of the other methods. The FFI binding goes here: https://github.com/sfackler/rust-openssl/blob/master/openssl-sys/src/lib.rs#L613, and then the publicly exposed enum here will need to be updated: https://github.com/sfackler/rust-openssl/blob/master/openssl/src/ssl/mod.rs#L122-L186. `TLS_method` was added relatively recently, so we'll want to put it behind a Cargo feature like many of the other ones, which are defined in the Cargo.tomls.

**Comment by sfackler** [comment]
Should also be noted that the `Sslv23` method (confusingly) behaves in the same way as `TLS_method`.
