### ISSUE TITLE
Document DEP_OPENSSL_INCLUDE

### ISSUE THREAD

**Issue by brson** [sfackler/rust-openssl#368]
I'm not even sure what it is for, but I had to set it to `C:\OpenSSL-Win64\include` in order to build rustup on Windows. I tried to set `OPENSSL_INCLUDE_DIR` unsuccessfully before discovering this variable in the source.

**Comment by sfackler** [comment]
It is a variable that's set by Cargo at the instruction of `openssl-sys`. Run cargo clean with correct values of `OPENSSL_INCLUDE_DIR` and `OPENSSL_LIB_DIR` and rebuild.

**Comment by brson** [comment]
Thanks for the hint @sfackler! I still haven't gotten everything to build, but I've used `OPENSSL_INCLUDE_DIR` and `OPENSSL_LIB_DIR` successfully.

**Comment by 0xpr03** [comment]
I'm sorry but I've to disagree, I've tried it multiple times today with different setups.
Only using `DEP_OPENSSL_INCLUDE` worked as variable.
