### ISSUE TITLE
Link to working openssl binaries

### ISSUE THREAD

**Issue by Diggsey** [sfackler/rust-openssl#369]
The precompiled openssl binaries linked to in the readme do not link correctly for all (any?) versions of visual studio when statically linking. This site has working binaries for all visual studio versions, both dynamically and statically linked:

http://www.npcglib.org/~stathis/blog/precompiled-openssl/

**Comment by sfackler** [comment]
I feel a bit uneasy in general about linking so some random person's binaries - does this source seem to be used reasonably heavily?

**Comment by Diggsey** [comment]
I did a lot of searching, and AFAICT they're the *only* binaries that statically link correctly under MSVC. I understand your uneasiness: can we at least for the moment put a warning over the current link explaining that those binaries will not work when statically linking, it wastes a lot of time downloading and setting up environment variables, only to find that they don't even work.

I'm not sure what the best option is, but here's some other possibilities:
1) Build openssl from source from the build script
2) Build "official" rust openssl binaries, and maybe have the build script download them
3) Find some way to get the existing binaries to work, maybe just needs some different linker options or an intermediary layer

**Comment by sfackler** [comment]
Anything that involves this crate building OpenSSL from source or downloading "official" versions that we build elsewhere scares me a bit - I don't want to be responsible for rushing out new releases the next time some crazy vulnerability gets discovered in OpenSSL.

**Comment by retep998** [comment]
Static linking requires that the libraries be compiled with the exact same version of msvc. Also that several settings for how they were compiled are also the same. If any of these important details don't match then stuff will very likely break. The only way to make static linking reliably work is to build openssl yourself on the spot.
