### ISSUE TITLE
Send for BIO_METHOD?

### ISSUE THREAD

**Issue by jwilm** [sfackler/rust-openssl#370]
Hi @sfackler 

Ran into an issue updating Solicit to rust-openssl 0.7 from 0.6. It looks like the BIO_METHOD type now includes a raw pointer which is `!Send`. Is there any reason the BIO_METHOD is actually `!Send`? It currently has a `Sync` impl.

```
src/http/client/tls.rs:179:6: 179:22 note: `*const i8` cannot be sent between threads safely
src/http/client/tls.rs:179:6: 179:22 note: required because it appears within the type `openssl_sys::BIO_METHOD`
src/http/client/tls.rs:179:6: 179:22 note: required because it appears within the type `openssl::ssl::SslStream<std::net::tcp::TcpStream>`
```

**Comment by sfackler** [comment]
The lack of `Send` is an oversight - we should tack on `unsafe impl Send for Foo {}` for all of the structs in the sys crate.

**Comment by jwilm** [comment]
*All* of the structs? I can send a PR for that real quick if it's that simple.

**Comment by sfackler** [comment]
Yep! It's the job of the things wrapping types defined in sys crates to expose a safe API, not the job of the sys crate itself.

**Comment by jwilm** [comment]
The question turns out to be, is `SslStream : Send`? It seems that the only `!Send` thing in `SslStream` is the `BIO_METHOD`. I'm not super comfortable with an `unsafe impl Send for SslStream` since something that is `!Send` could inadvertently be added without warning. Rather, we should probably add a `BioMethod` wrapper and `unsafe impl Send` on that.

**Comment by sfackler** [comment]
That plan sounds good to me!
