### ISSUE TITLE
Create PKey from provided public modulus and exponent? 

### ISSUE THREAD

**Issue by omniusaspirer** [sfackler/rust-openssl#375]
I'm interfacing with a web server and have been provided with an RSA public modulus and exponent. From this I need to build the public key so I can encrypt a password before sending it to the server. Is this functionality exposed within the openssl crate itself and I'm failing to find/understand it? Or do I need to work within openssl-sys for this?

**Comment by sfackler** [comment]
I believe you should be able to use [`RSA::from_public_components`](http://sfackler.github.io/rust-openssl/doc/v0.7.9/openssl/crypto/rsa/struct.RSA.html#method.from_public_components) followed by [`PKey::new`](http://sfackler.github.io/rust-openssl/doc/v0.7.9/openssl/crypto/pkey/struct.PKey.html#method.new) and [`PKey::set_rsa`](http://sfackler.github.io/rust-openssl/doc/v0.7.9/openssl/crypto/pkey/struct.PKey.html#method.set_rsa).

**Comment by omniusaspirer** [comment]
Thanks for the guidance! That's what I was attempting to do when I asked this question, but I'd messed up some syntax in some earlier unrelated code giving me faulty inputs. Got it all working now, feel a bit silly for asking with how simple it ended up being- joys of being new to a language. 

For anyone's future reference :
```rust
let rsa = RSA::from_public_components(modulus, exponent).unwrap();
let mut pkey = PKey::new();
pkey.set_rsa(&rsa);
```

**Comment by sfackler** [comment]
Great, glad you got things working!
