### ISSUE TITLE
Determining the version of libopenssl

### ISSUE THREAD

**Issue by Yoric** [sfackler/rust-openssl#378]
I haven't found a way to display the version of OpenSSL to which this crate is linked. It would be useful for troubleshooting.

**Comment by sfackler** [comment]
Should be easy to do by binding to https://www.openssl.org/docs/man1.0.2/crypto/SSLeay_version.html. Do you think you'd have the time/interest to make a PR? I can handle it in the next couple of days otherwise.

**Comment by Yoric** [comment]
@sfackler  I can try. In which module would you put it?

**Comment by sfackler** [comment]
Hmm, good question. Probably a function called `version` in the root module?
