### ISSUE TITLE
Error when building on OSX, targeting Android

### ISSUE THREAD

**Issue by GlenDC** [sfackler/rust-openssl#383]
When I try to build this lib targeting android (as a dependency for another library), I get linking errors related to the native openssl libraries.

I'm targeting: `arm-linux-androideabi`

This is the specific error message:

    note: /Users/glendc/.android/toolchains/A18-arm-4.8/bin/../lib/gcc/arm-linux- androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: ssl: no archive symbol table (run ranlib)
    
    /Users/glendc/.android/toolchains/A18-arm-4.8/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: error: crypto: no archive symbol table (run ranlib)

**Comment by sfackler** [comment]
Did you configure the compiler that's used by gcc-rs? It looks at the `CC_arm-linux-androideabi` environment variable.

**Comment by GlenDC** [comment]
I have this in my global cargo config:

    [target.arm-linux-androideabi]
    linker = "arm-linux-androideabi-gcc"

Do I need to specify also the compiler?

**Comment by sfackler** [comment]
That controls the executable that rustc uses to link binaries. The environment variable controls the executable that the gcc-rs library uses to compile C code.

**Comment by sfackler** [comment]
You may also need to set `LD_arm-linux-androideabi`

**Comment by GlenDC** [comment]
OK I got it working, by actually having the libraries available for android. The environment variables you talked about were already set. Is there a way to make openssl-rust use the static linked libraries rather than the dynamic ones?

**Comment by sfackler** [comment]
You can set `OPENSSL_STATIC` to 1 and it should statically link to openssl if you have static archives for it.

**Comment by GlenDC** [comment]
Sorry I never had to do such a thing before. How would I do that? As I'm not building OpenSSL-rs myself, but as a dependency of hyper, the library I'm using for HTTP requests.

**Comment by sfackler** [comment]
You can set that environment variable before the build - it'll be visible to this library when it gets built:

```
cargo clean
env OPENSSL_STATIC=1 cargo build
```

**Comment by GlenDC** [comment]
Ok that works, thx a lot @sfackler.
Perhaps you could add all of this as information to this project's README.
For now there is no section for either iOS or Android. It wasn't clear to me for example, that I had to provide the OpenSSL libraries myself for each target platform.

But other than that, I guess you could close this issue as it does now work.

**Comment by leeola** [comment]
@sfackler Is there a way to improve this? I suppose i could just start using a build script..

By improve this, i mean take queues from cargo configs or something to that effect. Environment variables can be nice for versatility, but they don't help me distribute the application at all.

Or is a build script just standard due to these types of constraints. Thoughts?
