### ISSUE TITLE
RS256/384/512 support

### ISSUE THREAD

**Issue by jjmornim** [sfackler/rust-openssl#384]
How can I encode something using RS256/384/512 algorithms? Does this library support that? There's no example at all. How can I do that?

**Comment by sfackler** [comment]
HS256 is I believe shorthand for HMAC-SHA256 and similarly for the other variants, which you can run via the `Hmac` struct and the `hmac` convenience function: http://sfackler.github.io/rust-openssl/doc/v0.7.10/openssl/crypto/hmac/index.html.

**Comment by jjmornim** [comment]
Sorry, RS, not HS.

RS256/384/512

**Comment by sfackler** [comment]
I don't believe that functionality's exposed at the moment, but PRs are welcome!

**Comment by cmsd2** [comment]
my PR #389 should be all you need to get this working.
