### ISSUE TITLE
Cannot build on CentOS: Error while loading shared object file: No such file or directory

### ISSUE THREAD

**Issue by euclio** [sfackler/rust-openssl#392]
I'm trying to compile this library on a CentOS machine that I don't have admin access to. Building without `OPENSSL_LIB_DIR` or `OPENSSL_INCLUDE_DIR` set, the program fails at runtime with `error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory`.

Building with `OPENSSL_LIB_DIR=/usr/lib64 OPENSSL_INCLUDE_DIR=/usr/include/openssl`, I get

```
note: /home/anrussell/repos/nourishbot/target/debug/deps/libcurl_sys-a48c2040a48201c2.rlib(libcurl_la-openssl.o): In function `ossl_connect_common':
openssl.c:(.text.ossl_connect_common+0xd05): undefined reference to `SSL_CTX_set_srp_username'
openssl.c:(.text.ossl_connect_common+0x10df): undefined reference to `SSL_CTX_set_srp_password'
collect2: ld returned 1 exit status
```

**Comment by sfackler** [comment]
You'll need to set `LD_LIBRARY_PATH` to tell the dynamic linker where to find your copy of libssl and libcrypto at runtime.

**Comment by euclio** [comment]
Hm, `LD_LIBRARY_PATH=/usr/lib64 cargo run` still fails. Is it because that that directory doesn't have `libssl.1.0.0`? Only 

```
$ ls /usr/lib64/libssl*
/usr/lib64/libssl3.so  /usr/lib64/libssl.so  /usr/lib64/libssl.so.10  /usr/lib64/libssl.so.1.0.1e
```

**Comment by sfackler** [comment]
Does `libssl.so.1.0.0` exist anywhere on the system? I am not incredibly well versed in `ld`, but I'd expect that it'd be trying to link to `libssl.so.1.0.0` because that was the one it found. There might be a way to ask the linker to dump its search path. At runtime you can set `LD_DEBUG=all` to have the runtime linker print information about what it's looking for and where.

**Comment by euclio** [comment]
That was it! There was a different version of OpenSSL sitting in a different directory. Removed that and it compiled without error. Thanks for your help.
