### ISSUE TITLE
how to set CA data from memory

### ISSUE THREAD

**Issue by softprops** [sfackler/rust-openssl#394]
You can currently set a [CA via file referece](http://sfackler.github.io/rust-openssl/doc/v0.7.11/openssl/ssl/struct.SslContext.html#method.set_CA_file), but it's unclear if you can provide the same information via bytes the the same way you can [certs](http://sfackler.github.io/rust-openssl/doc/v0.7.11/openssl/ssl/struct.SslContext.html#method.set_certificate) and [keys](http://sfackler.github.io/rust-openssl/doc/v0.7.11/openssl/ssl/struct.SslContext.html#method.set_private_key). Is this possible and if so what is the recommended interface?

**Comment by sfackler** [comment]
I don't believe that's currently exposed - I think it'd involve binding to some of the `X509_STORE` functions.

**Comment by softprops** [comment]
Would that be something that may be in a future roadmap of something you'd be looking for contributions on supporting?

**Comment by sfackler** [comment]
Yep, absolutely. Feel free to open a PR, but I'll probably work on this soonish otherwise.

**Comment by softprops** [comment]
Thanks. I actually ran into this as a side effect of looking into an unrelated issue. 

I recently upgraded to a newer version of hyper which added support of [hostname verification](https://github.com/hyperium/hyper/commit/01160abd92956e5f995cc45790df7a2b86c8989f#diff-8553a3e0b44e9d39fdbbb0e7af414452R669)

where I started to get the following error

```
err Http(
    Ssl(
        OpenSslErrors(
            [
                UnknownError {
                    library: "SSL routines",
                    function: "ssl3_get_server_certificate",
                    reason: "certificate verify failed"
                }
            ]
        )
    )
)
```

I started looking at ways to provide my servers certificate the ssl client. Also noticed that the tls interfaces [themselves have changed](https://github.com/hyperium/hyper/issues/792) so I'm also in the process if figuring our which one to use and how to configure the openssl sslcontext.

I just tried dropping my local CA data into a .pem file ( not ideal as Im just doing that to work around loading from a &str ) to test and I'm actually still getting the  `ssl3_get_server_certificate` error. I'll see what I can figure out.

**Comment by softprops** [comment]
> I just tried dropping my local CA data into a .pem file ( not ideal as Im just doing that to work around loading from a &str ) to test and I'm actually still getting the ssl3_get_server_certificate error. I'll see what I can figure out.

actually I was mistaken. I was referencing the wrong ca data in that first data. I corrected that and now the hostname verification works 🎆  

So once I sort out my issue with hyper openssl interfaces the ability to set ca data from `X509::from_pem(&str)` result would be key as I'm sourcing the CA data from a kubernetes config file and not a traditional pem file. Once I have that. I think I'll be off to the races.
