### ISSUE TITLE
Wrong linking libraries on Fedora 23?

### ISSUE THREAD

**Issue by dpc** [sfackler/rust-openssl#401]
On Fedora 23:

```
/home/dpc/lab/rust/tests/euphonium/target/debug/euctl-f93a1dbae89cb983: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
error: test failed
```

On my system I'm on `/usr/lib/libssl.so.1.0.2h`.

Originally reported in https://github.com/SAPikachu/euphonium/issues/1

**Comment by sfackler** [comment]
This libarary doesn't pick exactly which versions of shared libraries it links against - the linker does. You probably have two copies of openssl on the system. You can run `cargo build --verbose` to see how rustc is invoking the linker, and turn on some debugging flags on that to see what its search path looks like.
