### ISSUE TITLE
fatal error: openssl/hmac.h: No such file or directory

### ISSUE THREAD

**Issue by stiv-yakovenko** [sfackler/rust-openssl#405]
I've installed:
* http://slproweb.com/download/Win32OpenSSL-1_0_2h.exe
* mingw

I open rust console and run: 

>env OPENSSLLIBDIR=C:/OpenSSL-Win32/lib OPENSSLINCLUDEDIR=C:/OpenSSL-Win32/include cargo build

I get following error:

running: "gcc.exe" "-O0" "-ffunction-sections" "-fdata-sections" "-g" "-m64" "-I" "C:/OpenSSL-Win64/include" "-o" "C:\\Users\\steve\\Dropbox\\Projects\\dreams\\rust\\rusttest\\target\\debug\\build\\openssl-sys-extras-6cdd9aaab3f99a18\\out\\src\\openssl_shim.o" "-c" "src/openssl_shim.c"
ExitStatus(ExitStatus(1))

command did not execute successfully, got: exit code: 1

--- stderr
src/openssl_shim.c:1:26: fatal error: openssl/hmac.h: No such file or directory
 #include <openssl/hmac.h>
                          ^
compilation terminated.

what's wrong?
Is it possible to specify environment variables in config file?

**Comment by stiv-yakovenko** [comment]
Oh, I should have taken Win64OpenSSL-1_0_2h.exe

**Comment by sfackler** [comment]
I don't believe you can specify environments in any Cargo-specific config file.

Does C:/OpenSSL-Win64/include/openssl/hmac.h exist?

**Comment by stiv-yakovenko** [comment]
@sfackler , yes, I have resolved the issue and now it works. I've confused win32 and win64.
