### ISSUE TITLE
Bad linking error.

### ISSUE THREAD

**Issue by lephyrius** [sfackler/rust-openssl#415]
```
error: could not find native static library `openssl_shim`, perhaps an -L flag is missing?
error: Could not compile `openssl-sys-extras`.
```

I get this on OS X 10.11.
Using openssl/1.0.2h_1 installed using homebrew.

**Comment by sfackler** [comment]
This looks like an issue with either the gcc-rs crate or with Cargo. What does the output of `cargo build --verbose` look like after a `cargo clean`?

**Comment by sfackler** [comment]
The 0.9 release has heavily overhauled the library lookup process.
