### ISSUE TITLE
Provide openssl binaries without environment variables

### ISSUE THREAD

**Issue by jwilm** [sfackler/rust-openssl#417]
## Motivation

I'd like to provide pre-built binaries in my project without requiring extra work by whoever is compiling the project. That means not needing to mess around with environment variables, needing to use make instead of cargo, or any other work arounds.
## Problem Description

rust-openssl depends on either pkg-config or environment variables to locate openssl binaries.
Environment variables can't be exported from a build script and used in the project or other dependencies which means I can't just pull in my binaries and set OPENSSL_LIB_DIR and friends. For the same reason, I can't just set PKG_CONFIG_PATH. Since rust-openssl-sys already links with openssl, I can't just use my own build script and pretend it's not there.
## Discussion

Is it possible to override the openssl-sys build script with another build script? I was looking around the [build script docs](http://doc.crates.io/build-script.html), but all I found was overriding the build script with hard-coded metadata.

Another thought I've had would be using features to opt out of the rust-openssl build scripts. In that case, I could provide my own build script and have my application be responsible for openssl. I'm not super familiar with everything that happens at this level; maybe someone else could comment on the feasibility of this?

**Comment by sfackler** [comment]
I think I'd recommend writing a little script that manages tracking down/compiling OpenSSL and then invokes cargo with the right environment setup. Not sure there's a way to do it directly from Cargo.

**Comment by jwilm** [comment]
I was afraid you might say that 😞. Well, maybe in the future this can be possible. Do you think it's worth filing on issue on Cargo about this? Not openssl in particular, but rather the inability of a top-level project to change how dependent libraries are linked at all.

**Comment by nathanaeljones** [comment]
I've had success generating a build.rs file using Conan.io (for imazen/imageflow). Conan can fetch pre-built binaries.

**Comment by jackhftang** [comment]
+1 for providing openssl binaries

**Comment by nathanaeljones** [comment]
It's been breaking a new way every few weeks. I've been forced to completely pull HTTPS support from all of my libraries.  Some of this is due to openssl forcing API changes on a rapid schedule.

**Comment by sfackler** [comment]
This is now implemented!
