### ISSUE TITLE
MSVC toolchain instructions

### ISSUE THREAD

**Issue by F3real** [sfackler/rust-openssl#418]
I had to compile rust project using MSVC toolchain on windows. I've followed build instructions but it didn't work for some reason.
In the end I had to set following  env variables for it build:

```
SET DEP_OPENSSL_INCLUDE=C:/OpenSSL-Win64/include
SET OPENSSL_INCLUDE_DIR=C:/OpenSSL-Win64/include
SET OPENSSL_LIB_DIR=C:/OpenSSL-Win64/lib/VC
SET OPENSSL_LIBS=ssleay32MT:libeay32MT
```

and build it from **VS2015 x86 x64 Cross Tools Command Prompt**

maybe additional steps for MSVC toolchain could be clarified in README

**Comment by sfackler** [comment]
It shouldn't be necessary to set DEP_OPENSSL_INCLUDE - openssl-sys will manage that. You may need to `cargo clean` once to get it picked up.

The rest look right though - want to open a PR adding this to the README?

**Comment by F3real** [comment]
Sure, I can do that. I'll try to get it done tomorrow.

**Comment by retep998** [comment]
It's also important to point out _where_ to get OpenSSL in the first place. A guide I wrote up at one point includes steps for acquiring OpenSSL.

https://gist.github.com/retep998/eeca39710290d294c81f38e8f8490801

**Comment by sfackler** [comment]
The 0.9 release has heavily overhauled the library lookup process.
