### ISSUE TITLE
HMAC api uses asserts all over the place instead of returning Result

### ISSUE THREAD

**Issue by bbatha** [sfackler/rust-openssl#430]
Through out the HMAC api returned values are `assert`ed to be correct rather than returning results.

**Comment by bbatha** [comment]
I'm planning on tackling a larger refactor of the PKey apis. I'll use this as a starting place.

**Comment by sfackler** [comment]
:+1:

**Comment by gkoz** [comment]
I don't think any of `HMAC_` functions are expected to fail when used correctly. The asserts are asserting that the bindings aren't misusing the API. If there's a bug in this crate how are you going to handle that?

**Comment by bbatha** [comment]
Given that `HMAC_` is the low-level largely deprecated api in openssl. I think this crate should be binding to at a fairly low-level and pushing our users to our wrappers on the `EVP` apis. This crate will need to provide the low-level bindings for some platforms, notably macOS, and to provide coverage for apis not covered by the `EVP` apis. As a result its likely we'll want to be inspecting the errors directly.

At the very least the asserts should be replaced with `try_ssl!().unwrap()` so that better error messages can be surfaced.

**Comment by sfackler** [comment]
I adjusted the HMAC and Hash APIs to properly return errors, but I think I'm going to replace the hmac module entirely with a more generic sign/verify functionality to take advantage of the `EVP` APIs. The old HMAC functions were a nightmare anyways since their signatures changed in openssl 1.0.0.

**Comment by sfackler** [comment]
Ah, bummer, HMAC support wasn't added to the EVP APIs until 1.0.0, so that won't work.
