### ISSUE TITLE
X509_get_notAfter, X509_get_notBefore

### ISSUE THREAD

**Issue by dweinstein** [sfackler/rust-openssl#435]
Looks like bindings for these haven't been added yet. Just curious if there's any particular reason why before I try to take a stab at it.

**Comment by sfackler** [comment]
Go for it!

**Comment by dweinstein** [comment]
So I started out thinking I could just go and add the missing functions to the openssl-sys/lib.rs but doesn't seem as easy as following what was done for e.g., `X509_get_subject_name`.

somewhat unfortunately:

```
± rabin2 -s /usr/local/Cellar/openssl/1.0.2h_1/lib/libssl.1.0.0.dylib | grep -i x509_get
vaddr=0x00037180 paddr=0x00037180 ord=1081 fwd=NONE sz=0 bind=LOCAL type=FUNC name=imp.X509_get_issuer_name
vaddr=0x00037186 paddr=0x00037186 ord=1082 fwd=NONE sz=0 bind=LOCAL type=FUNC name=imp.X509_get_pubkey
vaddr=0x0003718c paddr=0x0003718c ord=1083 fwd=NONE sz=0 bind=LOCAL type=FUNC name=imp.X509_get_signature_nid
vaddr=0x00037192 paddr=0x00037192 ord=1084 fwd=NONE sz=0 bind=LOCAL type=FUNC name=imp.X509_get_subject_name

```

looks like (at least on my mac) X509_get_notBefore/notAfter are defined as preprocessor macros:

```
± grep "X509_get_not"  /usr/local/Cellar/openssl/1.0.2h_1/include/openssl/x509.h
# define         X509_get_notBefore(x) ((x)->cert_info->validity->notBefore)
# define         X509_get_notAfter(x) ((x)->cert_info->validity->notAfter)
```

so... I'm pretty new to rust FFI stuff but won't those macros be useless to us in openssl-sys and we'll need to do the pointer manipulation ourselves since there's no export to use? if you can nudge me or confirm I'm in the right direction I appreciate it.

**Comment by sfackler** [comment]
So right now we have some C code that we use to wrap all of those macros in C functions, but I want to start moving away from that where possible. I'd define those as Rust function in openssl-sys like this: https://github.com/sfackler/rust-openssl/blob/08e27f31ed851873f7684ac806b837e8cff4a28f/openssl-sys/src/lib.rs#L458

**Comment by dweinstein** [comment]
gotcha. so you're suggesting no shim at all to put into openssl-sys-extras `openssl_shim.c` for this? I think I understand the approach of using the C shim to reproduce the macro and then lifting that into rust, and don't quite know how to do this all within an unsafe block yet... specifically I don't know how to access e.g., the `(x)->cert_info` (simple as *x.cert_info ?) as I would normally in C within the rust... so that's what I'll try to figure out next :-)

**Comment by sfackler** [comment]
Hmm, on second though, just go with the ssl_sys_extras approach for now.

**Comment by dweinstein** [comment]
@sfackler here's my progress so far https://github.com/dweinstein/rust-openssl/tree/asn1_expiration

I have a test app that reads certificates from lockdown/usbmuxd (the thing that manages pairing w/ Apple devices) on my mac. it looks at the plist files and pulls out the certificates, their fingerprint and their notBefore/notAfter expiry. https://github.com/dweinstein/rust-lockdown-explore/blob/master/src/main.rs

```sh
± cargo run
     Running `target/debug/lockdown-explore`
finerprint: "8336eaee94930f1390ba2c2d3e92b5e26550a387"
Jan 16 19:00:11 2016 GMT
Jan 13 19:00:11 2026 GMT
finerprint: "f3bb141414b20a00acf89674f87f0449529c08cb"
Jan 16 19:00:11 2016 GMT
Jan 13 19:00:11 2026 GMT
finerprint: "407fdd6630275f6dcd8deee411655de75e333076"
Jan 16 19:00:11 2016 GMT
Jan 13 19:00:11 2026 GMT

```

do you think this progress is this worth opening a PR to discuss a bit further? I have questions about how I'm doing a few things, so could use the review.

**Comment by sfackler** [comment]
Yep, a PR is definitely a good place to go over that kind of thing.
