### ISSUE TITLE
sharing SslStream across multiple threads

### ISSUE THREAD

**Issue by kteza1** [sfackler/rust-openssl#445]
Hi. I have a TcpStream being used across 2 threads (with `try_clone()`). One thread does the blocking read and other thread for writes. I used to `try_clone` the `SslStream` to share it. Since it is wrong and is removed in 0.8, I tried to `Arc<Mutex>>` the SslStream and clone.

https://github.com/Ather-Energy/RuMqtt/blob/proper_openssl_lock/src/tls.rs#L46

But the problem is that I'm doing a blocking `read()` and the lock is held indefinitely. 

https://github.com/Ather-Energy/RuMqtt/blob/proper_openssl_lock/src/tls.rs#L76

I can't use nonblocking TcpStream coz I'm using read() in an infinite loop

```
loop {
    stream.read()
}
```

which creates a busy loop. `set_timeout` is also not feasible.

Any tips on what I could do to fix this?

**Comment by sfackler** [comment]
You could potentially use select/epoll/etc to check that data's available before making the read call.

**Comment by kteza1** [comment]
@sfackler Are there any such options on std's synchronous TcpStream which support all the platforms?  I can't use mio coz I need to use std's TcpStream.

**Comment by sfackler** [comment]
Not sure honestly.

**Comment by kteza1** [comment]
Ok. Thanks :)

**Comment by TheWaWaR** [comment]
I suppose this better mention in the documentation?
