### ISSUE TITLE
Windows 7 with OpenSSL-Win32 can't find ssleay32.

### ISSUE THREAD

**Issue by zoumi** [sfackler/rust-openssl#448]
there is someone have the same problem with me: https://github.com/hyperium/hyper/issues/637
I have installed OpenSSL-Win32 and set the environment variables:

OPENSSL_LIB_DIR=E:/OpenSSL-Win64 
OPENSSL_INCLUDE_DIR=E:/OpenSSL-Win64/include

But cargo still can not find ssleay32.dll

When I copy these files to E:\rustdir\target\debug\deps,it works.

In fact,when we install OpenSSL-Win32,it will automaticlly copy these files to systems seach path.So I think it's a problem of rust-openssl.

By the way,it seem that there is no ssleay32 in OpenSSL 1.1,But this crate still try to link with ssleay32 .

**Comment by sfackler** [comment]
Try `cargo clean` and then rebuilding with those environment variables set.

**Comment by zoumi** [comment]
@sfackler 
If I want to compile static type, should I set the OPENSSL_LIB_DIR to E:\OpenSSL-Win32 or E:\OpenSSL-Win32\lib   or  E:\OpenSSL-Win32\lib\MinGW???
I'm using mingw-w64_i686-5.3.0-posix-dwarf-rt_v4-rev0.
And now I get this error:

    error: could not find native static library `ssl32`, perhaps an -L flag is missing?
    error: Could not compile `openssl-sys`.

    Caused by:
      Process didn't exit successfully: `rustc E:\rustdir\registry\src\github.com-1ecc6299db9ec823\openssl-sys-0.7.17\src\lib.rs --crate-name openssl_sys --crate-type lib -g -C metadata=4a3524ef1bc5ab61 -C extra-filename=-4a3524ef1bc5ab61 --out-dir E:\rustdir\target\debug\deps --emit=dep-info,link -L dependency=E:\rustdir\target\debug\deps -L dependency=E:\rustdir\target\debug\deps --extern libc=E:\rustdir\target\debug\deps\liblibc-2fef79e23dc08cc8.rlib --extern user32=E:\rustdir\target\debug\deps\libuser32-5ec5fd1838282aa7.rlib --extern gdi32=E:\rustdir\target\debug\deps\libgdi32-f3ab4a9df12ff45c.rlib --cap-lints allow -L native=E:\OpenSSL-Win32\lib -l static=ssl32 -l static=eay32` (exit code: 101)

**Comment by zoumi** [comment]
I have test OPENSSL_LIB_DIR with
E:\OpenSSL-Win32
E:\OpenSSL-Win32\lib
E:\OpenSSL-Win32\lib\MinGW
none of them works.

**Comment by sfackler** [comment]
Which directory contains `libssl32.dll` and `libeay32.dll`?

**Comment by sfackler** [comment]
Oh, the package installed from http://slproweb.com/products/Win32OpenSSL.html does not contain static libraries I believe.

**Comment by zoumi** [comment]
It contains.
卷 各类软件 的文件夹 PATH 列表
卷序列号为 0007-962F
E:\OPENSSL-WIN32
├─bin
│  └─PEM
│      ├─demoCA
│      │  └─private
│      └─set
├─exp
├─include
│  └─openssl
└─lib
    ├─MinGW
    └─VC
        └─static
参数太多 - OpenSSL-Win32
卷 各类软件 的文件夹 PATH 列表
卷序列号为 0007-962F
E:\OPENSSL-WIN32
│  changes.txt
│  faq.txt
│  libeay32.dll
│  libssl32.dll
│  license.txt
│  news.txt
│  readme.txt
│  ssleay32.dll
│  unins000.dat
│  unins000.exe
│  
├─bin
│  │  4758cca.dll
│  │  aep.dll
│  │  atalla.dll
│  │  bftest.exe
│  │  bntest.exe
│  │  CA.pl
│  │  capi.dll
│  │  casttest.exe
│  │  chil.dll
│  │  clienthellotest.exe
│  │  constant_time_test.exe
│  │  cswift.dll
│  │  destest.exe
│  │  dhtest.exe
│  │  dsatest.exe
│  │  ecdhtest.exe
│  │  ecdsatest.exe
│  │  ectest.exe
│  │  enginetest.exe
│  │  evp_extra_test.exe
│  │  evp_test.exe
│  │  exptest.exe
│  │  gmp.dll
│  │  gost.dll
│  │  heartbeat_test.exe
│  │  hmactest.exe
│  │  ideatest.exe
│  │  libeay32.dll
│  │  md4test.exe
│  │  md5test.exe
│  │  mdc2test.exe
│  │  msvcr120.dll
│  │  nuron.dll
│  │  openssl.cfg
│  │  openssl.exe
│  │  padlock.dll
│  │  randtest.exe
│  │  rc2test.exe
│  │  rc4test.exe
│  │  rmdtest.exe
│  │  rsa_test.exe
│  │  sha1test.exe
│  │  sha256t.exe
│  │  sha512t.exe
│  │  shatest.exe
│  │  srptest.exe
│  │  ssleay32.dll
│  │  ssltest.exe
│  │  sureware.dll
│  │  ubsec.dll
│  │  verify_extra_test.exe
│  │  wp_test.exe
│  │  
│  └─PEM
│      │  ca-cert.srl
│      │  ca-key.pem
│      │  ca-req.pem
│      │  cert.pem
│      │  client.pem
│      │  dh1024.pem
│      │  dh2048.pem
│      │  dh4096.pem
│      │  dh512.pem
│      │  dsa-ca.pem
│      │  dsa-pca.pem
│      │  dsa1024.pem
│      │  dsa512.pem
│      │  dsap.pem
│      │  pca-cert.srl
│      │  pca-key.pem
│      │  pca-req.pem
│      │  privkey.pem
│      │  req.pem
│      │  rsa8192.pem
│      │  s1024key.pem
│      │  s1024req.pem
│      │  s512-key.pem
│      │  s512-req.pem
│      │  server.pem
│      │  server.srl
│      │  server2.pem
│      │  testCA.pem
│      │  
│      ├─demoCA
│      │  │  cacert.pem
│      │  │  index.txt
│      │  │  serial
│      │  │  
│      │  └─private
│      │          cakey.pem
│      │          
│      └─set
│              set-g-ca.pem
│              set-m-ca.pem
│              set_b_ca.pem
│              set_c_ca.pem
│              set_d_ct.pem
│              set_root.pem
│              
├─exp
│      4758cca.exp
│      aep.exp
│      atalla.exp
│      capi.exp
│      chil.exp
│      cswift.exp
│      gmp.exp
│      gost.exp
│      libeay32.exp
│      nuron.exp
│      padlock.exp
│      ssleay32.exp
│      sureware.exp
│      ubsec.exp
│      
├─include
│  └─openssl
│          aes.h
│          applink.c
│          asn1.h
│          asn1t.h
│          asn1_mac.h
│          bio.h
│          blowfish.h
│          bn.h
│          buffer.h
│          camellia.h
│          cast.h
│          cmac.h
│          cms.h
│          comp.h
│          conf.h
│          conf_api.h
│          crypto.h
│          des.h
│          des_old.h
│          dh.h
│          dsa.h
│          dso.h
│          dtls1.h
│          ebcdic.h
│          ec.h
│          ecdh.h
│          ecdsa.h
│          engine.h
│          err.h
│          evp.h
│          e_os2.h
│          hmac.h
│          idea.h
│          krb5_asn.h
│          kssl.h
│          lhash.h
│          md4.h
│          md5.h
│          mdc2.h
│          modes.h
│          objects.h
│          obj_mac.h
│          ocsp.h
│          opensslconf.h
│          opensslv.h
│          ossl_typ.h
│          pem.h
│          pem2.h
│          pkcs12.h
│          pkcs7.h
│          pqueue.h
│          rand.h
│          rc2.h
│          rc4.h
│          ripemd.h
│          rsa.h
│          safestack.h
│          seed.h
│          sha.h
│          srp.h
│          srtp.h
│          ssl.h
│          ssl2.h
│          ssl23.h
│          ssl3.h
│          stack.h
│          symhacks.h
│          tls1.h
│          ts.h
│          txt_db.h
│          ui.h
│          ui_compat.h
│          whrlpool.h
│          x509.h
│          x509v3.h
│          x509_vfy.h
│          
└─lib
    │  4758cca.lib
    │  aep.lib
    │  atalla.lib
    │  capi.lib
    │  chil.lib
    │  cswift.lib
    │  gmp.lib
    │  gost.lib
    │  libeay32.lib
    │  nuron.lib
    │  padlock.lib
    │  ssleay32.lib
    │  sureware.lib
    │  ubsec.lib
    │  
    ├─MinGW
    │      libeay32.a
    │      libeay32.def
    │      ssleay32.a
    │      ssleay32.def
    │      
    └─VC
        │  libeay32MD.lib
        │  libeay32MDd.lib
        │  libeay32MT.lib
        │  libeay32MTd.lib
        │  ssleay32MD.lib
        │  ssleay32MDd.lib
        │  ssleay32MT.lib
        │  ssleay32MTd.lib
        │  
        └─static
                libeay32MD.lib
                libeay32MDd.lib
                libeay32MT.lib
                libeay32MTd.lib
                ssleay32MD.lib
                ssleay32MDd.lib
                ssleay32MT.lib
                ssleay32MTd.lib

**Comment by zoumi** [comment]
What about the problem that there is no ssleay32 in OpenSSL 1.1.0???
And do you use a pc with windows OS? Do you use the virtualBox???

**Comment by zoumi** [comment]
@sfackler 
For the dymatic link. Your answer is right.
I set 

    OPENSSL_LIB_DIR=E:/OpenSSL-Win64 
    OPENSSL_INCLUDE_DIR=E:/OpenSSL-Win64/include
and then run 

    cargo clean
    cargo build -v
It now compile successly without copy the .dll to target\debug\deps.

**Comment by sfackler** [comment]
The 0.9 release has heavily overhauled the library lookup process.
