### ISSUE TITLE
Doesn't support OpenSSL 1.1.0

### ISSUE THREAD

**Issue by wagenet** [sfackler/rust-openssl#452]
If I'm correct, OpenSSL 1.1.0 doesn't include some methods relied upon by this crate, e.g. CRYPTO_set_locking_callback.

**Comment by sfackler** [comment]
That's correct. Supporting 1.1 is going to be a very nontrivial project that I haven't had a chance to do yet.

**Comment by dvc94ch** [comment]
I'm having trouble compiling the c_helpers file. I'm getting `dereferencing pointer to incomplete type ‘SSL`.  What's the latest version of openssl that works? I'm using 1.0.2h.

**Comment by sfackler** [comment]
1.0.2h should work but that error makes it seem like you're possibly pulling OpenSSL 1.1 headers, which is not currently supported.

**Comment by dvc94ch** [comment]
Ah, yes. Thank you!

**Comment by cuviper** [comment]
This will soon be an issue for Fedora Rawhide:
https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/EXLYHY6ZXH65IQXKMPE6XHPNTL45MO4Y/

Can you outline what you know needs porting?  Perhaps I can attempt it with some mentoring...

**Comment by sfackler** [comment]
1.1 has quite a bit of API cleanup. Many structs like `SSL`, `RSA`, etc are now opaque and accessor methods were added to poke at the various pieces. A bunch of macros are now functions. Some old stuff like SSLv23_method was removed in favor of more modern APIs.

The work here would involve removing all of the stuff in openssl-sys that is no longer correct in 1.1, and adding a bunch of C shimming on the openssl side to bridge the version gap. I'm also going to drop 0.9.8 support so we can remove some feature gating for stuff added in 1.0.

**Comment by cuviper** [comment]
OK, non-trivial indeed.  I guess my next question is - do you want help? Maybe the tasks can be divided?  Or do you just need to find the time to do it right yourself?

**Comment by sfackler** [comment]
Help would absolutely be appreciated! I believe @alexcrichton was also starting to poke around at this upgrade as well.

**Comment by sfackler** [comment]
Gah, early submit.

As far as an implementation strategy, I think a reasonable approach would be to fix up openssl-sys to the stuff that's in both 1.0 and 1.1, turn off all modules in openssl, and then start going through them one by one turning them back on.

**Comment by retep998** [comment]
Since appveyor explicitly downloads a specific openssl, you could test both openssl versions in the matrix.

**Comment by alexcrichton** [comment]
I've got a small branch with this starting over at https://github.com/alexcrichton/rust-openssl/tree/systest. My plan was basically what @sfackler mentioned, turn off everything and then slowly bring it all back one by one. I was also hoping to land `ctest` validation of FFI bindings as well as testing for 1.0.2 and 1.1.0 on at least Linux if not other platforms. 

I'll try to push more on this over the weekend.

**Comment by sfackler** [comment]
Other things I want to land if we're breaking back compat on openssl-sys include overhauling the build script logic to make it hopefully less painful, and using ctest to fix all of the FFI signatures that have drifted from what they actually should be.

**Comment by alexcrichton** [comment]
Do you have particular pieces in mind you'd like to break about the build script? Maybe it should just start from scratch with the current env vars and build from there?

**Comment by sfackler** [comment]
It's grown super complex over time, so I would like to burn it down and start anew. Concrete things that I want to improve include having a better strategy for selecting library names (ssleay32 vs ssl for example), and better support Homebrew'd installs on OSX by automatically checking in /usr/local/opt/openssl.

**Comment by alexcrichton** [comment]
Ok, status update. My [WIP branch](https://github.com/alexcrichton/rust-openssl/tree/systest) I think now is a solid starting point for the `openssl-sys` crate. I've enabled CI across major configurations I know of at least:

* 32/64 bit Windows GNU, Windows MSVC, Mac, and Linux
* OpenSSL versions 1.0.1, 1.0.2, and 1.1.0
* Rust stable/beta/nightly and the minimum version, 1.9.0

Right now the CI runs a new "systest" folder which is intended to just verify the validity of the FFI crate. With that running I'm at least pretty confident that any bindings and differences between the various versions are accounted for and are correct in the sys crate.

I've also basically started from scratch with the feature set of the `openssl-sys` crate, with some notable changes:

* The old `probe` module is gone, this belongs in the `openssl` crate if at all
* All features are gone from the `openssl-sys` crate. I'm not actually sure why these features existed, @sfackler I presume you know though? At the very least this seemed similar to the `libc` crate where exposing APIs that may not exist seems fine to me at least (as consumers just have to know to not use them)
* Many various impls of sync/copy/clone have all been deleted, I figure they can be added back in a principled fashion if need be later (ideally never...)

And finally, [the build script](https://github.com/alexcrichton/rust-openssl/blob/systest/openssl-sys/build.rs) has been completely rewritten from the ground up. Features include:

* A helpful message if no OpenSSL can be found.
* A helpful message if the wrong version of OpenSSL is found
* Auto detection on OSX of homebrew, if it exists
* Custom error message on OSX if homebrew doesn't exist
* Manual configuration remains via the old env vars
* Automatic detection of static/dylib linkage depending on what's available (if not configured)
* Automatic knowledge of library names on Windows (but I think there's more to do here)

I'm also curious if others have more use cases for the build script here in terms of automatic detection. I'd ideally like to make it as nice as possible! Eventually I'd like to look to bundling the OpenSSL source, but that's a feature for another time.

So all that's basically a fancy way of saying that I haven't actually gotten to the point of *using* the `openssl-sys` crate just yet. The `openssl` crate probably doesn't compile at all, and that's the next step. Hopefully though with all this groundwork that'll be mostly a breeze. (especially with CI).

Note that I've also been trying to focus on adding CI for everything we're interested in with the openssl crate, so eventually we can perhaps add more platform support (e.g. arm or musl) with CI for that as well.

**Comment by sfackler** [comment]
Awesome!

I think the feature gates are just in there because I assumed things would break if you defined a dangling extern. Since that's not the case it seems like we should remove all of them.

The build logic changes look mostly reasonable from a quick look. I think we can probably merge `OPENSSL_LIB_DIR` and `OPENSSL_INCLUDE_DIR` into just `OPENSSL_DIR`, since realistically they'll always be the same except for `/lib` vs `/include`. I think this is how CMake's OpenSSL module works as well. `determine_mode` seems a bit suspicious though - it seems like if that logic's necessary, it would be necessary in basically all sys crates, right?

**Comment by sfackler** [comment]
Oh yeah, and having builds for some cross targets, especially ARM would be great. I tried to get those set up a while ago but never got it working. We've accidentally broken the ARM build at least 3 times due to signed vs unsigned c_char so it'd be nice to have some checking other than people filing issues about releases being broken.

**Comment by cuviper** [comment]
>I think we can probably merge OPENSSL_LIB_DIR and OPENSSL_INCLUDE_DIR into just OPENSSL_DIR, since realistically they'll always be the same except for /lib vs /include.

What about when distros use e.g. `/usr/lib64`?  Or would you just assume the distro case is handled without needing environment variables?

**Comment by sfackler** [comment]
Yep, the distro case should be handled by pkg-config. If it turns out that people do need to override the inferred `/usr` and `/local` we can add the extra env vars back but it seems like it'd be nice for people to only have to export one in the common case.

**Comment by alexcrichton** [comment]
> Since that's not the case it seems like we should remove all of them.

Ok, sure simplifies those pieces! Did these exist on the *-sys side of things because there are builds of OpenSSL without these symbols? Or are these the ones that require C shims of one form or another?

> I think we can probably merge OPENSSL_LIB_DIR and OPENSSL_INCLUDE_DIR into just OPENSSL_DIR

Sounds good to me.

> determine_mode seems a bit suspicious though - it seems like if that logic's necessary, it would be necessary in basically all sys crates, right?

In the limit, yeah I think they'd need something like this to be as robust as possible. With openssl-sys at the core of so many dependency graphs though I figured it'd be worth having all the hairy logic in one place though.

> Oh yeah, and having builds for some cross targets, especially ARM would be great

Cool, I'll try to get that set up as well.

**Comment by sfackler** [comment]
In most cases the cfg'd symbols were added in a newer version of OpenSSL. In some other cases, those features can be disabled in OpenSSL at build time - this is the case for sslv2_method, and compression (#459). Stuff that needs to be shimmed is always shimmed I believe.

**Comment by alexcrichton** [comment]
Ah ok. The one feature I've encountered so far, hmac, was actually defined with symbols from 1.0.1+, so I guess that was just a `#define` macro in 0.9.8? I'll keep an eye out for those kinds of features, though.

**Comment by sfackler** [comment]
The hmac functions are weird - they changed signature from 0.9.8 to 1.0.

**Comment by sfackler** [comment]
Oh, I should note that the HMAC functions that are currently bound are deprecated in favor of the higher level EVP APIs, which added HMAC support in 1.0.0 or 1.0.1. We should probably stop using them entirely.

**Comment by alexcrichton** [comment]
Ok, another status update.

I've now got the entire crate uncommented out, but it's almost 1am, so I'm gonna turn in. The commit history is a bit of a mess but right now the CI is as it is before and I've also set up ARM CI (to execute via QEMU). The entire `openssl` crate minus the `ssl` module passes on ARM, but I haven't tried with the `ssl` module yet (just pushed) and there will likely be complications. In any case though, everything is compiling.

All functionality is ported over with lots of various `compat` modules to bridge the 1.0.x and 1.1.0 divide. If you'd like to see it implemented differently, though, I can also do that! Remaining tasks are:

* Some `ssl` test is segfaulting (or multiple). Just got the `ssl` module compiling and now I'm gonna go to sleep...
* The `SslMethod` enum got way worse than it was before. The situation here is a bit different than with 1.0.x, so curious what others think should happen here
* Various features like alpn/npn/etc are likely not working yet. I've been trying to remove features wherever possible for functionality supported everywhere (e.g. hmac, some x509 business, etc). I have yet to test this out with all the ssl features
* There's some various TODO scattered to take care of, mostly just confirming suspicions (@sfackler you may be able to help out here).

Unfortunately I may not have a lot of time to work on this over the coming week. Would you prefer if I send a PR and give you access to the branch via the PR? Or an alternative route? Up for whatever!

**Comment by alexcrichton** [comment]
Ah, and an [easy link of the diff with commits](https://github.com/sfackler/rust-openssl/compare/master...alexcrichton:systest)

**Comment by alexcrichton** [comment]
More progress, everything works except windows-gnu CI, gotta tweak the build script there most likely

**Comment by alexcrichton** [comment]
Another progress update! Everything is green and I think we're just to the "thorny API questions". That is, all CI work is done, I think all porting work is done, and everything is green on Travis/AppVeyor. 

@sfackler want me to send a PR?

**Comment by sfackler** [comment]
Yes, please do! We can hash out the API stuff there.

**Comment by alexcrichton** [comment]
[Done](https://github.com/sfackler/rust-openssl/pull/464)!

**Comment by sdroege** [comment]
Is there an ETA for a new release that works with OpenSSL 1.1?

**Comment by sfackler** [comment]
Hopefully tomorrow or even maybe tonight.
