### ISSUE TITLE
Document DEP_OPENSSL_INCLUDE

### ISSUE THREAD

**Issue by santagada** [sfackler/rust-openssl#453]
servo is using rust_openssl and they think that only setting DEP_OPENSSL_INCLUDE fixes the lib inclusion in osx 10.11 (you can see in: https://github.com/servo/servo/blob/master/README.md#os-x) to which I sent a pull-request, but I had to set three env vars to get servo to link against brew installed openssl: https://github.com/servo/servo/pull/13225/files

Can the docs be improved or this variable be removed (in preference of the OPENSSL_* ones)

**Comment by sfackler** [comment]
DEP_OPENSSL_INCLUDE is set by cargo based on the output of openssl-sys's build script. It shouldn't be adjusted manually.

**Comment by santagada** [comment]
Ok, so openssl-sys pass data to openssl? In servo at least it builds openssl first and without this change it doesn't find the openssl headers, then it build openssl-sys and that needs the two other vars.

Sorry I'm very new on rust but I really want to get this sorted.

**Comment by sfackler** [comment]
openssl-sys is always built before openssl. If you've adjusted which locations you want openssl-sys to look for openssl (via e.g. `OPENSSL_INCLUDE_DIR`), you'll need to "cargo clean" to trigger openssl-sys to build again.

**Comment by santagada** [comment]
ok I will try that, thanks

**Comment by santagada** [comment]
thanks that fixes it
