### ISSUE TITLE
use openssl::crypto::hmac::hmac; Could not find `hmac` in `openssl::crypto` error when using v0.8.x

### ISSUE THREAD

**Issue by rjgoldsborough** [sfackler/rust-openssl#454]
I receive this error when running any version 8. Reverting back to 0.7.14 fixes this.

```
use openssl::crypto::hmac::hmac; Could not find `hmac` in `openssl::crypto`
```

I do notice there isn't an `openssl-sys-extras` when using 0.8.x.
`Compiling openssl-sys-extras v0.7.14`

I'm running nightly rust through rustup and am on os x el capitan.
Please let me know what else I can provide.

**Comment by jwilm** [comment]
There's a feature for HMAC on 0.8; compiling with `features = ["hmac"]` should fix that! Pretty sure this was added since supporting HMAC required openssl headers.

**Comment by sfackler** [comment]
Yep, that's all you'll have to do.

Steven
