### ISSUE TITLE
Crash when using RSA sign (public_key_from_pem)

### ISSUE THREAD

**Issue by realli** [sfackler/rust-openssl#457]
The `RSA struct` has the function `private_key_from_pem` and `public_key_from_pem`. when I create RSA using `public_key_from_pem`, and then `sign`, program crashed, source code included:

```rust
extern crate openssl;
use openssl::crypto::rsa::RSA;
use openssl::crypto::hash::{Type, Hasher};
use std::io::Write;

fn main() {
	let rsa = RSA::generate(1200).unwrap();

	let u8s : Vec<u8> = rsa.public_key_to_pem().unwrap();
	let rsa_pub = RSA::public_key_from_pem(&u8s).unwrap();

	let u8s2 : Vec<u8> = rsa.private_key_to_pem().unwrap();
	let rsa_pri = RSA::private_key_from_pem(&u8s2).unwrap();

	let mut sha = Hasher::new(Type::SHA256).unwrap();
	sha.write_all( b"message");
	let digest = sha.finish().unwrap();

	rsa_pri.sign(Type::SHA256, &digest).unwrap();

	// fllowing line will crash..
	rsa_pub.sign(Type::SHA256, &digest);
 
}
```
Not familiar with RSA algorithm, but if sign with public_key is not allowed, `Err(...)` should be returned, right?

**Comment by sfackler** [comment]
It should certainly not crash, yes. `RSA_sign` signs using the private key, but it looks like it doesn't actually check if that's present before trying to use it :(. I'm not sure of a great way to synthesize an `Err` value that's actually correct, so I'll add an assert checking for the presence of the private key for `sign` and public key for `verify`.
