### ISSUE TITLE
Need a cfg to support OPENSSL_NO_COMP builds

### ISSUE THREAD

**Issue by Arnavion** [sfackler/rust-openssl#459]
`SSL_get_current_compression` and `SSL_COMP_get_name` are not defined in OPENSSL_NO_COMP builds.

The full list is:

```
ssleay:
SSL_get_current_compression
SSL_get_current_expansion
SSL_COMP_add_compression_method
SSL_COMP_free_compression_methods
SSL_COMP_free_compress_methods
SSL_COMP_get_compress_methods
SSL_COMP_get_compression_methods
SSL_COMP_get_name
SSL_COMP_set0_compress_methods
SSL_COMP_set0_compression_methods

libeay:
BIO_f_zlib
COMP_compress_block
COMP_CTX_free
COMP_CTX_new
COMP_expand_block
COMP_rle
COMP_zlib
COMP_zlib_cleanup
ERR_load_COMP_strings
```

but only those two are currently defined in openssl-sys/src/lib.rs

**Comment by sfackler** [comment]
Thanks for the report! We can stick this behind a feature flag, but we'll have to enable it by default for backwards compatibility which is a bit unfortunate.

**Comment by sfackler** [comment]
I'm a bit confused here, actually. It appears that OpenSSL defines these methods even if `OPENSSL_NO_COMP` is passed, they just return `NULL`: https://github.com/openssl/openssl/blob/OpenSSL_1_0_2-stable/ssl/ssl_ciph.c#L1934.

What compilation error are you running into?

**Comment by sfackler** [comment]
It appears that these are always defined, at least in 1.0.1 and up, which is all the next release is going to support. Feel free to reopen if that's not the case!

**Comment by Arnavion** [comment]
The .def file is generated based on configuration options. If it's configured with `no-comp` the functions will not be exported.

**Comment by sfackler** [comment]
Ah, so it's specifically a Windows issue?

**Comment by Arnavion** [comment]
I'm on Windows yes. I'm using the openssl build we build as part of [gtk-win32](https://github.com/hexchat/gtk-win32) where we configure with no-comp.

**Comment by Arnavion** [comment]
(You can generate a list like the one in the OP for any arbitrary feature-set by looking at `util/libeay.num` and `util/ssleay.num`. I believe `Configure` should generate these even on Linux. The format is described in `util/mkdef.pl`.)
