### ISSUE TITLE
Add private/public encrypt/decrypt to RSA

### ISSUE THREAD

**Issue by aoprisan** [sfackler/rust-openssl#460]
I am in need to use RSA public key encryption and I saw that the functions are missing from rust-openssl while the openssl-sys has them already. Browsing through history I saw they were removed from PKey where they initially lived. Would it be a good idea to add them to RSA ? I can make a PR in the next couple of days as I have a fork already.

**Comment by sfackler** [comment]
Please do! I must have forgotten to move the methods over. They didn't make sense on PKey since they didn't actually work with non-RSA things.

**Comment by aoprisan** [comment]
Will do the next couple of days, thanks.
