### ISSUE TITLE
Building under Yocto fails with new openssl-sys changes

### ISSUE THREAD

**Issue by posborne** [sfackler/rust-openssl#477]
Still investigating.  I would expect openssl-sys to use the definitions provided via pkg-config to give the build system sufficient information in order to find OpenSSL (1.0.1 in my case at present) and continue without problems.

In actuality, things fail with the following message:

```
| error: failed to run custom build command for `openssl-sys v0.7.17 (https://github.com/sfackler/rust-openssl.git#fdb41310)`
| process didn't exit successfully: `/opt/builds/paul-hubv2/build/tmp/work/cortexa9hf-vfp-neon-poky-linux-gnueabi/updater-ng/git+AUTOINC+25d5383597-r0/target/release/build/openssl-sys-17ce954dcb033eea/build-script-build` (exit code: 101)
| --- stderr
| thread 'main' panicked at '
|
| Could not find directory of OpenSSL installation, and this `-sys` crate cannot
| proceed without this knowledge. If OpenSSL is installed and this crate had
| trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
| compilation process.
|
| If you're in a situation where you think the directory *should* be found
| automatically, please open a bug at https://github.com/sfackler/rust-openssl
| and include information about your system as well as this message.
|
|     $HOST = x86_64-unknown-linux-gnu
|     $TARGET = armv7-unknown-linux-gnueabihf
|     openssl-sys = 0.7.17
|
| ', /opt/builds/paul-hubv2/build/tmp/work/cortexa9hf-vfp-neon-poky-linux-gnueabi/updater-ng/git+AUTOINC+25d5383597-r0/cargo_home/git/checkouts/rust-openssl-41da9d20ce19f5aa/master/openssl-sys/build.rs:129
| stack backtrace:
|    1:     0x5563b360fa29 - std::sys::backtrace::tracing::imp::write::h00e948915d1e4c72
|    2:     0x5563b361632c - std::panicking::default_hook::_{{closure}}::h7b8a142818383fb8
|    3:     0x5563b3615629 - std::panicking::default_hook::h41cf296f654245d7
|    4:     0x5563b3615c68 - std::panicking::rust_panic_with_hook::h4cbd7ca63ce1aee9
|    5:     0x5563b35f9c02 - std::panicking::begin_panic::h93672d0313d5e8e9
|    6:     0x5563b35fcacf - build_script_build::main::h7f6f3686e1d6be88
|    7:     0x5563b361de16 - __rust_maybe_catch_panic
|    8:     0x5563b3614da2 - std::rt::lang_start::h53bf99b0829cc03c
|    9:     0x7fabe97e0abf - __libc_start_main
|   10:     0x5563b35f7dd8 - _start
|   11:                0x0 - <unknown>
```

I believe the pkg-config setup within Yocto to be valid.  The following environment variables are set when the cargo build operation is taking place:

```
$ cat tmp/work/cortexa9hf-vfp-neon-poky-linux-gnueabi/updater-ng/git+AUTOINC+25d5383597-r0/temp/run.do_compile | grep PKG_
export PKG_CONFIG_SYSROOT_DIR="/opt/builds/paul-hubv2/build/tmp/sysroots/hubv2-dev"
export PKG_CONFIG_PATH="/opt/builds/paul-hubv2/build/tmp/sysroots/hubv2-dev/usr/lib/pkgconfig:/opt/builds/paul-hubv2/build/tmp/sysroots/hubv2-dev/usr/share/pkgconfig"
export PKG_CONFIG_DIR="/opt/builds/paul-hubv2/build/tmp/sysroots/hubv2-dev/usr/lib/pkgconfig"
export PKG_CONFIG_LIBDIR="/opt/builds/paul-hubv2/build/tmp/sysroots/hubv2-dev/usr/lib/pkgconfig"
export PKG_CONFIG_DISABLE_UNINSTALLED="yes"
```

With the .pc file for openssl being present at and containing the following:

```
$ cat tmp/sysroots/hubv2-dev/usr/lib/pkgconfig/openssl.pc
prefix=/usr
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: OpenSSL
Description: Secure Sockets Layer and cryptography libraries and tools
Version: 1.0.1l
Requires:
Libs: -L${libdir} -lssl -lcrypto
Libs.private: -lgcc -ldl
Cflags: -I${includedir}
```

This same build setup worked properly on the currently released rust openssl.  Build was performed with latest stable rust/cargo.

**Comment by alexcrichton** [comment]
Hm if you execute `pkg-config --libs openssl` does it print out the relevant libs and such?

**Comment by alexcrichton** [comment]
Oh right it looks like you're doing a cross compile here and `pkg-config` is disabled by default on cross-compiles (as it historically works pretty rarely)

If you set `PKG_CONFIG_ALLOW_CROSS` does the compile work for you?

**Comment by posborne** [comment]
> If you set PKG_CONFIG_ALLOW_CROSS does the compile work for you?

I updated the recipe for the piece of software I am building to set this variable and I was able to get things to build successfully.  Since this will be generally useful @nastevens and I can consider adding that as something that is automatically done in the [meta-rust-bin](https://github.com/rust-embedded/meta-rust-bin) yocto/openembedded layer which we maintain.

> pkg-config is disabled by default on cross-compiles

What is the problem that is being avoided in the general case by not using pkg-config for cross compilation?  Systems like Yocto (both for recipes in-tree and when using a generated SDK) use pkg-config pretty extensively for information build systems of library/header locations.

**Comment by sfackler** [comment]
In a "traditional" setup, pkg-config is going to find the host's OpenSSL, not the target OpenSSL.

**Comment by posborne** [comment]
> In a "traditional" setup, pkg-config is going to find the host's OpenSSL, not the target OpenSSL.

True, I wonder if there is some other variable which is likely already set that could help us make this decision better.  E.g. most host systems will not customize `PKG_CONFIG_SYSROOT_DIR` but most cross-compile environments will.

Anyway, I suppose I can move that discussion to the `pkg-config` crate if needed.

**Comment by alexcrichton** [comment]
Ah yeah @sfackler mentioned what I was going to where typically pkg-config doesn't work with cross compiles (e.g. by default it finds system libs). I'd love to soup up pkg-config-rs though to check to see if it was configured appropriately! Then you wouldn't have to set a random environment variable!
