### ISSUE TITLE
x86 OSX Travis build is slooooow

### ISSUE THREAD

**Issue by sfackler** [sfackler/rust-openssl#491]
It looks like it has to build OpenSSL from source (twice!?), which causes it to take ~15 minutes which is 3-5 times longer than any other build.

**Comment by alexcrichton** [comment]
Looking at travis, it takes 810s (13 minutes) to complete this step

> brew uninstall openssl && brew install openssl --universal

If you take that out of the build it's the same as others (around 2 minutes). I believe the default installed version doesn't have 32-bit support, and it looks like homebrew doesn't bottle the 32-bit version? Or maybe it does and the universal version isn't bottled?

At the time I couldn't figure out another way to install 32-bit OpenSSL on OSX, but perhaps I overlooked something!

**Comment by sfackler** [comment]
We could take a page out of the Linux builds and just compile it ourselves.

**Comment by alexcrichton** [comment]
Yeah that seems plausible. I've never even tried that actually but presumably it's not that much different than Linux.

**Comment by sfackler** [comment]
I've reordered tests a bit and sped up the install step by turning off tests, so it looks like it's no longer the blocker.
