### ISSUE TITLE
Unable to cross compile OSX -> x86_64-unknown-linux-musl

### ISSUE THREAD

**Issue by leeola** [sfackler/rust-openssl#495]
I'm having trouble cross compiling OpenSSL (via Hyper). However, after slowly progressing on much Googling, i have hit a wall. I believe below i've summed up the information as best i can - hopefully you have some idea, because i'm at a standstill.

Error: https://gist.github.com/anonymous/6ac39afbdd3cf6a3cf7d42da63755398

Brew:
```
~/w/mtest> brew info openssl
openssl: stable 1.0.2j (bottled) [keg-only]
```

Exported Variables:

```
~/w/mtest> echo $OPENSSL_INCLUDE_DIR
/usr/local/opt/openssl/include
~/w/mtest> echo $OPENSSL_LIB_DIR
/usr/local/opt/openssl/lib
~/w/mtest> echo $DEP_OPENSSL_INCLUDE
/usr/local/opt/openssl/include
~/w/mtest> echo $OPENSSL_DIR
/usr/local/opt/openssl
~/w/mtest> echo $C_INCLUDE_PATH
/usr/local/opt/openssl/include
```

Build Command:

```
env CC_x86_64-unknown-linux-musl=x86_64-linux-musl-gcc OPENSSL_STATIC=1 cargo build -v --target=x86_64-unknown-linux-musl
```

OS Version:
```
~/w/mtest> sw_vers
ProductName:    Mac OS X
ProductVersion: 10.12
BuildVersion:   16A323
```

Source code:
```
extern crate hyper;

use hyper::Client;

fn main() {
    println!("{:?}", Client::new().get("https://example.com").send());
}
```

Thoughts?

**Comment by sfackler** [comment]
Homebrew installs a version of OpenSSL that targets OSX - it's not going to work when building for Linux. You'll need to find one built for x86-64 Linux MUSL or build it from source yourself.

**Comment by leeola** [comment]
Ah hah, thank you. I spent far too long trying to get this to work -_-

Closing, hopefully my pain will save some Googler' time :)

**Comment by sfackler** [comment]
No problem!

**Comment by LoganDark** [comment]
What's the procedure for installing things like x86_64-unknown-linux-musl OpenSSL on macOS anyway? Should I just install it on Linux and copy the headers over to my own machine? Is there a homebrew thing I can install somewhere? How do I even compile it from source using the cross-compilers I have on my system?

**Comment by sfackler** [comment]
You'd use that toolchain to compile OpenSSL from source and then configure the crate to link to it with the `OPENSSL_DIR` environment variable.

**Comment by LoganDark** [comment]
@sfackler Alright so I downloaded the OpenSSL sources, ran `CC="x86_64-linux-musl-gcc -fPIE -pie" ./Configure no-shared no-async --prefix=/musl --openssldir=/musl/ssl linux-x86_64` to configure it and then used `make` to build it.

It wanted Linux headers along the way, so I went on over to [linux-libc-dev-amd64-cross](https://packages.ubuntu.com/bionic/linux-libc-dev-amd64-cross) and yoinked those (extracted the deb manually and installed its headers to my cross compiler's include directories). The compilation proceeded smoothly until the linking step.

![image](https://user-images.githubusercontent.com/4723091/88448231-60513000-cdf0-11ea-9348-2d4b165148fe.png)

I got hundreds of these failed linking messages and I don't know what they mean. If this isn't the right place to ask then please tell me where I can get help.

**Comment by LoganDark** [comment]
I apparently didn't specify all of the environment variables other than the C compiler. See https://github.com/FiloSottile/homebrew-musl-cross/issues/21#issuecomment-663841576
