### ISSUE TITLE
Implement DH functionality

### ISSUE THREAD

**Issue by jethrogb** [sfackler/rust-openssl#498]
This is one of the types of keys that can be loaded through PKey. Follow-up of #234.

Needed: key generation, getting key parameters, relevant crypto operations

**Comment by sfackler** [comment]
There are already some DH bindings: https://github.com/sfackler/rust-openssl/blob/master/openssl/src/dh.rs. Should be easy to add the relevant constructors/accessors for PKey.

**Comment by jethrogb** [comment]
This just adds the PKey conversion, but it doesn't make the DH struct useful.

**Comment by sfackler** [comment]
What specific functionality on the Dh struct are you looking for?

**Comment by jethrogb** [comment]
See and #234 and the Rsa struct: key generation, getting key parameters, relevant crypto operations.

**Comment by sfackler** [comment]
Thanks

**Comment by jD91mZM2** [comment]
I think I'm being blocked by this. Can't find any way to simply get a public key from a generated Diffie-Hellman instance. I think I need to use `PKey::from_dh` and then `public_key_to_der/pem`, but

```Rust
error[E0599]: no method named `public_key_to_der` found for type `openssl::pkey::PKey<openssl::pkey::Params>` in the current scope
   --> lib.rs:105:28
    |
105 |         let key_der = pkey.public_key_to_der()?;
    |                            ^^^^^^^^^^^^^^^^^
    |
    = note: the method `public_key_to_der` exists but the following trait bounds were not satisfied:
            `openssl::pkey::Params : openssl::pkey::HasPublic`
```

**Comment by sfackler** [comment]
How are you generating a DH instance? None of the APIs we currently bind create Dh objects with public keys.

**Comment by jD91mZM2** [comment]
`Dh::get_2048_256`

**Comment by sfackler** [comment]
That doesn't generate a public/private keypair, it just returns the standard RFC 5114 DH parameters.

**Comment by jD91mZM2** [comment]
Okay so that's my problem. How do I get a public key?

**Comment by sfackler** [comment]
We don't currently expose that functionality.

**Comment by jD91mZM2** [comment]
Ah, crap. I was wondering if that was related to this PR.

**Comment by jethrogb** [comment]
Yes, this issue covers exactly that missing functionality.
