### ISSUE TITLE
Implement EC_KEY structure and PKey conversion

### ISSUE THREAD

**Issue by jethrogb** [sfackler/rust-openssl#499]
This is one of the types of keys that can be loaded through PKey. Follow-up of #234.

**Comment by sfackler** [comment]
The type is defined in #503 but the API still needs to be built out.

**Comment by jethrogb** [comment]
This just adds the PKey conversion, but it doesn't make the EcKey struct useful.

**Comment by sfackler** [comment]
What specific functionality on EcKey are you looking for?

**Comment by jethrogb** [comment]
See and #234 and the Rsa struct: key generation, getting key parameters, relevant crypto operations.

**Comment by sfackler** [comment]
Thanks

**Comment by bluejekyll** [comment]
I'm looking at ecdsa support right now. I'm having trouble understanding how to go from binary public_key components -> an EcKey.

I believe the proper process is along these lines:
```
let pkey = EcGroup::from_curve_name(nid::SECP256K1)
                         .and_then(|group| EcPoint::from(public_key_bytes))
                         .and_then(|point| EcKey::public_key_from(point))
                         .map(|key| PKey::from_ec_key(key));
```

But currently the `EcKey::public_key_from(point)` doesn't look to be implemented. I'm adding this comment to this bug, not sure if they are 100% the same request. I'm happy to work on this if it's not already done.

I need this for verifying `ECDSAP256SHA256` and `ECDSAP384SHA384` in DNS.

**Comment by sfackler** [comment]
Yep, feel free to add functionality that seems to be missing!

**Comment by bluejekyll** [comment]
FYI, #541 is up. It might cover this case, I added an example use case for converting to a PKey, might be identical to the snippet that I put in here. This *may* be enough to close out this issue? It is for my use cases, anyway.

**Comment by sfackler** [comment]
This has been implemented.
