### ISSUE TITLE
Be consistent about PEM/DER support

### ISSUE THREAD

**Issue by jethrogb** [sfackler/rust-openssl#500]
Some structures can be loaded/saved only from/to [PEM format](https://sfackler.github.io/rust-openssl/doc/v0.8.3/openssl/crypto/pkey/struct.PKey.html), others only from/to [DER format](https://sfackler.github.io/rust-openssl/doc/v0.8.3/openssl/crypto/pkcs12/struct.Pkcs12.html) and yet others from/to [both formats](https://sfackler.github.io/rust-openssl/doc/v0.8.3/openssl/x509/struct.X509.html). All modules should support both PEM and DER loading.

**Comment by jethrogb** [comment]
PKey is still missing DER loading.

**Comment by sfackler** [comment]
PKey's DER deserialization seems pretty sketchy. There's `d2i_PrivateKey`, where you have to specify the type of the key up front in which case you may as well go through that type in the first place, or `d2i_AutoPrivateKey` which tries to "guess" the underlying type. It's not clear to me that `d2i_AutoPrivateKey` is reasonable enough to expose, but maybe?
