### ISSUE TITLE
Implement PKey<->DSA conversion

### ISSUE THREAD

**Issue by jethrogb** [sfackler/rust-openssl#501]
PKey currently only supports converting to/from RSA keys. Follow-up from #234.

**Comment by sfackler** [comment]
The construction side is already supported: https://github.com/sfackler/rust-openssl/blob/master/openssl/src/pkey.rs#L85. Should be very easy to handle the other direction just like we do now for RSA keys: https://github.com/sfackler/rust-openssl/blob/master/openssl/src/pkey.rs#L28

**Comment by jethrogb** [comment]
Cool, thanks!
