### ISSUE TITLE
Expose base64 decode/encode functions

### ISSUE THREAD

**Issue by simias** [sfackler/rust-openssl#509]
I could implement it but I'm not sure what would be the best way to do that.

OpenSSL implements base64 through its BIO abstraction, using `BIO_f_base64`. I'm not sure if rust-openssl should have a generic BIO handling interface (a bit like the current `Hash`/`MessageDigest` API) of if base64 is specific enough to warrant a straightforward `base64::encode` `base64::decode` implementation.

I don't know if there would be other uses for exposing the `BIO` interface. I tried to find other useful methods besides `BIO_f_base64` but since the OpenSSL doc is garbage I didn't find much of interest. If `base64` is the only useful use case then we might as well just implement that.

**Comment by sfackler** [comment]
I'd probably lean towards just having some free functions.

**Comment by simias** [comment]
Okay, I'll give it a try then.

**Comment by simias** [comment]
I'm closing this after the discussion in #510, we've come to the conclusion that it's probably better to use a native base64 crate instead.
