### ISSUE TITLE
Please fail more gently

### ISSUE THREAD

**Issue by e-oz** [sfackler/rust-openssl#514]
Please consider to use another way to report about errors (not panicking). Currently all I see from this library is "An error in the OpenSSL library". Without any explanations and, what is more important, code execution is interrupted, even if reading that URL wasn't critical.

**Comment by posborne** [comment]
@e-oz Is this with the very recently released version or with older versions.  I think significant progress has been made on this front with 0.9.0.

**Comment by e-oz** [comment]
0.7.17. I can't upgrade because a lot of other dependencies use 0.9.0 and I'm fighting whole day to hack it but no luck.

**Comment by sfackler** [comment]
I don't believe we should be panicking internally anywhere. Are you sure it's coming from rust-openssl itself? A backtrace would be helpful.

**Comment by jwilm** [comment]
@e-oz 

`0.7.17` is missing a lot of error handling (panics instead). The newer versions are better about this.

Since you say you can't upgrade, maybe you can vendor the API you're using? What APIs are you using anyway?

**Comment by e-oz** [comment]
@jwilm main pita is hyper 0.9.11 - it has "openssl 0.7.14" in list of dependencies and I can't override it. Vendoring hyper is.. well, dirty idea.

Sorry for opening issue about not actual version.

**Comment by sfackler** [comment]
Hyper's SSL backend is pluginizable, by the way. You can disable the feature that pulls in 0.7 and implement the `SslClient` and `SslServer` traits with 0.9. Should be a pretty simple wrapper on top of `SslConnector` and `SslAcceptor`.

**Comment by sfackler** [comment]
(cc @seanmonstar)
