### ISSUE TITLE
set_verify(SSL_VERIFY_NONE) do not disable certificates verification

### ISSUE THREAD

**Issue by aleksander** [sfackler/rust-openssl#517]
``` Rust
    let mut builder = SslConnectorBuilder::new(SslMethod::tls()).unwrap();
    builder.builder_mut().set_verify(SSL_VERIFY_NONE); // <- verification disabled
    let connector = builder.build();
    let stream = TcpStream::connect((host, port)).unwrap();
    let mut stream = connector.connect(host, stream).unwrap();
```
This code panics with error "unable to get local issuer certificate. certificate verify failed", but the verification is disabled (I believe).
What only helps me is set custom verification callback returning true:
``` Rust
    builder.builder_mut().set_verify_callback(SSL_VERIFY_NONE, |_,_| { true });
```

**Comment by sfackler** [comment]
The verification settings are overridden at the `Ssl` level, since it depends on the hostname: https://github.com/sfackler/rust-openssl/blob/master/openssl/src/ssl/connector.rs#L100-L102 https://github.com/sfackler/rust-openssl/blob/master/openssl/src/ssl/connector.rs#L256-L270

The callback version will work on 1.0.2 and 1.1.0, since we don't override the callback on those versions.

**Comment by sfackler** [comment]
Come to think of it, I should probably tweak the 1.0.2 and 1.1.0 code to overwrite the callback as well for consistency.

Why are you turning certificate verification off?

**Comment by aleksander** [comment]
> Why are you turning certificate verification off?
I don't need authentication. I only need an encrypted connection to receive some sensible data. In earlier versions of rust-openssl I just did connect() and everything worked. But yesterday I decided to update my dependencies and got this error and workaround. I don't know much about certificates, sorry. Maybe I just want something strange and unnatural :) Maybe the right way is to handle certificates stuff.

**Comment by sfackler** [comment]
Authentication and encryption are pretty closely tied, at least in the sense that the objective of encrypting data is to prevent someone else from seeing it. If you don't have authentication, you're setting up an encrypted connection with *someone*. That someone may be the person you're trying to securely retrieve data from, or it may be that person you don't want to see it who's sitting in the middle and recording/altering the transfer.

**Comment by aleksander** [comment]
Thank you for the explanation. It's pretty close to my understanding.
In my case I have to deal with an old server. On the server side no one cares about certificates, so the certificates is expired in 2010 :) No chance to me to handle certificates right. The only way is to disable verification.
Now I undestand that SslConnector::connect() is a wrapper that forces verification so I just need to use SslContext -> Ssl -> SslStream instead. Thank you for pointing me out.
I think the issue could be closed. Or it could stay open to track callback overwriting in 1.0.2 and 1.1.0.

**Comment by sfackler** [comment]
I've fixed the callback overriding consistency issue here: https://github.com/sfackler/rust-openssl/commit/aa7c27536ad56def21afad4043d6d658f517ecc4.

Using SslContext and Ssl manually does seem like a reasonable approach for your use case. One approach you can take to handle the authentication issue if you want is to pin the certificate - that is, register a callback that just checks the certificate's signature against the one you expect.
