### ISSUE TITLE
LibreSSL support

### ISSUE THREAD

**Issue by chneukirchen** [sfackler/rust-openssl#521]
The version check for OPENSSL_VERSION_NUMBER in build.rs bails out for LibreSSL, where the value is 0x20000000L. The crate seems to build fine else, assuming LibreSSL is like OpenSSL 1.0.1.

**Comment by sfackler** [comment]
I'd be more than happy to take a patch adding LibreSSL support!

**Comment by chneukirchen** [comment]
Hm, just lying its 1.0.1 breaks systest because it tries to look into structures opaque in LibreSSL.

I don't really know these APIs, help wanted. :)

**Comment by sfackler** [comment]
It'll probably be a somewhat significant amount of work, though I'm not sure how much the LibreSSL people have changed at the ABI level. The general approach would be to use the systest crate to figure out which definitions are wrong and add a new submodule with the correct definitions like we currently do for OpenSSL 1.1.0 and 1.0.x, and then when that's all working, making any necessary changes in the main crate. We'd also want CI builds added with whichever LibreSSL versions are supported.

**Comment by sfackler** [comment]
It sounds like it's API compatible with 1.0.1, but not ABI compatible, so I'm guessing some struct definitions will need to be adjusted: https://github.com/libressl-portable/portable#compatibility-with-openssl

**Comment by chneukirchen** [comment]
It would be great to have this in a release, as cargo 0.15 needs rust-openssl 0.9.3 and thus doesn't build on libressl platforms at the moment.

**Comment by sfackler** [comment]
Done!
