### ISSUE TITLE
Add AES IGE support

### ISSUE THREAD

**Issue by JuanPotato** [sfackler/rust-openssl#523]
OpenSSL already implements AES IGE, could you add it in this package? I'd be willing to help out as well

**Comment by sfackler** [comment]
Feel free! We don't currently bind anything in that header, so it'd probably just be a matter of adding a new `aes` module wit`hige_encrypt` and `ige_decrypt` functions.

**Comment by sfackler** [comment]
I'm also somewhat curious as to the reason - IGE appears to be an exceedingly obscure mode of operation.

**Comment by JuanPotato** [comment]
Ask Telegram not me lol. I just want to implement their api

**Comment by sfackler** [comment]
Oh Telegram.... Fair enough!

**Comment by JuanPotato** [comment]
I noticed that while the more common aes_ecb has an NID (not exactly sure what this is) located in the openssl code, I cannot find one for ige. Would this cause a problem?

**Comment by sfackler** [comment]
Those two functions in aes.h are the only places in OpenSSL AES IGE exists AFAIK. You'd have to add bindings for those specifically.

**Comment by JuanPotato** [comment]
Ok, I've looked related code in this project but I am a little confused. I am still learning Rust, and I don't seem to understand the ffi module. Would you mind explaining where you are calling the C functions or am I misunderstanding how it works? Would really appreciate it if you could help me understand.

**Comment by sfackler** [comment]
Sure, no problem!

The openssl-sys crate contains the definitions of all of the OpenSSL C types and functions we need to use. In this case, we need the `AES_KEY` type and the `AES_set_encrypt_key`, `AES_set_decrypt_key`, `AES_ige_encrypt`, and `AES_ige_decrypt` functions. The systest crate will compare the contents of openssl-sys to OpenSSL's headers to make sure everything's been defined properly.

Once those are there, we can call those functions in the main openssl crate.

**Comment by JuanPotato** [comment]
I think I mostly have it, i put this into `openssl-sys/src/lib.rs` and added `.header("openssl/aes.h")` in `systest/build.rs`. But I'm getting an error with `AES_ige_encrypt` when I try to run systest.

```
error: return from incompatible pointer type [-Werror=incompatible-pointer-types]
                 return AES_ige_encrypt;
                        ^~~~~~~~~~~~~~~
```


```
#[repr(C)]
pub struct AES_KEY {
    rd_key: [c_uint; 60],
    rounds: c_int
}
...
pub const AES_ENCRYPT: c_int = 1;
pub const AES_DECRYPT: c_int = 0;
...
extern {
    ...
    pub fn AES_ige_encrypt(inbuf: *const u8, outbuf: *mut u8,
                           inlen: size_t, key: *const AES_KEY,
                           iv: *const u8, encrypt: c_int);
    ...
}
```

**Comment by sfackler** [comment]
That seems reasonable looking - what does the C function that generated that error look like? It should be somewhere in target/debug/build/systest-asdfasdfasdfasdf/out

**Comment by JuanPotato** [comment]
Oh, forgot I could check that. It was just an issue with me accidentally making the iv a *const rather than *mut. Fixed that.

I was thinking of adding all the other AES functions (I got working ffi bindings for them) into an aes.rs, along with an enum of all the modes.

**Comment by sfackler** [comment]
Yeah, seems reasonable to add all of those functions.

**Comment by habnabit** [comment]
Any progress on this? Hoping to do the same thing.

**Comment by JuanPotato** [comment]
Yo sorry, I meant to actually do this, but I ended up dropping the project that needed it, so I forgot I had this open. You can implement it if you want, but if I may ask, what do you plan on using IGE for?

**Comment by habnabit** [comment]
Same thing, naturally.

**Comment by sfackler** [comment]
I can take a look at doing this.

**Comment by JuanPotato** [comment]
@habnabit Can you link me to your repository if you've started it yet? Would love to see how it comes along

**Comment by sfackler** [comment]
https://github.com/sfackler/rust-openssl/pull/558

**Comment by JuanPotato** [comment]
Well that was fast

**Comment by habnabit** [comment]
@JuanPotato due to the way my work handles copyright, source won't be available for a few weeks at least. sorry! I'll post it when I can.

@sfackler should I try the #558 locally first, or were you going to merge it presently?

**Comment by JuanPotato** [comment]
Dang that's unfortunate, well good luck on the project. :)
