### ISSUE TITLE
add minimum supported version to Travis

### ISSUE THREAD

**Issue by cardoe** [sfackler/rust-openssl#526]
So I know a lot of people use the nightly and a lot of people always run the latest stable rust. But there's some of us out there that will get stuck on a stable release for a few months due complexities in build environments, breakages moving forward, etc.

For all my crates I try to include the following in .travis-ci.yml so that there's a minimum supported version:
```
rust:
- nightly
- beta
- stable
- 1.4.0
```

Its fine to raise that level up as needed but its helpful to ensure that a "stable" series (e.g. 0.6.x) remains compatible with the same version of Rust or if it needs to be bumped up people can understand how they need to update.

This package currently tests only against `stable` so I'm asking for `stable` + something else. This has bitten me on the 0.7.x series once when going from 0.7.8 -> 0.7.14 depended on features that were unstable in the version of Rust I was stuck at.

**Comment by sfackler** [comment]
Oops, thought we were already doing this - must have gotten switched to stable by default. I believe it should be 1.10.0 though.

**Comment by sfackler** [comment]
Oh right, we do already to this actually! https://github.com/sfackler/rust-openssl/blob/master/.travis.yml#L47

**Comment by cardoe** [comment]
Oh my mistake. I only looked at the top variable and not the matrix. Thank you @sfackler.
