### ISSUE TITLE
Build failed: manifest path ... is a virtual manifest, but this command requires..

### ISSUE THREAD

**Issue by halmohri** [sfackler/rust-openssl#527]
I'm using `openssl 1.0` and `rustc 1.13.0`. I downloaded `rust-openssl` from github and did a cargo build. I get this error: 

error: manifest path ... is a virtual manifest, but this command requires running against an actual package in this workspace.  

Can you comment on this please?
Thanks!

Update: I was just building the main folder. Got it working.

**Comment by sfackler** [comment]
Good to hear it's working!

**Comment by halmohri** [comment]
There's a minor issue. I have openssl-verify as a dependency which itself uses rust-openssl. This is giving me a linking error. Sounds like trying to relink openssl again. Is there a workaround?
