### ISSUE TITLE
DTLS example

### ISSUE THREAD

**Issue by Yamakaky** [sfackler/rust-openssl#528]
I would like to use DTLS with openssl. There is `SslMethod::dtls()`, is it the only required change compared to TLS? This [DTLS example](https://gist.github.com/Jxck/b211a12423622fe304d2370b1f1d30d5) seem to have more changes.

**Comment by sfackler** [comment]
There are some tests that use DTLS - you will also need to be using a UDP socket instead of a TCP stream at the very least.

**Comment by Yamakaky** [comment]
I searched in the tests but couldn't find the one for DTLS?

**Comment by sfackler** [comment]
Anything with the run_test macro is run for both TLS and DTLS: https://github.com/sfackler/rust-openssl/blob/master/openssl/src/ssl/tests/mod.rs#L158

**Comment by Yamakaky** [comment]
So apart from using UDP and changing the Method, I don't have to change anything? Very cool!

**Comment by sfackler** [comment]
Yep!

**Comment by Yamakaky** [comment]
How does it interact with SslAcceptor and SslStream? Does one SslStream correspond to one client connection, so that if I call `ssl_read` or `ssl_write` it will not mess with the others connections?

**Comment by sfackler** [comment]
Yep, each SslStream is associated with one connection.

**Comment by Yamakaky** [comment]
Cool!

**Comment by Yamakaky** [comment]
How would it work with tokio? Since the connections share the same socket, should iterate over the connections when new bytes arrive?

**Comment by sfackler** [comment]
You could have multiple connections share the same socket, but that seems like kind of a pain - there'd need to be a routing layer.

**Comment by Yamakaky** [comment]
I'm talking about a UDP server.

**Comment by sfackler** [comment]
If you want to use the same socket for all of them, you'll need to have some extra state which routes based on the peer address I suppose.

**Comment by Yamakaky** [comment]
Oh, OK. So that's not magic XD
