### ISSUE TITLE
Can I access SSL_SESSION?

### ISSUE THREAD

**Issue by halmohri** [sfackler/rust-openssl#546]
Is it possible to somehow access [SSL_SESSION](https://www.openssl.org/docs/man1.0.1/ssl/SSL.html) through this crate? 
I need to access the session key (at the server side) at some point. Is this currently possible?

**Comment by sfackler** [comment]
I don't believe we currently provide access to `SSL_SESSION`, but I'd be happy to take a PR adding that functionality!

**Comment by halmohri** [comment]
OK. I'm working on this.
How do you specify this macro in your crate: `STACK_OF(X509)`?
I see the Stackable type. Is that related?

**Comment by sfackler** [comment]
See here for some code that works with a `STACK_OF(X509)`: https://github.com/sfackler/rust-openssl/blob/master/openssl/src/pkcs12.rs#L35

**Comment by halmohri** [comment]
Good. 
Following the current structure of the crate, `SSL_SESSION` struct should be added to openssl-sys (ossl10x.rs) while `Stack` is defined in openssl. What do you recommend?

**Comment by sfackler** [comment]
https://github.com/sfackler/rust-openssl/blob/master/openssl-sys/src/lib.rs#L1852

**Comment by halmohri** [comment]
Do you have a stack for `SSL_CIPHER`? 
`STACK_OF(SSL_CIPHER)`

**Comment by sfackler** [comment]
You'll have to add it:

https://github.com/sfackler/rust-openssl/blob/master/openssl-sys/src/libressl.rs#L8
https://github.com/sfackler/rust-openssl/blob/master/openssl-sys/src/ossl10x.rs#L9
https://github.com/sfackler/rust-openssl/blob/master/openssl-sys/src/ossl110.rs#L16

**Comment by halmohri** [comment]
OK. Almost done adding the struct. 
One thing to make sure of. What is the purpose of ossl110.rs?

**Comment by sfackler** [comment]
It contains definitions corresponding to OpenSSL 1.1.0

**Comment by halmohri** [comment]
Everything is working well except for this function I'm adding: 
`pub fn SSL_get_session(ssl: *mut ::SSL) -> *mut SSL_SESSION; `

And I get this warning: 

```
warning: found non-foreign-function-safe member in struct marked #[repr(C)]: found struct without foreign-function-safe representation annotation in foreign module, consider adding a #[repr(C)] attribute to the type, #[warn(improper_ctypes)] on by default
   --> src/ossl10x.rs:663:48
    |
663 |     pub fn SSL_get_session(ssl: *mut ::SSL) -> *mut SSL_SESSION; 
    |                                                ^^^^^^^^^^^^^^^^
```

**Comment by halmohri** [comment]
Do you have specific requirements for contributing to the crate that I should consider?

**Comment by sfackler** [comment]
Nothing in particular I don't think.

**Comment by halmohri** [comment]
SSL_get_session has a different prototype for ossl10 and ossl11. Which should go into libressl.rs?

**Comment by sfackler** [comment]
Whichever one [LibreSSL](https://www.libressl.org/) uses.

**Comment by halmohri** [comment]
You can remove the PR. I won't have time to fix all the issues. The error messages won't give a clue.
