### ISSUE TITLE
openssl-sys v0.9.5 can't find OpenSSL directory on OpenBSD

### ISSUE THREAD

**Issue by mfil** [sfackler/rust-openssl#551]
When I try to compile openssl-sys v0.9.5 on OpenBSD-current, I get an error message that the OpenSSL installation can't be found:

```
thread 'main' panicked at '

Could not find directory of OpenSSL installation, and this `-sys` crate cannot
proceed without this knowledge. If OpenSSL is installed and this crate had
trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
compilation process.

If you're in a situation where you think the directory *should* be found
automatically, please open a bug at https://github.com/sfackler/rust-openssl
and include information about your system as well as this message.

    $HOST = x86_64-unknown-openbsd
    $TARGET = x86_64-unknown-openbsd
    openssl-sys = 0.9.5

', build.rs:150
```
OpenBSD has the OpenSSL (LibreSSL) files in /usr/include and /usr/lib. In version 0.9.4, those were found automatically.

I played around a bit and found that when I write `openssl = "1.0"` (instead of 1.0.1) in Cargo.toml, metadeps finds the directory. But I don't know if that change would cause problems on other systems.

**Comment by sfackler** [comment]
We don't support `1.0.0`, but we check for that later anyway so it might just be easiest to make the change you propose. It seems a bit strange that OpenBSD wouldn't claim LibreSSL is version 1.0.1 since that's what API it mirrors.

**Comment by sfackler** [comment]
@semarie Do you know why LibreSSL's pkg-config entry is set up that way?

**Comment by semarie** [comment]
@sfackler In fact the version wasn't updated from ages on OpenBSD (2010). And now that LibreSSL forked from OpenSSL, trying to "mimic" a version of OpenSSL is a bit tendencious: some parts of API have been removed (EGD for example), or disabled. So even if the API is compatible with 1.0.1, it couldn't be claimed as "same as OpenSSL 1.0.1".
