### ISSUE TITLE
Sporadic build failure macOS w/ brew's OpenSSL

### ISSUE THREAD

**Issue by bluejekyll** [sfackler/rust-openssl#554]
I looked briefly at the rust-openssl build, but haven't had enough time to dig into this:

```
= note: "cc" "-m64" "-L" "/Users/benjaminfry/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "/Users/benjaminfry/Development/rust/trust-dns/target/debug/secure_client_handle_tests-1186407fd8b3feb4.0.o" "-o" "/Users/benjaminfry/Development/rust/trust-dns/target/debug/secure_client_handle_tests-1186407fd8b3feb4" "-Wl,-dead_strip" "-nodefaultlibs" "-L" "/Users/benjaminfry/Development/rust/trust-dns/target/debug/deps" "-L" "/usr/lib" "-L" "/usr/local/opt/openssl/lib" "-L" "/Users/benjaminfry/Development/rust/trust-dns/target/debug/build/ring-b04a0c9d4dc7829a/out/lib" "-L" "/Users/benjaminfry/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "/Users/benjaminfry/Development/rust/trust-dns/target/debug/deps/libtrust_dns_server.rlib" "/Users/benjaminfry/Development/rust/trust-dns/target/debug/deps/libtrust_dns.rlib" "/Users/benjaminfry/Development/rust/trust-dns/target/debug/deps/libtokio_core-7d79a0061e4987e4.rlib" "/Users/benjaminfry/Development/rust/trust-dns/target/debug/deps/libscoped_tls-53036341d2dbbe26.rlib" "/Users/benjaminfry/Development/rust/trust-dns/target/debug/deps/libmio-d8a3ebfe89185cdb.rlib" "/Users/benjaminfry/Development/rust/trust-dns/target/debug/deps/libslab-69010361762af86e.rlib" "/Users/benjaminfry/Development/rust/trust-dns/target/debug/deps/librand-8ea7d489d4a383a0.rlib" "/Users/benjaminfry/Development/rust/trust-dns/target/debug/deps/libopenssl-c9e7b933bde3d3a6.rlib" "/Users/benjaminfry/Development/rust/trust-dns/target/debug/deps/libdata_encoding-8503efda09142c21.rlib" "/Users/benjaminfry/Development/rust/trust-dns/target/debug/deps/libchrono-7342810e34d1c30d.rlib" "/Users/benjaminfry/Development/rust/trust-dns/target/debug/deps/librusqlite-a221a739db38f0bf.rlib" "/Users/benjaminfry/Development/rust/trust-dns/target/debug/deps/libtime-750bfdd52feafcb7.rlib" "/Users/benjaminfry/Development/rust/trust-dns/target/debug/deps/libbitflags-0e272044714c8076.rlib" "/Users/benjaminfry/Development/rust/trust-dns/target/debug/deps/libtoml-1a75b37a708f335b.rlib" "/Users/benjaminfry/Development/rust/trust-dns/target/debug/deps/librustc_serialize-6b938435173797f7.rlib" "/Users/benjaminfry/Development/rust/trust-dns/target/debug/deps/liblazycell-d53b754addaf1d91.rlib" "/Users/benjaminfry/Development/rust/trust-dns/target/debug/deps/libnix-56d9e0b660233faa.rlib" "/Users/benjaminfry/Development/rust/trust-dns/target/debug/deps/libring-863fd845bbadbb87.rlib" "/Users/benjaminfry/Development/rust/trust-dns/target/debug/deps/libfutures-21d097dc8f05f683.rlib" "/Users/benjaminfry/Development/rust/trust-dns/target/debug/deps/libbitflags-75746cc7f0e9d928.rlib" "/Users/benjaminfry/Development/rust/trust-dns/target/debug/deps/liblibsqlite3_sys-02dacca8e9891790.rlib" "/Users/benjaminfry/Development/rust/trust-dns/target/debug/deps/liblazy_static-7f1b96a3a3eb529d.rlib" "/Users/benjaminfry/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libtest-f5a209a9.rlib" "/Users/benjaminfry/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libterm-f5a209a9.rlib" "/Users/benjaminfry/Development/rust/trust-dns/target/debug/deps/libopenssl_sys-6c510e83c5b0b664.rlib" "/Users/benjaminfry/Development/rust/trust-dns/target/debug/deps/liberror_chain-5731652bab0d1a8e.rlib" "/Users/benjaminfry/Development/rust/trust-dns/target/debug/deps/libbacktrace-dffaf784d6265843.rlib" "/Users/benjaminfry/Development/rust/trust-dns/target/debug/deps/librustc_demangle-9f84838926c47318.rlib" "/Users/benjaminfry/Development/rust/trust-dns/target/debug/deps/libdbghelp-72843bd5c387f78b.rlib" "/Users/benjaminfry/Development/rust/trust-dns/target/debug/deps/libwinapi-0889532d327ff4e2.rlib" "/Users/benjaminfry/Development/rust/trust-dns/target/debug/deps/libnum-1fa4854b44bb6a54.rlib" "/Users/benjaminfry/Development/rust/trust-dns/target/debug/deps/libnum_iter-50df698bc905252c.rlib" "/Users/benjaminfry/Development/rust/trust-dns/target/debug/deps/libnum_integer-52fdddf28cd8e924.rlib" "/Users/benjaminfry/Development/rust/trust-dns/target/debug/deps/libnet2-755d3e4f87237d0e.rlib" "/Users/benjaminfry/Development/rust/trust-dns/target/debug/deps/libcfg_if-72c1f992b13d5087.rlib" "/Users/benjaminfry/Development/rust/trust-dns/target/debug/deps/liblibc-e1db4c5f3a4f3c2f.rlib" "/Users/benjaminfry/Development/rust/trust-dns/target/debug/deps/libuntrusted-6d5be7309ea48309.rlib" "/Users/benjaminfry/Development/rust/trust-dns/target/debug/deps/liblru_cache-5df7c7dfb11fae93.rlib" "/Users/benjaminfry/Development/rust/trust-dns/target/debug/deps/liblinked_hash_map-8bca62f90f0f04c7.rlib" "/Users/benjaminfry/Development/rust/trust-dns/target/debug/deps/libnum_traits-92bb90166cd1857c.rlib" "/Users/benjaminfry/Development/rust/trust-dns/target/debug/deps/libvoid-2cc31605fcb01ba1.rlib" "/Users/benjaminfry/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libgetopts-f5a209a9.rlib" "/Users/benjaminfry/Development/rust/trust-dns/target/debug/deps/liblog-bf16bb9a4912b11d.rlib" "/Users/benjaminfry/Development/rust/trust-dns/target/debug/deps/libkernel32-df86a08647459244.rlib" "/Users/benjaminfry/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libstd-f5a209a9.rlib" "/Users/benjaminfry/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libpanic_unwind-f5a209a9.rlib" "/Users/benjaminfry/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libunwind-f5a209a9.rlib" "/Users/benjaminfry/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librand-f5a209a9.rlib" "/Users/benjaminfry/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcollections-f5a209a9.rlib" "/Users/benjaminfry/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liballoc-f5a209a9.rlib" "/Users/benjaminfry/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liballoc_jemalloc-f5a209a9.rlib" "/Users/benjaminfry/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liblibc-f5a209a9.rlib" "/Users/benjaminfry/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librustc_unicode-f5a209a9.rlib" "/Users/benjaminfry/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcore-f5a209a9.rlib" "/Users/benjaminfry/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcompiler_builtins-f5a209a9.rlib" "-l" "c++" "-l" "sqlite3" "-l" "sqlite3" "-l" "sqlite3" "-l" "ssl" "-l" "crypto" "-l" "System" "-l" "pthread" "-l" "c" "-l" "m"
  = note: Undefined symbols for architecture x86_64:
  "_EVP_DigestVerifyFinal", referenced from:
      openssl::sign::Verifier::finish::h2254ce4db54d0d04 in libopenssl-c9e7b933bde3d3a6.rlib(openssl-c9e7b933bde3d3a6.0.o)
  "_EVP_DigestSignFinal", referenced from:
      openssl::sign::Signer::finish::hd5e70040d912dd63 in libopenssl-c9e7b933bde3d3a6.rlib(openssl-c9e7b933bde3d3a6.0.o)
  "_EVP_DigestVerifyInit", referenced from:
      openssl::sign::Verifier::new::hb1fc11f25f026f4f in libopenssl-c9e7b933bde3d3a6.rlib(openssl-c9e7b933bde3d3a6.0.o)
  "_EVP_DigestSignInit", referenced from:
      openssl::sign::Signer::new::h3ca1d35e4b331ef5 in libopenssl-c9e7b933bde3d3a6.rlib(openssl-c9e7b933bde3d3a6.0.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

It seems to be a race condition and happens more regularly on TravisCI macOS builds, but I see it regularly on my local machine as well.

**Comment by sfackler** [comment]
Is another dependency pulling in a `-L /usr/lib`? It could be that you're picking up OSX's built in OpenSSL depending on the order of those parameters. Try running with `--verbose` to see the full `rustc` invocation.

**Comment by bluejekyll** [comment]
out of curiosity, what is your recommended build? brew or just macOS' built in OpenSSL port?

**Comment by sfackler** [comment]
The builtin OpenSSL is not supported - it's way too old and doesn't come with headers anymore. Homebrew-installed OpenSSL is the recommended approach.

**Comment by bluejekyll** [comment]
updated the comment with the full linkage line.

**Comment by sfackler** [comment]
Yep, looks like a `-L /usr/lib` is the culprit. I've seen this happen before with sqlite since OSX also ships a copy of that. You can set `PKG_CONFIG_PATH= /usr/local/opt/sqlite/lib/pkgconfig` to get pkg-config to pick up a Homebrew installed copy of SQLite as well.

It's not a great situation, but getting cargo to avoid this kind of lookup directory leakage is a nontrivial problem :(

**Comment by sfackler** [comment]
cc @alexcrichton this is the kind of thing I was talking about last week.

**Comment by alexcrichton** [comment]
Last time `-L /usr/lib` came up it was b/c of libz-sys, @bluejekyll do you have that in your dependency graph? If so, is it up to date?

Otherwise yeah in general `-L /usr/lib` or `-L /usr/local/lib` ends up being dangerous so we try to avoid it, although most brew crates/packages are good about not printing that out.

**Comment by sfackler** [comment]
But isn't pkg-config-rs specifically asking for them to be printed? https://github.com/alexcrichton/pkg-config-rs/blob/master/src/lib.rs#L363

**Comment by alexcrichton** [comment]
Yeah but not all packages end up printing that out. My intention is to also add a flag to disable that env var being set to pkg-config-rs, as well.

**Comment by bluejekyll** [comment]
No, it doesn't look like I have `libz-sys` in my depedencies, just looked at the [Cargo.lock](https://github.com/bluejekyll/trust-dns/blob/master/Cargo.lock) file

**Comment by alexcrichton** [comment]
Hm mind grepping around in the `target` directory to see what's printing out `/usr/lib`? Figuring out what package is doing that may help here.

**Comment by bluejekyll** [comment]
I can do this after work today, don't have my other laptop with me. It's not a blocking issue, since rebuilding generally resolves the issue.

**Comment by bluejekyll** [comment]
So @sfackler is correct looks like:

`debug/build/libsqlite3-sys-f0bda98e9f4ee3fb/output:cargo:rustc-link-search=native=/usr/lib`

**Comment by alexcrichton** [comment]
Ah so it looks like libsqlite3-sys is printing out the path, I'm curious if it'd be possible to fix this there? Ideally that'd be left out so it doesn't cause these conflicts

**Comment by bluejekyll** [comment]
by "fix this there", do you mean in the `libsqlit3-sys` crate?

**Comment by alexcrichton** [comment]
Yeah just in the sense of suppressing that search path

**Comment by bluejekyll** [comment]
wouldn't that then require that people install `sqlite` with brew or some other means? i.e. it would not be using the system sqlite anymore, right?

**Comment by alexcrichton** [comment]
Oh no I just mean letting the default paths of the linker find the library rather than specifying it explicitly. Basically on OSX there are so many libs that override the default libs you have to be super careful about printing `-L` paths to system directories (we've discovered over time). The linker will find it anyway so typically the `-L` can just be omitted.

**Comment by sfackler** [comment]
Why does pkg-config-rs ask for system paths in the first place?

**Comment by bluejekyll** [comment]
maybe I'm doing something wrong, but I've removed all logic from the `libsqlite3-sys` build.rs main function, it used to print these:

```
    println!("cargo:rustc-link-lib=sqlite3");
    println!("cargo:rustc-link-search={}", lib_dir);
```

I still get the same issue. `usr/lib` is still being output, not sure why exactly, but I'm guessing this cargo option in the sys Cargo.toml is doing it: `links = "sqlite3"`

I have a workaround, which is to use the new `bundled` feature in 0.6.0 which will recompile from src `sqlite` each time. So I'll probably use that for now. I'm not sure this is exactly a bug with rust-openssl at this point, up to you how to treat this issue. I'm not 100% where this issue actually should live...

**Comment by sfackler** [comment]
It's printed directly by pkg-config-rs.

**Comment by alexcrichton** [comment]
@sfackler 

> Why does pkg-config-rs ask for system paths in the first place?

To find static libraries. Without these paths rustc is otherwise unable to find them. Nowadays it can't be changed due to backcompat, but the next major version will likely switch the defaults or conditionalize this on `statik` somehow.

> It's printed directly by pkg-config-rs.

I'm curious to confirm this, this isn't always the case. For example [pkg-config](https://github.com/jgallagher/rusqlite/blob/0990ad89aa5f4ab825ef1d9f4ace307405defb9a/libsqlite3-sys/build.rs#L20) seems to explicitly do this regardless of what pkg-config says.

Always good to check!

**Comment by sfackler** [comment]
Ah that line is suspicious.

**Comment by bluejekyll** [comment]
@alexcrichton ok, last night I screwed up my `[replace]` config, apparently that needs to go into the workspace file Cargo.toml :/

Anyway, after *actually* removing those lines, it looks like the linkage on macOS works properly.

**Comment by alexcrichton** [comment]
Aha good to hear! Perhaps this issue could be moved to sqlite3-sys, then? Basically just to not print `/usr/lib` by default if not otherwise found.

**Comment by sfackler** [comment]
Makes sense to me.

**Comment by jgallagher** [comment]
@alexcrichton I'm not sure this issue needs to be reopened, but I'm not exactly sure how to fix jgallagher/rusqlite#207. If the problem in this issue from above is the output

```
debug/build/libsqlite3-sys-f0bda98e9f4ee3fb/output:cargo:rustc-link-search=native=/usr/lib
```

I believe that's coming from pkg-config-rs; if we were hitting the manual addition of `/usr/lib` from libsqlite-sys's build.rs, that line wouldn't have `native=/usr/lib` (it would just be `rustc-link-search=/usr/lib`). I'm happy to remove the manual printing of `/usr/lib`, but it doesn't look like it would've had any effect here.

**Comment by alexcrichton** [comment]
@jgallagher I've pushed 0.3.9 of the pkg-config crate which allows you to disable the option that'll print /usr/lib, you likely want to update to that and use that option.

**Comment by jgallagher** [comment]
👍 done in jgallagher/rusqlite#216, thanks!
