### ISSUE TITLE
macOS Sierra Hint in README.md

### ISSUE THREAD

**Issue by stephanbuys** [sfackler/rust-openssl#573]
Hi, can you also add the hint provided here to the README.md? https://github.com/brianmario/mysql2/issues/795

Essentially `xcode-select --install` solved days of struggling to compile `rust-openssl` for me in one step. (I had openssl installed via brew already)

**Comment by sfackler** [comment]
Sure - want to open a PR with the language that makes sense to you?

I thought that homebrew did that automatically but maybe that's not the case?
