### ISSUE TITLE
Get signature from certificate

### ISSUE THREAD

**Issue by brooss** [sfackler/rust-openssl#576]
I feel like I might be missing something obvious here. After loading a certificate with one of the available X.509 methods (e.g. `X509::from_pem()`), how can I get access to (the bytes of) the certificates signature?

**Comment by sfackler** [comment]
This should do it for you: https://docs.rs/openssl/0.9.6/openssl/x509/struct.X509.html#method.fingerprint

**Comment by brooss** [comment]
Unless I'm misunderstanding, the `fingerprint` method will create a new hash of the loaded certificate. I'm interested in the existing signature contained in the X509 certificate.

For example, is it possible to implement something similar to this C program using the rust-openssl API?
[http://fm4dd.com/openssl/certsignature.htm](http://fm4dd.com/openssl/certsignature.htm)

**Comment by sfackler** [comment]
Ah, gotcha. Looks like we'd need to bind to [`X509_get0_signature`](https://www.openssl.org/docs/man1.1.0/crypto/X509_get0_signature.html) with a shim for 1.0.1.

**Comment by brooss** [comment]
Excellent, yes. I've tested and the `signature` method works exactly as expected for me. `signature_algorithm` looks good too, but isn't tested by my use case.
