### ISSUE TITLE
Ubuntu GNOME can't find OpenSSL?

### ISSUE THREAD

**Issue by jonathandturner** [sfackler/rust-openssl#577]
I tried building openssl-sys, but it complains that it can't find openssl and to set the OPENSSL_DIR env var.

I've installed libssl-dev, but to no avail.  Are there other packages I need to install?

**Comment by sfackler** [comment]
Do you have pkg-config?

**Comment by sfackler** [comment]
This was resolved in IRC - turned out to be a missing pkg-config.
