### ISSUE TITLE
Different versions required by crates.

### ISSUE THREAD

**Issue by zoumi** [sfackler/rust-openssl#578]
error: native library `openssl` is being linked to by more than one version of the same package, but it can only be linked once; try updating or pinning your dependencies to ensure that this package only shows up once

  openssl-sys v0.7.17
  openssl-sys v0.9.6

Is there a good way to solve this?

**Comment by sfackler** [comment]
You'll need to track down the dependencies pulling in 0.7 and update them.

**Comment by zoumi** [comment]
Thanks.

**Comment by zoumi** [comment]
Is there any tool to do this automaticaly?

**Comment by sfackler** [comment]
https://github.com/sfackler/cargo-tree can help identify the packages that need updating.

**Comment by zoumi** [comment]
Thank you very much!

**Comment by zoumi** [comment]
Sadly, I can't compile cargo-tree successfully:

    Compiling cargo-tree v0.10.0
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/home/zoumi/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/tmp/cargo-install.lHo7Wtrid0mE/release/deps/cargo_tree.0.o" "-o" "/tmp/cargo-install.lHo7Wtrid0mE/release/deps/cargo_tree" "-Wl,--gc-sections" "-pie" "-Wl,-O1" "-nodefaultlibs" "-L" "/tmp/cargo-install.lHo7Wtrid0mE/release/deps" "-L" "/tmp/cargo-install.lHo7Wtrid0mE/release/build/miniz-sys-ef5ba14b9a8cd643/out" "-L" "/tmp/cargo-install.lHo7Wtrid0mE/release/build/libgit2-sys-551aec5e9c1946f4/out/lib" "-L" "/tmp/cargo-install.lHo7Wtrid0mE/release/build/curl-sys-47a946fd1bff4db6/out/lib" "-L" "/home/zoumi/programs/openssl-1.1.0b/" "-L" "/usr/lib64" "-L" "/tmp/cargo-install.lHo7Wtrid0mE/release/build/libssh2-sys-d3b5c446708c2a4d/out/lib" "-L" "/home/zoumi/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "-Wl,-Bdynamic" "/tmp/cargo-install.lHo7Wtrid0mE/release/deps/libcargo-39e07a4dc0fc8860.rlib" "/tmp/cargo-install.lHo7Wtrid0mE/release/deps/libcrossbeam-57ab0771b45a9db1.rlib" "/tmp/cargo-install.lHo7Wtrid0mE/release/deps/libflate2-96f71db1c22e37e2.rlib" "/tmp/cargo-install.lHo7Wtrid0mE/release/deps/libgit2-6ffb937381cab5b2.rlib" "/tmp/cargo-install.lHo7Wtrid0mE/release/deps/libsemver-082724bd4ec9e2aa.rlib" "/tmp/cargo-install.lHo7Wtrid0mE/release/deps/libtempdir-2b2ad75f3a0cb4fc.rlib" "/tmp/cargo-install.lHo7Wtrid0mE/release/deps/libtoml-31aa0e6abda16ddf.rlib" "/tmp/cargo-install.lHo7Wtrid0mE/release/deps/libcrates_io-38367ad142e6b603.rlib" "/tmp/cargo-install.lHo7Wtrid0mE/release/deps/liburl-1a669a3fcfa69d9d.rlib" "/tmp/cargo-install.lHo7Wtrid0mE/release/deps/libcurl-75cc3deb1a2f79f1.rlib" "/tmp/cargo-install.lHo7Wtrid0mE/release/deps/libopenssl_probe-0555ebf984d86bfe.rlib" "/tmp/cargo-install.lHo7Wtrid0mE/release/deps/libidna-56e638e84ca06563.rlib" "/tmp/cargo-install.lHo7Wtrid0mE/release/deps/libunicode_bidi-6c2537d3abeb8173.rlib" "/tmp/cargo-install.lHo7Wtrid0mE/release/deps/libfs2-b70fb626365cea73.rlib" "/tmp/cargo-install.lHo7Wtrid0mE/release/deps/libnum_cpus-1765277d7e86a45e.rlib" "/tmp/cargo-install.lHo7Wtrid0mE/release/deps/libtar-c604b0a38989e74b.rlib" "/tmp/cargo-install.lHo7Wtrid0mE/release/deps/libfiletime-55a4a5f2fb5104db.rlib" "/tmp/cargo-install.lHo7Wtrid0mE/release/deps/libterm-b609d73b2a9b9710.rlib" "/tmp/cargo-install.lHo7Wtrid0mE/release/deps/libpetgraph-d55addc837653e7b.rlib" "/tmp/cargo-install.lHo7Wtrid0mE/release/deps/libfixedbitset-5a7ae64db426e465.rlib" "/tmp/cargo-install.lHo7Wtrid0mE/release/deps/liblog-47ac4ee9b4627d73.rlib" "/tmp/cargo-install.lHo7Wtrid0mE/release/deps/libmatches-c84ce17ea1a359a8.rlib" "/tmp/cargo-install.lHo7Wtrid0mE/release/deps/libunicode_normalization-221fbc2adfbd4cf9.rlib" "/tmp/cargo-install.lHo7Wtrid0mE/release/deps/libdocopt-0561c43607963ff2.rlib" "/tmp/cargo-install.lHo7Wtrid0mE/release/deps/librustc_serialize-538160d669eee985.rlib" "/tmp/cargo-install.lHo7Wtrid0mE/release/deps/libstrsim-b70b5bb577db8605.rlib" "/tmp/cargo-install.lHo7Wtrid0mE/release/deps/libminiz_sys-5e5cbc668bb75024.rlib" "/tmp/cargo-install.lHo7Wtrid0mE/release/deps/liblibgit2_sys-7ccf2bd4cd469981.rlib" "/tmp/cargo-install.lHo7Wtrid0mE/release/deps/libcurl_sys-0bbd500c39ae99a7.rlib" "/tmp/cargo-install.lHo7Wtrid0mE/release/deps/liblibssh2_sys-d0ac5dbc0db76c48.rlib" "/tmp/cargo-install.lHo7Wtrid0mE/release/deps/liblibz_sys-41921ebdd0ca3725.rlib" "/tmp/cargo-install.lHo7Wtrid0mE/release/deps/libglob-ad687337b228224c.rlib" "/tmp/cargo-install.lHo7Wtrid0mE/release/deps/libsemver_parser-a7f742a1fc2ca6d6.rlib" "/tmp/cargo-install.lHo7Wtrid0mE/release/deps/libregex-68fb807493a248dd.rlib" "/tmp/cargo-install.lHo7Wtrid0mE/release/deps/libutf8_ranges-d333ee72daa90b74.rlib" "/tmp/cargo-install.lHo7Wtrid0mE/release/deps/libregex_syntax-9e284665ea860ea0.rlib" "/tmp/cargo-install.lHo7Wtrid0mE/release/deps/libthread_local-0d0afb4cecbb25ba.rlib" "/tmp/cargo-install.lHo7Wtrid0mE/release/deps/libthread_id-8cc6fc7814357c36.rlib" "/tmp/cargo-install.lHo7Wtrid0mE/release/deps/libaho_corasick-73f5257ec031d67a.rlib" "/tmp/cargo-install.lHo7Wtrid0mE/release/deps/libmemchr-986a9c1eabf29057.rlib" "/tmp/cargo-install.lHo7Wtrid0mE/release/deps/librand-10d9c4fcbd924c1b.rlib" "/tmp/cargo-install.lHo7Wtrid0mE/release/deps/libopenssl-3d708b8d8b36a885.rlib" "/tmp/cargo-install.lHo7Wtrid0mE/release/deps/libopenssl_sys-fa6a35e46e174a39.rlib" "/tmp/cargo-install.lHo7Wtrid0mE/release/deps/liblazy_static-139f35e0122abba9.rlib" "/tmp/cargo-install.lHo7Wtrid0mE/release/deps/liblibc-d9ccbb5cf10993e8.rlib" "/tmp/cargo-install.lHo7Wtrid0mE/release/deps/libbitflags-d9002a9d89458efb.rlib" "/tmp/cargo-install.lHo7Wtrid0mE/release/deps/libordermap-b1c36c0e4f19b315.rlib" "/home/zoumi/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-1357b93f.rlib" "/home/zoumi/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-1357b93f.rlib" "/home/zoumi/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-1357b93f.rlib" "/home/zoumi/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librand-1357b93f.rlib" "/home/zoumi/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcollections-1357b93f.rlib" "/home/zoumi/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-1357b93f.rlib" "/home/zoumi/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_jemalloc-1357b93f.rlib" "/home/zoumi/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-1357b93f.rlib" "/home/zoumi/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_unicode-1357b93f.rlib" "/home/zoumi/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-1357b93f.rlib" "/home/zoumi/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-1357b93f.rlib" "-l" "z" "-l" "util" "-l" "dl" "-l" "pthread" "-l" "gcc_s" "-l" "pthread" "-l" "c" "-l" "m" "-l" "rt" "-l" "util"
  = note: /tmp/cargo-install.lHo7Wtrid0mE/release/deps/libcurl_sys-0bbd500c39ae99a7.rlib(libcurl_la-openssl.o): In function `Curl_ossl_seed':
openssl.c:(.text.Curl_ossl_seed+0x53): undefined reference to `RAND_egd'
/tmp/cargo-install.lHo7Wtrid0mE/release/deps/libcurl_sys-0bbd500c39ae99a7.rlib(libcurl_la-openssl.o): In function `X509V3_ext':
openssl.c:(.text.X509V3_ext+0x21): undefined reference to `sk_num'
openssl.c:(.text.X509V3_ext+0x4f): undefined reference to `sk_num'
openssl.c:(.text.X509V3_ext+0x63): undefined reference to `sk_value'
openssl.c:(.text.X509V3_ext+0x16d): undefined reference to `sk_num'
/tmp/cargo-install.lHo7Wtrid0mE/release/deps/libcurl_sys-0bbd500c39ae99a7.rlib(libcurl_la-openssl.o): In function `ossl_connect_common':
openssl.c:(.text.ossl_connect_common+0x414): undefined reference to `SSLv23_client_method'
openssl.c:(.text.ossl_connect_common+0x513): undefined reference to `SSLv3_client_method'
openssl.c:(.text.ossl_connect_common+0x6f3): undefined reference to `SSLv2_client_method'
openssl.c:(.text.ossl_connect_common+0xa4f): undefined reference to `sk_num'
openssl.c:(.text.ossl_connect_common+0xaa2): undefined reference to `sk_value'
openssl.c:(.text.ossl_connect_common+0xfa4): undefined reference to `sk_num'
openssl.c:(.text.ossl_connect_common+0xffd): undefined reference to `sk_value'
openssl.c:(.text.ossl_connect_common+0x1787): undefined reference to `sk_pop_free'
openssl.c:(.text.ossl_connect_common+0x2395): undefined reference to `sk_num'
openssl.c:(.text.ossl_connect_common+0x23ad): undefined reference to `sk_num'
openssl.c:(.text.ossl_connect_common+0x23bf): undefined reference to `sk_num'
openssl.c:(.text.ossl_connect_common+0x23cf): undefined reference to `sk_value'
openssl.c:(.text.ossl_connect_common+0x23e8): undefined reference to `sk_num'
openssl.c:(.text.ossl_connect_common+0x23fc): undefined reference to `sk_value'
openssl.c:(.text.ossl_connect_common+0x2661): undefined reference to `sk_pop'
openssl.c:(.text.ossl_connect_common+0x26a3): undefined reference to `sk_num'
openssl.c:(.text.ossl_connect_common+0x26db): undefined reference to `sk_pop_free'
/tmp/cargo-install.lHo7Wtrid0mE/release/deps/libcurl_sys-0bbd500c39ae99a7.rlib(libcurl_la-openssl.o): In function `Curl_ossl_init':
openssl.c:(.text.Curl_ossl_init+0x1d): undefined reference to `SSL_load_error_strings'
openssl.c:(.text.Curl_ossl_init+0x22): undefined reference to `SSL_library_init'
openssl.c:(.text.Curl_ossl_init+0x31): undefined reference to `OPENSSL_add_all_algorithms_noconf'
/tmp/cargo-install.lHo7Wtrid0mE/release/deps/libcurl_sys-0bbd500c39ae99a7.rlib(libcurl_la-openssl.o): In function `Curl_ossl_version':
openssl.c:(.text.Curl_ossl_version+0x17): undefined reference to `SSLeay'
collect2: error: ld returned 1 exit status


error: aborting due to previous error

error: failed to compile `cargo-tree v0.10.0`, intermediate artifacts can be found at `/tmp/cargo-install.lHo7Wtrid0mE`

Caused by:
  Could not compile `cargo-tree`.


But, I find another solution  at cargo-tree's issue list.
https://github.com/sfackler/cargo-tree/issues/11

**Comment by sfackler** [comment]
Looks like you're building against a version of OpenSSL that's unsupported by libcurl - probably 1.1.0?

**Comment by zoumi** [comment]
Thank you very very much @sfackler !
After change:

    export OPENSSL_STATIC=1
    export OPENSSL_DIR=/home/zoumi/programs/openssl-1.1.0b/
    export OPENSSL_LIB_DIR=/home/zoumi/programs/openssl-1.1.0b/
to

    export OPENSSL_STATIC=1
    export OPENSSL_LIB_DIR=/home/zoumi/programs/openssl-1.0.1b/
    export OPENSSL_DIR=/home/zoumi/programs/openssl-1.0.1b/
It compiles successfully!
