### ISSUE TITLE
Consider adding the option to building openssl

### ISSUE THREAD

**Issue by malbarbo** [sfackler/rust-openssl#580]
[Many people](https://www.reddit.com/r/rust/comments/5ts7cb/i_have_to_precompile_openssl_for_almost_any/) have to cross compile openssl many times... 

[curl-sys](https://github.com/alexcrichton/curl-rust/tree/master/curl-sys) is capable of building libcurl.

If rust-openssl was capable of building openssl, this would simplify cross compile crates that depends on rust-openssl. For example, cargo and rustup build system would be simplified (cargo was an [option](https://github.com/rust-lang/cargo/blob/6f1b860da7aba4c5ea97a49de08a61f3f330e92d/configure#L306) to build openssl, the [ci](https://github.com/rust-lang-nursery/rustup.rs/blob/408ed84f0e50511ed44a405dd91365e5da588790/ci/run-docker.sh#L10) of rustup is similar)

**Comment by sfackler** [comment]
This has come up before, and I am not comfortable being on the hook for rolling out emergency releases immediately after some critical CVEs get fixed in OpenSSL.

**Comment by malbarbo** [comment]
What if the user provides a tar.gz with the openssl source? That way, is the responsibility of the user to choose a release.

Not that building openssl does not mean static linking, the user can still choose dynamic linking.

The main idea is to facilitate cross compiling, if the user chooses static link, that their responsibility, even if using the openssl from the system.

**Comment by sfackler** [comment]
That seems like it could be workable.

**Comment by sfackler** [comment]
One "fun" bit of this would be the need to translate from rust target specs to openssl `Configure`'s target spec and manage `CC`.

**Comment by malbarbo** [comment]
Take a look at the approach that [cargo](https://github.com/rust-lang/cargo/blob/6f1b860da7aba4c5ea97a49de08a61f3f330e92d/Makefile.in#L198-L291) and [rustup](https://github.com/rust-lang-nursery/rustup.rs/blob/408ed84f0e50511ed44a405dd91365e5da588790/ci/run-docker.sh#L24-L127) has taken.

**Comment by sfackler** [comment]
@alexcrichton I'm thinking compiler detection will probably work the same way gcc-rs does. Could you give a quick overview of how the logic there works?

**Comment by sfackler** [comment]
I'm not sure it's a good idea to allow dynamic linking with this setup - compile time settings can break ABI compatibility. If we build an OpenSSL and dynamically link with the intention of using the local copy on the target, there is a decent chance things will go wrong in ways that I don't think can be detected ahead of time.

**Comment by alexcrichton** [comment]
FWIW I'm [adding logic to rustbuild](https://github.com/rust-lang/rust/pull/39917/files#diff-9a46b13a265be2ded97369dddf5037f5) to build OpenSSL, so if you'd like to copy/crib off that you're more than welcome :)

**Comment by jwilm** [comment]
We (OneSignal) would love to see this supported. Our build system has added complexity to support building and statically linking libssl/libcrypto.

Providing our own tarball would be totally fine. Would this be accomplished through a build script?

**Comment by sfackler** [comment]
It'd just be a check in the openssl-sys build script for `OPENSSL_SRC` which would cause it skip the normal search step, untar that, build it and statically link to it.

**Comment by sfackler** [comment]
Take a look at https://github.com/sfackler/rust-openssl/pull/589. It's still a bit hacky - Windows isn't supported and cross compilation requires you to set CC, LD and RANLIB yourself, but it seems to work.
