### ISSUE TITLE
Support for PKCS #8 encrypted keys

### ISSUE THREAD

**Issue by sebasmagri** [sfackler/rust-openssl#581]
Hi!

Is there any kind of support in place to load a PKCS8 encrypted key file? How should it be done?

**Comment by sfackler** [comment]
I believe you should be able to use https://docs.rs/openssl/0.9.7/openssl/pkey/struct.PKey.html#method.private_key_from_pem_passphrase or https://docs.rs/openssl/0.9.7/openssl/pkey/struct.PKey.html#method.private_key_from_pem_callback.

Similar methods are defined on the `Rsa` etc types as well.

**Comment by sebasmagri** [comment]
@sfackler yes, the problem is that input is given in DER format only. I could convert the key to PEM before loading it, but I was wondering if there was a better alternative.

**Comment by sfackler** [comment]
Ah, gotcha. Should just be a matter of tracking down the right OpenSSL function to do the decryption then. I should be able to do that tonight, but if you'd like to do it and open a PR that'd be great as well!

**Comment by sebasmagri** [comment]
Thanks @sfackler 

Looking forward to contribute with other OpenSSL trackings.

**Comment by silmeth** [comment]
Somehow related: is there an easy way to export a private key back to PKCS#8 DER bytes without going through PEM first?

It seems all the `private_key_to_der()` functions generate 'a key specific format’, that is PKCS#1 DER in case of RSA keys.
