### ISSUE TITLE
Add support for scrypt via the OpenSSL 1.1.0 EVP_PBE_scrypt() API

### ISSUE THREAD

**Issue by tarcieri** [sfackler/rust-openssl#586]
OpenSSL 1.1.0 added support for scrypt:

https://github.com/openssl/openssl/blob/d42d0a4dc7925e3ea398821028a254c94665d733/include/openssl/evp.h#L1044

It would be nice if this were exposed through rust-openssl

**Comment by sfackler** [comment]
Yep, sounds good to me.
