### ISSUE TITLE
Make `Verifier` usable with HMACs

### ISSUE THREAD

**Issue by Philipp91** [sfackler/rust-openssl#588]
- It makes the entire `sign` API usable with any kind of `PKey`.
- It can internally use `memcmp::eq()` to prevent unknowing users from using `==` instead, possibly making their application vulnerable to timing attacks.

**Comment by sfackler** [comment]
I think this is a feature request to make on OpenSSL itself. I don't really want to have any more extra logic on top of the raw OpenSSL APIs than is absolutely necessary.

**Comment by sfackler** [comment]
(it is definitely weird that you can't use the standard EVP verifier logic with HMAC keys, though)

**Comment by Philipp91** [comment]
Sorry, I didn't realize that the signing API mirrors OpenSSL so closely.

https://github.com/openssl/openssl/issues/2711
