### ISSUE TITLE
symm::Crypter ensures space in output buffer for padding even when padding is disabled

### ISSUE THREAD

**Issue by quvide** [sfackler/rust-openssl#596]
I'm not completely sure if the check is there for that exact reason. If it is, I can make a pull request fixing it.

Relevant line: https://github.com/sfackler/rust-openssl/blob/master/openssl/src/symm.rs#L278

**Comment by sfackler** [comment]
From the [man page](https://www.openssl.org/docs/man1.1.0/crypto/EVP_CipherUpdate.html):

>  The amount of data written depends on the block alignment of the encrypted data: as a result the amount of data written may be anything from zero bytes to (inl + cipher_block_size - 1) so out should contain sufficient room.

**Comment by quvide** [comment]
All right. Closing the issue then.
