### ISSUE TITLE
Can't build for musl on Linux

### ISSUE THREAD

**Issue by Timmmm** [sfackler/rust-openssl#603]
I'm trying to build something that uses rust-openssl on Ubuntu 16.04 using the -musl target.

    cargo build --release --target=x86_64-unknown-linux-musl

First when I build it it tells me to `export PKG_CONFIG_ALLOW_CROSS=1`. Not sure why but whatever; I did it.

Unfortunately then it seems to have trouble finding the OpenSSL headers. I installed them with `sudo apt install libssl-dev`. 

    cargo:warning=/home/parallels/myapp/target/x86_64-unknown-linux-musl/release/build/openssl-sys-9bee6f02b4f3e608/out/expando.c:2:33: fatal error: openssl/opensslconf.h: No such file or directory

You can do `export OPENSSL_DIR=/usr/include/x86_64-linux-gnu` and then it finds the headers, however then you get this error:

    thread 'main' panicked at 'OpenSSL library directory does not exist: /usr/include/x86_64-linux-gnu/lib', /home/parallels/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.9/build.rs:55

**Comment by sfackler** [comment]
You can use `OPENSSL_LIB_DIR` and `OPENSSL_INCLUDE_DIR` when the directories are split like this.

**Comment by Timmmm** [comment]
Hmmm the problem is it looks for `openssl/opensslconf.h` and `openssl/opensslv.h` but those are in different paths in Ubuntu, for some insane reason:

    /usr/include/x86_64-linux-gnu/openssl/opensslconf.h
    /usr/include/openssl/opensslv.h

It works with the non-musl target though. Maybe I need to link `/usr/include/x86_64-linux-musl/openssl` to `/usr/include/x86_64-linux-gnu/openssl`?

**Comment by Timmmm** [comment]
Yeah that seemed to do the trick. Although now `libssh2-sys` won't compile because it includes `openssl/sha.h` and apparently doesn't use `OPENSSL_INCLUDE_DIR`. Ugh. Can't wait for someone to rewrite OpenSSL in Rust.

**Comment by sfackler** [comment]
I'm confused - if you're cross-compiling to MUSL, you'll probably need an OpenSSL cross-compiled for MUSL as well. If you're not cross-compiling, pkg-config will handle all of this configuration for you when using the normal Ubuntu OpenSSL install.

**Comment by Timmmm** [comment]
Ah yes good point. I give up!

**Comment by fourohfour** [comment]
Note to anyone who comes across an error like this in the future - I was able to get this to work by building [openssl-1.0.2l](https://www.openssl.org/source/) from source. Make sure that whatever path you give to `./config --openssldir={path}` (`/usr/local/ssl` worked well for me) when building openssl, you also export as `OPENSSL_DIR` for the `rust-openssl` (or perhaps another crate such as `cargo`) build. It might be necessary to point `OPENSSL_INCLUDE_DIR` and `OPENSSL_LIB_DIR` as well, but normally `rust-openssl` finds what it needs without issues.

* [Docs on building OpenSSL from source](https://wiki.openssl.org/index.php/Compilation_and_Installation)

**Comment by tobias47n9e** [comment]
Confirming that same error happens on **Ubuntu 17.10** with **openssl-sys v0.9.27**.

**Comment by parasyte** [comment]
I just landed on this ticket looking for a way to build `native-tls` with MUSL. What worked for me was building in [`clux/muslrust`](https://github.com/clux/muslrust)

**Comment by sztomi** [comment]
@parasyte thank you so much for mentioning that here, works like a charm.

**Comment by ctopher7** [comment]
@parasyte thanks for saving my life. Been searching to compile my app with the rust official image and keep crashing on openssl. This image works like a charm

**Comment by Ujang360** [comment]
I solved this with `openssl = { version = "=0.10.33", features = ["vendored"] }`
