### ISSUE TITLE
OPENSSL_STATIC=1 doesn't seem to work on Ubuntu

### ISSUE THREAD

**Issue by Timmmm** [sfackler/rust-openssl#604]
Maybe I don't understand this, but I run the following:

    export OPENSSL_STATIC=1
    cargo build --release
    ldd target/release/myapp
	linux-vdso.so.1 =>  (0x00007ffeec755000)
	libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f2e91d78000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f2e91b74000)
	libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f2e9172f000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f2e91527000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f2e9130a000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f2e910f3000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2e90d2a000)
	/lib64/ld-linux-x86-64.so.2 (0x00005628c64a4000)

That... doesn't seem right does it? There is a `libssl.a` in `/usr/lib/x86_64-linux-gnu` which I was expecting it to use.

**Comment by sfackler** [comment]
What does `target/debug/build/openssl-sys-<SOME_HASH>/output` contain?

**Comment by onur** [comment]
I also have same issue. `OPENSSL_STATIC` never worked for me on Debian sid.

```
$ cat target/debug/build/openssl-sys-9bee6f02b4f3e608/output
cargo:rustc-link-lib=ssl
cargo:rustc-link-lib=dl
cargo:rustc-link-lib=crypto
cargo:rustc-link-lib=dl
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = None
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
PROFILE = Some("debug")
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-E" "/tmp/example-project/target/debug/build/openssl-sys-9bee6f02b4f3e608/out/expando.c"
ExitStatus(ExitStatus(0))
cargo:rustc-cfg=osslconf="OPENSSL_NO_KRB5"
cargo:rustc-cfg=osslconf="OPENSSL_NO_SSL3_METHOD"
cargo:conf=OPENSSL_NO_KRB5,OPENSSL_NO_SSL3_METHOD
cargo:rustc-cfg=ossl102
cargo:version=102
```

I am also getting this warning during build:

```
$ OPENSSL_STATIC=1 cargo build
   Compiling openssl v0.9.9
   Compiling libc v0.2.21
   Compiling bitflags v0.7.0
   Compiling pkg-config v0.3.9
   Compiling foreign-types v0.2.0
   Compiling gcc v0.3.45
   Compiling lazy_static v0.2.4
   Compiling openssl-sys v0.9.9
warning: redundant linker flag specified for library `dl`

   Compiling example-project v0.1.0 (file:///tmp/example-project)
    Finished dev [unoptimized + debuginfo] target(s) in 6.66 secs
```

**Comment by sfackler** [comment]
I'm guessing this `is_system` check is the culprit: https://github.com/alexcrichton/pkg-config-rs/blob/master/src/lib.rs#L433.

cc @alexcrichton

**Comment by Timmmm** [comment]
I think the problem is that if you don't specify `OPENSSL_INCLUDE_DIR` and `OPENSSL_LIB_DIR` and you don't specify `OPENSSL_DIR`, then the `build.rs` script always runs `find_openssl_dir()`, which always (except on OSX) calls `try_pkg_config()`, which always (except on Window) calls `std::process::exit(0);` so it never even gets to the `determine_mode()` bit which reads `OPENSSL_STATIC`. Something is very wrong with that logic.

**Comment by sfackler** [comment]
`OPENSSL_STATIC` is also understood by pkg-config-rs, except that there's this weird special case for /usr linked above.

**Comment by Timmmm** [comment]
Ah I see. So pkg-config will link statically except if the library is in `/usr` for some reason? What a mess!

**Comment by Karrq** [comment]
I stumbled on the same error while trying to statically compile the current version of rust-openssl on arch linux.

The library lives in `/usr/lib/`.

How am I supposed to get this to work? 
I don't see a clear way in the issue... 
@Timmmm made a supposition only, and the code linked by @sfackler doesn't explain much about an exception on `usr`...

**Comment by Timmmm** [comment]
I think this should be reopened - it's clearly very confusing. An interim solution might be to detect in the build script if `OPENSSL_STATIC` is set but `OPENSSL_INCLUDE_DIR` or `OPENSSL_LIB_DIR` are not set, and throw an error.

**Comment by Karrq** [comment]
Unfortunately I believe that is not enough, as the development package for openssl doesn't include the static library, as it's installed separately (at least in Arch and Ubuntu). 
Thus the include and lib directory need to be specified. It would be nice if a warning was emitted if `OPENSSL_STATIC` was set but not the other two, and the documentation update to include this detail.

**Comment by Timmmm** [comment]
> It would be nice if a warning was emitted if OPENSSL_STATIC was set but not the other two

That's what I said no?
