### ISSUE TITLE
Error: function: "SSL23_GET_SERVER_HELLO", reason: "unknown protocol",

### ISSUE THREAD

**Issue by rohitjoshi** [sfackler/rust-openssl#609]
I am getting below error and it seems rust-openssl is not able to use the latest version of openssl.

```
ssl: Ssl { state: "unknown state" } }, error: Ssl(ErrorStack([Error { code: 336031996, library: "SSL routines", function: "SSL23_GET_SERVER_HELLO", reason: "unknown protocol", file: "s23_clnt.c", line: 757 }])) }
```

Here is an error during travis build:   https://travis-ci.org/rohitjoshi/net-utils/jobs/217934022#L356

Test case executed:  https://github.com/rohitjoshi/net-utils/blob/master/src/net/poolmgr.rs#L544

**Comment by sfackler** [comment]
There are quite a few tests in this repo that connect to google - are you disabling any protocol versions? https://github.com/sfackler/rust-openssl/blob/master/openssl/src/ssl/tests/mod.rs#L1042

**Comment by rohitjoshi** [comment]
@sfackler thanks.  Seems I need to update .travis file to install/link the correct version of openssl.
