### ISSUE TITLE
ship test data on crates.io

### ISSUE THREAD

**Issue by ignatenkobrain** [sfackler/rust-openssl#612]
otherwise, `cargo test` fails on sources from crates.io with
```
error: couldn't read src/../test/dhparams.pem: No such file or directory (os error 2)
   --> src/dh.rs:131:22
    |
131 |         let params = include_bytes!("../test/dhparams.pem");
    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
and so on.

**Comment by sfackler** [comment]
Interesting, I wasn't aware that anyone was actually running tests on things pulled off of crates.io. Seems fine to remove that exclude I think.

**Comment by ignatenkobrain** [comment]
@sfackler when we package crates for Fedora we do run `cargo test` ;)
