### ISSUE TITLE
Unknown Domain

### ISSUE THREAD

**Issue by AlexCreamer** [sfackler/rust-openssl#614]
Hi, why is it that I look up reddit.com I get an error saying that there is an unknown domain. Also, when I look up google.ca, I get a message saying the document has been moved to https://www.google.ca/?gfe_rd=cr&amp;ei=2-3oWO7sLYPF8gev-r_4Bg -- and how do I fix this problem?

**Comment by sfackler** [comment]
I'm not sure these are related to openssl in particular? The google thing seems like a normal 301 Moved HTTP response. Could you go into more detail about the reddit.com issue?

**Comment by AlexCreamer** [comment]
I'm using the basic client example provided by openssl and when changing google.com to reddit.com, I get "unknown domain" as an error message.

**Comment by sfackler** [comment]
Looks like fastly requires a `Host` header to be included in the request:

```
extern crate openssl;

use openssl::ssl::{SslMethod, SslConnectorBuilder};
use std::io::{Read, Write};
use std::net::TcpStream;

fn main() {
    let connector = SslConnectorBuilder::new(SslMethod::tls()).unwrap().build();

    let stream = TcpStream::connect("reddit.com:443").unwrap();
    let mut stream = connector.connect("reddit.com", stream).unwrap();

    stream.write_all(b"GET / HTTP/1.0\r\nHost: reddit.com\r\n\r\n").unwrap();
    let mut res = vec![];
    stream.read_to_end(&mut res).unwrap();
    println!("{}", String::from_utf8_lossy(&res));
}
```

**Comment by AlexCreamer** [comment]
I tried it and I still don't get the main site. I know with Curl, the redirect follower command "-L" makes Curl downloads the main sites. Perhaps we need some kind of working redirect.

**Comment by sfackler** [comment]
This crate just deals with the encryption of the connection. If you want
something that speaks HTTP, take a look at hyper.
