### ISSUE TITLE
Build fails with x86_64-unknown-linux-musl target

### ISSUE THREAD

**Issue by beamspease** [sfackler/rust-openssl#621]
Slightly sanitized error below
```
error: failed to run custom build command for `openssl-sys v0.9.11`
process didn't exit successfully: `target/debug/build/openssl-sys-15073067e6bcb169/build-script-build` (exit code: 101)
--- stdout
run pkg_config fail: "Cross compilation detected. Use PKG_CONFIG_ALLOW_CROSS=1 to override"

--- stderr
thread 'main' panicked at '

Could not find directory of OpenSSL installation, and this `-sys` crate cannot
proceed without this knowledge. If OpenSSL is installed and this crate had
trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
compilation process.

If you're in a situation where you think the directory *should* be found
automatically, please open a bug at https://github.com/sfackler/rust-openssl
and include information about your system as well as this message.

    $HOST = x86_64-unknown-linux-gnu
    $TARGET = x86_64-unknown-linux-musl
    openssl-sys = 0.9.11

', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.11/build.rs:180
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by sfackler** [comment]
When cross compiling, you'll need to point rust-openssl towards a copy of OpenSSL that matches up with your target with some environment variables: https://github.com/sfackler/rust-openssl#manual-configuration

**Comment by infinity0** [comment]
It shouldn't be necessary to set that many specific environment variables, `pkg-config(1)` works when I set `PKG_CONFIG_PATH` to the target-architecture libs. However this buildscript still fails for some reason. Is it resetting envvars or something?

**Comment by infinity0** [comment]
Oh, looks like I have to set `PKG_CONFIG_ALLOW_CROSS=1` for the rust pkg-config crate, otherwise it fails on purpose.

**Comment by sfackler** [comment]
Yep!

**Comment by vitiral** [comment]
@infinity0 do you think you can help me out here? Are you doing this with `cross` on TravisCI? Where are the "target-architecture libs" located?

**Comment by infinity0** [comment]
Sorry, I only know about Debian. Here, it is possible to install foreign-architecture packages, and we have a `/usr/bin/${triplet}-pkg-config` shell script linked to [this file](https://sources.debian.net/src/pkg-config/0.29-4/debian/pkg-config-crosswrapper/#L1) which "just works" when you set `PKG_CONFIG` to it. You might also need to set some more things, see the [cargo Debian packaging files](https://anonscm.debian.org/cgit/pkg-rust/cargo.git/tree/debian/rules#n8) for a cross-compiling example.

**Comment by vitiral** [comment]
Thanks @infinity0, that might help
