### ISSUE TITLE
does not have these features: `npn, tlsv1_2`

### ISSUE THREAD

**Issue by mingjunyang** [sfackler/rust-openssl#623]
Are the `rust-openssl` not support tlsv1_2 ?

```
[dependencies.openssl]
version = "0.9.*"
features = ["v110"]
optional = true
```

```
error: Package `openssl v0.9.11` does not have these features: `npn, tlsv1_2`
```

**Comment by sfackler** [comment]
Those features do not exist in the 0.9 versions: https://github.com/sfackler/rust-openssl/blob/master/openssl/Cargo.toml#L14

**Comment by mingjunyang** [comment]
It's will be support in future？Or it's support before version 0.9?

tlsv1_2 more and more popular,  and tlsv1_3 will comming.

**Comment by sfackler** [comment]
Instead of having separate features for each bit of OpenSSL API, you now enable features that are tied to the versions of OpenSSL you want to depend on. If you want to use scrypt, for example, you'd enable the `v110` feature since that functionality was added in OpenSSL 1.1.0.

**Comment by deoxyseia** [comment]
Hi, I added all the features but I have the same issue

[Dependencies]
Openssl = {version = "0.9.12", features = ["v101", "v102", "v110"]}

The output when run load build:
Error: Package `openssl v0.9.12` does not have these features:` tlsv1_2, npn`

I have installed the indicated here:
https://github.com/sfackler/rust-openssl#windows-msvc

**Comment by sfackler** [comment]
Something is still turning those features on.
