### ISSUE TITLE
looking for a way to capture certificate timestamps

### ISSUE THREAD

**Issue by softprops** [sfackler/rust-openssl#624]
I'm looking for the equivalent of how to translate [this](https://community.letsencrypt.org/t/it-there-a-command-to-show-how-many-days-certificate-you-have/11351) to rust using your crate. If it's possible with openssl client, I'm fairly positive I can do it with this crate. Can you provide an example?

**Comment by sfackler** [comment]
Yep - something like this should do what you're looking for:

```rust
let cert = X509::from_pem(my_cert).unwrap();
println!("notBefore={} notAfter={}", cert.not_before(), cert.not_after());
```

**Comment by softprops** [comment]
Sry I should have more specific.  I'm trying to figure out how to get access to that cert given only a hostname.

**Comment by sfackler** [comment]
Oh, in that case something like this (untested) should work:

```rust
let connector = SslConnectorBuilder::new().unwrap().build().unwrap();
let socket = TcpStream::connect(("google.com", 443)).unwrap();
let stream = connector.connect("google.com", socket).unwrap();
let cert = stream.ssl().peer_certificate().unwrap();
println!("notBefore={} notAfter={}", cert.not_before(), cert.not_after());
```

**Comment by softprops** [comment]
Perfect. Thanks!
