### ISSUE TITLE
Boringssl support

### ISSUE THREAD

**Issue by rajatgoel** [sfackler/rust-openssl#628]
Hi, is there any plan to support boringssl in this crate? It doesn't exactly fit the `openssl` bill but is pretty close to openssl/libressl and would nice thing to support for users that do not want to switch to ring.

**Comment by bluejekyll** [comment]
you might want to look at https://github.com/briansmith/ring

**Comment by sfackler** [comment]
BoringSSL was originally based off of OpenSSL but the API has since
diverged significantly. I don't think it would make sense to try to support
here.

**Comment by rajatgoel** [comment]
Yeh, we know about ring. It just so happens that we are in a situation where we are already using these bindings for https support, and we also depend on boringssl (compiled separately as part of grpc). 

So for us instead of trying to link both SSL libs, or switching to ring (where the problem I guess still remains because both grpc and ring will continue to have their own copy of boringssl)...the easiest solution would be if rust-openssl adds supports for boringssl and we just make both grpc and rust-openssl depend on same copy of boringssl.

**Comment by briansmith** [comment]
> .the easiest solution would be if rust-openssl adds supports for boringssl and we just make both grpc and rust-openssl depend on same copy of boringssl.

I will help you port grpc to *ring* + rustls.

**Comment by rajatgoel** [comment]
The grpc we use in vanilla version from https://github.com/grpc/grpc. We use Bazel to build rust and  directly depend on cc_library targets from Bazel BUILD files in grpc repo. 

So I don't think in this kind of setup it will be feasible to change grpc to ring + rustls, right? If we were using some native grpc implementation, I am pretty sure we would be using ring in the first place.

**Comment by briansmith** [comment]
> So I don't think in this kind of setup it will be feasible to change grpc to ring + rustls, right? If we were using some native grpc implementation, I am pretty sure we would be using ring in the first place.

It would be feasible, but I probably shouldn't help do that, for political reasons. Instead I recommend people switch to one of the Rust GRPC implementations.

**Comment by rajatgoel** [comment]
Thanks for the prompt response to the issue everyone. We will figure out some work-around until we move to tokio/grpc based stack.
