### ISSUE TITLE
Decoding PKey from DER

### ISSUE THREAD

**Issue by sauyon** [sfackler/rust-openssl#629]
Can this be added/does it exist?

At the moment I'm using this function:

```rust
PKey::public_key_from_pem(
  format!("-----BEGIN PUBLIC KEY-----\n{}\n-----END PUBLIC KEY-----",
          base64::encode(bytes)).into_bytes().as_slice())
```

which is a bit ugly.

**Comment by sfackler** [comment]
Looks like it's just a matter of binding to `i2d_PUBKEY` - should be pretty straightforward.
