### ISSUE TITLE
License unclear

### ISSUE THREAD

**Issue by brson** [sfackler/rust-openssl#633]
The readme of this repo says "MIT/Apache-2.0", the openssl Cargo.toml says "Apache-2.0", the openssl-sys Cargo.toml says "MIT".

**Comment by sfackler** [comment]
The licensing story is best described as a "huge mess". Much of openssl was inherited with an ASL license and acrichto picked MIT when splitting openssl-sys out. The readme MIT/ASL only applies to future contributions to stop the bleeding.

At this point, I think I'd probably want to talk to a lawyer before relicensing :(

**Comment by DemiMarie** [comment]
@sfackler Can you contact all copyright owners?  It is always possible to relicense code with the permission of all copyright owners.

**Comment by sfackler** [comment]
This issue attempted to do that, but didn't get all the way: https://github.com/sfackler/rust-openssl/issues/331

In addition, one of the copyright holders is Google. The code that had that copyright has been pretty significantly rewritten, but IANAL.
