### ISSUE TITLE
Use feature guard instead of environment variable to enable static link

### ISSUE THREAD

**Issue by BusyJay** [sfackler/rust-openssl#653]
Using environment variable will have following shortcomings:

- A rebuild won't be triggered when set an environment variable;
- If some project always prefer linking statically, there is no clean way to build such a binary.

Features guard can solve both perfectly, and also a *rusty* way.

**Comment by sfackler** [comment]
This change would probably need to be made in pkg-config first.

**Comment by BusyJay** [comment]
I don't get it. `OPENSSL_STATIC` is not used by `pkg-config`, right? I think it should be simply adding `if cfg!(feature = "static-link")` at line https://github.com/sfackler/rust-openssl/blob/master/openssl-sys/build.rs#L395.

**Comment by sfackler** [comment]
`OPENSSL_STATIC` is used by pkg-config: https://docs.rs/pkg-config/0.3.9/pkg_config/.

**Comment by BusyJay** [comment]
Oh, I see. Sorry for my carelessness. Since `pkg_confg` [supports ](https://docs.rs/pkg-config/0.3.9/pkg_config/struct.Config.html#method.statik) passing `--static` explicitly, it should be able to check the features and add the flags without breaking old behavior.

**Comment by alexcrichton** [comment]
I'd personally find build configuration like this to be more naturally done as environment variables than as features. For example someone building a crate shouldn't need to modify `Cargo.toml` to configure the build. Additionally crates themselves shoudn't really care whether OpenSSL is linked statically or dynamically, that's more of a question of whomever is generating the final build artifact.

I think the biggest problem with using environment variables, build scripts don't get rerun if they're changed, has [now been fixed](https://github.com/rust-lang/cargo/pull/4125)
