### ISSUE TITLE
can't export raw (PKCS#1) public key

### ISSUE THREAD

**Issue by jlgale** [sfackler/rust-openssl#656]
I'm using the https://github.com/briansmith/ring library (via https://github.com/Keats/jsonwebtoken) to validate JWT signatures. I have an x509 certificate with the public key that I trust. The `rust-openssl` library will give me a `DER` encoding of that key, but it's in the PKCS#8 form. For whatever reason, the `jsonwebtoken`/`ring` library can't deal with this. They seem to expect the raw public key. Maybe it's a deficiency on their side? But it would be nice if `rust-openssl` could help me bridge this gap.

I'm not very familiar with openssl or public key cryptography so excuse me if I missed something that already addresses this. My understanding is informed by this article:
https://stackoverflow.com/a/29707204/2684334

**Comment by sfackler** [comment]
The [`Rsa::public_key_to_der`](https://docs.rs/openssl/0.9.14/openssl/rsa/struct.RsaRef.html#method.public_key_to_der) method should give you the key in PKCS#1. If you're working with a `PKey`, you can get the `Rsa` key out of it with [`PKey::rsa`](https://docs.rs/openssl/0.9.14/openssl/pkey/struct.PKey.html#method.rsa)

**Comment by jlgale** [comment]
It's possible that I'm confused, but in my case I found that the output of `PKey::public_key_to_der` and `Rsa::public_key_to_der` was identical. Both cases had the wrapper.

**Comment by sfackler** [comment]
Ah, right, you need a function wrapping `i2d_RSAPublicKey`, but `public_key_to_der` wraps `id2_RSA_PUBKEY`. Should be a pretty easy addition.

**Comment by jlgale** [comment]
Thanks for taking the time to look into this.

**Comment by sfackler** [comment]
Can you try #657 and make sure it does what you need?

**Comment by briansmith** [comment]
> he rust-openssl library will give me a DER encoding of that key, but it's in the PKCS#8 form. For whatever reason, the jsonwebtoken/ring library can't deal with this. They seem to expect the raw public key. Maybe it's a deficiency on their side?

rust-openssl is (probably) giving you the SPKI form, not PKCS#8. *ring* will eventually accept the SPKI form as soon as I have free time to merge the changes in. It's tracked in *ring* as https://github.com/briansmith/ring/issues/370.

**Comment by jlgale** [comment]
@sfackler thank you very much for the fix. It does indeed work for us.
