### ISSUE TITLE
Maybe include the libssl-dev dependency

### ISSUE THREAD

**Issue by TheCynosure** [sfackler/rust-openssl#685]
I am using a project that uses openssl-sys in it and when I run
```
cargo build
```
I get the following error:
```
error: failed to run custom build command for `openssl-sys v0.9.17`
process didn't exit successfully: `/home/jack/Dev/Projects/github_local/target/debug/build/openssl-sys-8408033d59a8de8c/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
cargo:rerun-if-env-changed=OPENSSL_DIR
run pkg_config fail: "`\"pkg-config\" \"--libs\" \"--cflags\" \"openssl\"` did not exit successfully: exit code: 1\n--- stderr\nPackage openssl was not found in the pkg-config search path.\nPerhaps you should add the directory containing `openssl.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'openssl\' found\n"

--- stderr
thread 'main' panicked at '

Could not find directory of OpenSSL installation, and this `-sys` crate cannot
proceed without this knowledge. If OpenSSL is installed and this crate had
trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
compilation process.

If you're in a situation where you think the directory *should* be found
automatically, please open a bug at https://github.com/sfackler/rust-openssl
and include information about your system as well as this message.

    $HOST = x86_64-unknown-linux-gnu
    $TARGET = x86_64-unknown-linux-gnu
    openssl-sys = 0.9.17

', /home/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.17/build.rs:201
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
__Fix__:
The fix I used was to install libssl-dev. On ubuntu I did this with:
```
sudo apt-get install libssl-dev
```
Is there anyway this dependency could be included in the project, or maybe suggested in the error message?

**Comment by sfackler** [comment]
libssl-dev contains the headers that match up with the system's OpenSSL version - there's no real way we can include those. We could potentially include some of the text in the README in the error message: https://github.com/sfackler/rust-openssl#linux.

There is also some in-progress work to have openssl-sys build its own copy of OpenSSL: https://github.com/sfackler/rust-openssl/pull/684 though we'll always look for the system installed copy by default.

**Comment by TheCynosure** [comment]
I think it would be great if you could put that on the ReadME

**Comment by sfackler** [comment]
Put what exactly on the readme?

**Comment by TheCynosure** [comment]
I now see that you have this already on the README, to install libssl-dev. I came here from another crate that required this one. I will tell the other crate owner that it might be a good idea to tell people that they need to install libssl-dev, or even link to your documentation.
