### ISSUE TITLE
OpenSSL not found automatically on FreeBSD 11.1

### ISSUE THREAD

**Issue by wezm** [sfackler/rust-openssl#686]
```
   Compiling openssl-sys v0.9.17
error: failed to run custom build command for `openssl-sys v0.9.17`
process didn't exit successfully: `/usr/home/wmoore/ruststickers/target/debug/build/openssl-sys-3f5c21ee30dd5527/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
cargo:rerun-if-env-changed=OPENSSL_DIR
run pkg_config fail: "Failed to run `\"pkg-config\" \"--libs\" \"--cflags\" \"openssl\"`: No such file or directory (os error 2)"

--- stderr
thread 'main' panicked at '

Could not find directory of OpenSSL installation, and this `-sys` crate cannot
proceed without this knowledge. If OpenSSL is installed and this crate had
trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
compilation process.

If you're in a situation where you think the directory *should* be found
automatically, please open a bug at https://github.com/sfackler/rust-openssl
and include information about your system as well as this message.

    $HOST = x86_64-unknown-freebsd
    $TARGET = x86_64-unknown-freebsd
    openssl-sys = 0.9.17
```

Compiling with `OPENSSL_DIR=/usr cargo b` builds successfully.

**OS Version:** FreeBSD 11.1-RELEASE
**Content of `/usr/include/openssl/opensslv.h`:** https://github.com/freebsd/freebsd/blob/stable/11/crypto/openssl/crypto/opensslv.h

**Comment by sfackler** [comment]
Do you have pkg-config installed?

**Comment by wezm** [comment]
No. I haven't tried with it installed but I don't think it would help. OpenSSL is part of the base system on the BSDs, it's not a package so I wouldn't expect installing pkg-config to add any `.pc` files to point at system libraries.

Ok I tried it with pkgconf installed. It does indeed still fail due to lack of openssl.pc:

```
error: failed to run custom build command for `openssl-sys v0.9.17`
process didn't exit successfully: `/usr/home/wmoore/ruststickers/target/debug/build/openssl-sys-3f5c21ee30dd5527/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
cargo:rerun-if-env-changed=OPENSSL_DIR
run pkg_config fail: "`\"pkg-config\" \"--libs\" \"--cflags\" \"openssl\"` did not exit successfully: exit code: 1\n--- stderr\nPackage openssl was not found in the pkg-config search path.\nPerhaps you should add the directory containing `openssl.pc\'\nto the PKG_CONFIG_PATH environment variable\nPackage \'openssl\', required by \'virtual:world\', not found\n"
```

**Comment by sfackler** [comment]
So does portable software have to detect it's on FreeBSD and guess where OpenSSL lives?

**Comment by wezm** [comment]
It's the same as all other system libraries. It's already in the include path/lib path of the compiler so it will be found automatically without any special arguments. Same as OS X (before they deprecated OpenSSL).

**Comment by sfackler** [comment]
But OSX ships /usr/lib/pkgconfig/openssl.pc.

**Comment by wezm** [comment]
Ahh. I double checked the code and it looks like they don't ship an openssl pkg conf file anywhere.

Looks like the build script already has special handling for different platforms. Perhaps there could be a generic (I.e. not Freebsd specific) branch in find_openssl_dir that looks in standard locations like /usr/include/openssl?

**Comment by sfackler** [comment]
Yeah, we'll probably want to special case FreeBSD a bit like we handle Homebrew on OSX: https://github.com/sfackler/rust-openssl/blob/master/openssl-sys/build.rs#L103

**Comment by myfreeweb** [comment]
pkgconf does work when LibreSSL/OpenSSL is also installed from packages

**Comment by durin42** [comment]
I just tripped on this. Should we do something like this?

```
if freebsd {
  openssl_dir = match pkg_config_path {
    Some(path) => path,
    None => "/usr",
  }
}
```

IOW prefer {Libre,Open}SSL from ports if it's there, otherwise use the one from the base system? Maybe with an environment variable to force using the one from the base system even if something else is installed from a package?

**Comment by bdrewery** [comment]
Thanks for this, was just looking into a fix and glad to see it's already handled.
