### ISSUE TITLE
 add minimum support Rust version to be tested

### ISSUE THREAD

**Issue by cardoe** [sfackler/rust-openssl#688]
https://github.com/sfackler/rust-openssl/blob/811be8dae2daba8f976354ea0bbae26f4673f7ba/.circleci/config.yml#L34

Please add the minimum supported Rust version to the test cases to avoid unpleasant surprised like servo/unicode-bidi#46

**Comment by sfackler** [comment]
Any reason to not treat 1.19 as the minimum supported version?

**Comment by cardoe** [comment]
Sure. But the constant pull up in stable version on the patch level release effectively breaks semver for people. Rust is effectively saying everything is semver except for depends on the stdlib and compiler. I'd love to see some commitment to version in changes that require newer versions of Rust.

**Comment by cardoe** [comment]
And I know I'm basically talking about rust-lang/rfcs#1133

**Comment by sfackler** [comment]
Are you running an old version of Rust?

**Comment by cardoe** [comment]
Yes. I'm stuck on 1.15.1. Unfortunately its not easy to just upgrade the compiler version everytime a release comes out so we were encouraged by the promise of semver compat.

**Comment by sfackler** [comment]
The upcoming 0.10 release will require Rust 1.20, which is what we're using in CI now.
