### ISSUE TITLE
inaccurate hint for mingw dependencies

### ISSUE THREAD

**Issue by jsen-** [sfackler/rust-openssl#689]
When openssl is missing on mingw the hint suggests installation of `openssl` package

```
It looks like you're compiling for MinGW but you may not have either OpenSSL or
pkg-config installed. You can install these two dependencies with:

    pacman -S openssl pkg-config
```
The package required is actually **`openssl-devel`**, so `pacman -S openssl-devel pkg-config` would be more appropriate.

I'm not sure how to find the version of msys/mingw I'm using :( I can provide any additional info if guided properly :)

**Comment by sfackler** [comment]
Fixed!
