### ISSUE TITLE
CC environment variable is too strictly parsed leading to compilation failure

### ISSUE THREAD

**Issue by mqudsi** [sfackler/rust-openssl#691]
`opensssl-sys` currently expects `CC` to be a path to a single executable and fails if it includes any command line arguments.

We have `CC` globally defined as `sccache cc` (to use the rust-powered [sccache](https://github.com/mozilla/sccache)), it's also common to have `CC` defined as `cc -fcolor-diagnostics` or `cc -W...`

The build system should not try to parse `CC` as a single path; it should instead be parsed as a command with the head being the path (so usually the first word but possibly a quoted path including spaces) and any subsequent "words" thereafter as being parameters to said executable.

Here's what the current build output looks like with CC defined:

> running: "sccache cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-Wall" "-Wextra" "-E" "/mnt/c/Users/Mahmoud/git/gittree/target/debug/build/openssl-sys-e70b6c3f5a58b72d/out/expando.c"
> 
> --- stderr
> thread 'main' panicked at '
> 
> Internal error occurred: Failed to find tool. Is `sccache cc` installed?

**Comment by sfackler** [comment]
This seems like something that should be filed on https://github.com/alexcrichton/gcc-rs?

**Comment by alexcrichton** [comment]
I believe this should be fixed by https://github.com/alexcrichton/gcc-rs/commit/3c636f76f4fb8015342c946566b3f1f937eab4fd

**Comment by mqudsi** [comment]
Thanks, @alexcrichton !
