### ISSUE TITLE
openssl-sys not building on linux when built with the -z compile option

### ISSUE THREAD

**Issue by mcdenhoed** [sfackler/rust-openssl#693]
(previously posted as https://github.com/rust-lang/cargo/issues/4483)
# Steps to Reproduce

On a linux rust install with nightly installed (tested on `rust version 1.22.0-nightly (ca94c75c5 2017-09-10)`):

* Make a new cargo bin project with the following `Cargo.toml`:

```
[package]
name = "opt_test"
version = "0.1.0"
authors = [""]

[dependencies]
openssl-sys = "0.9.17"

[profile.release]
opt-level = 'z'
```

* `cargo +nightly run --release`

Cargo will crash when attempting to compile `openssl-sys`, complaining about passing `gcc` the `-z` flag, which it does not support.
This does not crash on macOS, I suspect because `gcc` on macOS is just a `clang` alias, which does support the `-z` flag.

**Comment by sfackler** [comment]
The build script uses https://github.com/alexcrichton/gcc-rs to interface with gcc - this issue should probably be filed there.

**Comment by mcdenhoed** [comment]
Alright, I will post it there. Thanks!

**Comment by mcdenhoed** [comment]
This has been fixed in gcc-rs, so the next release of it should not have this issue.
