### ISSUE TITLE
Deprecate/remove `crypto` module?

### ISSUE THREAD

**Issue by alexcrichton** [sfackler/rust-openssl#703]
It's only got one item and it's deprecated!

**Comment by alexcrichton** [comment]
@sfackler mind commenting about the fate of this module?

**Comment by sfackler** [comment]
Yeah it only exists for back compat.

**Comment by johnthagen** [comment]
I believe #745 closed this issue (unless this issue is left open for the removal of the module). @sfackler can you confirm?

**Comment by sfackler** [comment]
Yep, we should be good to go here. Next time we're ready to cut a breaking release I'll just make a pass and delete all of the deprecated bits, so no need to keep issues open for everything.
