### ISSUE TITLE
Improve documentation for the `version` module

### ISSUE THREAD

**Issue by alexcrichton** [sfackler/rust-openssl#725]
This is a tracking issue for the impl period for the `openssl` crate, specifically for improving the documentation of the `version` module. Documentation should include:

* [ ] Documentation on all types contained in the module
* [ ] Documentation for all methods on these types
* [ ] Documentation for all free functions
* [ ] Module documentation explaining what it is and why you'd use it
* [ ] At least one code example in the module documentation

The documentation may also wish to link to the official OpenSSL documentation where possible to ensure that there's the most up-to-date info available!

**Comment by anna-liao** [comment]
Hello, I would like to take a crack at this.  Is there a guideline for how the docs.rs are generated from the source files and what markup is supported?  I looked in [rustdoc](https://doc.rust-lang.org/stable/rustdoc/) but it doesn't seem to cover the in-line documentation I see in the [ssl module](https://github.com/sfackler/rust-openssl/blob/master/openssl/src/ssl/mod.rs) with the leading `//!' notation.

Also is there a docs.rs for another crate with a similar module, i.e. output version information, that I could refer to as a good style guideline?  Thanks!

I'm in the process of reading about OpenSSL, so thought that writing docs for rust-openssl would be a good exercise to enhance my learning.

**Comment by sfackler** [comment]
Please do!

There's more detailed information here: https://doc.rust-lang.org/book/first-edition/documentation.html
