### ISSUE TITLE
"warning: expando.c" printed during build on Windows

### ISSUE THREAD

**Issue by johnthagen** [sfackler/rust-openssl#735]
On Windows 10 x64, using this OpenSSL installer: https://slproweb.com/download/Win64OpenSSL-1_1_0f.exe

A warning is printed during `cargo build`

```cmd
rust-openssl\openssl> cargo build
   Compiling vcpkg v0.2.2
   Compiling foreign-types v0.2.0
   Compiling libc v0.2.31
   Compiling bitflags v0.9.1
   Compiling lazy_static v0.2.8
   Compiling pkg-config v0.3.9
   Compiling openssl v0.9.18 (rust-openssl/openssl)
   Compiling cc v1.0.0
   Compiling openssl-sys v0.9.18 (rust-openssl/openssl-sys)
warning: expando.c
    Finished dev [unoptimized + debuginfo] target(s) in 10.89 secs
```

**Comment by johnthagen** [comment]
This is also occurring in CI builds: https://ci.appveyor.com/project/sfackler/rust-openssl/build/1.0.1702/job/aatoilm1orh74e02#L127

**Comment by sfackler** [comment]
@alexcrichton seems like something's sneaking out of cc's logic?

**Comment by alexcrichton** [comment]
Perhaps! I'll try to take a look when I'm back at a windows machine

**Comment by alexcrichton** [comment]
I think this has to do with `cl.exe /E` where the `cl.exe` typically prints the filenames its compiling to stdout but using `/E` I think switches that to stderr. We should probably suppress the output here in the `cc` crate and not print stderr by default in these situations.

**Comment by sfackler** [comment]
Closing - this is something that needs to be handled by `cc`.

**Comment by johnthagen** [comment]
@sfackler Should I open an issue in `cc`? Just want to make sure it was captured somewhere. If it's already opened in `cc`, could a reference be placed in this issue?

**Comment by sfackler** [comment]
Yeah, it would probably be best to open an issue there.
