### ISSUE TITLE
Convert try! to ?

### ISSUE THREAD

**Issue by johnthagen** [sfackler/rust-openssl#746]
Can/should we convert `try!` usages to the idiomatic `?` usage?

It's been stable since [1.13](https://blog.rust-lang.org/2016/11/10/Rust-1.13.html).

It looks like Circle CI is pinned to 1.19 and Travis and Appveyor track latest stable. Is 1.19 the oldest supported version?

Relates to #688

**Comment by sfackler** [comment]
Yep, we can do this migration now.
