### ISSUE TITLE
cargo build report error "/home/test/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.20/src/ossl10x.rs:768: undefined reference to `OPENSSL_add_all_algorithms_noconf'"

### ISSUE THREAD

**Issue by dllhlx** [sfackler/rust-openssl#765]
The reported error desc is as title, has anybody encountered this error before?

**Comment by dllhlx** [comment]
My Cargo.toml as below:
```
[dependencies]
openssl = "0.9.20"
grpcio = "0.1"
```
run ```cargo build``` will report error: 
```
note: /home/test/target/debug/deps/libopenssl_sys-83f37b3f53691d0c.rlib(openssl_sys-83f37b3f53691d0c.0.o): In function `openssl_sys::ossl10x::init::{{closure}}':
          /home/test/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.20/src/o  l10x.rs:768: undefined reference to `OPENSSL_add_all_algorithms_noconf'
▽         collect2: error: ld returned 1 exit status
```
if I remove grpcio from Cargo.toml dependencies then cargo build will be ok. Anybody meet this case?

**Comment by sfackler** [comment]
grpcio links BoringSSL, which is incompatible with OpenSSL.

**Comment by dllhlx** [comment]
@sfackler  get it! thx.

**Comment by dllhlx** [comment]
@sfackler  When grpcio is  incompatible with openssl, Could you please show which rust grpc library can compatible with openssl? The rust  grpc library [is](https://docs.rs/grpc/) not easy to use.

**Comment by sfackler** [comment]
I don't have any experience with those libraries unfortunately.

**Comment by dllhlx** [comment]
@sfackler  thanks a lot.
