### ISSUE TITLE
Mark types that are Send and Sync

### ISSUE THREAD

**Issue by gbip** [sfackler/rust-openssl#772]
Hello,
It seems that [OpenSSL is thread safe](https://stackoverflow.com/questions/33777302/is-openssl-thread-safe#33780647) but rsa::Rsa and symm::Crypter are not marked Send nor Sync.
Would it be possible to implement this ?

**Comment by sfackler** [comment]
Yep, we should be able to mark all of our wrapper types as Send + Sync.

**Comment by gbip** [comment]
Does this just involve implementing Send and Sync for most of the type, or is there some specific behavior to watch for ?

**Comment by sfackler** [comment]
I think we can implement Send/Sync for all types created via `foreign_types!{}`.

**Comment by gbip** [comment]
So all there is to do is to modify the macro ?
If it is that simple, I might want to implement it and make a PR.

**Comment by sfackler** [comment]
That macro is defined in another crate, but you could make a macro in this crate that wraps it and adds the Send/Sync impls.

**Comment by gbip** [comment]
Ok, I will take a look at that.
