### ISSUE TITLE
panick: error: failed to run custom build command for `openssl-sys v0.9.21`

### ISSUE THREAD

**Issue by voteleobrown** [sfackler/rust-openssl#782]
--- stdout
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR
cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR
cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR
cargo:rerun-if-env-changed=OPENSSL_DIR
run pkg_config fail: "`\"pkg-config\" \"--libs\" \"--cflags\" \"openssl\"` did not exit successfully: exit code: 1\n--- stderr\nPackage openssl was not found in the pkg-config search path.\nPerhaps
 you should add the directory containing `openssl.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'openssl\' found\n"

--- stderr
thread 'main' panicked at '

Could not find directory of OpenSSL installation, and this `-sys` crate cannot
proceed without this knowledge. If OpenSSL is installed and this crate had
trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
compilation process.

If you're in a situation where you think the directory *should* be found
automatically, please open a bug at https://github.com/sfackler/rust-openssl
and include information about your system as well as this message.

    $HOST = x86_64-unknown-linux-gnu
    $TARGET = x86_64-unknown-linux-gnu
    openssl-sys = 0.9.21

', /home/services/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.21/build.rs:210

-------------------------------------------------------------

stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /build/rustc-ccfJ49/rustc-1.17.0+dfsg2/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /build/rustc-ccfJ49/rustc-1.17.0+dfsg2/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /build/rustc-ccfJ49/rustc-1.17.0+dfsg2/src/libstd/sys_common/backtrace.rs:60
             at /build/rustc-ccfJ49/rustc-1.17.0+dfsg2/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /build/rustc-ccfJ49/rustc-1.17.0+dfsg2/src/libstd/panicking.rs:371
   4: std::panicking::rust_panic_with_hook
             at /build/rustc-ccfJ49/rustc-1.17.0+dfsg2/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
             at /build/rustc-ccfJ49/rustc-1.17.0+dfsg2/src/libstd/panicking.rs:511
   6: build_script_build::find_openssl_dir
             at ./build.rs:210
   7: build_script_build::main::{{closure}}
             at ./build.rs:59
   8: <core::option::Option<T>>::unwrap_or_else
             at /build/rustc-ccfJ49/rustc-1.17.0+dfsg2/src/libcore/option.rs:358
   9: build_script_build::main
             at ./build.rs:59
  10: std::panicking::try::do_call
             at /build/rustc-ccfJ49/rustc-1.17.0+dfsg2/src/libstd/panicking.rs:454
  11: __rust_maybe_catch_panic
             at /build/rustc-ccfJ49/rustc-1.17.0+dfsg2/src/libpanic_unwind/lib.rs:98
  12: std::rt::lang_start
             at /build/rustc-ccfJ49/rustc-1.17.0+dfsg2/src/libstd/panicking.rs:433
             at /build/rustc-ccfJ49/rustc-1.17.0+dfsg2/src/libstd/panic.rs:361
             at /build/rustc-ccfJ49/rustc-1.17.0+dfsg2/src/libstd/rt.rs:57
  13: main
  14: __libc_start_main
  15: _start

**Comment by sfackler** [comment]
Do you have openssl's headers installed?

**Comment by Thunderbottom** [comment]
What OS is this? And do you have LibreSSL installed?

**Comment by voteleobrown** [comment]
Ubuntu 16.04.3 LTS

Ok I did not have LibreSSL installed at the time of this post, but after @Thunderbottom posted I followed these instructions:

http://gamblisfx.com/how-to-install-libressl-2-0-2-on-ubuntu-14-04/

--- stderr
thread 'main' panicked at '

This crate is only compatible with OpenSSL 1.0.1, 1.0.2, and 1.1.0, or LibreSSL
2.5 and 2.6.0, but a different version of OpenSSL was found. The build is now
aborting due to this version mismatch.


So I tracked down a newer version from:
https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/

And tried again. It compiled successfully, but then gave me this error upon 'cargo run':
error while loading shared libraries: libssl.so.44: cannot open shared object file: No such file or directory

No idea why, ultimately I'm only compiling the rust-curl example code, straight from the repository README:

extern crate curl;

use std::io::Read;
use curl::easy::Easy;

fn main() {
    let mut data = "this is the body".as_bytes();

    let mut easy = Easy::new();
    easy.url("http://www.example.com/upload").unwrap();
    easy.post(true).unwrap();
    easy.post_field_size(data.len() as u64).unwrap();

    let mut transfer = easy.transfer();
    transfer.read_function(|buf| {
        Ok(data.read(buf).unwrap_or(0))
    }).unwrap();
    transfer.perform().unwrap();
}

**Comment by voteleobrown** [comment]
If it makes any difference that was using https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-2.6.3.tar.gz

**Comment by Thunderbottom** [comment]
I'm not on BSD but you need to find the `libssl.so` lib. It is usually in `/usr/lib`. Try symlinking it to `libssl.so.44` and then remove the symlink after you're done. Probably not the best way to do it but should get the job done

**Comment by Thunderbottom** [comment]
Also I guess u just need to isntall this: [libssl-dev](https://packages.ubuntu.com/search?keywords=libssl-dev)

You may disregard the previous message and try this first.

**Comment by sfackler** [comment]
Yeah, please install the `-dev` package and don't manually mess with your `/usr` directory.

**Comment by Thunderbottom** [comment]
symlinking shouldn't be a problem, since it won't do anything to the main lib. But that's for later when there are no other options I guess. And since he's on ubuntu I guess libssl-dev should work fine.

**Comment by sfackler** [comment]
There is no situation I'm aware of where you'd ever need to manually edit your system-managed directories to use this library.

**Comment by Thunderbottom** [comment]
Indeed, but he has apparently used the BSD version of LibreSSL.

**Comment by sfackler** [comment]
If you installed LibreSSL in the way that post says to, you've put your system in a very bad state. There are competing, binary incompatible, versions of openssl on the system search path. It will probably take some surgery to purge the LibreSSL install.

If you want to use the system copy of OpenSSL, install `libssl-dev` and `pkg-config`.

If you want to use LibreSSL, install it to a custom prefix and point this library to it via the environment variables in the README.

**Comment by Thunderbottom** [comment]
Yes I agree with you. (OT) Been using Void Linux for a while now and if you look at the package management, it is really amazingly managed with all the things organized just how it should be.
