### ISSUE TITLE
Segfault when attempting to sign with a public key

### ISSUE THREAD

**Issue by P-E-Meunier** [sfackler/rust-openssl#790]
Since the `RSA` type does not tell whether the key contains all components or just the public ones, it's possible to be stupid and cause rust-openssl to segfault when signing with a key that doesn't have the private components.

This could be easily prevented at compile time, by adding two types, `pub enum Public {}` and `pub enum Private{}`, and a field of type `PhantomData<T>` to `Rsa`. Then, `sign` would force the key to be of type `Rsa<Private>`, and verify could be `Rsa<T>`.

The modification is nontrivial though, since this code is currently generated by macros.

This would also make some parts of the interface easier (and thus safer) to read and use, such as `PKey::rsa()`, which is currently confusing (does it contain a private or a public key?).

**Comment by sfackler** [comment]
I'm planning on cutting a new breaking release in December, so now is the time to make this kind of change!

**Comment by sfackler** [comment]
PR is up: #810.
