### ISSUE TITLE
cross compiling against incorrect header (undefined reference to `OPENSSL_init_ssl')

### ISSUE THREAD

**Issue by aep** [sfackler/rust-openssl#791]
i'm not clear on how cross compilation works with rust yet, so far i am failing with this crate.

```
OBJCOPY=mips-openwrt-linux-objcopy PKG_CONFIG_ALLOW_CROSS=1 cargo rustc --bin archon --release --target mips-unknown-linux-musl -- -C linker=mips-openwrt-linux-gcc  

/home/aep/proj/korhal/archon/target/mips-unknown-linux-musl/release/deps/libopenssl_sys-205733415bcffc31.rlib(openssl_sys-205733415bcffc31.openssl_sys0.rust-cgu.o): In function `std::sync::once::Once::call_once::{{closure}}':
openssl_sys0-4b34a5713d94a5ef72431be5700e6456.rs:(.text._ZN3std4sync4once4Once9call_once28_$u7b$$u7b$closure$u7d$$u7d$17hcc1654f71f61c3a3E+0x24): undefined reference to `OPENSSL_init_ssl'


```

i think this is because it compiled against my host headers (no way to tell since there's no debug output) which is much newer than the target version it then links against

**Comment by sfackler** [comment]
So you have a copy of OpenSSL compiled for MUSL? Where is it located on the filesystem - is pkg-config configured to find it?

**Comment by aep** [comment]
pkg-config seems to prefer the one in /usr/lib, but setting OPENSSL_INCLUDE_DIR and OPENSSL_LIB_DIR fixed this.   I found it very confusing that there's no generic sysroot option for cargo, but i'm not sure if this crate could do anything about it.

**Comment by sfackler** [comment]
Yeah, the configuration for this stuff is really ad-hoc right now. We're going to be working on pushing towards a more standardized system in the new year.

**Comment by aep** [comment]
nice <3 . closing this for because user error, probably.
