### ISSUE TITLE
libopenssl_sys-a52622bf176c3c0d.rlib(ssl_lib.o): relocation R_MIPS_HI16 against `__gnu_local_gp' can not be used when making a shared object; recompile with -fPIC

### ISSUE THREAD

**Issue by aep** [sfackler/rust-openssl#792]
passing CFLAGS=-fPIC  doesn't seem to help

**Comment by sfackler** [comment]
-fPIC will fix this - example from the CI infrastructure: https://github.com/sfackler/rust-openssl/blob/master/test/build_openssl.sh#L48

**Comment by aep** [comment]
aha! your link helped me understand that ssl_lib.o is actually from openssl, not from this crate, and that wasnt compiled fPIC
