### ISSUE TITLE
Question: Is Cert-Store reloading certs from dir at runtime?

### ISSUE THREAD

**Issue by algermissen** [sfackler/rust-openssl#816]
Do you happen to know whether the underlying cert store will check for unsigned certs in the configured path on demand? At runtime?

https://github.com/sfackler/rust-openssl/blob/753a7d07b1eebcc3739905b17b26ecdea5cbe230/openssl/src/x509/store.rs#L96

Apologies to ask that here, but a) Web search didn't yield anything and I am also interested whether the rust-openssl will handle the effect.
  
(To provide some context: I am receiving certs to trust from Google cloud API dynamically and want to add them to a hyper-based client after client creation.)

**Comment by sfackler** [comment]
If you're using the hashed directory-based store, OpenSSL will load certificates on demand, but they're then stored in-memory. So adding new certificates when you receive them will work, but all the certificates you've ever added and were used will be living in memory indefinitely. If the certificates were expiring really frequently that could be a problematic memory leak but it doesn't seem like it'd be that much of a problem in practice.

The other option would probably be to construct a new `SslContext` when your trusted cert list changes and stick that into your client.

**Comment by algermissen** [comment]
Thanks a lot!
