### ISSUE TITLE
Enabling FIPS Mode

### ISSUE THREAD

**Issue by rohitjoshi** [sfackler/rust-openssl#818]
OpenSSL Support the FIPS 140 compliant mode.  How to enable with `rust-openssl`?

OpenSSL has `FIPS_mode_set()` function to enable/disable fips mode and `FIPS_mode()` to check the current status. 

They are declared in: https://github.com/majek/openssl/blob/2f58cda4ce45c88f5c1d284eb155cbc9bcf4705f/crypto/crypto.h#L565

**Comment by sfackler** [comment]
Those aren't exposed right now but it should be reasonable to add them.

**Comment by rohitjoshi** [comment]
👍   Thanks.  I will try this out from the master branch.  I believe an application has to link OpenSSL lib statically to enable fips mode but will let you know.
