### ISSUE TITLE
Enable static linking without specifying link dirs

### ISSUE THREAD

**Issue by drahnr** [sfackler/rust-openssl#825]
Use `.statik(std::env::var("OPENSSL_STATIC").is_ok())` in `fn try_pkg_config()` which would remove the need to specify the `_INCLUDE_DIR` and `_LIB_DIR` for the case like fedora where the statically linked binaries are provided in the standard locations beside the dynamically linked.

**Comment by sfackler** [comment]
pkg-config-rs already looks at that environment variable. You're probably running into https://github.com/alexcrichton/pkg-config-rs/pull/37

**Comment by drahnr** [comment]
Just for reference, there is this rust lang forum topic: https://users.rust-lang.org/t/how-to-link-openssl-statically/14912/2 and ticket https://github.com/alexcrichton/pkg-config-rs/issues/54 for `pkg-config-rs`
