### ISSUE TITLE
Archlinux: certificate verify failed (tls_process_server_certificate)

### ISSUE THREAD

**Issue by mabbamOG** [sfackler/rust-openssl#829]
Hello,
I have an app querying https://translate.google.com written using the reqwest library, which panics when executing a  `reqwest::RequestBuilder::send().unwrap()` **ONLY** when the program is build with static openssl and _not_ run using cargo (which sets env flags).
The program is built with:
```
env OPENSSL_STATIC=yes OPENSSL_INCLUDE_DIR=/usr/local/include OPENSSL_LIB_DIR=/usr/local/lib/ cargo build --release
```
The issue is the following:
```
thread 'main' panicked at 'ERROR: connection fail: Error { kind: Io(Error { repr: Custom(Custom { kind: Other, error: Ssl(ErrorStack([Error { code: 337047686, library: "SSL routines", function: "tls_process_server_certificate", reason: "certificate verify failed", file: "ssl/statem/statem_clnt.c", line: 1230 }])) }) }), url: Some("https://translate.google.com/[redacted]") }', /checkout/src/libcore/result.rs:906:4
```
and it can be fixed by setting the environmnet variable `SSL_CERT_FILE=/etc/ssl/cert.pem`when running the program on my machine.
I have a feeling this is an archlinux-only path and is not included in the default searched paths, how can this be fixed so I can freely distribute the binary without any shell script or additional cacert file?

**Comment by sfackler** [comment]
OpenSSL has a special directory which it uses to find trusted certificates by default. This can be customized at build time, and of course every distro has its own strong opinion on where that directory should be that differs from everyone else.

The standard way to work around this when statically linking to OpenSSL is to use the [openssl-probe](https://crates.io/crates/openssl-probe) crate which searches around all of the common locations. This is what Cargo itself uses, for example.

**Comment by mabbamOG** [comment]
Ah thanks! that really seems to solve the issue.
