### ISSUE TITLE
RSA_PKCS1_OAEP_PADDING with sha256

### ISSUE THREAD

**Issue by gaetanww** [sfackler/rust-openssl#848]
In the spec of PKCS1 the defined as function is sha1. OpenSSL lets us use sha256 using the EVP_PKEY API:  see [here](https://stackoverflow.com/questions/17784022/how-to-encrypt-data-using-rsa-with-sha-256-as-hash-function-and-mgf1-as-mask-ge) and [here](https://groups.google.com/forum/#!topic/mailing.openssl.dev/tBLpITGSyy8).
Would there be an easy way to access that part of the API? I noticed some of the macro are not implemented but I could modify it without too much pain, but it doesn't really seemeven worth it, since EVP_PKEY_encrypt is not implemented either.

**Comment by sfackler** [comment]
It should be doable to add bindings to those functions.

**Comment by sfackler** [comment]
These are exposed in the PkeyCtx type.

**Comment by cn-kali-team** [comment]
Hello, I encountered the same problem in using OpenSSL. Can you teach me how to implement it?
- This is my Python code
```python
from Cryptodome.Cipher import AES
from Cryptodome.Hash import SHA256
from base64 import b64encode
from Crypto import Random
from Crypto.PublicKey import RSA
from Crypto.Cipher import PKCS1_OAEP
# ...
private_key = RSA.importKey(self.private_key)
cipher = PKCS1_OAEP.new(private_key, hashAlgo=SHA256)
aes_plain_key = cipher.decrypt(base64.b64decode(aes_key))
```

**Comment by Xynnn007** [comment]
Same question as @cn-kali-team . Is there a guide for this?
