### ISSUE TITLE
Panicking when conecting with a SSL server

### ISSUE THREAD

**Issue by PhdTrollSlayer** [sfackler/rust-openssl#851]
Runtime error:
`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Failure(MidHandshakeSslStream { stream: SslStream { stream: TcpStream { addr: V4(127.0.0.1:39962), peer: V4(127.0.0.1:6666), fd: 3 }, ssl: Ssl { state: "SSLv3/TLS write client hello", verify_result: X509VerifyResult { code: 0, error: "ok" } } }, error: Error { code: ErrorCode(5), cause: None } })', /checkout/src/libcore/result.rs:916:5`

Client code: 

pub fn connect() {
    let connector = SslConnector::builder(SslMethod::tls()).unwrap().build();

    let stream = TcpStream::connect("127.0.0.1:6666").unwrap();

    let mut finalstream = connector.connect("127.0.0.1:6666", stream).unwrap(); //This line is having problems
}

Server code:
pub fn start() {
    let listener = TcpListener::bind("127.0.0.1:6666").unwrap();
    let mut acceptor = SslAcceptor::mozilla_intermediate(SslMethod::tls())
        .unwrap()
        .build();

    for stream in listener.incoming() {
        match stream {
            Ok(stream) => handle_client(stream),
            Err(e) => { /* connection failed */ }
        }
    }
}

**Comment by PhdTrollSlayer** [comment]
Backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at /checkout/src/libstd/sys_common/backtrace.rs:68
             at /checkout/src/libstd/sys_common/backtrace.rs:57
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:23
  10: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:782
  11: crypto_me::ssl::ssl_client::connect
             at src/ssl/ssl_client.rs:10
  12: crypto_me::main
             at src/main.rs:38
  13: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  14: std::panicking::try::do_call
             at /checkout/src/libstd/rt.rs:59
             at /checkout/src/libstd/panicking.rs:480
  15: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:101
  16: std::rt::lang_start_internal
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:365
             at /checkout/src/libstd/rt.rs:58
  17: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  18: main
  19: __libc_start_main
  20: _start

**Comment by sfackler** [comment]
Where are you using the acceptor on the server side?

**Comment by PhdTrollSlayer** [comment]
> Where are you using the acceptor on the server side?
I have just this handler in the server file if thats what you are asking:

fn handle_client(mut stream: TcpStream) {
    let mut buffer = [0; 4096];

    stream.read(&mut buffer).unwrap();

    println!("Request {}", String::from_utf8_lossy(&buffer[..]));
}

Also, if it makes any difference, the client panics as soon as it connects. The handler prints on screen what apeers to be encrypted data with the IP and port number by the end

**Comment by sfackler** [comment]
I am asking where you are using this value:

```rust
let mut acceptor = SslAcceptor::mozilla_intermediate(SslMethod::tls())
    .unwrap()
    .build();
```

**Comment by PhdTrollSlayer** [comment]
Ohh ok. I see what you are saying I modified the listner.incoming() loop to this:
`
for stream in listener.incoming() {
match stream {
            Ok(stream) => {
                let acceptor = acceptor.clone();
                thread::spawn(move || {
                    let stream = acceptor.accept(stream).unwrap();
                    handle_client(stream);
                });
            }
            Err(e) => { /* connection failed */ }
        }
    }
`

But still, now both the client and server panics
Server panic message:
`thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failure(MidHandshakeSslStream { stream: SslStream { stream: TcpStream { addr: V4(127.0.0.1:6666), peer: V4(127.0.0.1:41158), fd: 4 }, ssl: Ssl { state: "error", verify_result: X509VerifyResult { code: 0, error: "ok" } } }, error: Error { code: ErrorCode(1), cause: Some(Ssl(ErrorStack([Error { code: 337092801, library: "SSL routines", function: "tls_post_process_client_hello", reason: "no shared cipher", file: "ssl/statem/statem_srvr.c", line: 1404 }]))) } })', /checkout/src/libcore/result.rs:916:5
`

**Comment by sfackler** [comment]
Are you setting up the certificate and private key, as shown in the documentation here? https://docs.rs/openssl/0.10.4/openssl/ssl/index.html#examples

**Comment by PhdTrollSlayer** [comment]
Like this (updated server):

pub fn start() {
    let rsa = Rsa::generate(2048).unwrap();
    let pkey = PKey::from_rsa(rsa).unwrap();

    let mut name = X509Name::builder().unwrap();
    name.append_entry_by_nid(Nid::COMMONNAME, "127.0.0.1")
        .unwrap();
    let name = name.build();

    let mut builder = X509::builder().unwrap();
    builder.set_version(2).unwrap();
    builder.set_subject_name(&name).unwrap();
    builder.set_issuer_name(&name).unwrap();
    builder.set_pubkey(&pkey).unwrap();
    builder.sign(&pkey, MessageDigest::sha256()).unwrap();

    let certificate: X509 = builder.build();

    let mut acceptor = SslAcceptor::mozilla_intermediate(SslMethod::tls()).unwrap();
    acceptor.set_private_key(&pkey).unwrap();
    acceptor.set_certificate(&certificate).unwrap();
    acceptor.check_private_key().unwrap();
    let acceptor = Arc::new(acceptor.build());

    let listener = TcpListener::bind("127.0.0.1:6666").unwrap();

    for stream in listener.incoming() {
        match stream {
            Ok(stream) => {
                let acceptor = acceptor.clone();
                thread::spawn(move || {
                    let stream = acceptor.accept(stream).unwrap();
                    handle_client(stream);
                });
            }
            Err(e) => { /* connection failed */ }
        }
    }
}

I assume that the certificate and priv key are used only on the server side

**Comment by juanibiapina** [comment]
I have similar code. I patched it together from two examples:

https://docs.rs/openssl/0.10.4/openssl/x509/index.html (generate cert)
https://docs.rs/openssl/0.10.4/openssl/ssl/index.html (use it, just like above)

But I get the error `unsupported certificate:s3_pkt.c:1500:SSL alert number 43`. I'm probably missing something as well, but I find the fact that the examples don't work together seamlessly slightly misleading.

**Comment by sfackler** [comment]
X509 certificates are complex - I would not recommend trying to create one yourself. The `openssl` CLI tool can make one for you: `openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365`.

**Comment by PhdTrollSlayer** [comment]
Making the certificate in the CLI tool and setting it up just like in the examples returns...

Server:
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Failure(MidHandshakeSslStream { stream: SslStream { stream: TcpStream { addr: V4(127.0.0.1:6666), peer: V4(127.0.0.1:55212), fd: 4 }, ssl: Ssl { state: "SSLv3/TLS write server done", verify_result: X509VerifyResult { code: 0, error: "ok" } } }, error: Error { code: ErrorCode(1), cause: Some(Ssl(ErrorStack([Error { code: 336151576, library: "SSL routines", function: "ssl3_read_bytes", reason: "tlsv1 alert unknown ca", file: "ssl/record/rec_layer_s3.c", line: 1399, data: "SSL alert number 48" }]))) } })', /checkout/src/libcore/result.rs:916:5

Client:
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Failure(MidHandshakeSslStream { stream: SslStream { stream: TcpStream { addr: V4(127.0.0.1:55212), peer: V4(127.0.0.1:6666), fd: 3 }, ssl: Ssl { state: "error", verify_result: X509VerifyResult { code: 18, error: "self signed certificate" } } }, error: Error { code: ErrorCode(1), cause: Some(Ssl(ErrorStack([Error { code: 337047686, library: "SSL routines", function: "tls_process_server_certificate", reason: "certificate verify failed", file: "ssl/statem/statem_clnt.c", line: 1230 }]))) } })', /checkout/src/libcore/result.rs:916:5

**Comment by sfackler** [comment]
Have you configured the connector to trust your server's certificate?

**Comment by PhdTrollSlayer** [comment]
No, is there a code example in the docs?

**Comment by sfackler** [comment]
https://docs.rs/openssl/0.10.4/openssl/ssl/struct.SslConnectorBuilder.html#method.set_ca_file

**Comment by PhdTrollSlayer** [comment]
Ok, I set it. Now the client fails to verify the certificate:
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Failure(MidHandshakeSslStream { stream: SslStream { stream: TcpStream { addr: V4(127.0.0.1:56878), peer: V4(127.0.0.1:6666), fd: 3 }, ssl: Ssl { state: "error", verify_result: X509VerifyResult { code: 62, error: "Hostname mismatch" } } }, error: Error { code: ErrorCode(1), cause: Some(Ssl(ErrorStack([Error { code: 337047686, library: "SSL routines", function: "tls_process_server_certificate", reason: "certificate verify failed", file: "ssl/statem/statem_clnt.c", line: 1230 }]))) } })', /checkout/src/libcore/result.rs:916:5

I found that the conector.set_verify(SslVerifyMode::NONE) makes a conection, does the data still get encrypted even if there is no verification of the certificate?

**Comment by sfackler** [comment]
The hostname you're passing to the connector needs to match what's on the certificate.

**Comment by PhdTrollSlayer** [comment]
I'm having brain farts here. I assume that the hostname is `127.0.0.1` in this case. The conector has `let mut conector = connector.connect("127.0.0.1", stream).unwrap();`
Where does the hostname go in the certificate?

**Comment by juanibiapina** [comment]
@sfackler If you wouldn't recommend creating one, the example is misleading because it makes it seem like it should work.

**Comment by juanibiapina** [comment]
@sfackler I'm still investigating, but it seems to produce a corrupt certificate.

**Comment by PhdTrollSlayer** [comment]
I'm slowly becoming brain dead. Last dump:
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Failure(MidHandshakeSslStream { stream: SslStream { stream: TcpStream { addr: V4(127.0.0.1:51302), peer: V4(127.0.0.1:6666), fd: 3 }, ssl: Ssl { state: "error", verify_result: X509VerifyResult { code: 64, error: "IP address mismatch" } } }, error: Error { code: ErrorCode(1), cause: Some(Ssl(ErrorStack([Error { code: 337047686, library: "SSL routines", function: "tls_process_server_certificate", reason: "certificate verify failed", file: "ssl/statem/statem_clnt.c", line: 1230 }]))) } })', /checkout/src/libcore/result.rs:916:5

I swear to god that I can't find anything about `code: 64, error: "IP address mismatch" `
`openssl verify cert.pem` returns ok

**Comment by sfackler** [comment]
The certificate verification doesn't think the IP address you provided matches what's in the certificate.

**Comment by aep** [comment]
@juanibiapina ever got it to produce a valid cert?  ASN1_get_object:too long for me too

**Comment by juanibiapina** [comment]
No, I gave up.

**Comment by aep** [comment]
@juanibiapina this worked for me https://github.com/sfackler/rust-openssl/blob/d3fff74ae8ab092a77050ba210b942e86c3bd9ff/openssl/examples/mk_certs.rs#L35

**Comment by juanibiapina** [comment]
I'll keep it in mind, but I don't think I'll need to take this path any longer.

**Comment by haslersn** [comment]
I had the same error as in the original post, using LibreSSL. I solved it by using OpenSSL instead of LibreSSL.
