### ISSUE TITLE
Are the version-specific features worth it?

### ISSUE THREAD

**Issue by sfackler** [sfackler/rust-openssl#852]
We currently require you to opt-in to APIs that aren't available on all supported OpenSSL versions by enabling a special Cargo feature. This is designed to make people realize what OpenSSL versions their code will work with. However, it's not really airtight. If a feature was disabled at compile time in OpenSSL, we simply remove the APIs (e.g. `EcGroupRef::components_gf2m`). LibreSSL is also a bit weird here, since it sort of looks like 1.0.1, but is increasingly backporting a bunch of APIs.

It seems like it may be the case that the feature stuff just isn't worth it. We can make the features no-ops in a backwards compatible way, fortunately.

**Comment by sfackler** [comment]
cc @alexcrichton I think you designed the setup when adding 1.1.0 support?

**Comment by alexcrichton** [comment]
Yeah the initial thinking was that there were a lot of parallels here to platform support, but in reality this may not be too feasible. 

I wonder if in OpenSSL's case it may be best to unconditionally provide all APIs and return a recognizable error when they're not supported and/or not compiled in? That way everything should always compile and the intrepid can do detection at runtime if necessary.

**Comment by alexcrichton** [comment]
Oh hm I was thinking the functions would still be available and would simply return a runtime error rather than a compile-time error. To me at least I've found that tends to be more flexible?

**Comment by sfackler** [comment]
Oh right, trying to generate a compile_error on use doesn't actually make any sense...

**Comment by Ralith** [comment]
For my purposes I absolutely require 1.1.1-only features, and would much prefer a helpful compile error over a runtime explosion.

**Comment by sfackler** [comment]
#868 is related - X509_V_ERR_INVALID_CALL was added in 1.0.2h, but increasing feature granularity to every patch release seems like a bummer.
