### ISSUE TITLE
OpenSSL library not found

### ISSUE THREAD

**Issue by SLASHLogin** [sfackler/rust-openssl#855]
```
error:

 failed to run custom build command for `openssl-sys v0.9.24`
process didn't exit successfully: `C:\Users\przem\Desktop\Pliki\rust\clouder\target\debug\build\openssl-sys-37a83c20c1c3f413\build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_MSVC_OPENSSL_LIB_DIR
cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_MSVC_OPENSSL_INCLUDE_DIR
cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_MSVC_OPENSSL_DIR
cargo:rerun-if-env-changed=OPENSSL_DIR
note: vcpkg did not find openssl as libcrypto and libssl : VcpkgNotFound("No vcpkg.user.targets found. Set the VCPKG_ROOT environment variable or run \'vcpkg integrate install\'")
note: vcpkg did not find openssl as ssleay32 and libeay32: VcpkgNotFound("No vcpkg.user.targets found. Set the VCPKG_ROOT environment variable or run \'vcpkg integrate install\'")

--- stderr
thread 'main' panicked at '

Could not find directory of OpenSSL installation, and this `-sys` crate cannot
proceed without this knowledge. If OpenSSL is installed and this crate had
trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
compilation process.

If you're in a situation where you think the directory *should* be found
automatically, please open a bug at https://github.com/sfackler/rust-openssl
and include information about your system as well as this message.

    $HOST = x86_64-pc-windows-msvc
    $TARGET = x86_64-pc-windows-msvc
    openssl-sys = 0.9.24


It looks like you're compiling for MSVC but we couldn't detect an OpenSSL
installation. If there isn't one installed then you can try the rust-openssl
README for more information about how to download precompiled binaries of
OpenSSL:

    https://github.com/sfackler/rust-openssl#windows

', C:\Users\przem\.cargo\registry\src\github.com-1ecc6299db9ec823\openssl-sys-0.9.24\build.rs:210:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
```
The environment:
```
OPENSSL_DIR = C:\OpenSSL-Win64
OPENSSL_CONF = C:\Program Files (x86)\OpenSSL-Win32\bin\openssl.cfg
```

**Comment by sfackler** [comment]
What is inside of `C:\OpenSSL-Win64\include`?

**Comment by SLASHLogin** [comment]
C:\OpenSSL-Win64\include\openssl - header files of c lang

**Comment by sfackler** [comment]
That message is only printed if OPENSSL_DIR isn't set - are you sure it's configured properly to be visible to Cargo and rustc?

**Comment by SLASHLogin** [comment]
It went properly when run with higher permission. Thank you!

**Comment by zodiake** [comment]
# macOS
$ brew install openssl@1.1
 
# Arch Linux
$ sudo pacman -S pkg-config openssl
 
# Debian and Ubuntu
$ sudo apt-get install pkg-config libssl-dev
 
# Fedora
$ sudo dnf install pkg-config openssl-devel

**Comment by steelx** [comment]
@zodiake  thanks :) 
`$ sudo apt-get install pkg-config libssl-dev` worked.

**Comment by yuanmomo** [comment]
@zodiake 

Thanks.

`$ sudo apt-get install pkg-config libssl-dev`  

this worked for me as well.

**Comment by ribrea** [comment]
@zodiake Thanks :)

**Comment by Oskii** [comment]
I can't seem to install libssl-dev - any ideas?

`1 upgraded, 1 newly installed, 0 to remove and 249 not upgraded.
Need to get 2906 kB of archives.
After this operation, 8010 kB of additional disk space will be used.
Err:1 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libssl1.1 amd64 1.1.1f-1ubuntu2.10
  404  Not Found [IP: 91.189.91.38 80]
Err:2 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libssl-dev amd64 1.1.1f-1ubuntu2.10
  404  Not Found [IP: 91.189.91.38 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.10_amd64.deb  404  Not Found [IP: 91.189.91.38 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl-dev_1.1.1f-1ubuntu2.10_amd64.deb  404  Not Found [IP: 91.189.91.38 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?`

**Comment by fengbenming** [comment]
> If anyone is still running into this issue (like I was), I was able to resolve it just by updating/upgrading
> 
> ```
> sudo apt-get update
> sudo apt-get upgrade
> 
> ## attempt to build again
> ```
It is really work, you can upgrade openssl can sovle problems.  Why so many downs ？

**Comment by yourmoonlight** [comment]
> 

not work

**Comment by yourmoonlight** [comment]
> > If anyone is still running into this issue (like I was), I was able to resolve it just by updating/upgrading
> > ```
> > sudo apt-get update
> > sudo apt-get upgrade
> > 
> > ## attempt to build again
> > ```
> 
> It is really work, you can upgrade openssl can sovle problems. Why so many downs ？

cause it it not work

**Comment by Altar12** [comment]
> 

Thanks a lot @zodiake. Worked perfectly after executing the command specified

**Comment by lukasdll** [comment]
> 

Because that solution works only on very specific situations, and the vast majority of the people had a different issue. For that solution to work you should already have the required library installed, but installed so long ago that it became outdated and did not work. The majority of the people having this issue had a fresh OS install and the library was not installed, therefore, update and upgrade did not solve the problem.

**Comment by sai-kalai** [comment]
Thanks!
`sudo apt-get install pkg-config libssl-dev`
worked for me on WSL2 Ubuntu22.4LTS

**Comment by asifm** [comment]
This worked for OpenSUSE-Tumbleweed:

`sudo zypper install libopenssl-devl`

**Comment by autb** [comment]
Thanks!
sudo apt-get install pkg-config libssl-dev
worked for me ! "pkg-config" seems important in my case becasue only "libssl-dev" was not enough.

**Comment by meisbokai** [comment]
```
sudo apt-get install pkg-config libssl-dev
```
Works for Windows 11, WSL2, Ubuntu 22.04
