### ISSUE TITLE
Expose EVP_PKEY_id()

### ISSUE THREAD

**Issue by frehberg** [sfackler/rust-openssl#869]
Right now the rust-interface openssl::pkey::PKey does not expose the type of the underlying key.

The interface of openssl::pkey::PKey should expose the functionality of EVP_PKEY_id()

`EVP_PKEY_id() returns the type field. For example an RSA key will return EVP_PKEY_RSA.`

https://www.openssl.org/docs/man1.1.0/crypto/EVP_PKEY_id.html

**Comment by sfackler** [comment]
This was added recently in #862.

**Comment by frehberg** [comment]
Great that it is in the git already! *smile* When will it be available as release via crates.io?
