### ISSUE TITLE
Static Compilation Doesn't Work According to Docs

### ISSUE THREAD

**Issue by naftulikay** [sfackler/rust-openssl#877]
On the README it says the following relating to static compiling OpenSSL:

> `OPENSSL_STATIC` - If specified, OpenSSL libraries will be statically rather than dynamically linked.

Passing this environment variable has no effect if `OPENSSL_LIB_DIR` and `OPENSSL_INCLUDE_DIR` are not specified.: https://github.com/naftulikay/rust-openssl-static-example/pull/

**Comment by sfackler** [comment]
pkg-config also looks at OPENSSL_STATIC, but you may be running into alexcrichton/pkg-config-rs#37
