### ISSUE TITLE
how to convert base64 “PEM” format rsa  privte_key to PKCS#8 form?

### ISSUE THREAD

**Issue by zhangsoledad** [sfackler/rust-openssl#880]
Often, keys generated for use in OpenSSL-based software are stored in the Base64 “PEM” format without the PKCS#8 wrapper. Such keys can be converted to binary PKCS#8 form using the OpenSSL command line tool like this:
```sh
openssl pkcs8 -topk8 -nocrypt -outform der \
   -in rsa-2048-private-key.pem > rsa-2048-private-key.pk8
```
How to achieve it through `rust-openssl` in rust?

**Comment by sfackler** [comment]
You can read the key in with https://docs.rs/openssl/0.10.5/openssl/pkey/struct.PKey.html#method.private_key_from_pem and write it out with https://docs.rs/openssl/0.10.5/openssl/pkey/struct.PKey.html#method.private_key_to_pem_pkcs8.

**Comment by zhangsoledad** [comment]
@sfackler  3Q.  
I am not familiar with `openssl`, I have tried `private_key_to_pem_pkcs8`, I get a `PEM` format PKCS#8 form i guess，it not equel to the output of `rsa-2048-private-key.pk8`, How should I convert it to der form?

**Comment by sfackler** [comment]
That isn't currently supported - we'd need to bind https://www.openssl.org/docs/man1.0.2/crypto/i2d_PKCS8PrivateKey_bio.html

**Comment by zhangsoledad** [comment]
@sfackler got it, thx.
