### ISSUE TITLE
Could not find directory of OpenSSL installation

### ISSUE THREAD

**Issue by WandyLau** [sfackler/rust-openssl#882]
I try to cross-compilation a rust program from x86 OS.
And the openssl is one dependency. And I install it for sure.
when I try to build it, error raise: 

**Could not find directory of OpenSSL installation, and this `-sys` crate cannot
proceed without this knowledge. If OpenSSL is installed and this crate had
trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
compilation process.**

The OS info is below:   
 **$HOST = x86_64-unknown-linux-gnu
     $TARGET = s390x-unknown-linux-gnu
     openssl-sys = 0.9.27**

**Comment by sfackler** [comment]
Do you have pkg-config and OpenSSL's headers installed? https://github.com/sfackler/rust-openssl#linux

**Comment by sfackler** [comment]
You're cross compiling, so you'll need to compile a version of OpenSSL for s390x and set `OPENSSL_DIR` to point at it.

**Comment by WandyLau** [comment]
And other dependencies, I will need cross compile them all for the s390x?

**Comment by sfackler** [comment]
Yep

**Comment by WandyLau** [comment]
And manually set the environment variables?

**Comment by sfackler** [comment]
You'll need to look at how the other crates linking to those C libraries are configured.

**Comment by WandyLau** [comment]
OK. Thanks for your reply.
