### ISSUE TITLE
get_serial_number is missing ?

### ISSUE THREAD

**Issue by fdubois1** [sfackler/rust-openssl#886]
I'm creating a certificate with a serial number. When I read back my certificate to build my X509 object, I can't get back my serial number.  Is it something missing ?  Or how can I get the certificate serial number ?  I would need it to remove my certificate from the store with certutil tool from windows.  Thanks

**Comment by sfackler** [comment]
We just need to expose https://www.openssl.org/docs/man1.1.0/crypto/X509_get_serialNumber.html. Should be pretty straightforward to do!
