### ISSUE TITLE
Create public RSA key from private key

### ISSUE THREAD

**Issue by maufl** [sfackler/rust-openssl#914]
Maybe I'm missing something obvious in the documentation, but is there an easy way to get the corresponding public key for a given private key?

**Comment by sfackler** [comment]
An `Rsa<Private>` is a superset of an `Rsa<Public>` - it can be used in places that need a public key. If you explicitly want to make an `Rsa<Public>` value from an `Rsa<Private>` value, the most straightforward way would probably be to create it from the public components.

**Comment by maufl** [comment]
Ok, I've got it working now. I overlooked the `HasPublic` and `HasPrivate` traits and how they work. Thanks.
