### ISSUE TITLE
Unable to cross compile to i686-unknown-linux-gnu

### ISSUE THREAD

**Issue by johnthagen** [sfackler/rust-openssl#931]
On a fresh Ubuntu 18.04 machine I installed:

```
$ sudo apt install gcc gcc-multilib libssl-dev libssl-dev:i386 pkg-config
```

```
$ rustup target add i686-unknown-linux-gnu
```

```
cargo build --target i686-unknown-linux-gnu --release
   Compiling openssl-sys v0.9.31
error: failed to run custom build command for `openssl-sys v0.9.31`
process didn't exit successfully: `/home/user/GitHub/tls/target/release/build/openssl-sys-56b2f59992938bdf/build-script-main` (exit code: 101)
--- stdout
cargo:rerun-if-env-changed=I686_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR
cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
cargo:rerun-if-env-changed=I686_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR
cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
cargo:rerun-if-env-changed=I686_UNKNOWN_LINUX_GNU_OPENSSL_DIR
cargo:rerun-if-env-changed=OPENSSL_DIR
run pkg_config fail: "Cross compilation detected. Use PKG_CONFIG_ALLOW_CROSS=1 to override"

--- stderr
thread 'main' panicked at '

Could not find directory of OpenSSL installation, and this `-sys` crate cannot
proceed without this knowledge. If OpenSSL is installed and this crate had
trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
compilation process.

Make sure you also have the development packages of openssl installed.
For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.

If you're in a situation where you think the directory *should* be found
automatically, please open a bug at https://github.com/sfackler/rust-openssl
and include information about your system as well as this message.

    $HOST = x86_64-unknown-linux-gnu
    $TARGET = i686-unknown-linux-gnu
    openssl-sys = 0.9.31

', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.31/build/main.rs:232:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

I get the same error on `rustc 1.28.0-nightly (29ffe51e3 2018-05-23)` and `rustc 1.26.0 (a77568041 2018-05-07)`

I thought I had gotten this to work previously, but can't reproduce it on the latest Ubuntu, `rustc`, `openssl-sys` combination.

I thought that it was possible to use `libssl-dev:i386` for this. Was I mistaken?

**Comment by sfackler** [comment]
It is possible, but you'll need to point openssl-sys to the right location via environment variables: https://github.com/sfackler/rust-openssl#manual-configuration

**Comment by johnthagen** [comment]
I ended up just creating a 32-bit Linux host environment instead as it didn't seem like `libssl-dev:i386` laid things out quite as `openssl-sys` was expecting.

**Comment by juicermv** [comment]
This issue shouldn't have been closed imo. It still very much exists to this day and should not be left for the poor victim to figure out by possibly installing an entirely different operating system.

**Comment by Skepfyr** [comment]
This issue was closed by the initial raiser, it's definitely possible to cross compile to i686 Linux.. If anyone else attempts to do this and gets stuck they can raise another issue or comment on this one.

**Comment by juicermv** [comment]
> they can raise another issue or comment on this one.

That's what I did...

**Comment by Skepfyr** [comment]
Sorry I thought you were specking hypothetically. As far as I'm aware it *is* possible to cross compile to i686-unknown-linux-gnu, cross-compiling is just hard and we can't document how to do it for every pair of systems so you're expected to try to work it out. If you're having specific problems then open an issue and we may be able to help.

**Comment by juicermv** [comment]
I'm having the exact same issue documented here lol. That's why I made the comment in the first place.

**Comment by Skepfyr** [comment]
As sfackler said above you either need to configure pkg_config correctly so that it can find the i686 OpenSSL, or you need to specify the OpenSSL environment variables directly:
https://docs.rs/pkg-config/latest/pkg_config/#cross-compilation
https://docs.rs/openssl/latest/openssl/#manual

If you want help you're going to have to provide more detail as to what you've tried, what's not working, why you expect it to work, etc.
