### ISSUE TITLE
[Help] No examples for proper AES encryption

### ISSUE THREAD

**Issue by Skarlso** [sfackler/rust-openssl#956]
Hi. 

So I'm struggling to properly implement AES encryption. I found some pieces of code here and there, but I faced all sort of problems with cipher length and incorrect encryption and decryptions.

I tried the code in the test which presumably works, but also has a lot of dummy data and hardcoded length which I'm not sure where to derive from.

So what I'm basically asking is how to use this library for proper cryptography or at least some guidelines as to where to start.

For example given this code:

```rust
extern crate openssl;
extern crate rustc_serialize;
use openssl::symm::{Cipher, Crypter, Mode};
use rustc_serialize::hex::ToHex;

fn main() {
    let plaintext = "AAAAAAAAAAAAAAAA".as_bytes();
    let key = "BBBBBBBBBBBBBBBB".as_bytes();

    let encrypter = Crypter::new(Cipher::aes_128_ecb(), Mode::Encrypt, key, None);
    let mut ciphertext = vec![0u8; 32];
    let cipherlen = encrypter.unwrap().update(plaintext, ciphertext.as_mut_slice()).unwrap();

    let decrypter = Crypter::new(Cipher::aes_128_ecb(), Mode::Decrypt, key, None);
    let mut decrypted = vec![0u8; 32];
    decrypter.unwrap().update(&ciphertext[..cipherlen], decrypted.as_mut_slice()).unwrap();

    println!("{}", plaintext.to_hex());
    println!("{}", ciphertext.as_slice().to_hex());
    println!("{}", decrypted.as_slice().to_hex());

    println!("{}", plaintext.len());
    println!("{}", ciphertext.len());
    println!("{}", decrypted.len());
}
```

Which was kindly put into a ticket 2 years ago by someone... Obviously, I want aes_256 by now. None is the IV which I don't even bother with for now, but given this piece of code if you happen to change either plaintext even one letter, it fails with: 

```bash
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorStack([Error { code: 101163138, library: "digital envelope routines", function: "EVP_CIPHER_CTX_set_key_length", reason: "invalid key length", file: "crypto/evp/evp_enc.c", line: 564 }])', libcore/result.rs:945:5
```

Which I'm guessing is due to the fact `ciphertext` is in fixed length I think. But I'm unsure. Changing it in any ways didn't help though so it must be something else.

So what's the problem here? Obviously the key and plaintext size shouldn't be the same. Help?

**Comment by sfackler** [comment]
Are you trying to implement AES as a learning experience or to use in "real" things? If it's not just to learn, I would highly suggest not touching AES directly, but rather using something like [fernet](https://crates.io/crates/fernet) or [sodiumoxide](https://crates.io/crates/sodiumoxide) or [ring](https://crates.io/crates/ring) that provide a higher level API and help avoid the many pitfalls that exist (they do not use AES ECB for example!).

There are examples on the various methods in the symm module, e.g. https://docs.rs/openssl/0.10.10/openssl/symm/fn.decrypt.html.

**Comment by Skarlso** [comment]
@sfackler Hi! First off, thank you for the answer!

Second, I'm trying to use it for a pet project, so nothing industrial. But essentially I would like to provide proper encryption for the end-user.

I was looking at Ring, but frankly, I find it clanky. I was looking at sodium which looks promising, but... I actually would rather use OpenSSL which is tried and tested for a long time now.

I'm trying to port one of my C++ projects which is using openssl and aes. I thought I knew what I'm doing until I was trying to do it in Rust. :) Now this is obviously me, trying to learn things here. So I might be trying too much, but I honestly didn't think that it would be this hard. 

Oh wow that example is actually awesome. 😨I didn't see that earlier!! It's just what I need. 

So, if I understand this correctly... I'm going to pad my password to the length of `cipher`-s key_length, right? Those there happened to be a convenient method for that by any chance? I was using something like, 

```rust
     while password.len() < cipher.key_len() {
         password.push(b'0');
     }
```

earlier. Which is a boring 0 pad, but good enough. Also, I'm guessing it's the same for encrypt as well? And those two are `as_byte` if they happened to be `&str`s? 

Sorry, to ask so much, I probably shouldn't start learning Rust by porting a crypto heavy c++ app. :D But where's the challenge in anything else, right? :)

Thank you very much!

**Comment by sfackler** [comment]
libsodium is an widely used, well regarded cryptography library specifically structured to be hard to misuse. Fernet uses openssl internally as an alternate option.

You should use a key derivation function to derive a key from a password.

**Comment by Skarlso** [comment]
@sfackler Right! And iv can be stored next to the data. I'll look for one. :)

Thanks! I made it work finally. :) Yeah I know libsodium. But I found this one to be more readable. :) 👍

**Comment by kjkellytexas** [comment]
@Skarlso , I am trying to do the same thing and running into a similar problem.  While it's dated, your last post on 7/3/18 indicates that you solved it.  Are you willing to share that here?

**Comment by Skarlso** [comment]
Sure. On my user there is repo called totp. I solved it in there.

**Comment by Skarlso** [comment]
Here 

https://github.com/Skarlso/totp/blob/master/src/encrypt.rs#L34
