### ISSUE TITLE
could SslCipher::name() return a &'static str

### ISSUE THREAD

**Issue by Geal** [sfackler/rust-openssl#961]
hello,

I see that `SslRef::version_str()` returns a `&'static str` for the protocol version string: https://docs.rs/openssl/0.10.10/x86_64-unknown-linux-gnu/openssl/ssl/struct.SslRef.html#method.version_str

And I was wondering why `SslCipher::name()` is not doing that:
https://docs.rs/openssl/0.10.10/x86_64-unknown-linux-gnu/openssl/ssl/struct.SslCipherRef.html#method.name

it would make my life slightly easier to get the cipher name as a `&'static str`, but I'm not too familiar with openssl's API and I know it's a long shot, so it's not a very important request :)

**Comment by sfackler** [comment]
I think this change should be valid - SSL_CIPHERs aren't dynamically created or destroyed.

**Comment by Geal** [comment]
Awesome, thanks !
