### ISSUE TITLE
Methods for DTLS SRTP

### ISSUE THREAD

**Issue by eun-ice** [sfackler/rust-openssl#966]
hello, thank you for your wonderful lib.

However, I use OpenSSL for a DTLS SRTP handshake. To do that, I had to add some bindings for these methods: https://www.openssl.org/docs/man1.1.0/crypto/SSL_set_tlsext_use_srtp.html

I have done that quick&dirty in: https://github.com/eun-ice/rust-openssl/commit/de84f061e48830662378653f4cf27f69d0098417

This is by no means tested against all OpenSSL/LibreSSL versions. Also the STACK_OF(SRTP_PROTECTION_PROFILE) seems to be implemented in a wrong way, there is no SRTP_PROTECTION_PROFILE_free method, since it seems to be memory managed by OpenSSL.

How would I go about and test this against all OpenSSL/LibreSSL versions? How to correctly implement STACK_OF(SRTP_PROTECTION_PROFILE)? How to build test cases?

I would love to contribute, please give me some pointers on how to proceed.

**Comment by sfackler** [comment]
This is something of an interesting case! All of the SRTP_PROTECTION_PROFILE instances have static lifetimes so there isn't any functions to create or destroy them. I think the way to handle it is to manually implement ForeignType/ForeignTypeRef which'll mean we don't actually need to include a drop impl at all.

**Comment by sfackler** [comment]
As far as testing goes, I think all we'd need is a simple little test that starts up a client and server, negotiates an SRTP protocol, and checks to make sure both sides agree on that protocol. It'll probably look similar to the ALPN tests.

**Comment by eun-ice** [comment]
I have added a dummy SRTP_PROTECTION_PROFILE_free method, not beautiful but should work.

Here I tried to write a test-case https://github.com/eun-ice/rust-openssl/commit/1b4228960fb3f0ab2d76ff05c3257dac2f593ca4

Curiously openssl s_erver -dtls terminates without an open shell, so I had to keep stdin open using a fake thread.

Please give me a hint if I'm on the right track and what needs to be done to get this accepted upstream, besides cleaning up the messed up whitespaces and comments.

Specifically:
- Is using the fake  SRTP_PROTECTION_PROFILE_free ok for now?
- Can I keep the fake stdin thread for dtls server?
- Do you agree with the way I mapped SRTP_PROTECTION_PROFILE to SrtpProfile and SrtpProfileId?

**Comment by sfackler** [comment]
Could you open a PR? It'll be easier to review there.

**Comment by eun-ice** [comment]
Here it is:  #973

**Comment by eun-ice** [comment]
I created a new pull request  https://github.com/sfackler/rust-openssl/pull/975 to have everything in one commit and rebase. (sorry for my GIT illiteracy)

Now all checks should be green, but I had to disable the testcase for SRTP with libressl 2.7.2. The test case just hangs after exchanging a few bytes.

**Comment by eun-ice** [comment]
Thank you for merging pull request #975 , issue closed.
