### ISSUE TITLE
Build issue on OSX

### ISSUE THREAD

**Issue by tpitale** [sfackler/rust-openssl#97]
I've added Iron as a dependency on a brand new project, using rust 0.12-nightly installed with homebrew.

When I `cargo build` it beings updating git repos/dependencies. It fails when it gets to this repo.

Any help would be appreciated, thanks!

```
    Updating git repository `https://github.com/sfackler/rust-openssl.git`
Unable to update https://github.com/sfackler/rust-openssl.git

Caused by:
  ../../../.cargo/git/checkouts/rust-openssl-4145800ab3594a0f/master/Cargo.toml is not a valid manifest

Feature `tlsv1_1` includes `openssl-sys/tlsv1_1` which is neither a dependency nor another feature
```

**Comment by hugoduncan** [comment]
I just hit this trying to enable the `tlsv1_1` feature:

```
Undefined symbols for architecture x86_64:
  "_TLSv1_1_method", referenced from:
      ssl::SslMethod::to_raw::h26539f130132e2b9xMc in libopenssl-542895e66fca368b.rlib(openssl-542895e66fca368b.o)
```

Force linking the brew openssl package fixed the issue.

**Comment by sfackler** [comment]
@hugoduncan The copy of openssl installed by default on OSX is too old to have tlsv1.1 support. That's why support for it is behind a feature.
