### ISSUE TITLE
getting regular "BUG: sni callback missing" errors

### ISSUE THREAD

**Issue by Geal** [sfackler/rust-openssl#979]
I encounter this error message regularly, it is apparently coming from https://github.com/sfackler/rust-openssl/blob/19430b114ea1a39e927c169186afdc25e487b62a/openssl/src/ssl/callbacks.rs#L164
is there anything I should look for to fix my code? Or information you would need to debug it?

**Comment by sfackler** [comment]
Hmm, that's very strange. Does it seem to happen randomly, or do you end up with an SslContext/SslAcceptor that always hits the error? Are you doing anything particularly strange with your SslContext/SslAcceptor? A small bit of code that can reproduce it would be helpful.

**Comment by sfackler** [comment]
I did notice that we aren't checking if SSL_CTX_set_ex_data is returning an error which we should fix, but that'll only happen on a malloc failure from what I can see.
