### ISSUE TITLE
Add support for openssl-1.1.1

### ISSUE THREAD

**Issue by luben** [sfackler/rust-openssl#984]
It is currently in Beta but is already shipped by some linux distributions, e.g. Debian/sid ships version "1.1.1~~pre9-1"

The major addition is TLS 1.3 support. Here are the release notes:
https://www.openssl.org/news/openssl-1.1.1-notes.html

**Comment by sfackler** [comment]
We already support and test against 1.1.1-pre9.

**Comment by luben** [comment]
Great, is it also for the 0.9.x branch? Currently mio/tokio is still on it.

**Comment by sfackler** [comment]
It may or may not work on 0.9.x.

0.10 has been out for 10 months. Libraries on 0.9 should upgrade.

**Comment by luben** [comment]
Agree, closing the issue.
