### ISSUE TITLE
Support multiplexing DTLS connections on a single UDP socket

### ISSUE THREAD

**Issue by scottjmaddox** [sfackler/rust-openssl#985]
In order to multiplex multiple DTLS connections onto a single UDP socket, it's necessary to maintain a separate `Ssl` state for each client, and to use `MemBio`s as the base. However, `MemBio` is not currently exposed, and neither is an equivalent of `Bio_read` or `Bio_write`, which are necessary for moving data between the UDP socket and the `Ssl` state.

Thus, multiplexing DTLS connections currently requires dropping down to FFI calls.

I'm confident that support could be added in an entirely backwards-compatible way, using one of three options:

1. Expose `MemBio`, add `Bio_read` and `Bio_write` equivalent methods, and add new methods to `Ssl` for setting the base and accessing the `MemBio`s.
2. Keep `MemBio` private, and add new methods to `Ssl` for using a `MemBio` base and for `Bio_read` and `Bio_write` equivalents.
3. Keep `MemBio` private, and add a new `MemSsl` (modulo the name) type that that transparently uses a `MemBio` base and provides `Bio_read` and `Bio_write` equivalents.

In order to make building the `SslContext` less awkward, it would also be nice to provide `SslContext::mozilla_intermediate` and `SslContext::mozilla_modern`. This could also be done in an entirely backwards-compatible way.

If there's interest from the maintainer(s?), I could take a stab at a PR. I would just need to know which option is preferred.

**Comment by sfackler** [comment]
You don't need to use specifically MemBio, just a `Read + Write` that buffers data. There's an example in our tests that use this strategy: https://github.com/sfackler/rust-openssl/blob/master/openssl/src/ssl/test.rs#L1572-L1707

**Comment by scottjmaddox** [comment]
Hmm, yes I suppose that works. What do you think about about moving `MemoryStream` into the library and exposing it?

Also, `SslContext::mozilla_intermediate` and `SslContext::mozilla_modern` would still be nice to have, but perhaps those should be in a separate issue / PR?

**Comment by sfackler** [comment]
I don't think MemoryStream necessarily makes sense in this library.

Why doesn't SslAcceptor work for your use case? `SslContext` is currently designed to be awkward to use to lead people towards SslAcceptor/SslConnector.

**Comment by scottjmaddox** [comment]
Thanks, I see now how to use SslAcceptor with a copy of MemoryStream. I appreciate the help!

**Comment by cameronelliott** [comment]
> You don't need to use specifically MemBio, just a `Read + Write` that buffers data. There's an example in our tests that use this strategy: https://github.com/sfackler/rust-openssl/blob/master/openssl/src/ssl/test.rs#L1572-L1707

Just in case someone is looking for this here, I updated the commit so you can see the example talked about. 

https://github.com/sfackler/rust-openssl/blob/ea18d84de3ff5a6bc374fb954f05a8629648a37e/openssl/src/ssl/test.rs#L1572-L1707
