### ISSUE TITLE
Doesn't compile with OpenSSL 1.1.1

### ISSUE THREAD

**Issue by joshtriplett** [sfackler/rust-openssl#986]
With OpenSSL 1.1.1 prereleases, rust-openssl fails to detect the version of OpenSSL, and fails to build.

**Comment by crumblingstatue** [comment]
On OpenSSL 1.1.1, this seems to break a fresh install of `cargo-edit`, with no pre-existing `Cargo.lock`.

Should I just notify the maintainers to bump their deps?

**Comment by sfackler** [comment]
If they're using openssl 0.9 they'll need to bump to 0.10. That corresponds to bumping native-tls from 0.1 to 0.2 FYI.

**Comment by sdroege** [comment]
Would it be possible to do a new 0.9 release with that change to unbreak everything that currently still depends on 0.9?
