### ISSUE TITLE
SslOptions overridden

### ISSUE THREAD

**Issue by MichaelTheriot** [sfackler/rust-openssl#989]
`openssl = "0.10"`

I am trying to build an `Ssl` instance that only allows specific versions. It appears to override my options.

```rust
let mut builder = SslContext::builder(SslMethod::tls()).unwrap();
builder.set_options(SslOptions::NO_TLSV1_2);
Ssl::new(&builder.build()).unwrap().version_str(); // TLSv1.2
```

Is this behavior correct, and if so how can I accomplish this?

**Comment by sfackler** [comment]
The value of `version_str` before the handshake completes isn't valid, since no protocol has been selected yet.
