### ISSUE TITLE
[openssl][0.9.24] Fail to build on hosts with openssl 1.1.1

### ISSUE THREAD

**Issue by otavio** [sfackler/rust-openssl#994]
Today I updated my host development machine and found that it was not building my source code anymore. 

Got the following failure:

```
error: failed to run custom build command for `openssl v0.9.24`
process didn't exit successfully: `.../target/debug/build/openssl-4dcd4d0c1d4575a6/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Unable to detect OpenSSL version', .../.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.9.24/build.rs:16:14
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

It needs to be upgraded to `openssl-sys` last releases. This is important as multiple vendors will start upgrading OpenSSL and more people will face it. For now, I downgraded my host to `openssl 1.1.0`

**Comment by jereksel** [comment]
I'm having the same error, but I think it's dependency problem and not library's. Current library version is `0.10.12` and I think we should update our dependencies to use the latest version.

**Comment by sfackler** [comment]
I would prefer that people update to the current release of this crate that already supports 1.1.1.

**Comment by est31** [comment]
E.g. the [iron framework](https://github.com/iron/iron) still uses hyper 0.10 and depends on [hyper-native-tls](https://github.com/sfackler/hyper-native-tls). And hyper-native-tls only supports native-tls 0.1 which only supports openssl 0.9. So what to do now? Sure, optimally iron updates its hyper dependency from 0.10 to 0.12, but this will neccessitate major changes and most likely get to users as well through a change in the iron API.

**Comment by jereksel** [comment]
Frankly, this example for me shows "fault" of iron, not openssl. As a library developer I should ensure that I'm using the latest dependencies. openssl-rust developer shouldn't care which version native-tls, hyper or iron uses - his job is to ensure compatibility with latest openssl.

**Comment by est31** [comment]
native-tls, hyper-native-tls are both maintained by the same person as the openssl crate is. Yet both required breaking changes to update from openssl 0.9 to 0.10.

**Comment by sfackler** [comment]
> If you want the ecosystem to switch to your newer versions more eagerly, you should bring it to them.

There are 161 crates on crates.io which directly depend on rust-openssl, and 105 that directly depend on native-tls. It is not feasible for me to push out upgrades to all of those whenever I cut a new release.

> But don't force them, please. The current way of treatment is just annoying everyone in the ecosystem.

What are your expectations around support? How many crates continue maintaining old major versions in perpetuity?

**Comment by mqus** [comment]
just a question for my usecase: I have openssl 1.0.2p installed alongside 1.1.1, how do I tell cargo to use only openssl1.0.2p?

**Comment by sfackler** [comment]
Set the OPENSSL_DIR environment variable to point to the location 1.0.2 is
installed

**Comment by est31** [comment]
> There are 161 crates on crates.io which directly depend on rust-openssl, and 105 that directly depend on native-tls. It is not feasible for me to push out upgrades to all of those whenever I cut a new release.

I think it's important to get the populous projects that are using your crate to use the newer version before you end support for the older one. And with enough time in between the two events so that users are given time to switch. The number of popolous projects is small, I'd say. Even simple pings would help: "hello, I'd like you to update to openssl 0.10, as openssl 0.9 will go out of maintenance on ABC"

> What are your expectations around support? How many crates continue maintaining old major versions in perpetuity?

My expectation is that if there is a significant amount of users of a specific version of a crate, that version should still see some little level of support. Given that high-profile projects like reqwest or iron are still using openssl 0.9, this seems to be fulfilled.

**Comment by otavio** [comment]
I understand that ultimately, 0.9.x need to be abandoned and all energy and effort to be focused on 0.10.x or any other future release, however, we are facing some major changes in multiple projects and upgrades have been slowed down a bit.

The openssl upgrade from 1.1.0 to 1.1.1 is a minor release, from user point of view. I understand it ended having more features added along the way but adding support for existing features would be enough and provide an upgrade path for users.

**Comment by sfackler** [comment]
> And with enough time in between the two events so that users are given time to switch.

0.10 was released *10 months ago*. The 0.7.x series was last released over 2 years go, and is still downloaded 75-100 times a day. I have very little interest in year long maintenance periods for old releases.

>  Given that high-profile projects like reqwest or iron are still using openssl 0.9, this seems to be fulfilled.

Iron hasn't had a release in 10 months - is it abandoned? It's not clear to me why the onus is on me to maintain old releases rather than those high profile projects to update.

Supporting 1.1.1 in 0.9 is not necessarily a trivial one line change. The addition of TLS 1.3 is pretty significant, and 0.9 doesn't provide any of the APIs to interact or control that.

**Comment by sfackler** [comment]
native-tls 0.1 unfortunately can't take major version bumps to openssl because it's exposed as a public dependency (there are extension traits that allow you to downcast from the native-tls types to the openssl types). That's one of the things that 0.2 fixed.

**Comment by dns2utf8** [comment]
@sfackler Thank you for putting so much time into it!
I am successfully building my applications with docker for now. Will look at it on the weekend and try to help release the fixed deps on the weekend.

**Comment by jebrosen** [comment]
> native-tls 0.1 unfortunately can't take major version bumps to openssl because it's exposed as a public dependency

I believe the situation is actually worse than this: no crate should bump its openssl(-sys) dependency unless it also does a major version bump itself, regardless of whether it's publicly exposed or not. Otherwise, a minor update in a dependency changing its `openssl` dependency to 0.10 (for example) would conflict with another dependency still using 0.9 because of `links`.

**Comment by sfackler** [comment]
@jebrosen that's not a problem in this case - openssl 0.10 still uses openssl-sys 0.9.

**Comment by mqus** [comment]
In my case (archlinux, bitwarden_rs) it was enough to rely on the already instaled openssl-1.0 package and compile via 
```bash
$> OPENSSL_LIB_DIR="/usr/lib/openssl-1.0" OPENSSL_INCLUDE_DIR="/usr/include/openssl-1.0" makepkg
```
(for archlinux packages)  or 
```bash
OPENSSL_LIB_DIR="/usr/lib/openssl-1.0" OPENSSL_INCLUDE_DIR="/usr/include/openssl-1.0" cargo build 
``` 
like suggested above.

**Comment by ishitatsuyuki** [comment]
If you have no workaround available, you can also try to replace with the branch of #1001. I believe it has no compatibility issues, but it's good to test it out.

**Comment by Redrield** [comment]
This is starting to really get in my way because I'm at the point where I'm having to choose between having my rust tools work, or having my system work. reqwest still isn't updated and it's becoming unsustainable for me to stay on 1.1.0 while the rest of everything in my system starts to expect 1.1.1

**Comment by sfackler** [comment]
Reqwest was updated 3 weeks ago.

**Comment by Redrield** [comment]
cargo-edit is still using the reqwest that uses the broken version of openssl

**Comment by rustonaut** [comment]
@Redrield: if you still have old deps consider:

```bash
export_openssl_1.0_vars() { 
    export OPENSSL_LIB_DIR="/usr/lib/openssl-1.0";
    export OPENSSL_INCLUDE_DIR="/usr/include/openssl-1.0"
}
```

And then run it in the shell you compile thinks in.
(Through you have to fix the paths depending on where it had been placed on your system).

**Comment by nox** [comment]
Can we get some progress on this? I invalidate my Servo build every day because I forgot to export the two environment variables, and as said earlier it's not trivial to update to 0.10 and requires an Hyper bump, which is complex to land in Servo because a lot of stuff was removed from that version of Hyper.

**Comment by rustonaut** [comment]
I think what we actually need is a way to inject environment variables into
the build process of creates you depend on _and only that crate and
potentially it's sub creates if "requested"_.

The think is that for this case we got away by "just" setting some
environment variables in the Shell we use to compile. But there might be
situations where setting environmental variables will fix one crate withe a
C/C++ dep while breaking another.
(Through the are a lot of things to consider for this to work well which
are completely office for the thread).

**Comment by sfackler** [comment]
@nox No, it does not require a Hyper bump.

**Comment by est31** [comment]
@sfackler servo still uses hyper 0.10 which is only supported on the 0.2 branch of hyper-openssl... which in turn only supports the openssl 0.9 branch. So I'd say it does require a hyper bump unless `hyper-openssl` 0.2.x gets updated to support openssl 0.9.

**Comment by sfackler** [comment]
I am not the only person in the world that has the ability to write an implementation of [`NetworkConnector`](https://docs.rs/hyper/0.10.13/hyper/net/trait.NetworkConnector.html) that talks to openssl 0.10.

**Comment by MggMuggins** [comment]
That works for `openssl`, but not `openssl-sys` (Same branch, `"openssl-sys:0.9.23"`).

**Comment by nox** [comment]
> @nox If you need something kinda permanent, did you try my compat branch?

I don't want to use a replace and rely on git dependencies for this.

**Comment by nox** [comment]
> I am not the only person in the world that has the ability to write an implementation of [`NetworkConnector`](https://docs.rs/hyper/0.10.13/hyper/net/trait.NetworkConnector.html) that talks to openssl 0.10.

But you are the only person who can accept to make the 0.9 crate support the 1.1.1 openssl version so that everyone doesn't need to reinvent the wheel.

**Comment by sfackler** [comment]
It should not come as a surprise that lagging behind by a year+ on major dependencies will impose an increasing maintenance burden. I have no interest in indefinitely maintaining old releases of this crate. If Mozilla is interested in an extended support contract for the 0.9 release, feel free to contact me!

**Comment by marmistrz** [comment]
Why does `openssl-sys` reject the unknown version? IMO it should at least try to build the bindings and not fail just because the version is newer.

**Comment by sfackler** [comment]
What do you mean by "reading the bindings"? openssl-sys contains the binding definitions.

**Comment by sfackler** [comment]
Building the bindings will succeed - they're an assertion of the ABI of OpenSSL, and if they're wrong, that's undefined behavior.

**Comment by jens1o** [comment]
Hey @sfackler, how have this been fixed exactly?

**Comment by jonhoo** [comment]
@jens1o I think this is being closed as `wontfix` given [this comment](https://github.com/sfackler/rust-openssl/issues/994#issuecomment-429634655).

**Comment by sfackler** [comment]
That's correct.

**Comment by jens1o** [comment]
Alright, thanks. :)

**Comment by bnewbold** [comment]
Apologies for necro-posting on this already very long thread!

A work around for me on Ubuntu 18.04 bionic was fairly straight forward and I didn't see a working solution in the thread above:

    # note that libssl1.0-dev conflicts with libssl-dev, but openssl1.0 does not conflict with openssl, and that the libssl1.0.0 package version is 1.0.2
    sudo apt install openssl1.0 libssl1.0.0 libssl1.0-dev
    cargo clean
    OPENSSL_LIB_DIR="/usr/lib/x86_64-linux-gnu" OPENSSL_INCLUDE_DIR="/usr/include/openssl" cargo build

A gotcha for me was a host setup script that kept installing `libssl-dev`, replacing `libssl1.0-dev`.

Thank you to everybody involved for their patience with both gnarly API dependencies and the long-tail of folks with old environments!
